### ISSUE TITLE
Simbad ROW_LIMIT will not set properly in Spyder

### ISSUE THREAD

**Issue by LJNolan** [astropy/astroquery#1008]
Hello all, please forgive me if I make any obvious errors in formatting or forum etiquette, this is my first time on Git Hub.  My problem is that I'm trying to pull a limited amount of data from SIMBAD with a query_criteria that will otherwise return over 65,000 objects.  Obviously, this is not practical.  Unfortunately, when I set my custom astroquery.simbad module (that might be the wrong word) row limit as follows in Spyder:

OdataSimbad = Simbad()
OdataSimbad.remove_votable_fields('coordinates')
OdataSimbad.ROW_LIMIT = 200

and then run my query_criteria, the program will still time out in data request.  I've tried reducing my row limit down to 10, so it's not that 200 is timing out the program, for some reason the change in ROW_LIMIT doesn't take.  When I run the same program line-by-line in the command window in Spyder it works fine, I just can't get this to work in my saveable file in the IDE.  Does anyone know how to fix this?  I know I could reconfigure Astroquery to set the row limit automatically, but I want to be able to run my program on any computer without messing with configuration.  Thank you for your help.

~LJNolan

**Comment by keflavich** [comment]
Could you show the complete query script?  What you've described is odd and shouldn't happen, but we need a complete minimum working example (MWE) to test it.

**Comment by LJNolan** [comment]
Yes, of course.  Thank you for the quick response.  The full query is as follows:

OdataSimbad = Simbad()
OdataSimbad.ROW_LIMIT = 200
OdataSimbad.remove_votable_fields('coordinates')
OdataResult = dataSimbad.query_criteria('otype != "BH?" & Bmag > 0 & Vmag > 0 & Kmag > 0 & umag > 0')
print(OdataResult)

I conduct some other queries (with different instances of SIMBAD) in the same code but they are very quick and shouldn't cause any problems.  I also plan to conduct some analysis on this result but I'm just printing it right now to make sure the data is correct.  Thank you for your time.

~LJNolan

**Comment by keflavich** [comment]
There's a small typo there: `oDataResult = dataSimbad...` should be `OdataSimbad`, right?  I doubt that's the issue, but just in case.

**Comment by keflavich** [comment]
When I run this, I get the expected result: 200 entries returned.  What are you seeing?
```
print(len(OdataResult))
200
```

**Comment by LJNolan** [comment]
I'm very sorry there's been such a delay in my responses when yours have been so prompt.  I won't be able to get to my computer in all likelihood until about noon (classes and stuff), so I'll check then, but embarrassingly, the typo could be the problem.  I have another instance of Simbad called dataSimbad which I never set a limit on.  I will check the fixed typo ASAP and get an answer when I have.  Thank you for your patience.

~LJNolan

**Comment by LJNolan** [comment]
I feel very foolish.  The typo was the only problem.  Thank you very much for your help.

~LJNolan
