### ISSUE TITLE
TAP query redirect error

### ISSUE THREAD

**Issue by dr-rodriguez** [astropy/astroquery#1009]
When attempting to access a TAP service with TapPlus, some services will issue a 303 redirect that gets caught as an error. Alternative tools like Topcat follow through and deliver the data, but astroquery does not.

Example code:
```
from astroquery.utils.tap.core import TapPlus
url = 'http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/tap'
cadc = TapPlus(url=url)
job = cadc.launch_job("select top 100 observationID, instrument_name from caom2.Observation")
```

**Comment by jcsegovia** [comment]
@dr-rodriguez you are right, sync. jobs redirections (303) are not handled properly.

**Comment by jcsegovia** [comment]
Fixed with the integration of branch issue_1009_tap_redirect_error

**Comment by bsipocz** [comment]
Thanks @jcsegovia!
