### ISSUE TITLE
Problems with some units in astroquery.gaia

### ISSUE THREAD

**Issue by lauralwatkins** [astropy/astroquery#1013]
I ran example 1.1 from the documentation page and started looking at the results. It looks like something is screwed up with the units. My guess is that they are given in a non-standard format in the VOTable and so that the astropy units package cannot recognise them.

This is the code directly from the example:
```
import astropy.units as u
from astropy.coordinates.sky_coordinate import SkyCoord
from astropy.units import Quantity
from astroquery.gaia import Gaia
coord = SkyCoord(ra=280, dec=-60, unit=(u.degree, u.degree), frame='icrs')
width = Quantity(0.1, u.deg)
height = Quantity(0.1, u.deg)
r = Gaia.query_object_async(coordinate=coord, width=width, height=height)
```

The proper motion units work as expected. `print(r["pmra"].unit)` returns `mas / yr` and `print(r["pmra"].unit.physical_type)` correctly returns that this is an angular speed.

But `print(r["ra_error"].unit)` returns `Angle[mas]`, which is not a valid unit (it should be simply `mas`). And `print(r["ra_error"].unit.physical_type)` returns `unknown`. This problem is true for all column with units of mas.

There are similar problems for columns with units of `Angle[mas^-2]` which should be `1 / mas2`, units of `Flux[e-/s]` which should be `electron/s`, units of`Magnitude[mag]` which should be `mag`, and dimensionless quantities `Dimensionless[see description]` which can be `dimensionless_angles` or `dimensionless_unscaled` or simply `None`.

**Comment by jcsegovia** [comment]
We have detected this problem with units you are referring to (we have several tickets in our system to handle it).
It is not a software problem but a data model one. Units will be modified to make them more 'VO compatible'.
It will be fixed for (Gaia Data Release 2: DR2) and, as soon as the new data are available, this problem will be solved.

**Comment by bsipocz** [comment]
As I see this has been resolved.
