### ISSUE TITLE
IRSA ALLWISE long-form query in astroquery

### ISSUE THREAD

**Issue by bwholwerda** [astropy/astroquery#1018]
Hello,

I am trying to ping the IRSA ALLWISE catalog and I would like it to return the long-form (more columns) query as opposed to standard. That is a setting in the IRSA webform but I do not know how to set that in astroquery. 

Can one do this in astroquery? 

currently using this:
```
table = Irsa.query_region(coord.SkyCoord(ra_2mrs[i],dec_2mrs[i], unit=(u.deg,u.deg)),
                                  catalog='allsky_4band_p3as_psd', onlist=0, spatial='Box', width=2*u.arcsec)
```

is there a different catalog for the long-form or is there a toggle I should switch? 

with kind regards,

Benne

**Comment by keflavich** [comment]
It looks like we cannot presently do this.  The 'Long Form' query button activates a new form, which in turn requests the complete set of column names.  The astroquery approach does not explicitly request *any* column names, and therefore just receives the default table, which appears to be the "Standard" / "Short-form" table with all columns.

Astroquery could be modified to be more flexible by having it parse the IRSA web query form and identify the possible table columns to query for.  However, this is a nontrivial modification that requires writing the appropriate HTML parsing tools, and therefore I cannot commit to doing it.

Are there any other IRSA devs who can chime in on whether there might be a single-keyword approach for getting the long-form table data?

**Comment by bwholwerda** [comment]
Hello,

I would be perfectly happy if the long-form version of the ALLWISE catalog was available as a separate catalog. Wouldn't that solve the issue? The main reason being that for anyone using this catalog for galaxies would like to use an appropriate aperture.

with kind regards,

Benne

**Comment by bsipocz** [comment]
We have switched out the backend, and now you're able to write any ADQL queries you wish, which should allow access to all the columns available in any of the catalogs.
