### ISSUE TITLE
Additional columns in NASA Exoplanet Archive queries

### ISSUE THREAD

**Issue by ladsantos** [astropy/astroquery#1027]
When querying the NASA Exoplanet Archive, the standard columns returned from the database table do not include some important exoplanet parameters, such as transit midpoint (the default columns are listed [here](https://exoplanetarchive.ipac.caltech.edu/docs/API_exoplanet_columns.html#defaultcol). **It would be useful if we could include additional columns to the query**. However, the Exoplanet Archive's API seems to allow only one additional column (with the URL string '&addcol'), which is not very useful if more than one additional column is required.

I think the best solution would be to have a standard list of columns that should be returned from the query, and then the user should be able to add any column they want. Then, it should be as simple as using the URL string '&select=column0,column1,column3...'.

**Comment by keflavich** [comment]
cc @bmorris3

**Comment by bmorris3** [comment]
I agree, it'd be great if those features were added. If you're up to the task, I'd be happy to review the pull request. 

In the mean time, the [Exoplanet Orbit Database within astroquery](http://astroquery.readthedocs.io/en/latest/exoplanet_orbit_database/exoplanet_orbit_database.html) already allows you to query for transit times easily. 

...and if you're looking to plan transit observations with this ephemerides, I highly recommend pairing astroquery with astroplan, [see here for a tutorial on how.](https://astroplan.readthedocs.io/en/latest/tutorials/periodic.html)
