### ISSUE TITLE
conesearch.list_catalogs uses stale URL

### ISSUE THREAD

**Issue by StuartLittlefair** [astropy/astroquery#1031]
This routine uses the URL http://stsdas.stsci.edu/astrolib/vo_databases/conesearch_good.json, which is a deprecated webpage.

**Comment by pllim** [comment]
Aww, man. I think this is a side effect of what @SaraOgaz implemented yesterday. Sara, is there a way to revive just stuff under `vo_databases`? Please advise.

**Comment by pllim** [comment]
c/c @jhunkeler and @redinam or alternative in-house solutions.

**Comment by jhunkeler** [comment]
@pllim @StuartLittlefair The rules on the web server have been changed to allow access to `astrolib/vo_databases/.*`.

Note: This URL will likely change at some point in the future though.

**Comment by pllim** [comment]
Thanks for the quick fix, @jhunkeler !

@bsipocz and @keflavich , we have 2 options:

* Backward-incompatible: Change the URL and only support the next release with this new URL.
* Backward-compatible: Change the URL and backport this change to all supported versions.

Please advise.

**Comment by keflavich** [comment]
What is the consequence of leaving the current version with the outdated URL?  We've never done any backporting in astroquery before, we just make new releases.  Partly, we do this because the services themselves are (ideally slowly) moving targets; there is no real expectation that older versions of astroquery should work at all.

**Comment by pllim** [comment]
> What is the consequence of leaving the current version with the outdated URL? 

Ideally, we wouldn't retire outdated URL until the *next* release (0.3.8). But then, once retired, `vo_conesearch` in the older versions (< 0.3.8) would not work anymore. User will have to upgrade. Does that sound reasonable to you? Do you have a tentative timeline for 0.3.8 release?

**Comment by SaraOgaz** [comment]
We we're thinking about doing a follow up move of those pages end of February, but we can extend it a little if needed.

**Comment by bsipocz** [comment]
0.3.7 has just been released. There isn't a strict timeline, but normally we have at least a few month between releases to get some new features added for the new one.

However, we already have two big "new service" PRs almost ready, so I think it's fine to get a new release out once both of them are merged in.

**Comment by pllim** [comment]
Update: New URL is in place and the old one is redirectly to the new one already. #1033 should update `vo_conesearch` to the new one entirely.
