### ISSUE TITLE
astroquery.eso ROW_LIMIT

### ISSUE THREAD

**Issue by tpuzia** [astropy/astroquery#1055]
I was toying around with your astroquery.eso package and ran into the following issue with increasing the row limit of the query:

In [1]: from astroquery.eso import Eso

In [2]: Eso.login('SOMEUSER')
INFO: Authenticating SOMEUSER on www.eso.org... [astroquery.eso.core]
INFO: Authentication successful! [astroquery.eso.core]
Out[2]: True

In [3]: **Eso.ROW_LIMIT = 1e6**

In [4]: all_pi_proj = Eso.query_instrument('xshooter', pi_coi='someuser')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-8461fe338056> in <module>()
----> 1 all_pi_proj = Eso.query_instrument('xshooter', pi_coi='someuser')

/usr/local/lib/python2.7/site-packages/astroquery/eso/core.pyc in query_instrument(self, instrument, column_filters, columns, open_form, help, cache, **kwargs)
    446         url = self.QUERY_INSTRUMENT_URL+'/{0}/form'.format(instrument.lower())
    447         return self._query(url, column_filters=column_filters, columns=columns,
--> 448                            open_form=open_form, help=help, cache=cache, **kwargs)
    449 
    450     def _query(self, url, column_filters={}, columns=[],

/usr/local/lib/python2.7/site-packages/astroquery/eso/core.pyc in _query(self, url, column_filters, columns, open_form, help, cache, **kwargs)
    484             content = instrument_response.content
    485             # First line is always garbage
--> 486             content = content.split(b'\n', 1)[1]
    487             log.debug("Response content:\n{0}".format(content))
    488             if _check_response(content):

IndexError: list index out of range
==========================

However, setting **Eso.ROW_LIMIT = -1** works fine and give unlimited access to all output rows.

Ideas?

**Comment by jwoillez** [comment]
Could you please try with `Eso.ROW_LIMIT = 1000000`? If it works, it is quite probably related to the fact that python interprets `1e6` as a `float`, rather than an `int`, which must make `astroquery` generate a malformed query.

**Comment by tpuzia** [comment]
That's exactly it. Throwing in an int() statement at the right place would easily solve this issue.

**Comment by jwoillez** [comment]
@tpuzia I've submitted pull request for a fix of your issue. Thanks for the report!
