### ISSUE TITLE
New service: NOAO

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1057]
We began work on an NOAO archive interface last summer, but progress stalled.

The archive is hosted [here](http://archive.noao.edu/).  

This gist establishes the basic process for sending a query and receiving the results.  It needs to be converted into a standard astroquery module:
https://gist.github.com/keflavich/b13988322707d7bdda10d3e897ed6678

cc @tpuzia, who expressed interest.

**Comment by kakirastern** [comment]
I would like to use this for my GSoC project idea...

**Comment by bsipocz** [comment]
@kakirastern - let's have that telecon first.

**Comment by kakirastern** [comment]
Okay, sure @bsipocz

**Comment by bsipocz** [comment]
I'm closing this in favour of #2081
