### ISSUE TITLE
Deprecated service: LCOGT

### ISSUE THREAD

**Issue by Fingel** [astropy/astroquery#1061]
Hi,
The included LCOGT module queries an API that is deprecated and no longer available. It's probably better to remove it. @zemogle any objections?

**Comment by bsipocz** [comment]
We would definitely prefer the LCO module to be fixed, and @zemogle actually already put some effort into it https://github.com/astropy/astroquery/pull/911
So I wonder whether it's feasible to get that PR finished any time soon. If not, then I agree it may be better to remove the module altogether.
