### ISSUE TITLE
New service: SSOIS

### ISSUE THREAD

**Issue by migueldvb** [astropy/astroquery#1062]
The Solar System Object Image Search allows to look for images of solar system objects using different parameters for searching the database. 

http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/ssois/

This will require parsing the HTML table ouput.

**Comment by mommermi** [comment]
@migueldvb, we will add this service as part of sbpy. I just added a list (#1075) of all the services we are planning to add to astroquery as part of that. There is already some code available for the query and the parsing - it's just a matter of plugging it into astroquery.

**Comment by migueldvb** [comment]
Wonderful! That sounds perfect.

**Comment by migueldvb** [comment]
Superseded by #1075
