### ISSUE TITLE
ENH: Use newer STScI VAO registry for Cone Search validation

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1070]
The current VAO registry, `http://vao.stsci.edu/directory/NVORegInt.asmx/VOTCapabilityPredOpt?...` in `astroquery.vo_conesearch.validator.conf.conesearch_master_list` can be finicky and return empty VO table. Its developer says this is actually a "legacy" service now. Hence, I need to investigate if their newer RegTAP service is viable as an alternative.

**Comment by pllim** [comment]
Update: After some investigation, it might be least painful for me to make some backward-incompatible code changes to go with this. However, all the changes should be contained within just the `validator` portion and should not affect typical users who only do queries. Any objection?

**Comment by keflavich** [comment]
No objection, just include a changelog entry and maybe a helpful warning?
