### ISSUE TITLE
Integrate utils.tap with astropy.votable

### ISSUE THREAD

**Issue by eteq** [astropy/astroquery#1072]
While fiddling around with the Gaia module in astroquery recently, I notice that the tables returned from `load_tables` (from `utils.tap`), have no apparent connection to either the `astropy.io.votable` nor the `astropy.table.Table` objects.  This is not good, because it represents further divergence in the "table-like-thingie" aspect of the ecosystem.  I realize this is more of a "metadata" element, since `launch_job` gives tables, but it still seems like it might be a duplication?

In particular I'm confused why the `utils.tap` data model is completely distinct from `astropy.votable`.  Isn't it mandatory for TAP results to be `VOTables`? Is it that `VOTable` can't handle "table with no data"? Does anyone have insight into whether there's an essential difference here?

cc @jcsegovia @keflavich @bsipocz

**Comment by eteq** [comment]
(Also I can't help but think this is rather time-sensitive, as it would be good to have at least a plan on this, ideally even an implementation, by Gaia DR2!)

**Comment by bsipocz** [comment]
I'm closing this issue now based on the comment above, as well as we don't plan to further develop utils.tap but rather deprecate it once the current TapPlus using modules are refactored to use PyVO.
