### ISSUE TITLE
readthedocs stable version failed build

### ISSUE THREAD

**Issue by migueldvb** [astropy/astroquery#1084]
There is a problem with the stable version docs on readthedocs
(http://astroquery.readthedocs.io/en/stable/)
that currently is giving:
```
        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
```
However, latest and v0.3.6 versions are building fine.

**Comment by bsipocz** [comment]
Is there a link anywhere that points to this page? Normally we link to `latest` rather than stable, so this is a somewhat expected behaviour unless of course if we advertize this `stable` link anywhere.

**Comment by bsipocz** [comment]
Oh, I see, it's listed in the dropdown on RTD?

**Comment by keflavich** [comment]
`latest` is also [failing](https://readthedocs.org/projects/astroquery/builds/6962559/).  The error is something about pdflatex and overfull hboxes.  =(

**Comment by bsipocz** [comment]
@keflavich - Actually the rendered html docs is indeed the latest version, but indeed the PDF version doesn't build. I'll open a separate issue for it as this current one is solved and getting the PDF fixed has lower priority.
