### ISSUE TITLE
PDF version of the docs doesn't build on RTD

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1086]
The PDF build of the docs stopped working a while ago (the latest version on RTD is from February). 

Full log is e.g. here: https://readthedocs.org/projects/astroquery/builds/6962559/

**Comment by migueldvb** [comment]
I can confirm that the PDF build of the docs is not working locally for me.

**Comment by bsipocz** [comment]
I'm closing this as we don't build PDF versions on RTD any more.
