### ISSUE TITLE
shrinking box size towards the celestial poles?

### ISSUE THREAD

**Issue by shiaki** [astropy/astroquery#1088]
https://github.com/astropy/astroquery/blob/ac719ee24bdf5b66bd93b84100f13a7099c0d1f7/astroquery/sdss/core.py#L1009

I think using "(ra - dr / cos_dec, ra + dr / cos_dec, ..." is better. Otherwise the actual box size will shrink towards the celestial poles. Also, adding boundary detection near RA~0/360 might be helpful.

I've been using astroquery for a while, which helped a lot in my research. Thanks anyway!

**Comment by bsipocz** [comment]
PR #2477 has refactored this piece of code to use the SDSS conesearch API, so I'm closing this now.
