### ISSUE TITLE
travis-ci failures: keyring in py2.7?

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1097]
We have several parallel ci errors that appear to be the same thing:

https://travis-ci.org/astropy/astroquery/jobs/363777242
https://travis-ci.org/astropy/astroquery/jobs/363867194
https://travis-ci.org/astropy/astroquery/jobs/364053671

They're failing on this stage:
```
        - os: linux
          stage: Test docs, astropy dev, and without optional dependencies
          env: PYTHON_VERSION=2.7
               CONDA_DEPENDENCIES='requests beautifulsoup4 html5lib keyring'
```
and seem to be keyring import failures.

**Comment by pllim** [comment]
Perhaps unrelated but when inspecting the first log, I saw these:
```
astroquery/sdss/setup_package.py:2: RuntimeWarning: Parent module 'astroquery.sdss' not found while handling absolute import
  import os
astroquery/mast/tests/setup_package.py:1: RuntimeWarning: Parent module 'astroquery.mast.tests' not found while handling absolute import
  import os
```

As for `keyring`, I wonder if opening an issue at https://github.com/jaraco/keyring/issues would help.

**Comment by keflavich** [comment]
it might be a conda failure though?

**Comment by pllim** [comment]
I have seen some packages failed mysteriously, only to pass later when you rerun the job without any code changes. But there was also one that is still failing (Appveyor + PY2). So... :woman_shrugging:
