### ISSUE TITLE
astroquery.gaia.Gaia queries failing (ESA archive is down for DR2 prep)

### ISSUE THREAD

**Issue by Vb2341** [astropy/astroquery#1098]
I use astroquery.gaia in a number of scripts, and noticed today the Gaia queries are failing.  This is because the ESA Gaia archive is down to prepare for DR2.  With some digging, I was able to point the queries to a different partner data center, and get queries working again by creating `TapPlus` instance myself, and then passing that to the `GaiaClass` constructor:
```python
from astroquery.gaia import TapPlus, GaiaClass
Gaia = GaiaClass(TapPlus(url='http://gaia.ari.uni-heidelberg.de/tap'))

# From there, use as normal:
job = Gaia.cone_search('NGC 6791', radius='.05 deg')
tbl = job.get_results()
```

This might be obvious to many, but I thought it might be worth sharing as DR2 is so close, and some may still need to access the DR1 data in prep for DR2.

**Comment by keflavich** [comment]
cc @jcsegovia - perhaps this should be mentioned in the documentation as a workaround when servers are down?

**Comment by pllim** [comment]
Is this related to timeout error I am getting for `http://vizier.u-strasbg.fr/viz-bin/conesearch/I/345/gaia2?` ?

**Comment by bsipocz** [comment]
This supposed to be a different service and provider, so I doubt it being related to any vizier timeouts.

**Comment by bsipocz** [comment]
Given the answer above and the remaining action item tracked in the other issue (https://github.com/astropy/astroquery/issues/1121), I'm closing this PR. 

Bottom line, use the TAP implementation from pyVO as TapPlus is to support the ESA archives only. And ideally it would be nice to support alternative servers.
