### ISSUE TITLE
Use logger rather than prints 

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1110]
Many modules still have prints though it would be preferable to use the logger instead to give more control to the users what content they want to see.

Triggered by this #1093 PR, but it doesn't only affect the tap module.

**Comment by Phantsure** [comment]
Should all print statements be changed or just the ones for logging(can't differentiate)?

**Comment by keflavich** [comment]
Most print statements should be `log.info`, but there may be a few one-off cases where a print statement is actually needed.  I don't know if there are any general criteria we can apply to differentiate these.

**Comment by bsipocz** [comment]
@Phantsure - one rule of thumb, all the prints after a check for the `verbose` kwarg can stay, and as @keflavich said some of the others are needed, too, so this requires a bit more work than blindly running  `sed`.

**Comment by Phantsure** [comment]
what exactly do you mean by "few one-off cases"? an example might help

**Comment by Phantsure** [comment]
did i get it, this time correctly?

**Comment by bsipocz** [comment]
I reopen this as there are still prints left in the code that could be cleaned up in favour of logging.

**Comment by bsipocz** [comment]
as pointed out in https://github.com/astropy/astroquery/pull/1649,  the `astrometry_net` module needs to be cleaned up of prints, too.

**Comment by daisycodes** [comment]
I would like to help fix this if no one else is working on it.
