### ISSUE TITLE
BUG: vo_conesearch validator skipping 2 URLs

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1125]
This is a follow-up of #1114.

I am getting this from the nightly validator:
```
WARNING: 2 not found in registry! Skipped:
        b'http://vizier.u-strasbg.fr/viz-bin/conesearch/I/243/out?'
        b'http://vizier.u-strasbg.fr/viz-bin/conesearch/II/246/out?'
```

For whatever reason, these two access URLs are not returned by `VOSDatabase.from_registry()` but I can query them separately via http://vao.stsci.edu/regtap/querymanager.html by using SQL statement like:
```
select * from rr.interface natural join rr.resource natural join rr.capability
    where access_url='http://vizier.u-strasbg.fr/viz-bin/conesearch/I/243/out?'
```

I might need to contact STScI VAO registry provider to get relevant server log. For now, these are just not reported as "good" in https://astropy.stsci.edu/aux/vo_databases/ . But they are still theoretically usable. 

* `http://vizier.u-strasbg.fr/viz-bin/conesearch/I/243/out?` is USNO-A1, which I think is superseded by A2, which is validated successfully.
* `http://vizier.u-strasbg.fr/viz-bin/conesearch/II/246/out?` is 2MASS, which I think has alternate access URLs that are validated successfully.

So, this is not critical.

There is also another issue with GAIA DR2 access URL: See https://github.com/astropy/astroquery/issues/1098#issuecomment-385189072

**Comment by pllim** [comment]
Maybe this will naturally be solved when I can use what is in #1158.

**Comment by theresadower** [comment]
Hm, yes both these records exist and are findable through our keyword search and RegTAP interfaces. While I run the registry at ST, the records originally come from the VizieR registry at http://cdsweb.u-strasbg.fr/reg-bin/vizier/oai.pl and are harvested by us nightly for inclusion in search results. I'm unfamiliar with VOSDatabase.from_registry, is it possible to test this pointed at their home registry to see if there is a problem with the record at home, or if there is an issue in ingest/translation?

**Comment by pllim** [comment]
> is it possible to test this pointed at their home registry

Not sure. `from_registry` has hard-coded field names. I have a feeling that registry layouts are not uniform across the internet?

https://github.com/astropy/astroquery/blob/7cecd833bc18ebcec525709ec12d37ea9e1950d5/astroquery/vo_conesearch/vos_catalog.py#L530

**Comment by pllim** [comment]
Now the URL got some sort of `urldefense` prefix. 🤷 
```
WARNING: 2 not found in registry! Skipped:
        b'https://urldefense.com/v3/__http://vizier.u-strasbg.fr/viz-bin/conesearch/I/243/out?__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!jJGEbWHczbygojfkuJHFENxhQc7mDs5wRfT9ONy8VGN5NWyjQdCum0TbOWif$ '
        b'https://urldefense.com/v3/__http://vizier.u-strasbg.fr/viz-bin/conesearch/II/246/out?__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!jJGEbWHczbygojfkuJHFENxhQc7mDs5wRfT9ONy8VGN5NWyjQdCum0TRvHSC$ '
```

**Comment by bsipocz** [comment]
@pllim - is this still an issue?

**Comment by pllim** [comment]
Thanks for the ping. I cannot find the log from last night. I'll let you know tomorrow. 😆

**Comment by pllim** [comment]
I don't see them in the log anymore, so let's close. Thanks!
