### ISSUE TITLE
Retrieving all columns from MAST catalog with object_query

### ISSUE THREAD

**Issue by Mayankattifr** [astropy/astroquery#1142]
I am Mayank Narang from the Tata Institute of Fundamental Research.  I am currently working on a project that requires me to access GALEX UV data. I was trying to use Mast catalog feature from the astroquery module. 

I wanted to know is there a way of displaying all the columns for GALEX I am primarily interested in the source size columns and the FWHM column. 

It would be really helpful if you could help me with the same.

Looking forward to your reply.

Many Thanks,
Mayank Narang 

Research Scholar 
Department Of Astronomy and Astrophysics 
Tata Institute of Fundamental Research

**Comment by ceb8** [comment]
Hi @Mayankattifr, the columns returned through astroquery are all the columns available through that particular API call.
