### ISSUE TITLE
Can MAST Observation download to a given directory name?

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1150]
I saw this example:
```python
from astroquery.mast import Observations
import glob
import shutil

obs_table = Observations.query_criteria(obs_id='JD5702011')

Observations.download_products(obs_table['obsid'], mrp_only=False,
                              productSubGroupDescription=['RAW', 'SPT'])

files = glob.glob('mastDownload/HST/*JMQ/*.fits')
for f in files:
    shutil.move(f, '.')
    
shutil.rmtree('mastDownload')
```

And I wonder if user should be compelled to call `move` and `rmtree` like this. It would be cleaner for `Observation` to take a path name and directly put those FITS files there. c/c @ceb8 @tddesjardins

**Comment by ceb8** [comment]
The reason that the files are downloaded into that directory tree is that the actual fits filenames are not guaranteed to be unique but the Mission/Observation ID/Filename path *is* guaranteed to be unique.

**Comment by ceb8** [comment]
@pllim There is now an option to download a single file by URI, which allows the user to specify the output location directly. See PR https://github.com/astropy/astroquery/pull/1825. I can't direct you to the docs, because they aren't building at the moment, but I am working on that.

**Comment by pllim** [comment]
Thanks for the update, @ceb8 ! When will this be on PyPI (whether as `--pre` or proper release)?

**Comment by ceb8** [comment]
I believe it's on Pypi as `--pre` right now, it's only the doc builds that are failing not the pypi ones.

**Comment by pllim** [comment]
Okay. I thought deploy won't happen unless CI passes? But maybe my memory is outdated. Thanks!

**Comment by ceb8** [comment]
@pllim The CI is passing fine, it's at readthedocs that the failure is happening, which is why it gets deployed to Pypi ok (and also probably why we didn't notice right away).
