### ISSUE TITLE
ESASky: get_maps() doesn't handle HST tar files

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1172]
This was originally reported by @bastianpeter at the astropy core repo, but really is an ESASky module bug:

```
from astroquery.esasky import ESASky
maps = ESASky.query_object_maps('13 29 52.7 +47 11 43')
maps_data = ESASky.get_maps(maps, missions='HST')
```

The files are actually provided as `tar`s with a content of 2 fits files and 2 jpegs, and thus `astropy.io.fits` cannot (and shouldn't) really handle that.

xref: https://github.com/astropy/astropy/issues/7569

**Comment by imbasimba** [comment]
This seems like a change to the HST archive... I plan to fix this during the week, but first I need gather some information about the intent of this change and how it should be handled in ESASky

**Comment by imbasimba** [comment]
This issue was fixed a few years ago
