### ISSUE TITLE
astroquery.vizier for KIC and EPIC returns IDs in int16, which is too low precision.

### ISSUE THREAD

**Issue by christinahedges** [astropy/astroquery#1173]
We're trying to use astroquery to search for targets in the Kepler/K2 input catalogs KIC and EPIC. These should return IDs that are 8 and 9 digit integers. However, when we run astroquery.vizier().query_region() we are returned an int16. This is too low precision to get a correct target ID. 

The screenshot below shows a search for a target with a Kepler ID 3403340. In the returned table the ID is 32676 because the int16 dtype is too low precision. 

![image](https://user-images.githubusercontent.com/14965634/41555761-89057138-72ed-11e8-84b6-17b725c72b4e.png)

If we query vizier online we find the correct ID, so we think this must be an astroquery problem. We can't find where to fix the units.

Any help much appreciated!

```
from astropy.coordinates import SkyCoord
import astropy.units as u
from astroquery.vizier import Vizier
# Target KIC 3403340
cent = SkyCoord(ra=302.854640, dec=38.400139, frame='icrs', unit=(u.deg, u.deg))
v = Vizier(catalog=['V/133/kic'])
result = v.query_region(cent, radius=0.1*u.arcmin, catalog=['V/133/kic'])['V/133/kic']
result
```

**Comment by keflavich** [comment]
This is an incorrect specification in the VOTABLE returned from Vizier.  
```
    <FIELD name="KIC" ucd="ID_MAIN" datatype="short" width="8">
      <DESCRIPTION>[1,13161029] KIC identifier (running number) [NULL integer written as an empty string]</DESCRIPTION>
      <VALUES null="-32768" />
    </FIELD>
```
We need to report this to the Vizier folks; they should not be labeling the IDs as `short` integers when the values exceed 32768.

**Comment by keflavich** [comment]
I've reported it upstream.  In the meantime, a workaround is to do something like:
```
result = v.query_region_async(cent, radius=0.1*u.arcmin, catalog=['V/133/kic'])
votable = result.text
with open('my_votable.xml', 'w') as fh:
    fh.write(votable)
# go in and manually edit 'short' to 'long' in that entry
Table.read('my_votable.xml')
```
or something along those lines (I haven't tested that code...)

**Comment by christinahedges** [comment]
Thanks that's great, and thanks for the work around. We'll use that hack!

**Comment by bsipocz** [comment]
Closing as being upstream and even then a workaround is provided.

**Comment by keflavich** [comment]
This was also reported as being fixed upstream this morning.

**Comment by Emmavt** [comment]
I'm running into essentially the same issue with astroquery.vizier().query_object(), in that the ID is being returned as an int16, which is too low precision to get a correct EPIC target ID. The workaround posted above also works to fix this issue, but I was wondering who I should contact to report it? Any help would be greatly appreciated!

**Comment by keflavich** [comment]
Contact CDS (http://cds.u-strasbg.fr/).  If they report back, it would be good to post about it here too.

**Comment by Emmavt** [comment]
I heard back from CDS, and the issue with EPIC (the table meta data) should now be resolved.
