### ISSUE TITLE
Is there similar (or the same) functionality as the SIMBAD basic search?

### ISSUE THREAD

**Issue by willfurnell** [astropy/astroquery#1174]
Hi,

I'm in the process of writing a web application, and am looking at using the SIMBAD search through astroquery to get RA and Dec co-ordinates (FK5, J2000) for any given co-ordinates/name. 

It looks like the SIMBAD basic search (http://simbad.u-strasbg.fr/simbad/sim-fbasic) will do all this conversion automatically no matter what the user enters which is perfect, and I was wondering if astroquery provides similar or the same functionality through the SIMBAD API?

Thanks,

Will.

**Comment by keflavich** [comment]
No, we don't have that implemented, which is kind of weird since we've implemented all the other interfaces.  It should be really easy to do just by copying and pasting one of the existing query tools and replacing the URL with 'sim-fbasic'

**Comment by willfurnell** [comment]
Fantastic, thank you!

**Comment by willfurnell** [comment]
Looks like the query script does it automatically itself. Eg.
http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=query+vega%0D%0A

**Comment by keflavich** [comment]
Right, that's what we'd need to use.  Right now, you either have to `query_object` for an objectname or `query_region` if you know the coordinates.  Are there any other cases handled by the SIMBAD `basic` query?  If not, is it really needed?  Usually you know whether the query string is a name or a coordinate, right?

**Comment by willfurnell** [comment]
It looks like it takes an object name, co-ordinates or a bibcode - but yes usually you'd know whether the query string is a name or co-ordinate (you'd have get the user to specify) so yes, the need for this is debatable.

**Comment by bsipocz** [comment]
@keflavich @willfurnell - Is there a decision on whether this is needed or not? If the latter, I would suggest to close the issue.
