### ISSUE TITLE
query._download_file could handle progress bar more like astropy.utils.data.download_file

### ISSUE THREAD

**Issue by texadactyl** [astropy/astroquery#1179]
EDIT by @bsipocz:
The progress bar features in astropy cannot handle log levels natively, so instead, in the meantime, astroquery could handle progress bar more like it's done in `astropy.utils.data.download_file`.

However the downside that it's done via private functions, so it's not very appealing to add another keyword to each and every methods that does some download.

Original issue text:

When already in the cache ("Found cached file..."), I see no logging with WARN or ERROR but I can see them with INFO or DEBUG. So, Astroquery obeys its own log level.

If not yet cached locally ("Downloading URL ..."), then I see a progress bar for any level. It seems that in {Astroquery treetop}/astroquery/query.py _download_file, the progress bar is being emitted without being conditioned on the log level. 

See line 277 in https://github.com/astropy/astroquery/blob/master/astroquery/query.py.

Expected result: If log level is WARN or ERROR, no progress bar should appear analogous to cached file handling.

**Comment by bsipocz** [comment]
Thanks for the report, I feel this should be dealt with upstream in astropy.

**Comment by texadactyl** [comment]
@bsipocz Thank you very much for following up with Astropy.  Such diligence!  (=:

**Comment by pllim** [comment]
See #1188 for potential solution.
