### ISSUE TITLE
Simbad otypelist

### ISSUE THREAD

**Issue by marusazerjal** [astropy/astroquery#1182]
Many Simbad objects have 'Other object types' besides the main one. 'otype' votable field returns only one of them. How to get all of them, is there an equivalent of Simbad's `OTYPELIST`?

Example:
```
>>> from astroquery.simbad import Simbad

>>> custom_simbad = Simbad()
>>> custom_simbad.add_votable_fields('otype')

>>> data = custom_simbad.query_objects(['28 Tau'])
>>> print data['OTYPE']
OTYPE
-----
  Be*
```
while [the webpage](http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=pleione&submit=SIMBAD+search) lists
`Ir* (), * (*,AG,...), IR (AKARI,IRAS,...), *iC (Cl*,Cl), V* (V*,AAVSO), UV (CEL,TD1), X (1E), ** (WDS), Be* (Ref), Em* (EM*)`.

**Comment by keflavich** [comment]
I don't think this is possible with the current SIMBAD interface; I tried forcing it with their script interface and got:
```
::script::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

votable {main_id,coordinates,otype,otype(v),otypelist}
votable open
query id  28 Tau
votable close

::console:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

C.D.S.  -  SIMBAD4 rel 1.7  -  2018.07.06CEST11:01:17
total execution time: 0.03 secs
simbatch done

::error:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Field otypelist not found

::data::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```

Could you e-mail the SIMBAD team at CDS and ask them how to do this, and forward them to this Issue?  This is a feature I'd like to have, but don't presently know how to implement it

**Comment by marusazerjal** [comment]
Thanks for the votable script, I was experimenting a bit and tried with `otypes(v)` and it seems to work:
```
::script::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

votable {main_id,coordinates,otype,otype(v),otypes(v)}
votable open
query id  28 Tau
votable close

::console:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

C.D.S.  -  SIMBAD4 rel 1.7  -  2018.07.06CEST11:27:13
total execution time: 0.023 secs
simbatch done

::data::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```
[lines skipped]
```
<TR><TD>*  28 Tau</TD><TD>03 49 11.21755</TD><TD>+24 08 12.1722</TD><TD>14</TD><TD>14</TD><TD>0.1899</TD><TD>0.1184</TD><TD>90</TD><TD>A</TD><TD>Opt</TD><TD>2018yCat.1345....0G</TD><TD>Be*</TD><TD>v</TD><TD>**|*|*iC|Em*|Be*|V*|Ir*|IR|UV|X</TD></TR>
```

**Comment by keflavich** [comment]
Oh!  That's not documented [here](http://simbad.u-strasbg.fr/simbad/sim-help?Page=sim-fscript), unfortunately, and that's the web page we use to validate the added VOtable keywords.

There is a hackaround you can use to get astroquery to perform this query for you:
```
custom_simbad._VOTABLE_FIELDS.append('otypes')
```
but unfortunately I don't have a good idea of how to make that one of the 'allowed' keywords.  If you try to do it the 'right' way, you'll get this traceback:
```
custom_simbad.add_votable_fields('otypes(v)')
Traceback (most recent call last):
  File "<ipython-input-33-943b6eec4892>", line 1, in <module>
    custom_simbad.add_votable_fields('otypes(v)')
  File "/Users/adam/repos/astroquery/astroquery/simbad/core.py", line 386, in add_votable_fields
    raise KeyError("{field}: no such field".format(field=field))
KeyError: 'otypes(v): no such field'
```
I'd still like this reported upstream; we should ask the CDS team to update the documentation

**Comment by aoberto** [comment]
Ok, I just added it in the documentation page

**Comment by rickyegeland** [comment]
My work today lead me to want the `otypes` field.  I verified that `otypes` is now on the [SIMBAD documentation page](
http://simbad.u-strasbg.fr/simbad/sim-help?Page=sim-fscript).  But `otypes` does not appear when calling `list_votable_fields()`, and I get the "no such field" error mentioned above when trying `custom_simbad.add_votable_fields('otypes')`.  Doing `custom_simbad._VOTABLE_FIELDS.append('otypes')` did work, though the result is a `|`-separated list, where commas would be better looking in my opinion.

What is left to do to make `custom_simbad.add_votable_fields('otypes')` work?

**Comment by keflavich** [comment]
TODO:

 * [ ] re-run `get_votable_fields` and push the update

**Comment by bsipocz** [comment]
`otypes` is in the list for a while now, so I'm closing this.
