### ISSUE TITLE
Incorporate SkyQuery and CasJobs into astroquery

### ISSUE THREAD

**Issue by jhand1993** [astropy/astroquery#1190]
Hello people of astroquery,

I am a graduate student at University of Pittsburgh who was writing a script to perform queries via various survey data set web services until I found astroquery and realized you guys had already done it.  That being said I had started working on a CasJobs interface, including authorization.  It is by no means stable and I haven't started testing it, but I decided to reach out to @keflavich and offer to integrate what I was working on into astroquery.  My working repository is https://github.com/jhand1993/gpr, with the casjobs api wrapper being located in skyservergrabbers.py with authorization.py being my initial attempt at adding authorization.

I am by no means an expert, but astroquery is really neat and I would like to help incorporate SkyServer web services into it.

-Jared

**Comment by keflavich** [comment]
So the first step is to have a look at the template module and see if you can put some of your code in that form.  I'm looking over what you've written to see if I can give more specific suggestions.  SkyServerGrabber looks like it might be reasonably similar to BaseQuery in overall structure...

**Comment by bsipocz** [comment]
Also, I wonder how much the overlap is with the functionality of the existing sdss module?

**Comment by jhand1993** [comment]
So I'm expecting there to be tons of overlap.  Let me look into the sdss module and BaseQuery, and I will lay out a better proposal of sorts.  @bsipocz CasJobs via SkyServer definitely overlaps with the existing SDSS module.  One advantage (or extra layer of complexity) is that is allows for a user to grab data from their MyDB after organizing the data online.

**Comment by bsipocz** [comment]
I'm inclined to close this issue as I expect this ship/plan has sailed. Feel free to reopen with a more detailed proposal that explains the added functionality compared to the currently existing sdss module.
