### ISSUE TITLE
Possibly unhandled URI format

### ISSUE THREAD

**Issue by hughdickinson** [astropy/astroquery#1191]
When trying to use the new MAST dataset on AWS, the `Observations.get_hst_s3_uris()` method seems unable to handle the `dataURI` column format that is being returned by `Observations.get_product_list()`.

In my case, the entries in the `dataURI` column are of the form:

> mast:HLSP/url/cgi-bin/getdata.cgi?dataset=hlsp_candels_hst_wfc3_gs-tot-sect12_f125w_v1.0_drz

This does not appear to correspond with the formatting expectation of the method. Moreover, the `obs_id` column (also used by the method) contains entries like:

> hlsp_candels_hst_wfc3_gs-tot-sect22_f105w_v1.0_drz

While the code and comments therein seem to expect an arbitrary alphanumeric sequence. 

I think that this unexpected might be related to querying for products from a large legacy-style survey (CANDELS in this case).

Any help or advice would be much appreciated! 

https://github.com/astropy/astroquery/blob/04484f5c141aad32fed43f998c15e6b1a387b2e6/astroquery/mast/core.py#L1331

**Comment by pllim** [comment]
@ceb8

**Comment by ceb8** [comment]
@cam72cam

**Comment by cam72cam** [comment]
We only have the main public HST data for the currently active instruments.  Things like HLSP's and HLA still require you to hit mast directly and won't have a S3 url.

A enhancement to the get_hst_s3_uris would be to print out a warning when someone tried to get the S3 uris of data that's not on S3

**Comment by ceb8** [comment]
Closing this issue as this warning now exists.
