### ISSUE TITLE
small error in documentation (object-notes instead of object_notes)

### ISSUE THREAD

**Issue by mbietenholz** [astropy/astroquery#1195]
On the page
     
http://astroquery.readthedocs.io/en/latest/ned/ned.html#reference-api
[astroquery.readthedocs.io]

In the section "Fetching other data tables for an object" it has that the kind of table to fetch can be "object-notes".   It should be "object_notes" [underscore instead of dash]

**Comment by agarwalrounak** [comment]
I will work on it.
