### ISSUE TITLE
Support for Hubble Source Catalog v3?

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1208]
Hubble Source Catalog v3 released -- http://archive.stsci.edu/archive_news/2018/07-Jul/index.html#article2

It might be useful as part of cone search (which depends on it being in STScI VAO registry) or MAST. cc @tomdonaldson @ceb8

**Comment by ceb8** [comment]
As part of this PR: #1203  I updated the astroquery.mast to include HST v3.

**Comment by bsipocz** [comment]
I'm closing this one as #1203 should ended up in the latest release on pypi, deployed 3 days ago. 

Please feel free to reopen if this is not the case.
