### ISSUE TITLE
jplhorizons not working parse table

### ISSUE THREAD

**Issue by MatheusGysi** [astropy/astroquery#1212]
Hello, I'm trying to use jplhorizons query  with the last version of astroquery 0.3.9.dev4742, with the example code
```
>>> from astroquery.jplhorizons import Horizons
>>> obj = Horizons(id='3552', location='568',
...                epochs={'start':'2010-01-01', 'stop':'2019-12-31',
...                        'step':'1y'})
>>> eph = obj.ephemerides()
```
 but every time raises

> OSError: Cannot parse table column names.

When I print obj
```
print(obj)
```
> JPLHorizons instance "3552"; location=568, epochs={'start': '2010-01-01', 'stop': '2019-12-31', 'step': '1y'}, id_type=smallbody
```
print(obj.ephemerides)
```
> <function async_to_sync.<locals>.create_method.<locals>.newmethod at 0x7fdc4f966048>

Is there something that I can do to fix this problem?

Thanks

**Comment by MatheusGysi** [comment]
I'm sorry I did not found a solution before 'cause i was searching only for open issues
https://github.com/astropy/astroquery/issues/1192

**Comment by bsipocz** [comment]
@MatheusGysi - Your example code above works for me. Could you try and upgrade your astroquery version to the latest release upload to pypi yesterday (https://pypi.org/project/astroquery/0.3.9.dev480/)
No conda package is available, use `pip install --pre --upgrade astroquery`

**Comment by MatheusGysi** [comment]
Thanks a lot @bsipocz
