### ISSUE TITLE
Update gaia docs for DR2

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1217]
The default table is currently DR2, so ideally the examples should be updated to be DR2, too.

**Comment by damivik** [comment]
Hi @bsipocz 
I'm an outreachy applicant. Can I attempt this issue?

**Comment by bsipocz** [comment]
@damivik - welcome, and let us know if you have any questions.

**Comment by sebaucillon** [comment]
Hello @bsipocz and @damivik 
Is this as simple as revising the document file for gaia and making sure dr1 is replaced to dr2 or must there be some explanation as well (new features etc)?
I'd like to work on this issue as well.

**Comment by bsipocz** [comment]
Yes, this supposed to be that simple, but all the examples have to run and the outputs should be updated accordingly.

**Comment by sebaucillon** [comment]
> Yes, this supposed to be that simple, but all the examples have to run and the outputs should be updated accordingly.

I need to get myself better equipment. I had to switch to my work laptop and it's somehow not recognising astropy package, so I am unable to test anything I edit. This is bad :(

**Comment by bsipocz** [comment]
Doctesting for the gaia narrative docs is now enabled, so it reflects the actual behaviour of the module, therefore this issue is not relevant any more.
