### ISSUE TITLE
Installation into CASA

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1219]
In case anyone (...me) wants to install astroquery into CASA, you can mostly follow these instructions:

http://docs.astropy.org/en/stable/install.html#installing-astropy-into-casa

but you might encounter this issue:
```
Traceback (most recent call last):
  File "/home/casa/packages/RHEL6/prerelease/casa-prerelease-5.4.0-47/lib/python2.7/start_casa.py", line 10, in <module>
    from IPython import start_ipython
  File "/home/casa/packages/RHEL6/prerelease/casa-prerelease-5.4.0-47/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application  File "/home/casa/packages/RHEL6/prerelease/casa-prerelease-5.4.0-47/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler  File "/home/casa/packages/RHEL6/prerelease/casa-prerelease-5.4.0-47/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>    from IPython.core import ultratb
  File "/home/casa/packages/RHEL6/prerelease/casa-prerelease-5.4.0-47/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size  File "/home/casa/packages/RHEL6/prerelease/casa-prerelease-5.4.0-47/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
```

Unfortunately, you can't use CASA's pip to install the workaround, you have to use a system-level python2.7 pip.

This fails:
`/home/casa/packages/RHEL6/prerelease/casa-prerelease-5.4.0-47/bin/python -c "import pip; pip.main(['install', 'backports.shutil_get_terminal_size', '--user'])"`

this succeeds:
`/usr/local/bin/python -c "import pip; pip.main(['install', 'backports.shutil_get_terminal_size', '--user'])"`

**Comment by low-sky** [comment]
Me too.  But `pip.main()` is deprecated in recent versions of pip (18.0).  I tried several things including what I thought would work, namely a command line install with system python and a `--user`, but that didn't catch the right backports and CASA still won't start.

**Comment by keflavich** [comment]
cc @astrofrog, this affects the installation instructions for astropy.  I'm looking for a solution...
http://docs.astropy.org/en/stable/install.html

**Comment by keflavich** [comment]
https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program
Their recommendation is 
```
subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'my_package'])
```
but they preface this by saying one should run pip from the command line.  We don't have a reason to run from within CASA, except that is was theoretically easier to direct users to run commands from within CASA than to find the right executable..... and install pip...

argh, this leads me to thing the right solution is not to use pip.  I'm going to keep looking...

**Comment by low-sky** [comment]
The install seems to work, but it's the call to get `backports.shutil_get_terminal_size` doesn't seem to take.  I tried bringing up the casa python and running the subprocess from there.

**Comment by low-sky** [comment]
I've tried a few different iterations of this have not been able to get a successful `backports.shutil_get_terminal_size` installation, leaving the CASA ipython broken. Since I do have working version using `casa-pip` I'll definitely proceed with that.  When it works, it works well.

**Comment by keflavich** [comment]
How weird.  For other users, casa-pip is available here: https://github.com/radio-astro-tools/casa-python

**Comment by keflavich** [comment]
Also, this is a long-known issue:
https://github.com/radio-astro-tools/casa-python/issues/19
Too bad I, the reporter of said issue, didn't think to look it up before posting this one...

**Comment by keflavich** [comment]
Closing this: solved with the latest astropy instructions.
