### ISSUE TITLE
Add a [skip deploy] hook to not deploy on some merges

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1221]
As pointed out by @pllim [here](https://github.com/adamginsburg/astroquery-paper/issues/43#issuecomment-410362537), we sometimes *don't* want to deploy merged PRs.  We need a way to not do that.

**Comment by bsipocz** [comment]
This is done for a while now, see #1166.

The incantation is `[nodeploy]` in the merge commit message.
