### ISSUE TITLE
Panstarrs query

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1225]
xref https://github.com/astropy/astroquery/issues/896#issuecomment-312898136 (cc @ceb8 )

Is there a more "astroquery" way to do this? If not, is it in the future plan? Example below from @mkelley 

```python
import io
import requests
from astropy.io import votable

params = dict(RA=ra, DEC=dec, SR=search_radius, max_records=100,
              ordercolumn1='ndetections', descending1='on',
              selectedColumnsCsv=','.join(COLUMNS))
q = requests.get('https://archive.stsci.edu/panstarrs/search.php', params=params)

with io.BytesIO(q.text.encode()) as xml:
    tab = votable.parse_single_table(xml).to_table()
```

**Comment by caseyjlaw** [comment]
Also relevant: https://panstamps.readthedocs.io/en/latest/

**Comment by jpdeleon** [comment]
Also relevant tutorial: https://ps1images.stsci.edu/ps1image.html

**Comment by bsipocz** [comment]
And there are also examples in the astroquery.mast docs, so maybe we can close this issue:

https://astroquery.readthedocs.io/en/latest/mast/mast.html#catalog-queries
