### ISSUE TITLE
Simbad will not return more than 20,000 rows, even if ROW_LIMIT is set higher.

### ISSUE THREAD

**Issue by christinahedges** [astropy/astroquery#1230]
I am trying to use astroquery to query Simbad. I want results from a 10 square degree field, which is roughly 100,000 hits in Simbad. 

Here's a snippet of the code I'm using.

``` Python
    from astroquery.simbad import Simbad
    import astropy.units as u
    from astropy.coordinates import SkyCoord

    customSimbad = Simbad()
    customSimbad.TIMEOUT = 100000
    customSimbad.ROW_LIMIT = 0

    customSimbad.add_votable_fields('bibcodelist(1800-2018)', 'flux(B)', 'flux(V)', 'otype')
    c = SkyCoord('150, 10', unit=(u.deg, u.deg))
    result_table = customSimbad.query_region(c, radius=radius)
```

This will not return more than 20,000 rows. I can't find out why.

**Comment by christinahedges** [comment]
I've tried to use `Simbad.query_criteria()` to get around this by picking small boxes in this region, however it breaks for me. The example from the readthedocs (here https://astroquery.readthedocs.io/en/latest/simbad/simbad.html) gives an error and no data. 

```Python
    Simbad.query_criteria('region(box, GAL, 0 +0, 3d 1d)', otype='SNR')
```

Returns
![image](https://user-images.githubusercontent.com/14965634/45388170-0ca71600-b5cd-11e8-9521-e4d9838c2c19.png)

**Comment by bsipocz** [comment]
can you get out more than 20000 rows using the webform?

**Comment by christinahedges** [comment]
You're right the hard limit is set by the simbad webform.
