### ISSUE TITLE
Simbad.query_criteria() from the docs produces an error.

### ISSUE THREAD

**Issue by christinahedges** [astropy/astroquery#1231]
In trying to work around issue #1230 I've tried to use `Simbad.query_criteria()`, however it breaks for me. The example from the readthedocs (here https://astroquery.readthedocs.io/en/latest/simbad/simbad.html) gives an error and no data. 

```Python
    Simbad.query_criteria('region(box, GAL, 0 +0, 3d 1d)', otype='SNR')
```

Returns
![image](https://user-images.githubusercontent.com/14965634/45388170-0ca71600-b5cd-11e8-9521-e4d9838c2c19.png)

**Comment by christinahedges** [comment]
This issue seems to be similar to #466 and @gully's fix can produce results.

**Comment by christinahedges** [comment]
I think the fix is to change line 262 from the Simbad core.py from

``` python
    _VOTABLE_FIELDS = ['main_id', 'coordinates']
```

to

``` python
    _VOTABLE_FIELDS = ['MAIN_ID']
```

Which will actually return a result. I don't yet understand why the field needs to be all caps.

**Comment by bsipocz** [comment]
This seems to be serverside:

```
b'::script::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n\nvotable {main_id,coordinates}\nvotable open\nquery sample  region(box, GAL, 0 +0, 3d 1d) &  otype=SNR\nvotable close\n\n::console:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n\nC.D.S.  -  SIMBAD4 rel 1.7  -  2018.09.12CEST00:08:12\ntotal execution time: 4.16 secs\nsimbatch done\n\n::error:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n\n[2] java.lang.NullPointerException\n\n::data::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n\n<?xml version="1.0" encoding="UTF-8"?>\n<VOTABLE xmlns="http://www.ivoa.net/xml/VOTable/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.2" version="1.2">\n<DEFINITIONS>\n<COOSYS ID="COOSYS" equinox="2000" epoch="J2000" system="ICRS"/>\n</DEFINITIONS>\n<RESOURCE name="Simbad query" type="results">\n</RESOURCE>\n</VOTABLE>\n\n'
```

**Comment by christinahedges** [comment]
I don't think so, if I change the `_VOTABLE_FIELDS` field I get no error and a result:

![image](https://user-images.githubusercontent.com/14965634/45390647-e5544700-b5d4-11e8-9b01-b593c5e5770e.png)

**Comment by bsipocz** [comment]
well, then PRs are welcome

**Comment by aoberto** [comment]
Hello,

Yes it was serverside. Sorry, it was a temporary issue, I will try to figure out to avoid it in the future.

Sorry again

**Comment by bsipocz** [comment]
Thanks @aoberto for the info. I'm closing this issue then.

**Comment by christinahedges** [comment]
Is the serverside error fixed? I still get the same error:
```python
from astroquery.simbad import Simbad
Simbad.query_criteria('region(box, GAL, 0 +0, 3d 1d)', otype='SNR')
```

![image](https://user-images.githubusercontent.com/14965634/45447800-8b5f8a00-b685-11e8-9d04-5df2642924e7.png)

**Comment by bsipocz** [comment]
It's coming from the cache, you need to clear first. `Simbad.cache_location` shows the location.
