### ISSUE TITLE
mast query fails cryptically when too many observations are requested

### ISSUE THREAD

**Issue by eteq** [astropy/astroquery#1247]
The following code:
```
from astroquery.mast import Observations
Observations.query_criteria_async(obs_collection='HST')  #FAILS
```
consistently fails with the following exception:
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
...
~/miniconda3/envs/astro36/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The debugger reveals the root of the problem: the response from the query is:
```
> /Users/erik/miniconda3/envs/astro36/lib/python3.6/json/__init__.py(354)loads()
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

ipdb>  p len(s)
183
ipdb>  p s
'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.12.2</center>\r\n</body>\r\n</html>\r\n'
```

That is, there's a 504 error somewhere in the process of trying to get all the data.

While it may be MAST wants to fix this, I think the real problem here as far as astroquery is concerned is that the error is a `JSONDecodeError`, which doesn't really report the true problem.  So perhaps this case should be caught somehow and the true request error code passed up?

cc @ceb8

**Comment by ceb8** [comment]
I believe I've fixed this problem, I now do a raise_for_status check on the server response, so it will still be limited by whatever error the server chooses to raise, but it should at least be clear that the mast servers are the origin of the error.
