### ISSUE TITLE
Document the continuous release process

### ISSUE THREAD

**Issue by eteq** [astropy/astroquery#1250]
Right now the continuous release process is a rather non-standard approach to releasing.  That's a good thing, except that it's not really documented anywhere I can see.  We probably need to resolve #1155 before bothering to tackle this, but once that's done there should probably be a page in the developer docs that lays out exactly what the various version numbers mean.

cc @bsipocz @keflavich

**Comment by bsipocz** [comment]
For documentation we can always refer to the paper 😉 
But I agree, things need to be fixed first.

**Comment by bsipocz** [comment]
CD has not been migrated to gha, and the other open issues also kind of cover this extra docu needs (the docs already contains what the users should know about this), so I'm closing this as a duplicate.
