### ISSUE TITLE
parse_coordinates returning incorrect results

### ISSUE THREAD

**Issue by ceb8** [astropy/astroquery#1251]
astroquery.utils.commons.parse_coordinates is appending "25" to coordinates given to it:
```
>>> from astroquery.utils.commons import parse_coordinates
>>> parse_coordinates("251.51 32.36")
<SkyCoord (ICRS): (ra, dec) in deg
    (251.5125, 32.3625)>

>>>parse_coordinates("51.0 -30.003")
<SkyCoord (ICRS): (ra, dec) in deg
    (51.025, -30.0033)>
```
This comes directly from the [Sesame service](http://cds.u-strasbg.fr/cgi-bin/Sesame) which is called on the given coordinate string via astropy's [SkyCoord.from_name](http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.from_name).  

Looking at the documentation for SkyCoord.from_name and the Sesame service it is not clear that they are designed to take a coordinate as opposed to an object name.  Additionally, it seems unnecessary to call a resolver service simply to parse a coordinate string, so my recommendation is to avoid calling sesame at all on coordinate strings. Perhaps parse_coordinates need not also resolve objects?

**Comment by bsipocz** [comment]
@ceb8 - This looks very much like a bug. I also have a deja vu for `parse_coordinates` related refactoring plans, but can't find any trace of it.

The easiest fix seems to be to change the internal logic of `parse_coordinates` to only call on the name resolver once the string cannot be interpreted as a coordinate as is.

PR is to come soon.

**Comment by ceb8** [comment]
@bsipocz I should have mentioned that @tomdonaldson also sent an email to the Sesame folks to make them aware of any bugs on their side.

**Comment by bsipocz** [comment]
Actually my thinking here was rushed, too, ``"51.0 -30.003"`` cannot be really passed to the coordinate constructor as is, so reordering the internals of `parse_coordinates` does nothings :(

**Comment by ceb8** [comment]
Is that true? `SkyCoord("51.0 -30.003",unit='deg')` works for me....

**Comment by bsipocz** [comment]
yes, but only if the `unit='deg'` part is added. I'm not yet certain we can do that, but will check whether any of the services pass non degree coordinates to the function.

Anyway, I think the logic should be changed to first try to parse the string as a coordinate and only when that fails go for name resolution.

**Comment by ceb8** [comment]
@bsipocz That makes sense.
