### ISSUE TITLE
Astroquery.mast missing components in tutorial

### ISSUE THREAD

**Issue by exowanderer** [astropy/astroquery#1253]
I copy/pasted the `astroquery.mast` code as `https://mast-labs.stsci.io/` into AWS instance; but there two places that had substantial errors. 

Notebly, here are the two lines that are giving me trouble:

```python
from astroquery.mast import Observations

Observations.enable_s3_hst_dataset()
s3_urls = Observations.get_hst_s3_uris(filtered_products)
```

It seems that the `ObservationsClass` does not contain the methods `enable_s3_hst_dataset` and `get_hst_s3_uris`.  BUT: I checked the `astroquery` github repo (from which I installed `astroquery`).

Do you know why this might be an issue? Do you know if there is more updated syntax for "enabling the s3 hst" or "getting the hst s3 uris" (sidenote: i don't know what `uris` means?).

**Comment by exowanderer** [comment]
This issue was with recognizing which version python was using.

Although I installed `astroquery` from the github; there was a pre-installed version from PYPI, which was interfering with my python session. That is to say that I had 2 versions installed and python was selecting the PYPI version, which did not have the `enable_s3_hst_dataset` or `get_hst_s3_uris` methods.

**Comment by bsipocz** [comment]
self solving issues are the best kind. Thanks @exowanderer for reporting back.
fyi, we do automated releases, and you can also install these versios from PyPI with the ``--pre`` option. These automated releases are in no way any less stable than the latest manually released one, so I I can wholeheartedly can suggest to use them.

``pip install --upgrade --pre astroquery``
