### ISSUE TITLE
Spontaneous `NoResultsWarning` warning

### ISSUE THREAD

**Issue by exowanderer** [astropy/astroquery#1254]
I have been using astroquery.mast for a few days now -- including a dozen times today; but I just recently started getting a warning that says 

`WARNING: NoResultsWarning: Query returned no results. [astroquery.mast.core]`

and, in fact, the command
```python
# from https://mast-labs.stsci.io tutorial
from astroquery.mast import Observations
obsTable = Observations.query_criteria(project='HST',
                                       filters='F160W',
                                       instrument_name='WFC3/IR',
                                       proposal_id=['12062','12061','12062'])
```

Returns *no* observations (i.e. the `obsTable` is empty).  This is anomalous because I've been using this command all day to try and find test my AWS pipeline with the public data, and it worked up until about 10 minutes ago.

This implies to me that the AWS HST Public Data no longer exists or that the SQL link between them died.

I tried this command on AWS and my local machine (both of which worked within the last hour).

I further tried:

`obsTable = Observations.query_criteria(project='HST', instrument_name='WFC3/IR')`
and
`obsTable = Observations.query_criteria(project='HST')`
to try and grab all of them and see if it's just that one filter

**Comment by exowanderer** [comment]
It seems that the keyword for `projects` was changed to `obs_collection`. The command above works as expected now

**Comment by ceb8** [comment]
This was a database issue that has since been corrected, so this query is functional again.

However, the recommended way to filter by mission is to use the key "obs_collection" rather than "project."

**Comment by bsipocz** [comment]
> However, the recommended way to filter by mission is to use the key "obs_collection" rather than "project."

maybe we should raise a warning to point this out, or is this only a very soft recommendation?

**Comment by ceb8** [comment]
@bsipocz I don't think it needs a warning, because there are legitimate use cases for filtering on project, it's just that project != obs_collection for all missions. The spontaneous failing of this query due to database changes was a database mistake and should not happen again.

**Comment by exowanderer** [comment]
There should be a warning when any flag is changed; at least a 'depreciation' warning.

There are existing, official tutorials that include the case `project='HST'`. So instead of the usage error ('warning') for "NoResultsWarning", the user could have a more constructive response: "the filter `project` has been changed to `obs_collection` for most cases; if no results are found, try `obs_collection`".

Otherwise, a user of those tutorials and scripts has to google `NoResultsWarning` and find this issue page.

**Comment by ceb8** [comment]
@exowanderer Yes, however that column was not supposed to have been changed, so the solution in this case was to change it back rather than issue a warning. The meaning of the keywords "project" and "obs_collection" have not changed and are documented here: https://mast.stsci.edu/api/v0/_c_a_o_mfields.html.
