### ISSUE TITLE
Planck Query To SkyView Now Gives 404

### ISSUE THREAD

**Issue by Stargrazer82301** [astropy/astroquery#1267]
Within the past few days, astroquery.SkyView is no longer able to retrieve Planck data. Whilst list_images and get_images still receive URLs from SkyView, they simply lead for 404 errors. For instance: https://skyview.gsfc.nasa.gov/tempspace/fits/skv32527833284.fits

This issue is not affecting all SkyView services. Also, Planck maps can still be retrieved from SkyView when interacting with the website manually.

**Comment by keflavich** [comment]
Could you compare the URL of an astroquery request to one from skyview?  Maybe they changed their URL and we need to update it.

**Comment by Stargrazer82301** [comment]
Looking at the code, I think that astroquery doesn't use URLs to sent requests to SkyView, but instead uses BeautifulSoup to actually interact with the webform.

The result URL returned by astroquery, like the example above, appears to have the same format as the ones given by SkyView when interacting with it manually. Just the ones given by astroquery all 404.

**Comment by keflavich** [comment]
OK, can you put a sample failed query here?

**Comment by Stargrazer82301** [comment]
Here's one:

SkyView.get_image_list('80.8942 -69.7561', 'Planck 030', pixels='352', radius=astropy.units.Quantity(20.0, unit='deg'))

**Comment by keflavich** [comment]
I can't reproduce any error.  The return from running that for me was:
`https://skyview.gsfc.nasa.gov/tempspace/fits/skv445129826707.fits`

and downloading worked fine:
```
In [6]: SkyView.get_images('80.8942 -69.7561', 'Planck 030', pixels='352', radius=astropy.units.Quantity(20.0, unit='deg'))
/Users/adam/repos/astroquery/astroquery/utils/commons.py:171: UserWarning: Coordinate string is being interpreted as an ICRS coordinate provided in degrees.
  warnings.warn("Coordinate string is being interpreted as an "
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv445129826707.fits
|======================================================================================================================================================================================| 509k/509k (100.00%)         0s
Out[6]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x115e80940>]]
```

I'm curious what's going wrong for you.  Are you using the latest version of astroquery?

**Comment by Stargrazer82301** [comment]
How odd. I am indeed using the latest version. In fact, I was originally using the latest release (0.3.8), and also tried updating to the latest dev release, to no avail.

The query above definitely doesn't work for me. _But_, if I pass the `pixels` kwarg as an `int` instead of a `str`, the query _does_ work. Which seems strange to say the least.

**Comment by bsipocz** [comment]
Checking this now, it works for me, too. If it's still an issue for you @Stargrazer82301, then could you please try again after clearing the cache (``rm -r ~/.astropy/cache/astroquery/``)?

**Comment by Stargrazer82301** [comment]
I am now getting good output again (didn't even need to clear the cache) - thanks for help!

**Comment by bsipocz** [comment]
Glad to hear. 

Feel free to open a new issue if you run into problems again.
