### ISSUE TITLE
In a Vizier query, width and height are wrongly swapped

### ISSUE THREAD

**Issue by eztean** [astropy/astroquery#1269]
I noticed this by doing simple rectangular 2MASS queries, for which the width and height are swapped in the resulting star samples. I think these are the relevant lines in the code: 

https://github.com/astropy/astroquery/blob/d950234e9fd3f17824547fed77943766aa00e3a8/astroquery/vizier/core.py#L426-L427

**Comment by keflavich** [comment]
Looks like a simple fix.  A PR would be welcome.

**Comment by bsipocz** [comment]
This has been fixed by #1406
