### ISSUE TITLE
Auto-logout issue with ESO retrieve_data

### ISSUE THREAD

**Issue by AnthonyCheetham** [astropy/astroquery#1272]
The ESO portal automatically logs users out after 2hrs. When downloading large datasets using the EsoClass.retrieve_data function in https://github.com/astropy/astroquery/blob/master/astroquery/eso/core.py , this results in all remaining files being replaced by a html file of the ESO login page.

There are a few potential solutions to this. For example, the function could check whether the downloaded files are as expected (i.e. not a html file), or check the authentication status before downloading each file.

**Comment by saimn** [comment]
Same issue here, I will try to find a solution.
