### ISSUE TITLE
Possible IRSA dust query bug: inconsistent handling of sky coordinate formats

### ISSUE THREAD

**Issue by mattgrayling** [astropy/astroquery#1280]
Firstly, I'm a first time commenter so my apologies if the format of this post isn't right. I'm using astroquery.irsa_dust for my research and am having some problems using get_query_table. I'm trying to open a number of identically-formatted data tables, retrieve the RA and Dec and then query IRSA dust for the extinction data (I'm using get_query_table rather than get_extinction_table as I'm specifically after just the colour excess). The code is shown below:

    from astroquery.irsa_dust import IrsaDust
    import astropy.units as u
    from astropy import coordinates
    import os
    from astropy.io import ascii

    for filename in os.listdir('./Data'):
        fp = open('./Data/{0}'.format(filename))
    
        for line in fp:
            if line[0:2] == 'RA':
                RA = line.split()[1]
            if line[0:4] == 'DECL':
                Dec = line.split()[1]
                break
        print(RA,Dec)
        co = coordinates.SkyCoord(ra=RA, dec = Dec,  unit=(u.deg,u.deg))
        print(co)
        table = IrsaDust.get_query_table(co,section='ebv')

I have a small subset of data in a folder called Initial_Data, and when I use this folder instead the code works perfectly. However, when using the full set of data as in the code above I get the following error:

    runfile('/home/matt/Documents/Lightcurves/extinction.py', wdir='/home/matt/Documents/Lightcurves')
    53.599800 -28.714764
    <SkyCoord (ICRS): (ra, dec) in deg
        (53.5998, -28.714764)>
    Traceback (most recent call last):

      File "<ipython-input-4-449177a18559>", line 1, in <module>
        runfile('/home/matt/Documents/Lightcurves/extinction.py', wdir='/home/matt/Documents/Lightcurves')

      File "/home/matt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

      File "/home/matt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

      File "/home/matt/Documents/Lightcurves/extinction.py", line 20, in <module>
    table = IrsaDust.get_query_table(co,section='ebv')

      File "/home/matt/anaconda3/lib/python3.7/site-packages/astroquery/irsa_dust/core.py", line 299, in get_query_table
    xml_tree = utils.xml(response.text)

      File "/home/matt/anaconda3/lib/python3.7/site-packages/astroquery/irsa_dust/utils.py", line 119, in xml
    raise Exception("The dust service responded with an error: " + message)

    Exception: The dust service responded with an error: 
        ERROR: required input [location] is missing.

No matter which table I start with, the error always occurs on the first one. I know that RA and Dec are being retrieved correctly and that the coordinates object is being created, so I don't understand why this error occurs. I have checked for a number of different coordinates on the IRSA website and there is data available. I have also tried retrieving the coordinates and inputting them as a string but this still doesn't work.

I have also looked at the data set that does work and still notice some irregularities. The code works when defining a coordinates.SkyCoord object as above but putting in the same coordinates as a string gives the same error:

    In [6]: co
    Out[6]: 
    <SkyCoord (ICRS): (ra, dec) in deg
        (34.906941, -6.071715)>

    In [7]: table = IrsaDust.get_query_table(co,section='ebv')

    In [8]: table = IrsaDust.get_query_table('2h19m37.67 -6d4m18.17s',section='ebv')
    /home/matt/anaconda3/lib/python3.7/site-packages/astroquery/utils/commons.py:162: UserWarning: Coordinate string is being interpreted as an ICRS coordinate.
      warnings.warn("Coordinate string is being interpreted as an "
    Traceback (most recent call last):

      File "<ipython-input-8-f8614cacb31e>", line 1, in <module>
    table = IrsaDust.get_query_table('2h19m37.67 -6d4m18.17s',section='ebv')

      File "/home/matt/anaconda3/lib/python3.7/site-packages/astroquery/irsa_dust/core.py", line 299, in get_query_table
        xml_tree = utils.xml(response.text)

      File "/home/matt/anaconda3/lib/python3.7/site-packages/astroquery/irsa_dust/utils.py", line 119, in xml
    raise Exception("The dust service responded with an error: " + message)

    Exception: The dust service responded with an error: 
        ERROR: required input [location] is missing.

Essentially, I have two questions.

1) Why does the first section of code work for one set of table data but not for another set of identically formatted data?

2) Why does one coordinate not work as a string when it works as a SkyCoords object and as a string on the IRSA dust website?

I'm not sure if there's something else I could have done wrong or if there's a bug in the code. I've had others look who have more experience and they can't see what's going wrong. Thank you very much for your time, please let me know if there's anything else I can provide that would be helpful.

**Comment by keflavich** [comment]
In general, could you please copy & paste text rather than take screenshots?

I attempted your last query, and it worked without issue for me:
```
In [3]: from astroquery.irsa_dust import IrsaDust

In [4]: IrsaDust.get_query_table('2h19m37.67 -6d4m18.17s', section='ebv')
/Users/adam/repos/astroquery/astroquery/utils/commons.py:159: UserWarning: Coordinate string is being interpreted as an ICRS coordinate.
  warnings.warn("Coordinate string is being interpreted as an "
Out[4]:
<Table length=1>
    ext desc                                                              ext image                                                           ... ext SFD max ext SFD min
                                                                                                                                              ...
    bytes100                                                               bytes255                                                           ...   float64     float64
---------------- ---------------------------------------------------------------------------------------------------------------------------- ... ----------- -----------
E(B-V) Reddening https://irsa.ipac.caltech.edu:443//workspace/TMP_fgSgUH_26392/DUST/34.906964058380055_-6.071714979149301.v0001/p165Dust.fits ...      0.0254      0.0242
```

So, I don't know what's going wrong.  It looks like the data are somehow getting uploaded incorrectly?  Could you tell us what version of `astroquery`, `requests`, and `astropy` you're using?

**Comment by mattgrayling** [comment]
Sorry, noted, I'll provide text next time. I'm using astroquery v0.3.7, requests v2.19.1 and astropy v3.0.4, running on Python 3.7.0 on Ubuntu 18.04.1. I've also tried running it in Python 3.5.6 but had the same result.

**Comment by keflavich** [comment]
Your astroquery version is quite out of date, you should update.  The problem *may* be that IRSA has moved to https.  I don't know why it works for you some of the time - maybe they have a flaky redirect from http->https?

**Comment by mattgrayling** [comment]
Okay, I've updated and it seems to be working now. I recently installed astroquery through pip but should've tried updating it first, thanks very much for your help.
