### ISSUE TITLE
Change HTTP user-agent when running CI

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1281]
To help archives separate out user & testing statistics, we can change the HTTP user agent when running from CI.  This should be pretty easy....

**Comment by amet-vikram13** [comment]
Hello @keflavich I would like to take up this issue. Can you just tell me where to start looking into it..

**Comment by vaishnav97** [comment]
@keflavich Which CI are you talking about here - Travis or CircleCI? I have heard of these two only. If you are talking about some other CI, then please tell me so that I can learn and start solving this issue.

**Comment by keflavich** [comment]
Both

**Comment by kakirastern** [comment]
Hi @keflavich! Can I work on this issue?

**Comment by bsipocz** [comment]
Feel free to!

**Comment by kakirastern** [comment]
I would like to prepare for GSoC 2019 and this seems like something I should work on in order to learn about CI testing as applied to astroquery.

**Comment by kakirastern** [comment]
@bsipocz Yup, cool! I will start work on it and open a PR to follow up soon.

**Comment by kakirastern** [comment]
Just wanted to check: I suppose I will need to change both [https://github.com/astropy/astroquery/blob/master/.travis.yml](https://github.com/astropy/astroquery/blob/master/.travis.yml) and [https://github.com/astropy/astroquery/blob/master/appveyor.yml](https://github.com/astropy/astroquery/blob/master/appveyor.yml)?

**Comment by kakirastern** [comment]
I noticed the headers for the user-agent are set in [https://github.com/astropy/astroquery/blob/master/astroquery/query.py#L148](https://github.com/astropy/astroquery/blob/master/astroquery/query.py#L148) and [https://github.com/astropy/astroquery/blob/master/astroquery/utils/commons.py#L81](https://github.com/astropy/astroquery/blob/master/astroquery/utils/commons.py#L81)...

**Comment by kakirastern** [comment]
PR #1394 opened to deal with this issue. Ready for a review...

**Comment by bsipocz** [comment]
#1307 has addressed this.
