### ISSUE TITLE
Change versioning to work nicely with pip

### ISSUE THREAD

**Issue by cdeil** [astropy/astroquery#1295]
This issue is triggered by the question by @bmatthieu3 via email:
> Do you know the date for the next release of astroquery (v0.3.9) ? Some people have been asking me when they will be able to use astroquery.cds which should be available for the next release.

Indeed currently users will get https://pypi.org/project/astroquery/0.3.8/  from April 2018 if they use the usual command to install or update:
```
pip install astroquery
pip install -U astroquery
```
Looking at https://pypi.org/project/astroquery/#history one can see that there are plenty of new releases, e.g. https://pypi.org/project/astroquery/0.3.9.dev5086/ from earlier today.
But pip doesn't pick them up.

@keflavich @bsipocz - I know you want to do a continuous and frequent releases model for astroquery. That's fine.

But can you please change the versioning scheme to something that `pip` will understand and pick up by default?

I'm sure there's special pip flags and you can document those, but still - most users will just do `pip install astroquery` and expect to get the latest version, and get 0.3.8, which IMO is bad.

**Comment by keflavich** [comment]
@cdeil - you need to do `pip install --pre astroquery`.  We will release a new big numbered version soon, but do tell users to switch to `--pre` as well.

**Comment by cdeil** [comment]
> We will release a new big numbered version soon

That's good!

> tell users to switch to --pre

Like I said, I think that's weird and not a good idea. But I don't want to argue, I'm not even using astroquery myself any more, I just wanted to note the suggestion to change that again. Or introduce more frequent normal releases that `pip install astroquery` will pick up, that would do the trick as well.

**Comment by bsipocz** [comment]
Yes, the fix is in the work as well as a new manually tagged release, but anyone reading our docs should see that the current setup is to use ``--pre`` for the automated releases. It's not a secret trick but something widely communicated all over.

**Comment by bsipocz** [comment]
#1604 is a concrete proposal of how to achieve this while also keep a way to note the automatically deployed versions. So I'm closing this now as a duplicate.
