### ISSUE TITLE
Coordinates in IRSA queries have insufficient precision

### ISSUE THREAD

**Issue by stargaser** [astropy/astroquery#1306]
The `ra` and `dec` columns in IRSA queries can have insufficient precision. The first cone search example in the documentation for `astroquery.irsa` can be used to reproduce this.

```
from astroquery.irsa import Irsa
import astropy.units as u
table = Irsa.query_region("m31", catalog="fp_psc", spatial="Cone",  radius=2 * u.arcmin)
print(table)
```

When `table` is output to FITS, the precision is fine. When `table` is output to an IPAC table, the `ra` and `dec` columns carry only three decimal places which is insufficient.

A user can change the `.format` attribute of these columns to get their desired precision when writing to an IPAC table.

I have examined the VOTable string returned from the IRSA query. The `width` and `precision` of the `.format` attribute are set there.

**Comment by bsipocz** [comment]
@stargaser - can we close this now that #1313 is merged?

**Comment by stargaser** [comment]
yes -- I see the online docs include this section. Thank you for all the help! Closing the issue.

**Comment by stargaser** [comment]
I should have mentioned, the IRSA archive will also increase the precision specified for ra and dec in their VOTable outputs. They have made an internal ticket for it.
