### ISSUE TITLE
NASA Exoplanet all columns unused in query_planet

### ISSUE THREAD

**Issue by wtgee** [astropy/astroquery#1317]
#1183 added in the `all_columns` parameter to `get_confirmed_planets_table` and `query_planet` methods, but it is missing on [line 104 of `query_planet`](https://github.com/astropy/astroquery/blob/1e93977c12a85f4b2c68ec258990f9d9af7485d7/astroquery/nasa_exoplanet_archive/nasa_exoplanet_archive.py#L104).

I can put together a simple fix, but it's a little unclear to me if passing this will trigger a new download if the previous download is cached. If that is handled automagically then the PR is trivial. Will submit PR soon. Edit: see PR #1318 for suggested fix.

**Comment by bsipocz** [comment]
Fixed by #1318
