### ISSUE TITLE
Changes to alma.archive_url variable are ignored after the first alma.stage_data() call

### ISSUE THREAD

**Issue by alipnick** [astropy/astroquery#1320]
If more than one call to alma.stage_data() is successful (Issue #1319), subsequent calls of alma.stage_data() ignore re-definitions of the alma.archive_url variable (see ipython session below).

```python
In [1]: from astroquery.alma import Alma as alma

In [2]: alma.login('alipnick')
WARNING: No password was found in the keychain for the provided username. [astroquery.query]
alipnick, enter your password:

INFO: Authenticating alipnick on asa.alma.cl ... [astroquery.alma.core]
INFO: Authentication successful! [astroquery.alma.core]

In [3]: link_list = alma.stage_data('uid://A001/X1320/X114')
INFO: Staging files... [astroquery.alma.core]
......
In [4]: alma.archive_url
Out[4]: u'http://almascience.org'

In [5]: alma.archive_url = u'bogus'

In [6]: alma.archive_url
Out[6]: u'bogus'

In [7]: link_list2 = alma.stage_data('uid://A001/X1320/X114')
INFO: Staging files... [astroquery.alma.core]
.....
In [8]: link_list['URL'][0]
Out[8]: u'https://almascience.nrao.edu/dataPortal/requests/alipnick/1646491138733/ALMA/uid___A002_Xd1ff61_X473c/2017.1.00894.S_uid___A002_Xd1ff61_X473c.asdm.sdm.tar'

In [9]: link_list2['URL'][0]
Out[9]: u'https://almascience.nrao.edu/dataPortal/requests/alipnick/1646491344818/ALMA/uid___A002_Xd1ff61_X473c/2017.1.00894.S_uid___A002_Xd1ff61_X473c.asdm.sdm.tar'
```
I should note that changing the variable alma.archive_url _before_ the first call to alma.stage_data() does work but specifically changes to the variable after the first call are ignored.

**Comment by pllim** [comment]
That is because it is cached:

https://github.com/astropy/astroquery/blob/b93761514fb5c2b54aada87dcfb41f29ad8f2830/astroquery/alma/core.py#L220-L235

Maybe ALMA maintainer can advise on how to clear the cache but from the code itself, looks like a feature and not a bug.

**Comment by alipnick** [comment]
I've tried an astroquery.alma.Conf().reset() but it didn't work to change alma.archive_url variable. But I'm also not sure if that is expected to work or not, I'm pretty out of my element at this point.

**Comment by pllim** [comment]
A hack is to do `del self.dataarchive_url` and then set `alma.archive_url` (untested) but that is indeed very hacky.

**Comment by alipnick** [comment]
Thanks for the quick work-around, I just tested it and it does work, but I would like to know how to actually clear the cache...

**Comment by keflavich** [comment]
This is somewhat intentional.  You should create a new Alma instance for
each stage_data query.

More detail later; on mobile

**Comment by alipnick** [comment]
Hi @keflavich, can you tell me how to create a new Alma instance? I use astroquery as part of an automated script so I'm not sure I really have the option of opening up a separate session if I need to change the `alma.archive_url` variable. Unfortunately, it's very common for the connection to the NA Archive to drop so in cases where the connection is unstable, I'd like to be able to switch ARCs to try using the ESO Archive instead.

**Comment by alipnick** [comment]
@keflavich thanks for the solution!
