### ISSUE TITLE
Issue installing with pip 19

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroquery#1344]
Astroquery is not installable with pip 19+ due to the presence of the pyproject.toml file (which disables all imports unless specified in the build requirements of pyproject.toml). According to @Cadair, the fix is to add the following to ``setup.py``:

https://github.com/sunpy/sunpy/pull/2906/files#diff-2eeaed663bd0d25b7e608891384b7298R18

Another option is to change baldrick so that it doesn't rely on the pyproject.toml file since using the bot shouldn't automatically lead us to use build isolation...

**Comment by Cadair** [comment]
> Another option is to change baldrick so that it doesn't rely on the pyproject.toml file since using the bot shouldn't automatically lead us to use build isolation...

No. This is a pip bug and there are many more tools other than baldrick that use `pyproject.toml` as described by PEP 518.

The easiest fix is the one the committed to SunPy and that is what I recommend you do.

**Comment by keflavich** [comment]
@astrofrog - whatever solution you come up with, I'm fine with.  https://github.com/astropy/astroquery/blame/master/pyproject.toml
