### ISSUE TITLE
nasa_exoplanet_archive module would benefit from a query_star function

### ISSUE THREAD

**Issue by sealauren** [astropy/astroquery#1351]
At the moment there is a query_planet() function but not a query_star() function [as far as I can tell].  This would be a great feature to develop! @bmorris3

**Comment by sashank27** [comment]
Hi! I would like to take up this issue. May I know where to start on this? @bsipocz

**Comment by sealauren** [comment]
I think with some basic pandas groupby logic you can fetch the stars rather
than the planets.

**Comment by sashank27** [comment]
I explored the API, and I guess I would be required to use the Kepler Stellar Table, using the `keplarstellar` delivery name. Am I correct? @bsipocz @sealauren @bmorris3 
Also, I am new to this, so a little help on the API would be great!

**Comment by sashank27** [comment]
@sealauren @bsipocz @bmorris3 Am I correct in my approach?

**Comment by keflavich** [comment]
I can't say whether that's the right approach, having no experience with this, but I suggest that you try to get something working and submit it as a PR, then ask more detailed questions.

**Comment by bmorris3** [comment]
@sashank27 The correct approach would be to add a keyword argument to the `get_confirmed_planets_table` method, perhaps called `index_by_star=False`, which will indicate the star should be index as @sealauren requests. Then [these lines](https://github.com/astropy/astroquery/blob/master/astroquery/nasa_exoplanet_archive/nasa_exoplanet_archive.py#L81-L87) would be tweaked in the case that `index_by_star == True`.

**Comment by bsipocz** [comment]
Long term this module need to be refactored to both use the common astropy API, and also to query the archive using their API rather than hacking with the downloaded full table. 

This current solution is more a quick way around than an extendable solution.

**Comment by alexiscoutinho** [comment]
@bsipocz What do you mean by "common astropy API"? What classes/modules?

**Comment by bsipocz** [comment]
This functionality has been added some time ago, and now `query_object()` takes either planet or host star name. Also, more flexibility has been added very recently as well as more docs,  so I'm going ahead and close this issue now.
