### ISSUE TITLE
astroquery.simbad missing Gaia DR2 Identifiers

### ISSUE THREAD

**Issue by jacobhhamer** [astropy/astroquery#1368]
Using astroquery version 0.3.9:

For some objects, SIMBAD shows a Gaia DR2 identifier when queried on the website, but when querying with astroquery.Simbad, the Gaia DR2 identifier does not appear.  One object for which the query works is WASP-18. One object for which it fails is WASP-12.

![wasp12simbadonline](https://user-images.githubusercontent.com/25343516/53264915-df49b280-36aa-11e9-863b-7a754a8333c9.png)
![wasp12simbad](https://user-images.githubusercontent.com/25343516/53264916-dfe24900-36aa-11e9-8a15-1ce986da0729.png)

**Comment by keflavich** [comment]
What's the error here?  The query you show appears to be successful for WASP-12.

**Comment by jacobhhamer** [comment]
The error is that not all of the identifiers for the object appear when queried through astroquery.simbad.Simbad.query_objectids(). Note that the browser query includes a Gaia DR2 id, but the astroquery response does not. Is this due to a mistake on my part?

**Comment by keflavich** [comment]
Clear your cache by deleting `~/.astropy/cache/astroquery/Simbad/...` or redo the query with `cache=False`:
```
In [6]: Simbad.query_objectids('WASP-12', cache=False)
Out[6]:
<Table length=8>
             ID
          bytes28
----------------------------
     2MASS J06303279+2940202
             UCAC2  42216354
                     WASP-12
                  SPOCS 2670
Gaia DR2 3435282862461427072
             TYC 1891-1178-1
             NAME Bergfors-6
Gaia DR1 3435282862461427072
```

**Comment by jacobhhamer** [comment]
Thanks! Closing issue.
