### ISSUE TITLE
XMatch available tables

### ISSUE THREAD

**Issue by stefanocovino** [astropy/astroquery#1377]
Dear friends,

I am not sure this is a problem or simply I am missing something.

However, there are several tables that  are available by the "vizier", i.e. 'vizier:VII/281/glade2', 'vizier:I/345/gaia2'. However, these tables are not available according to a query as:
XMatch.is_table_available('vizier:I/345/gaia2')

Is anything that can be solved from a user's side?

python 3.5
astroquery 0.3.9

Thanks, 
   Stefano

**Comment by bsipocz** [comment]
Could you provide a bit more info? This works for me:

```
In [1]: import astroquery
In [2]: astroquery.__version__
Out[2]: '0.3.9'
In [3]: from astroquery.xmatch import XMatch
In [4]: XMatch.is_table_available('vizier:I/345/gaia2')
Out[4]: True
```

**Comment by stefanocovino** [comment]
Hi Brigitta,

thanks for your rapid reply.

This is what I get with your example:

import astroquery
astroquery.__version__
'0.3.9'
from astroquery.xmatch import XMatch
XMatch.is_table_available('vizier:I/345/gaia2')
False


I am on a Mac OSX running Mojave (10.14.2). Python 3.5 (miniconda). What else could be useful to know for this issue?

Bye,
  Stefano

**Comment by keflavich** [comment]
You need to clear your cache.  Something like:
`rm ~/.astropy/cache/astroquery/XMatch/*`
will do it, but be sure you want to delete everything there first.

**Comment by stefanocovino** [comment]
Hi Adam,

thanks a lot. Now it works as expected.

Bye,
  Stefano
