### ISSUE TITLE
ALMA upstream: logging in no longer works

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1381]
Reported by a user and confirmed; logging in seems to be temporary or breaks somewhere.  I cannot retrieve data at the moment.

**Comment by keflavich** [comment]
Followup: I can't debug this at all; apparently the ALMA science archive is totally toast at the moment.  I can't log in via the web at all.  However, I was able to on Friday, so it's unclear to me what's going on.

**Comment by keflavich** [comment]
ALMA changed their login URL from `asa.alma.cl` to `rh-cas.alma.cl`, which broke everything.  It was still possible to log in to `asa.alma.cl`, but it stopped doing anything.  This is now solved in #1369.

**Comment by bsipocz** [comment]
🤦‍♀️

**Comment by keflavich** [comment]
Closed by #1369

**Comment by alipnick** [comment]
Just FYI, ALMA appears to have changed the URL back to `asa.alma.cl` from rh-cas with an update that was performed yesterday.
