### ISSUE TITLE
Help: mass of body from JPL Horizons

### ISSUE THREAD

**Issue by waterfl0w** [astropy/astroquery#1382]
I hope this is the right place to ask this question but it seems as if I am not able to query the mass of celestial body through the JPL Horizons module. I checked the documentation https://astroquery.readthedocs.io/en/latest/api/astroquery.jplhorizons.HorizonsClass.html#astroquery.jplhorizons.HorizonsClass but I cannot find an appropriate call.

Thank you for your time.

**Comment by mommermi** [comment]
No, `jplhorizons` is not able to query masses - but `jplsbdb` is:

    from astroquery.jplsbdb import SBDB
    from astropy import constants as const 
    ceres = SBDB.query('Ceres', phys=True)
    (ceres['phys_par']['GM']/const.G).to('kg')
    <Quantity 9.38382519e+20 kg>

However, please note that masses are only available for a tiny number of objects.
