### ISSUE TITLE
JPL SBDB doc related query

### ISSUE THREAD

**Issue by Himanshu-Garg** [astropy/astroquery#1387]
the doc related to SBDB [available here](https://astroquery.readthedocs.io/en/latest/jplsbdb/jplsbdb.html) - 

while writing the following commands-

- from astroquery.jplsbdb import [SBDB]
- sbdb = SBDB.query('3552')
- print(sbdb)

it gives a long list like - 
![Screenshot (158)](https://user-images.githubusercontent.com/43913398/54601776-f0959d00-4a65-11e9-8bab-5c4e673dee57.png)

here in elements section; names like e,a,q,i,om, etc are very confusing and their full form is missing in the doc.
so after doing a lot of search, I found the meaning at [SBDB website](https://ssd-api.jpl.nasa.gov/doc/sbdb.html)

its screenshot is as follows:
![Screenshot (159)](https://user-images.githubusercontent.com/43913398/54601943-4e29e980-4a66-11e9-9454-747fca10c894.png)

so, i suggest that the title of these symbols should be displayed in the doc (available at astrowuery) also.
such as 
e - eccentricity
q - perihelion distance
etc

**Comment by Himanshu-Garg** [comment]
I am interested in updating the doc related to this, if you agrees...

**Comment by keflavich** [comment]
Sounds like a good idea, go ahead and work on that change.

**Comment by Himanshu-Garg** [comment]
Sure...
