### ISSUE TITLE
ALMA: Logging in works but stage_data() still requests login

### ISSUE THREAD

**Issue by alipnick** [astropy/astroquery#1395]
Logging in to the ALMA archive in the normal way works like usual and shows that I have authenticated. However, when I go to stage the data, I receive an error message saying that I must login. Running the alma.login() command again shows that I have been successful so it's not clear where the issue is coming from. 

``` python
>>> from astroquery.alma import Alma as alma
>>> alma.login('alipnick')
alipnick, enter your ALMA password:

INFO: Authenticating alipnick on asa.alma.cl ... [astroquery.alma.core]
INFO: Authentication successful! [astroquery.alma.core]
True

>>> MOUS = ['uid://A001/X1296/Xbbd', 'uid://A001/X87d/X839', 'uid://A001/X133d/X1bfe', 'uid://A001/X87d/X630']
>>> link_list = alma.stage_data(MOUS) 
INFO: Staging files... [astroquery.alma.core]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da_data/lava-RHEL7/LAVA-RHEL7/lib/python2.7/site-packages/astroquery/alma/core.py", line 291, in stage_data
    raise ValueError("You must login before downloading this data set.")
ValueError: You must login before downloading this data set.

>>> alma.login('alipnick')
INFO: Already logged in. [astroquery.alma.core]
True
```

**Comment by alipnick** [comment]
My apologies, this appears to be a symptom of Issue #1381. I updated `_login` in `alma/core.py` to use `rh-cas.alma.cl` instead of `asa.alma.cl` and it fixed the issue.

**Comment by keflavich** [comment]
@alipnick #1369 fixed this, so if you install the most recent astroquery, it should work again.

**Comment by teuben** [comment]
ah, I ran into the same just now.   conda and pip didn't work (not updated yet), so installing from source was the way I got mine to work.

**Comment by bsipocz** [comment]
`pip install --upgrade --pre astroquery` picks up the latest auto deployed release.

**Comment by alipnick** [comment]
Just FYI, ALMA issued an update yesterday to their CAS login service which changed the login URL *back* to `asa.alma.cl`.

**Comment by keflavich** [comment]
thank you - everything broke yesterday and it was sad =(
