### ISSUE TITLE
Simbad main identifier 

### ISSUE THREAD

**Issue by dagnic** [astropy/astroquery#1411]
Hello, 

This a proposition of improvement.

I think it would be useful that `Simbad.query_objectids()` return as the first element of the Table, the main identifier (the one given by  `Simbad.query_object()`).

**Comment by bsipocz** [comment]
@dagnic - I'm afraid we can't do much about it here, the IDs are returned from the server unordered and we just parse that response, in the order they provide it, into a Table. 
As you said the main ID is kind of already available when doing `query_object, so I would suggest you use that method to get it.

**Comment by keflavich** [comment]
I'm closing this since we have a workaround and it is effectively only correctable via upstream changes.
