### ISSUE TITLE
NIST query returns JavaScript mixed into table

### ISSUE THREAD

**Issue by abostroem** [astropy/astroquery#1417]
I'm running astroquery version 0.3.9

The first example in the NIST documentation returns JavaScript in some of the columns:
```
import astroquery                                                                                                                                               
from astroquery.nist import Nist                                                                                                                                
import astropy.units as u       
table = Nist.query(4000 * u.AA, 7000 * u.AA, linename="H I")      
print(table) 
```
Returns:

   Observed        Ritz      Rel.     Aki        fik     Acc.        Ei           Ek              Lower level           Upper level      Type    TP        Line    
------------- ------------- ------ ---------- ---------- ---- ------------------------------ --------------------- --------------------- ---- -------- ------------
           -- 4102.85985517     --  4287700.0   0.021641  AAA <span id="001001.001.000002" c ass="en_span" onclick "selectById('001001.0  1.0 002')" o mouseover="s
           -- 4102.86191087     --   245010.0 0.00061831  AAA <span id="001001.001.000002" c ass="en_span" onclick "selectById('001001.0  1.0 002')" o mouseover="s
           --     4102.8632     --         --         --   --                             --              |      |              |      |   --       --          c57

**Comment by bsipocz** [comment]
This has been fixed in #1359, please try the latest release from PyPI with 
`pip install --upgrade --pre astroquery`.
