### ISSUE TITLE
astroquery.eso new instruments APICAM and MASCOT 

### ISSUE THREAD

**Issue by jmilou** [astropy/astroquery#1420]
I need to access via a programmatic interface such as that provided by astroquery.eso to the achival images of the Paranal all-sky cameras APICAM and MASCOT. 

These 2 cameras can be queried as any other science instruments from the ESO archive http://archive.eso.org/eso/eso_archive_main.html however they do not appear as available instruments from the astroquery.eso API.

Could it be added to the list of instruments that can be queried from astroquery.eso ?

**Comment by bsipocz** [comment]
The current way we query the archive is via the individual instrument query forms (supported instruments are listed here: http://archive.eso.org/cms/eso-data/instrument-specific-query-forms.html). The all-sky cameras don't seem to be supported by this backend.

Contributions are welcome to add workaround to provide access to those observations, but I expect this to be non trivial amount of work to do it right.

**Comment by jmilou** [comment]
Thanks a lot for your reply. I asked the ESO archive if this was feasible and they actually explained me that this is already supported by astroquery (even though neither APICAM or MASCOT is part of the supported instruments). 

Here is an example of code to download APICAM data for instance: 

```
   from astroquery.eso import Eso
   eso = Eso()
   eso.login("YOURUSERNAME")
  
   # Example of a query using the eso_archive_main interface:
   table = eso.query_main(column_filters={'instrument': 'APICAM', 'filter_path': 'Red', 'stime':'2018-12-17', 'etime':'2018-12-19'}, cache=False)
  
   print(table)
  
   # Downloading the first 2 encountered APICAM files
   data_files = eso.retrieve_data(table['Dataset ID'][:2])
```

**Comment by keflavich** [comment]
That's pretty neat.  Would you be willing to add this example to the documentation?  It's not obvious how to do this, as you noted.

**Comment by jmilou** [comment]
I can, if I get a bit of guidance on how to do that

**Comment by keflavich** [comment]
Edit the documentation under [`astroquery/docs/eso/eso.rst`](https://github.com/astropy/astroquery/blob/master/docs/eso/eso.rst) and submit a pull request.  See https://www.astropy.org/contribute.html for a lot more detail

**Comment by jmilou** [comment]
Perfect. I'll do that in the next days and submit the pull request

**Comment by jmilou** [comment]
Done: pull request #1432 [https://github.com/astropy/astroquery/pull/1432]
