### ISSUE TITLE
astropy.timeseries.TimeSeries should be returned when sensible

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1443]
The idea came up on our (UW) time domain meeting that it would be great to receive `astropy.timeseries.TimeSeries` from astroquery queries where the object is actually a timeseries. 

E.g mast could support this alreay, and in the future it would be a good way to provide ZTF/LSST etc timeseries to users.

**Comment by bsipocz** [comment]
We should add labels for the affected modules, but atm I'm not 100% which could be do this right away.

cc @ceb8

**Comment by ceb8** [comment]
I think this is a great idea! mast is not set up to do this right away (unless TimeSeries can handle target pixel file data, I didn't see anything about that in the docs, but I didn't look that hard), but it would be a nice thing to do in conjunction with the work suggested in this issue: https://github.com/astropy/astroquery/issues/1374
