### ISSUE TITLE
Add parameters to jplhorizons.vectors to specify units, form of aberration correction

### ISSUE THREAD

**Issue by DaveStrickland** [astropy/astroquery#1450]
At present the vectors() function of astroquery.jplhorizons always returns GEOMETRIC cartesian states with distances in AU and rates in AU/day. 

It would be useful to add parameters to the vectors() function to allow other units (km, km/day and km, km/s; Horizons codes KM-D and KM-S respectivly) and the two additional choices for aberration correction (astrometric states and apparent states, Horizons codes LT and LT+S) to be queried for.

These settings are useful for working with satellites, for example. The units issue can be worked-around by converting the existing AU, AU/day data but the aberration corrections are a real pain to deal with.

Thanks, Dave

**Comment by mommermi** [comment]
@DaveStrickland: thanks for bringing this up! I will work on including an aberration option, but in the case of the units, I would prefer to go with the current solution, i.e., the user can use `astropy.units.Quantity` functionality to convert to any unit they want.

**Comment by mommermi** [comment]
Different aberration corrections have been implemented as part of #1478. This issue can be closed.

**Comment by DaveStrickland** [comment]
Great, thanks for the quick turnaround! I've installed and verified it works as I expect.
