### ISSUE TITLE
Parse error VOTable in XMatch

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1465]
When there is an error in XMatch a VOTable is returned with description of the error. Parse this table and raise a more informative error than `response.reason` that comes out of `response.raise_for_status()` automatically.

xref: https://github.com/astropy/astroquery/issues/1376

**Comment by keflavich** [comment]
notes for future:
```
vt = votable.parse(io.BytesIO(response.content))
st = vt.get_info_by_id('QUERY_STATUS')
log.error(st.content)
```
