### ISSUE TITLE
Rework Simbad to use TAP

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1468]
Using TAP queries is more efficient for Simbad, and thus the internals of the module

**Comment by ManonMarchand** [comment]
- [ ] Sort current issues/PR about Simbad before starting the refactoring
- [ ] Increase coverage until satisfactory to be sure we wont break anything
- [ ] Following #243 discussion, add a TAP access directly. This will require extensive documentation with the navigation in the relational database.

**Comment by ManonMarchand** [comment]
@keflavich : would you like to discuss these changes with @aoberto and me? We work at CDS and it's something that we will try to handle. Maybe you have an idea/some tips on how to do it properly?

**Comment by keflavich** [comment]
@ManonMarchand Sure, happy to discuss them.  If you're going through with a refactoring to use TAP on the backend, I'd just request that you open a draft PR early so we can discuss user interface decisions as they are made.  What else needs to be discussed?  If you want to schedule a call, I can do that too.

**Comment by bsipocz** [comment]
Also, let me know if you're planning to travel to the next IVOA, we could certainly do some focused work there, if you think it would be helpful.
