### ISSUE TITLE
alma stage_data returns superset of the requested data

### ISSUE THREAD

**Issue by andamian** [astropy/astroquery#1480]
For example:
`stage_data('A002_Xad2d3f_X7')` returns urls to all the data in project `2015.1.00007.S` and this includes, besides member OUD `A002_Xad2d3f_X7`, also member OUDs `A002_Xad2d3f_X9` and `A002_Xad2d3f_Xd`. IMO, filtering should be done in `stage_data` or the documentation should state that the returned set might be a superset of the requested one.

Thanks

**Comment by keflavich** [comment]
I've always wondered why the ALMA archive does this.  I'm in favor of adding optional filtering, default on, and adding docs about it.
