### ISSUE TITLE
Return number of SIMBAD objects in paper associated with bibcode

### ISSUE THREAD

**Issue by ojustino** [astropy/astroquery#1490]
Hello -- as the title says, I'm trying to provide `astroquery` with a bibcode and get back the number of SIMBAD objects referenced in the paper associated with that bibcode.

At the moment, this is the best method I've come up with:

```
from astroquery.simbad import Simbad
sim2 = Simbad()
sim2.ROW_LIMIT = 150
sim2.remove_votable_fields('coordinates')
n_obj = len(sim2.query_bibobj('2017AJ....154..115H'))
```

However, I would like to do this for a list of ~3,000 bibcodes, which becomes very time-consuming and is prone to breaking thanks to `ConnectionError`. I checked if you can vectorize `query_bibobj()` like you can by changing `query_object()` to `query_objects()`, but it seems like that's not possible.

I looked through SIMBAD's documentation and found that if you enter a bibcode on [this page](http://simbad.u-strasbg.fr/simbad/sim-fref) in the "bibcode or DOI" field, it generates a very quick estimate of the number of SIMBAD objects in the paper on the next line down, even for one with 23,000 objects like `2017AJ....154..115H`.

So it's possible to do this somehow. If you "View Page Source" for the linked page, you can see that the calculation is done in a file called `simbad.js`. The comments are in French and I don't read jQuery well, so that's as far as I've gotten to this point.

My final questions are:
1. **How, if at all, can I can use `astroquery` to retrieve this estimate of the number SIMBAD objects attached to a bibcode?** If I can't, how else would you recommend automating this process?
2. **Is it possible to retrieve data for more than one bibcode at a time through `query_bibobj()`, `query_bibcode()`, or another method?** Or do I have to call the method once per bibcode in a loop?

**Comment by keflavich** [comment]
The SIMBAD team has said they want vectorized queries, not a large series of independent queries, but I don't know how to address this.  @aoberto, @bmatthieu3, could you assist?  Do we need to implement something new for this use case?

**Comment by aoberto** [comment]
Hello, 
First, the usage from astroquery is using Simbad script with a votable output, and unfortunately, we have not developed the way to output bibliographical information (and so, in your case, just get the number of objects).
Then, to stay with astroquery `query_bibobj` (which gives you data on all objects), in this mode, we could vectorize until 10,000 queries. But, still it would be time consuming, because it will retrieve all objects (especially slow for bibcode on long list of objects). Anyway, we can add a way to vectorize it.
Secondly, the web page you mentioned, is using TAP queries, and then getting directly the information. You can try this URL in python to get only the number of objects : 
http://simbad.u-strasbg.fr/simbad/sim-tap/sync?query=select+nbobject+from+ref+where+bibcode='2019A&A...625A..80K'&format=text&lang=adql&request=doQuery
In the future, we will try to give you a way to query TAP Simbad, directlty in astroquery.
Remember, to add a call to sleep(0.2) after each call to Simbad. 
Anais

**Comment by ojustino** [comment]
Thank you for the responses. I think vectorization on `query_bibobj` and the ability to query TAP Simbad in `astroquery` would be nice, even if in a limited manner.

I had success trying @aoberto's solution through `requests`. The speed I get at the moment is about 0.6 seconds per bibcode, which is still sizable when dealing with a few thousand bibcodes. However, optimizing that is probably outside the scope of this pull request.

I appreciate the help.

**Comment by smoh** [comment]
Hi,

I think a possible solution is to send ADQL query with a table using pyvo then you can query entire 3000 with one query.

```python
from astropy.table import Table
import pyvo
```


```python
simbad_tap_baseurl = 'http://simbad.u-strasbg.fr/simbad/sim-tap/'
simbad = pyvo.dal.TAPService(simbad_tap_baseurl)
```


```python
# just testing out to make sure everything's consistent
r = simbad.run_sync("""
SELECT nbobject
FROM ref
WHERE bibcode='2019A&A...625A..80K';
""")
```


```python
r
```




    <Table masked=True length=1>
    nbobject
     int32  
    --------
           5



Use synchronous ADQL with an uploaded table to query for a number of queries

I think 3000 bibcodes should be fine with synchronous. Below just try three.


```python
from io import BytesIO
```


```python
t = Table({'bibcode':['2019A&A...625A..80K', '2019A&A...625A..80K', '2019A&A...625A..80K']})
t
```




<i>Table length=3</i>
<table id="table4809893424" class="table-striped table-bordered table-condensed">
<thead><tr><th>bibcode</th></tr></thead>
<thead><tr><th>str19</th></tr></thead>
<tr><td>2019A&amp;A...625A..80K</td></tr>
<tr><td>2019A&amp;A...625A..80K</td></tr>
<tr><td>2019A&amp;A...625A..80K</td></tr>
</table>




```python
# prepare file-like object without writing to disk.
f = BytesIO()
t.write(f, format='votable')
f.seek(0)
```




    0




```python
r1 = simbad.run_sync("""
select ref.nbobject
from tmp
left join ref on tmp.bibcode = ref.bibcode;""", uploads={'tmp':f})
```


```python
r1
```




    <Table masked=True length=3>
    nbobject
     int32  
    --------
           5
           5
           5



Check out `simbad.run_sync` for details. As ipynb notebook [here](https://gist.github.com/b57567e0d52ec787afbdd3d6ec6fd781).

**Comment by ojustino** [comment]
@smoh Your solution works very well for me, and it scales to 3000 with no problem. Thank you for putting it together in a notebook, too.

**Comment by bsipocz** [comment]
I think it would be useful to add this example to the narrative docs?

**Comment by smoh** [comment]
Hmm.. I don't know. I'm happy to add it to simbad.rst but I think technically it belongs more to pyvo docs? My draft for letting people know that this is available would be to add the following below "A warning about big queries" and above specific method examples:

```
Different ways to access Simbad
-------------------------------
The Simbad tool described here provides a number of convenient methods that
internally creates a `script query
<http://simbad.u-strasbg.fr/simbad/sim-fscript>`__ to Simbad server, which is
also how the `Simbad web interface <http://simbad.u-strasbg.fr/simbad/>`__
operates.

Simbad provides another way to access its database via `TAP
Service<http://simbad.u-strasbg.fr/simbad/sim-tap>`__. This may be better
suited for some usage. If you need a python client for TAP Services,
check out `pyvo<https://pyvo.readthedocs.io/en/latest/>`__.
```

**Comment by bsipocz** [comment]
Yes, you're right. Your suggestion above makes more sense at least until a tap based query will be available under the hood here (it came up before as a possible way forward).
