### ISSUE TITLE
Inclusion of query tool for SVO Filter Profile Service

### ISSUE THREAD

**Issue by jaladh-singhal** [astropy/astroquery#1495]
Hi @keflavich & entire Astroquery team,

At [wsynphot](https://github.com/starkit/wsynphot), I and @wkerzendorf are implementing a query tool to fetch filter data from **_SVO Filter Profile Service (FPS)_** under https://github.com/starkit/wsynphot/pull/27. But we are more than happy for it to live in Astroquery.

SVO FPS is a service developed by [SVO](http://svo2.cab.inta-csic.es/svo/theory/main/) that offers information about astronomical filters in a standardized way. It provides both [web interface](http://svo2.cab.inta-csic.es/svo/theory/fps/index.php?mode=browse) and a [VO service](http://svo2.cab.inta-csic.es/svo/theory/fps/index.php?mode=voservice) (sort of programmatic interface) to access this filter data. We're using the latter to create some functions at wsynphot. These functions can send HTTP queries to SVO FPS for accessing the data as VOTables, which are then returned after parsing them using Astropy.

Currently we have developed functions that can get filter index, transmission data and filter list. You can quickly get an overview of how they work as illustrated in this [notebook](https://github.com/jaladh-singhal/wsynphot/blob/get-data/docs/io/get_filter_data.ipynb). 

So please have a look at our work and if it suits you, let us know. We will be glad to contribute SVO FPS query tool in Astroquery.

**Comment by bsipocz** [comment]
Including a new service to query the filter service sounds very useful. However I think we would prefer if the API would follow the usual astroquery layout. E.g. there'll be a main class with methods rather than functions, etc. Please have a look at our current services, logically this could follow the non-archive modules (https://astroquery.readthedocs.io/en/latest/),

**Comment by jaladh-singhal** [comment]
Thanks @bsipocz 
By non-archive modules, do you mean [catalogs](https://astroquery.readthedocs.io/en/latest/#catalogs) as mentioned in docs?

**Comment by bsipocz** [comment]
no, I mean the line lists or simulations. I suspect this should be very similar in logic to the line lists (e.g. it makes no sense to have a `query_object` method, etc.

**Comment by jaladh-singhal** [comment]
Now SVO FPS is included by merging #1498 - thanks to the hard work of @keflavich & @ceb8 on that PR :tada:
