### ISSUE TITLE
MAST: Observation.get_cloud_uris() gives ClientError

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1513]
**UPDATE:** Even bypassing `get_cloud_uris()` to get the URIs manually, I still get `ClientError` when I attempt to download the file as instructed. I am beginning to think this is some problem in the data themselves? 

With its current implementation, there is no option to pass in `aws_access_key_id=` and `aws_secret_access_key=` here:

https://github.com/astropy/astroquery/blob/badace6aacd493b17d7b82a94ff3c5b3282744e2/astroquery/mast/core.py#L1641

As a result, following instructions at https://mast-labs.stsci.io/2018/12/tess-data-available-on-aws , I get `ClientError` at `s3_urls = Observations.get_cloud_uris(filtered)`.

Also, I don't know why the example is done in the way that `Observations.get_cloud_uris()` uses its own `self._boto3` client, and then asks the user to create yet another `boto3.client` (this time with proper credentials as input) a few lines down.

**Comment by pllim** [comment]
Temporary workaround, bypassing some kind of internal check:
```python
from astroquery.mast import fpl
s3_urls = [fpl.paths(data_product) for data_product in filtered]
```

**Comment by pllim** [comment]
Turns out the instructions assumed user has `~/.aws/credentials` **and** set both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables (the same as those in `credentials` in the EC2 instance.

**Comment by bsipocz** [comment]
@pllim - PRs are welcome to improve the docs so others don't run into this.
