### ISSUE TITLE
Unable to make a Simbad query of a list/array of elements

### ISSUE THREAD

**Issue by Titanosaurus** [astropy/astroquery#1520]
I have a list of IDs of many stars and I need to find Gaia's DR2 ID for all of them (if they have).
For that I'm doing a for loop that queries all the simbad IDs for a specific star in the list and serches for the Gaia DR2 designation.

I'm using
`tab = Simbad.query_objectids(star_list[i])`
, where i is the index of the for loop.

Is there any way to launch everything in just one query? Some way of having as a result a list of tables (each table of Simbad IDs for each star in star_list). I'm currently launching hundreths of queries and I would like to do it in just one (because of speed and because I don't want to be halted by the Simbad servers each time I exceed the limit of queries).

**Comment by bsipocz** [comment]
What is your astroquery version?

Have you tried to use `Simbadquery_objects()` instead? Vectorized queries are definitely possible with that one.

**Comment by Titanosaurus** [comment]
My astroquery version is 0.3.9. I've tried `Simbad.query_objects()` but I can't extract the Simbad IDs for each object of the array.

Could the `Simbad.query_objectids()` method be expanded to allow for lists as inputs so that Simbad performs just one big query instead of many smaller ones?

By the way, somehow related is the `Vizier.query_object()` method. I'm currently only allowed to use it one star at a time and I wish it could use an array of IDs as inputs. The resulting tables showing the entries per catalog of all the stars in the array.

**Comment by aoberto** [comment]
Before calling the "query_objects" method you can customize output using :
`Simbad.add_votable_fields('ids')`
to get all identifiers, like query_objectids or
`Simbad.add_votable_fields('id(Gaia)')`
to get only Gaia identifier if exists
