### ISSUE TITLE
vo_conesearch should return astropy Table rather than  votable

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1522]

**Comment by pllim** [comment]
Can you please assign to me? I am not watching the repo, so I didn't get notified.

Note to self: Answer "does it handle vector skycoords?"

**Comment by pllim** [comment]
Short answer: "classic" API follows original `astropy` behavior. Astroquery API in `core.py` should have returned `Table`. Please post a snippet with your use case. Thanks!

**Comment by bsipocz** [comment]
```
>>> from astroquery.vo_conesearch import conesearch
>>> from astropy.table import Table
>>> result = conesearch.conesearch( (287.9869104, 13.0748496), radius=0.1, catalog_db="http://localhost:8080/cone?", timeout=4*60)
>>> print(type(result))
<class 'astropy.io.votable.tree.Table'>
```

**Comment by pllim** [comment]
What you are using is the "classic" API. The first example in https://astroquery.readthedocs.io/en/latest/vo_conesearch/vo_conesearch.html#getting-started is the `astroquery` compliant one, and it does return `Table` but the API is not as flexible.

**Comment by bsipocz** [comment]
should the "classic" maybe return a warning that it's "classic"?

**Comment by pllim** [comment]
I am not convinced that everyone would notice the warning. They are already bombarded with VO table warnings because none of the services are 100% compliant.

If this really bothers you, in the next astroquery **major** release, I can change the behavior for "classic" API. Let me know when it is time to do so. Thanks!

**Comment by bsipocz** [comment]
Thank you @pllim. I would love it to be a Table as astropy.table.Table (as the most confusing part was that when you print a votable it says "Table" at the top, but then none of the expected behaviours work. 
However I don't know whether it fully round trips for votable-Table-votable. If it's not then maybe another "output_format" kwarg, or more examples in the docs would be the solution.

**Comment by pllim** [comment]
It is completely reasonable to change the returned table to be `astropy.table.Table`, as no sane person wants to access `votable.Table` directly given the choice. Although extra option does not hurt, so I'll definitely follow your suggestion when the time comes. Thanks!

**Comment by bsipocz** [comment]
Thanks, I really appreciate it :)

**Comment by pllim** [comment]
I just realized that I might have to update tutorials when these changes are in too... :grimacing:

**Comment by pllim** [comment]
Actually, I take it back... The "new" API also seems to return `votable`... Ops.
