### ISSUE TITLE
Does vo_conesearch handle vector SkyCoord? (ANSWERED)

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1529]
In response to question from https://github.com/astropy/astroquery/issues/1522#issuecomment-518847581 by @bsipocz , the answer is no. The interface defined by http://www.ivoa.net/documents/REC/DAL/ConeSearch-20080222.html#req is to take one RA, one Dec, and one search radius per query. Thus, its interface allows search for one `SkyCoord` through multiple services, but does *not* support searching for multiple `SkyCoord` at the same time.

Even if you implement an interface to accept vector `SkyCoord`, you would have to submit the query one by one, thus unable to take advantage of the vectorization. 

Maybe @tomdonaldson could correct me if I am wrong.

*tl;dr: No*

**Comment by bsipocz** [comment]
hmm, this is not ideal I suppose, but as you say we can't do much about it.

cc @ctslater
