### ISSUE TITLE
have timeout for cache

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1531]
Would be nice to have a mechanism to invalidate the cache. E.g. when new data is added at the serverside users should be able to automatically get access to that. Whether to achieve that with a timeout (which wouldn't work well right around when the new data is added, and would ignore cache unnecessary when there is no data added for a long time) or my some other means is up for discussion.

**Comment by bsipocz** [comment]
A caching issue came up again on a twitter thread, this time regarding the jplhorizon module (where ephemeris got updated server side, yet the cached version got used in the query).

I marked both cache related issues (#1511) as critical for the next release, and I feel this should be resolved sooner rather than later.

**Comment by keflavich** [comment]
We have yet another affected module.  

Much as I love caching, maybe we need to start defaulting it to 'off' to circumvent these issues?

**Comment by bsipocz** [comment]
@ceb8 has resurrected the old cache timeout PR in #1634, I'll try to review what she has there soonish instead of changing the defaults.

**Comment by bsipocz** [comment]
#1634 meant to address this, reopen if it's not the case.
