### ISSUE TITLE
gzip was not found on your system!

### ISSUE THREAD

**Issue by erwanp** [astropy/astroquery#1538]
I use `astroquery` in my infrared spectroscopy package [radis](https://github.com/radis/radis) to retrieve HITRAN data.  

However, on each first import I get a printed message (originates from [astroquery.utils.system_tools.py](https://github.com/astropy/astroquery/blob/master/astroquery/utils/system_tools.py) )  

> gzip was not found on your system! You should solve this issue for astroquery.eso to be at its best!
On POSIX system: make sure gzip is installed and in your path!On Windows: same for 7-zip (http://www.7-zip.org)!

I do not use the `astroquery.eso` module and thus I'd like not to have to install gzip, nor to see that message. 
There are two easy options:

1. The gzip check could be moved within the `astroquery.eso` function calls.  
2. The `print` can be replaced with a Warning, which I can catch and filter from my own code. 

Option 1. requires some knowledge of `astroquery` which I don't have. Option 2. does not and I can do a MR.  

What do you think?

**Comment by keflavich** [comment]
Agreed, this should be changed.  A few things should happen:
(1) the print statement should be a warning (so it can be silenced)
(2) the 'gunzip' utility should be reevaluated - I'm not clear that there's any reason to use a system-wide gunzip instead of the python gzip package
(3) the warning should only be raised if a zip file is encountered, not before

**Comment by erwanp** [comment]
I can work on (1) and (3) but someone else must decide (2)

**Comment by erwanp** [comment]
@keflavich do you know who could decide on (2) ?

**Comment by keflavich** [comment]
Let's just get rid of it - python's gzip is fine.

**Comment by erwanp** [comment]
Ok, i'll submit a PR sometimes in the week then!
