### ISSUE TITLE
AttributeError: 'HorizonsClass' object has no attribute 'uri'

### ISSUE THREAD

**Issue by shbhuk** [astropy/astroquery#1539]
This error displays when I run the Horizons class within the jplhorizons submodule.
```
from astroquery.jplhorizons import Horizons
obj = Horizons(id='Ceres', location='568', epochs=2458133.33546)
print(obj.uri)
```
OUTPUT:
`AttributeError: 'HorizonsClass' object has no attribute 'uri'
`
Astropy Version Number 3.2.1

Based on - https://astroquery.readthedocs.io/en/latest/jplhorizons/jplhorizons.html

**Comment by bsipocz** [comment]
what is your astroquery version?

**Comment by shbhuk** [comment]
0.3.8

**Comment by bsipocz** [comment]
You need to upgrade then. As I see 0.3.9 already has it, but for astroquery it's actually best to go with the latest automatic release with 
`pip install --pre -U astroquery`

**Comment by bsipocz** [comment]
Hmm, this doesn't seem right.

cc @mommermi

**Comment by bsipocz** [comment]
Hmm, actually looking into the details of the class, I think the `uri` is populated when you actually start doing things with the class instance. E.g. 
```
from astroquery.jplhorizons import Horizons
obj = Horizons(id='Ceres', location='568', epochs=2458133.33546)
obj.ephemerides()
print(obj.uri)
```
