### ISSUE TITLE
Can't import astroquery.astrometry_net no module named

### ISSUE THREAD

**Issue by dts350z** [astropy/astroquery#1540]
This is on windows with anaconda (python 3.7 64bit)

I did pip install --pre --upgrade  astroquery

As stated in the directions, but it gives me 0.3.10.dev0 

Do I need a higher version to get to get astroquery.astrometry_net and if so how do I get it?

If not, what am I doing wrong:

from astroquery.astrometry_net import AstrometryNet

**Comment by bsipocz** [comment]
When did you install astroquery? `astrometry_net` got included in a release made available yesterday, so if it's anything older than you might want to upgrade again.
