### ISSUE TITLE
VizieR PS1 query returns strange results at very specific random position

### ISSUE THREAD

**Issue by ysBach** [astropy/astroquery#1551]
I was running my photometry pipeline which worked perfectly in other cases, but I found it failed only one single image out of thousands of images I tested so far.

Sample code (I am using python 3.7.3):
```python
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
from astropy import units as u

import astropy
import astroquery
print(astropy.__version__)
print(astroquery.__version__)
# 3.2.1
# 0.3.10.dev5707

def testing(ra, dec, radius):
    _params = dict(ra=ra, dec=dec, radius=radius)

    for k, v in _params.items():
        if v is None:
            continue
        if not isinstance(v, u.Quantity):
            _params[k] = v * u.deg
            
    vquery = Vizier(columns=["**", "+objID"],
                    column_filters={"rmag": "10.0..15.2"},
                    row_limit=-1)

    field = SkyCoord(ra=_params['ra'], dec=_params['dec'], frame='icrs')

    queried = vquery.query_region(field,
                                  radius=_params['radius'],
                                  catalog="II/349/ps1")[0]
    return queried

ra = 17.26479
dec = 6.72688
rad = 0.35377228300444524
q1 = testing(ra, dec, rad)
q2 = testing(ra + 1.e-6, dec, rad)
q3 = testing(ra, dec, rad + 3.e-17)
print(len(q1))  # 18
print(len(q2))  # 83
print(len(q3))  # 83
```
As can be seen, I only added extremely small values to RA or cone radius, but the number of stars differ a lot. 

For check, I plotted the location of stars:
```python
from matplotlib import pyplot as plt
from matplotlib.patches import Circle

fig, ax = plt.subplots(1, 1, figsize=(4, 4))

circ = Circle(xy=(ra, dec), radius=rad, fill=False)

ax.plot(q1["RAJ2000"], q1["DEJ2000"], 'b+')
ax.plot(q3["RAJ2000"], q3["DEJ2000"], 'rx')
ax.add_artist(circ)

ax.set(xlabel="RAJ2000 [deg]", ylabel="DEJ2000 [deg]")
plt.show()
```
![image](https://user-images.githubusercontent.com/17214293/65111445-0ab13780-da17-11e9-8fee-8b6108c5baf1.png)

For the very specific ``ra, dec, rad`` combination, the star query seems to have been halted at the lower right corner(?) of the above image.

PS) I have just tested without ``column_filters`` in the ``testing`` function (takes more time). And the results are all identical as 10276. But I don't find any reason why they differ so much if ``column_filters`` is given...

**Comment by keflavich** [comment]
Interesting bug.  Could you try clearing the cache and re-running it, though?  Running your code, I get:
```
4.0.dev25458
0.3.10.dev5611
83
83
83
```

**Comment by ysBach** [comment]
@keflavich Oh my..!!! Why haven't I tried that...:man_facepalming: ! 
Thank you so much! That resolved the problem. 
Maybe there was a problem at some point by my mistake and my innocent computer utilized the cached one.
