### ISSUE TITLE
Astroquery.cadc Error ->  'TAPResults' object has no attribute 'to_table'

### ISSUE THREAD

**Issue by jsuarez314** [astropy/astroquery#1556]
Recently I have used the astroquery package to access to the DB of the CADC data, the tasks that I need to complete is download some .fits files images from this DB. I have installed the astropy 1.3.3, astroquery 0.3.10 and pyvo 0.6.1 packages, but when I try to run any code block from the jupyter-notebook, the result always is

AttributeError: 'TAPResults' object has no attribute 'to_table'

For example, when I try to run this codeblock.

from astroquery.cadc import Cadc
cadc = Cadc()
result = cadc.query_name('Nr3491_1')
print(len(result))

I do not understand what happen.

**Comment by bsipocz** [comment]
Please do upgrade to pyvo v1.0, there are known incompatibilities with older versions.

**Comment by jsuarez314** [comment]
It works for me. I have to uninstall pyvo from conda and install newly with pip.  Thanks!

**Comment by bsipocz** [comment]
Thanks for following up, I'm closing this then.

As for the conda version, something when wrong with the conda packaging, we'll remedy it.

**Comment by bsipocz** [comment]
fyi the 1.0 version of pyvo should now exists on the astropy channel.
