### ISSUE TITLE
Vizier database problems..

### ISSUE THREAD

**Issue by selseyastro** [astropy/astroquery#1562]
Vizier.query_region(coord.SkyCoord(ra=xra, dec=xde,unit=(u.deg, u.deg),frame='icrs'),width="14m",catalog=["UCAC"])
  
The output data only has 5 columns wide and has  ---- for missing data
also when you try to sort say ("+_r") it does not when you have specified _r as a column.
It also only outputs 10 rows and a gap ---- then the last 10 rows
I have tried limiting rows to say 30.  No impact.
This also happens for GSC catalog.
Not sure what the problem is.
John

**Comment by jwoillez** [comment]
@selseyastro This is how astropy tables are printed by default. If you want to see everything in a table use `tbl.pprint(max_width=-1, max_lines=-1)`.

@bsipocz Not a bug, can be closed.
