### ISSUE TITLE
CADC get_images() or query_region() raise DALQueryError: operator does not exist: scircle && double precision[]

### ISSUE THREAD

**Issue by falon3** [astropy/astroquery#1564]
I don't believe I have any syntax issues but whenever I execute a query_region, or get_images request like any of those on the documentation [page](https://astroquery.readthedocs.io/en/latest/cadc/cadc.html#module-astroquery.cadc) I get the same error:

>>> from astroquery.cadc import Cadc
>>> cadc = Cadc()
>>> coords = '01h45m07.5s +23d18m00s'
>>> radius = 0.1
>>> results = cadc.query_region(coords, radius, collection='CFHT')

 `raise DALQueryError(self._status[1], self._status[0], url)
pyvo.dal.exceptions.DALQueryError: ERROR: operator does not exist: scircle && double precision[]
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 2353`

This never used to be a problem for me until today and I never updated any libraries that I know of today?

**Comment by bsipocz** [comment]
cc @andamian

**Comment by andamian** [comment]
The problem is related to a service upgrade at the CADC that took place yesterday. We are working on a fix.

**Comment by andamian** [comment]
The service has been fixed and this should work once again. Thanks for reporting.

**Comment by falon3** [comment]
Thanks for the info and updates!
