### ISSUE TITLE
Vizier not returning Tables for all catalogs (rare bug, certain coordinates?)

### ISSUE THREAD

**Issue by dennisalp** [astropy/astroquery#1574]
coo are my coordinates: 
<SkyCoord (ICRS): (ra, dec) in deg
    (280.32640233, 31.04649113)>

When I run the following, Vizierreturns 1 catalog (2MASS)
Vizier(columns=['*', '+_r'], timeout=60, row_limit=10).query_region(coo, radius=5*u.arcsec, catalog='I/345/gaia2,II/246/out,V/147/sdss12')
TableList with 1 tables:
	'0:II/246/out' with 16 column(s) and 1 row(s) 

The problem is that I know there's a GAIA source here (clearly from Aladin or VizieR online interface). If I query Vizier with just 1 catalog I find it.
Vizier(columns=['*', '+_r'], timeout=60, row_limit=10).query_region(coo, radius=5*u.arcsec, catalog='I/345/gaia2')
TableList with 1 tables:
	'0:I/345/gaia2' with 33 column(s) and 1 row(s) 

This seems to only happen on very rare occasions (particular coordinates/only sometimes it seems). Can anyone else replicate this?

**Comment by dennisalp** [comment]
Just reran the same code and it seems to work now. I guess that sometimes catalogs can be missed when querying Vizier (some sort of silent failure)?

**Comment by jwoillez** [comment]
I could not reproduce with the following:

    coo = SkyCoord(280.32640233, 31.04649113, unit='deg')
    Vizier(columns=['*', '+_r'], timeout=60, row_limit=10).query_region(coo, radius=5*u.arcsec, catalog='I/345/gaia2,II/246/out,V/147/sdss12')

Note the `'*'` for one of the columns specifiers.

@bsipocz Should we keep open?

**Comment by jwoillez** [comment]
@bsipocz, @keflavich, could this issue be closed?
