### ISSUE TITLE
TAP/TAP+ doesn't support the MAXREC parameter

### ISSUE THREAD

**Issue by jontxu** [astropy/astroquery#1581]
Hello,

I am a maintainer of a TAP service, and some user has been complaining about the astroquery TAP implementation returning less rows than expected in some queries. Looking into it I saw that it lacks support for the [MAXREC parameter](http://www.ivoa.net/documents/TAP/20190927/REC-TAP-1.1.html#tth_sEc2.7.4), wherewith the user can specify the maximum number of records they want to fetch. In our case the default is 100.000 and for a query which should return more rows it would yield partial results.

For this very reason I had to write the python examples for our service with PyVO (another astropy affiliated package). But I heard that astroquery as a “catch-all library” might supersede it and I am looking into rewriting them.

I was looking into the docs and -- when I could not find it -- the source code and I saw that @jcsegovia from ESA is the person who developed this alongside the `gaia` submodule (#836). I have been able to implement it, but I would like to hear from him before creating a pull request. 

I feel like this is a key part of the functionality which has been overlooked...

**Comment by bsipocz** [comment]
the big picture plans we have is to switch to pyvo as a dependency for astroquery and deprecate the tap implementation here, and keep astroquery's focus on the user facing functionalities.  Obviously it requires some significant refactoring, so I cannot provide an ETA, @jcsegovia might be able to provide some details.

Also, a PR sounds good to patch current limitations.

**Comment by jcsegovia** [comment]
like @bsipocz has said, this module will be deprecated. For now, please, feel free to create a PR with the patch you propose.

(In any case, please, keep in mind that you can use TOP to limit the number of results, e.g.:
SELECT TOP 100 * FROM table
)

**Comment by jontxu** [comment]
Yes, that's what I understood in the IVOA Paris Interop. But a coworker has been asking for it so I can't help it. I am pushing for PyVO for that exact reason at the time being.

>(In any case, please, keep in mind that you can use TOP to limit the number of results, e.g.:
SELECT TOP 100 * FROM table)

This wouldn't work if the default MAXREC (an implicit `TOP <number>`, basically) is lower than the number of records the query is going to return.
