### ISSUE TITLE
Travis is on 🔥 

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1582]
Locally I couldn't reproduce  the failures yet, but the travis jobs are on fire for reasons seemingly unrelated.

We should at least need to see whether it's just an infrastructure issue or is expected to affect users, too. If the latter we need to fix it asap.

**Comment by keflavich** [comment]
oh no.  I am out of 💧  (but really out of 🕐 ), so I hope this 🔥 self-douses.

This is the worst and best issue title I've seen.

**Comment by bsipocz** [comment]
yeah, I'm out of ⏲, too as travelling, and given that I don't see it locally, I'm not in panic mode yet.

**Comment by bsipocz** [comment]
This has been fixed for a while now, so closing.
