### ISSUE TITLE
vizier.find_catalogs returns an empty dict for 2MASS

### ISSUE THREAD

**Issue by bmatthieu3** [astropy/astroquery#1583]
Hi @bsipocz,

@kathl @gilleslandais -``Vizier.find_catalogs`` returns empty dictionaries for "2MASS" and "Arp Webb" inputs.

Example:
```python
catalog_list = Vizier.find_catalogs('2MASS')
catalog_list
Out[41]: OrderedDict()
```
We tested on a jupyter notebook running on binder and in local on two different computers.

By checking the Vizier logs in `http://vizier.u-strasbg.fr/` we did not find anything too. Do you have more information, ideas about what is going on ? Thank you very much.

**Comment by keflavich** [comment]
2 cents - I was trying to search for catalogs on vizier (via the web) 2-3 days ago and got zero hits for things that should have existed.  Maybe something is broken server side?

**Comment by gilleslandais** [comment]
Can you give me the URL you started in astroquery ?

Gilles landais (CDS)

**Comment by bmatthieu3** [comment]
@gilleslandais - I close the issue as it seems to work again.
