### ISSUE TITLE
Gemini support

### ISSUE THREAD

**Issue by olyoberdorf** [astropy/astroquery#1595]
Just letting people know I am working on a basic first-pass for Gemini Archive support for astroquery.

Plans for the initial version are to support:

query by cone search
query by target name
query by a core set of search fields (as you see on archive.gemini.edu, the ones that are always visible)
query by flexible arguments (mimics what the website responds to in the URL, maximum flexibility)

I'm open to any input on this either for the initial work or to be done in the future.

**Comment by keflavich** [comment]
If you'd like to open a "Work in progress" (WIP) pull request, we're happy to provide code reviews along the way and direct feedback on what you've written.

Your planned approach sounds good, though!

**Comment by bsipocz** [comment]
Everything in the list above got implemented as part of https://github.com/astropy/astroquery/pull/1596, thus this can be closed.
