### ISSUE TITLE
KeyError: 'esatapplus:flags' in standard TAP request

### ISSUE THREAD

**Issue by hdevillepoix** [astropy/astroquery#1597]
I have an issue querying a TAP server using astroquery.
The server in question works with other clients (tried with topcat),
but the astroquery TAP+ method didn't work,
so I assumed the server is not TAP+ compatible.

Then tried normal TAP, but get the same error:

**KeyError: 'esatapplus:flags'**

```
from astroquery.utils.tap.core import Tap
url="http://api.skymapper.nci.org.au/public/tap/"
tap_service = Tap(url=url)
tables = tap_service.load_tables()
```

Looks like the normal TAP method is attempting to access a Tap+ specific key.

I get the same behaviour with both the current stable version (0.3.10), as well as the bleeding edge (0.4.dev0).

**Comment by bsipocz** [comment]
Another option would be to try and use the tap implementation from pyvo, astroquery will also slowly moving towards using that one: https://pyvo.readthedocs.io/en/stable/

**Comment by bsipocz** [comment]
I'm closing this now as a won't fix as we plan to deprecate TapPlus from here in favour of PyVO. So no development effort is planned to make TapPlus more generic than serving the backend for the currently supported ESA modules.
