### ISSUE TITLE
HELP Simbad: add_votable_fields --> the columns repeat themselves

### ISSUE THREAD

**Issue by AlySpoly** [astropy/astroquery#1612]
Dear all,

I'm not sure this is the right place to ask these doubts! But I don't know who to ask. 

I'm working with `astroquery.simbad`. I'm doing a research on sources which are in a circular region with a radius of 1.75 degrees from the center whose coordinates are, in my example, that of the Crab Nebula. In particular I want only sources with a B or V magnitude less than 6. 
The line code is: `result = Simbad.query_criteria('region(circle, 05h34m31.94s +22d00m52.2s, 1.75d) & Vmag < 6.0 | Bmag < 6.0')`.
And it works.

Now, I'm trying to add the columns `flux(V)` and `flux(B)` to this table. I did it with `customSimbad.add_votable_fields('flux(V)', 'flux(B)')`. 
It works, but every time I run the code (I'm using jupiter notebook), new identical columns `flux(V)` and  `flux(B)` are added.  Like `FLUX_V_1`and  `FLUX_B_1`,  `FLUX_V_2`and  `FLUX_B_2`, etc (see below).  
How can I stop this "loop" on columns?  

*****
The Output is this: 
MAIN_ID        RA           DEC      RA_PREC DEC_PREC ... FLUX_V_6 FLUX_B_6 FLUX_V_7 FLUX_B_7
--------- ------------- ------------- ------- -------- ... -------- -------- -------- --------
  * o Tau 05 27 38.0840 +21 56 13.073      11       11 ...    4.868    4.719    4.868    4.719
* zet Tau 05 37 38.6854 +21 08 33.158      11       11 ...     3.03     2.84     3.03     2.84
*****

Sorry, but I am pretty new on coding/programming.
Thanks a lot for any help.

**Comment by keflavich** [comment]
You can just check whether `flux(B)` is in the fields:
```
if 'flux(B)' not in Simbad.get_votable_fields():
    Simbad.add_votable_fields('flux(B)')
```
