### ISSUE TITLE
Astroquery Spectral Type Extraction

### ISSUE THREAD

**Issue by jrmusiov** [astropy/astroquery#1617]
I'm using Vizier through Astroquery, and I'm trying to get each spectral type extracted.

So far, my code is:
Vizier.ROW_LIMIT = -1
catalogs = Vizier.get_catalogs('I/131A')
print(len(catalogs))
pd.options.display.max_rows = None
catalogs[0].pprint()

This gives me the full SAO catalog (I/131A) with 11 columns and 258,997 rows. I want to create an All-Sky map of the whole catalog, and want to extract each spectral type (SpType=O,B,A,F,G,K,M) to then over-plot their RA and DEC.

I have seen the code for Simbad which uses 
customSimbad = Simbad()
customSimbad.add_votable_fields('sptype')
result = customSimbad.query_object('g her')

but it doesn't work for Vizier.

Has anybody tried extracting individual spectral types before?

**Comment by bmatthieu3** [comment]
Hi @jrmusiov,

I have seen that one column of catalogs[0] is called 'SpType', the output looks like this:
```
<MaskedColumn name='SpType' dtype='bytes3' description="Spectral type, '+++' for composite spectra" length=258997>
 A0
 F2
   
   
   
 F0
   
   
   
...
 B8
 K0
 K5
 G0
 K0
 K0
 K0
 K0
```
Is this what you are looking for ?

For the RA, DEC there are two columns named '_RA.icrs' and '_DE.icrs'. You can convert these columns using e.g. astropy.coordinates.Angle objects: https://docs.astropy.org/en/stable/coordinates/angles.html
```python
from astropy.coordinates import Angle, SkyCoord
ra=Angle(catalogs[0]['_RA.icrs'], unit="hourangle")
dec=Angle(catalogs[0]['_DE.icrs'], unit="degree")
coords = SkyCoord(ra, dec)
```

**Comment by jrmusiov** [comment]
> Hi @jrmusiov,
> 
> I have seen that one column of catalogs[0] is called 'SpType', the output looks like this:
> 
> ```
> <MaskedColumn name='SpType' dtype='bytes3' description="Spectral type, '+++' for composite spectra" length=258997>
>  A0
>  F2
>    
>    
>    
>  F0
>    
>    
>    
> ...
>  B8
>  K0
>  K5
>  G0
>  K0
>  K0
>  K0
>  K0
> ```
> 
> Is this what you are looking for ?
> 
> For the RA, DEC there are two columns named '_RA.icrs' and '_DE.icrs'. You can convert these columns using e.g. astropy.coordinates.Angle objects: https://docs.astropy.org/en/stable/coordinates/angles.html
> 
> ```python
> from astropy.coordinates import Angle, SkyCoord
> ra=Angle(catalogs[0]['_RA.icrs'], unit="hourangle")
> dec=Angle(catalogs[0]['_DE.icrs'], unit="degree")
> coords = SkyCoord(ra, dec)
> ```

Hi @bmatthieu3,

I can see the SpType column, but when trying to print only the RA and DEC for each spectral type it's not working. I am able to print each type, but cannot isolate the coordinates.

I tried the Vizier code:
v = Vizier(columns=['_RA.icrs', '_DE.icrs', 'SpType'], column_filters={"SpType":"O*"}), but will not print more than 50 objects. I'm sure it's something simple I'm missing.

**Comment by bmatthieu3** [comment]
> I tried the Vizier code:
v = Vizier(columns=['_RA.icrs', '_DE.icrs', 'SpType'], column_filters={"SpType":"O*"}), but will not print more than 50 objects. I'm sure it's something simple I'm missing.

There is the attribute ROW_LIMIT that you can set to -1 on the Vizier object you instantiated to say "I want all the rows matching this filter". So this code returns me a table with 97 rows
```python
v = Vizier(columns=['_RA.icrs', '_DE.icrs', 'SpType'], column_filters={"SpType":"O*"})
v.ROW_LIMIT = -1
v.get_catalogs('I/131A')
```
