### ISSUE TITLE
jplhorizons elements broken

### ISSUE THREAD

**Issue by fraserw** [astropy/astroquery#1624]
Elements query is no longer functional. 

Steps to reproduce, and resultant error:
```
>>> from astroquery.jplhorizons import Horizons as Hor
>>> el = Hor(id='Eris',location='500@10',epochs=24550000.5).elements()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fraserw/anaconda3/envs/tomtom/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/Users/fraserw/anaconda3/envs/tomtom/lib/python3.7/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "/Users/fraserw/anaconda3/envs/tomtom/lib/python3.7/site-packages/astroquery/jplhorizons/core.py", line 1284, in _parse_result
    data = self._parse_horizons(response.text)
  File "/Users/fraserw/anaconda3/envs/tomtom/lib/python3.7/site-packages/astroquery/jplhorizons/core.py", line 1178, in _parse_horizons
    raise ValueError(('Query failed without error message; '
ValueError: Query failed without error message; check URI for more information
```
Version of python 3.7.4, astroquery 0.4, installed with anaconda and pip.

**Comment by fraserw** [comment]
Sorry about the messed up formatting.

**Comment by bsipocz** [comment]
The real error is this one: `Cannot interpret date. Type "?!" or try YYYY-Mon-Dy {HH:MM} format.`

Passing a JD definitely worked, so I suspect this maybe part of the recent changes server side?

Either way, we need more tests as apparently this is not being picked up by the test suite.

cc @mommermi

**Comment by talister** [comment]
Isn't there one too many digits in the JD in the `epochs` being passed ? Or was this just a cut-n-paste when creating the issue ?

**Comment by fraserw** [comment]
Good catch @talister It is indeed being an order of magnitude too high on the JD. I suspect that's a problem on JPL's end with the 405 (or equivalent) ephemeris files not going up to the year 62,000. Either way, should be a pretty easy catch with astroquery in that horizons has returned garbage, which should be caught accordingly.

**Comment by talister** [comment]
The available time span seems to depend on the object. For a random NEO (35107) and Eris, the website returns:
```
Available time span for currently selected target body:1599-Dec-12 to 2500-Dec-30 TT.
```
For the Solar System Barycenter, it gave me: `BC 9998-Mar-20 to AD 9999-Dec-31 TT.` Neither corresponds to the end-dates of the DE431 ephemeris the returned table says it's using but it's presumably failing the date range validation part on the backend HORIZONS system.

**Comment by fraserw** [comment]
Well ya learn something new every day. That probably shouldn't be surprising. 

I wonder if the valid date range could be returned in the exception?

**Comment by bsipocz** [comment]
Nice detective work! Nevertheless, I think we need to parse the error message and return something reasonable and human readable to give users a clue.

**Comment by mommermi** [comment]
Thanks, guys! I'll work on implementing a more useful error message.

**Comment by mkelley** [comment]
Is this solved?  Independent of how astroquery handles the error, Horizons should be more clear.  Did anyone contact JPL about their error message?  If no, I can do that.

**Comment by bsipocz** [comment]
This example now provides a much clearer error message, so I'm closing this issue. Please reopen this or a new one if you still run into ambiguous errors, or any issues with the module:
```
>>> from astroquery.jplhorizons import Horizons as Hor
>>> el = Hor(id='Eris',location='500@10',epochs=24550000.5).elements()

ValueError: Ambiguous target name; provide unique id:
  ID#      Name                               Designation  IAU/aliases/other   
  -------  ---------------------------------- -----------  ------------------- 
 20136199  Eris (system barycenter)                                             
920136199  Eris (primary body)                                                  
120136199  Dysnomia                                        Eris I     
```
