### ISSUE TITLE
ENH: vo_conesearch to use registry from pyvo

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1628]
xref https://github.com/astropy/astroquery/pull/1158#issuecomment-580867442

If we switch to using `pyvo` registry in validation, then maybe #1125 will be non-issue. However, this means significant refactoring in the validator's inner machinery.

**Comment by bsipocz** [comment]
I feel that https://github.com/astropy/astroquery/issues/2027 overrides this issue as we aim to rather move this module upstream we are unlikely will spend significant time for refactorings here. Feel free to reopen if you disagree.
