### ISSUE TITLE
bytes/str issue for heasarc.query_region() in python3.6

### ISSUE THREAD

**Issue by caseyjlaw** [astropy/astroquery#1637]
I'm using latest builds on python 3.6:
```
> print(astropy.__version__, astroquery.__version__)                                                                                                          
4.1.dev27307 0.4
```

And when querying a heasarc catalog in a region with *no* survey data, I get this:
```
>>> from astropy.coordinates import SkyCoord
>>> import astropy.units as u
>>> from astroquery import heasarc
>>> he = heasarc.Heasarc()                                                                                                                                       
>>> coo = SkyCoord(ra=0*u.deg, dec=-90*u.deg)                                                                                                             
>>> he.query_region(coo, 'first', radius='1 degree')                                                                                                        
```

```                                                                                                 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/heasarc/core.py in _parse_result(self, response, verbose)
    223             data = BytesIO(response.content)
--> 224             table = Table.read(data, hdu=1)
    225             return table

~/anaconda3/envs/py36/lib/python3.6/site-packages/astropy-4.1.dev27307-py3.6-macosx-10.7-x86_64.egg/astropy/table/connect.py in __call__(self, *args, **kwargs)
     58 
---> 59         out = registry.read(cls, *args, **kwargs)
     60 

~/anaconda3/envs/py36/lib/python3.6/site-packages/astropy-4.1.dev27307-py3.6-macosx-10.7-x86_64.egg/astropy/io/registry.py in read(cls, format, *args, **kwargs)
    522         reader = get_reader(format, cls)
--> 523         data = reader(*args, **kwargs)
    524 

~/anaconda3/envs/py36/lib/python3.6/site-packages/astropy-4.1.dev27307-py3.6-macosx-10.7-x86_64.egg/astropy/io/fits/connect.py in read_table_fits(input, hdu, astropy_native, memmap, character_as_bytes)
    215             return read_table_fits(hdulist, hdu=hdu,
--> 216                                    astropy_native=astropy_native)
    217         finally:

~/anaconda3/envs/py36/lib/python3.6/site-packages/astropy-4.1.dev27307-py3.6-macosx-10.7-x86_64.egg/astropy/io/fits/connect.py in read_table_fits(input, hdu, astropy_native, memmap, character_as_bytes)
    202         else:
--> 203             raise ValueError("No table found")
    204 

ValueError: No table found

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-10-7906b1189339> in <module>
----> 1 tab = he.query_region(coo, 'first', radius='1 degree')

~/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

~/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response
---> 29             result = self._parse_result(response, verbose=verbose)
     30             self.table = result
     31             return result

~/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/heasarc/core.py in _parse_result(self, response, verbose)
    225             return table
    226         except ValueError:
--> 227             return self._fallback(response.content)
    228 
    229     def _args_to_payload(self, **kwargs):

~/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/heasarc/core.py in _fallback(self, content)
    190         new_table = []
    191 
--> 192         old_table = content.split("END")[-1].strip()
    193         for line in old_table.split("\n"):
    194             newline = []

TypeError: a bytes-like object is required, not 'str'

```

Setting the coordinate to a region that know has data returns data as expected.

**Comment by pllim** [comment]
This might be fixed by  astropy/astropy#9505

**Comment by bsipocz** [comment]
I still see this error, and arguably I'm on top of astropy master.

**Comment by pllim** [comment]
Okay, I don't think this is related to the astropy PR. The offending line is

https://github.com/astropy/astroquery/blob/f34e6c92c2cbc44af719a1e1beb578fe4c9de5df/astroquery/heasarc/core.py#L192

It needs to be

```python
old_table = content.split(b"END")[-1].strip()
```

because `content` is `bytes`. The code got here in `_fallback` because this failed

https://github.com/astropy/astroquery/blob/f34e6c92c2cbc44af719a1e1beb578fe4c9de5df/astroquery/heasarc/core.py#L224

Maybe I am just seeing the symptoms. I wouldn't know which is the real bug to fix.

**Comment by EfremBraun** [comment]
I'd like to give this a bump, as the bug renders HEASARC Queries useless. Most of the examples given on https://astroquery.readthedocs.io/en/latest/heasarc/heasarc.html no longer work.

**Comment by rhuang-astro** [comment]
I have exactly the same problem with @EfremBraun

**Comment by keflavich** [comment]
This problem is deeper than identified by @pllim, unfortunately.  It looks like the upstream API has changed; these queries are returning things like:
```
  HEASARC_FIRST : NO MATCHING ROWS 
```
so either the queries were blank and the error message is misleading, or the query was poorly specified.  I'm investigating further.

**Comment by keflavich** [comment]
@EfremBraun your problem is that `rospublic` no longer exists.  I'm not sure what it was originally pointing to, but maybe `rospspc`.  However, correcting this problem led to another: the returned catalog appears malformatted.  Errors like this:
`ValueError: Invalid format for column 'COUNT_RATE': could not display values in this column using this format (Unable to parse format string "{:10.4f}" for entry "  4.5660  " in column "COUNT_RATE")`

This looks like a real error in the returned data.

**Comment by keflavich** [comment]
@caseyjlaw your error is that there is no FIRST data at dec=-90, which I suspect you knew but you were using it as a MWE?  This query works for me:
```
>>> from astropy.coordinates import SkyCoord
>>> import astropy.units as u
>>> from astroquery import heasarc
>>> he = heasarc.Heasarc()
>>> coo = SkyCoord(ra=12*u.h, dec=50*u.deg)
>>> result = he.query_region(coo, 'first', radius='1 degree')
```
but I'll add a better error message

**Comment by esabol** [comment]
@EfremBraun: The HEASARC catalog `rospublic` has been deprecated for 16 years. :) We (the HEASARC) recently switched to a new database system, and it's not in the new database. You really should be using the HEASARC catalog `rosmaster` instead.

**Comment by rhuang-astro** [comment]
Maybe someone should modify the examples given on https://astroquery.readthedocs.io/en/latest/heasarc/heasarc.html. 
Most of them are rospublic.

**Comment by EfremBraun** [comment]
> @EfremBraun: The HEASARC catalog `rospublic` has been deprecated for 16 years. :) We (the HEASARC) recently switched to a new database system, and it's not in the new database. You really should be using the HEASARC catalog `rosmaster` instead.
> 
> https://heasarc.gsfc.nasa.gov/W3Browse/rosat/rosmaster.html

That indeed fixes it. I'll fix the examples in the docs now.

**Comment by bsipocz** [comment]
I believe all the issues here have been addressed and fixed therefore I'm closing the issue. If you find it otherwise please reopen.
