### ISSUE TITLE
WARNING: ALMA's archive system is going to change 11 March

### ISSUE THREAD

**Issue by alipnicky** [astropy/astroquery#1640]
I am a member of the North American ALMA Science Center who uses the astroquery.alma() interface daily. This week (on Wednesday, Feb. 12) ALMA is planning on updating their current archive request handler to a new version that will break astroquery.alma's ability to access the archive. This new request handler simplifies the download links to a format like 

https://[archive-URL]/dataPortal/[filename]

where [archive-URL] is like almascience.nrao.edu or almascience.eso.org and [filename] is the name of the file to download like uid____A002_X12311_X124. This is much simpler than the previous link structure however it breaks astroquery's ability to access the data and retrieve the correct download URLs. If you instead provide the new link format directly to Alma.download_files() it only works with public data. It seems that logging in with Alma.login() no longer carries the correct credentials to download proprietary data as trying to access proprietary data leads to a 403 error. If you put the same link in a browser, you'll receive:

403 Forbidden: anonymous cannot access [filename]

**Comment by keflavich** [comment]
I've done some initial investigation, and it seems that the problem is that the metadata about the request number is now more difficult to find.  However, maybe that's not needed any longer.

**Comment by keflavich** [comment]
Any idea if there's a good way to test whether the server is pre- or post- update?  Does it return some sort of version number so users can be smoothly transitioned from one to the other?

**Comment by alipnick** [comment]
Hmmm... not that I know of.

**Comment by keflavich** [comment]
What URL do you need to use to get a list of files now?  I'm trying to fix up the `stage_data` component, and I'm stuck at retrieving that list, which now seems to be executing a series of javascript commands.  Those are reproducible, but only with a large effort.

**Comment by keflavich** [comment]
@alipnick regarding your original issue, about `login` not carrying the credentials - the problem appears to be in the URL construction.  For example, this proprietary data set:
`https://almascience.nrao.edu/dataPortal/sso/2016.1.00620.S_uid___A001_X879_X14e_auxiliary.tar`
will work just fine with the above URL (in the new system), while this one:
`https://almascience.nrao.edu/dataPortal/2016.1.00620.S_uid___A001_X879_X14e_auxiliary.tar`
will not.  Note the lack of `sso/` in the latter.

**Comment by alipnick** [comment]
Ah, I see, the `sso` appears to be necessary, I had missed that. When you request the downloads via a download script from the archive, the list of files to download gets put in the top of the script. Based on those links, I did not see the `sso` part of the URL. I agree that the URL construction is really the issue here.

**Comment by keflavich** [comment]
I still can't figure out a way to get the URLs.  The browser loads this page (for example):
https://almascience.nrao.edu/rh/requests/keflavich/1651800637126
from a post request, then populates the page with some autogenerated javascript queries.  If someone can help point me in the right direction, it will be quick work, but right now I have to reverse-engineer the internal API to get these URLs, and that's a pain.

**Comment by alipnick** [comment]
It looks like the deployment will be delayed by a few months, that should give plenty of time for figuring this out.

**Comment by alipnick** [comment]
March 11 is the new date for this update to occur.

**Comment by alipnick** [comment]
@keflavich requested that I send some of my standard testing that I perform:
```python
from astroquery.alma import Alma
alma = Alma()
#alma.archive_url = '' #if needed, for a test RH for instance 
alma.login('alipnick')
links = alma.stage_data('uid://XXX/XXX/XXX') #usually a proprietary dataset
urls = links['URL']
alma.download_files(urls)
```
This standard download process usually hits all the break points that I encounter. The first sticking point is logging in. If that works, the next sticking point is retrieving the links. If I can retrieve the links, it's never failed after that point (besides timeouts).

**Comment by alipnick** [comment]
While testing the new core.py in the above commit, I keep running into a couple of issues. My first issue is a requests error
```python
requests.exceptions.SSLError: HTTPSConnectionPool(host='2020feb.asa-test.hq.eso.org', port=443): 
Max retries exceeded with url: /rh/forceAuthentication (Caused by SSLError(CertificateError("hostname '2020feb.asa-test.hq.eso.org' doesn't match '2019dec.asa-test.hq.eso.org'",),))
```
which may just be an issue with the test system that is currently setup and not an astroquery issue.

If I ignore trying to log in and attempt to stage data (proprietary or non-proprietary), I get an error message related to `dataarchive_url`:
```python
alipnick<1060> python
Python 2.7.3 (default, Jun 11 2013, 15:39:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.alma import Alma
>>> alma = Alma()
>>> links = alma.stage_data('uid://A001/X1465/X1e96')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da_data/lava-test/lib/python2.7/site-packages/astroquery/alma/core.py", line 258, in stage_data
    jdata = self._request('GET', '{}/rh/data/expand/{}'.format(self.dataarchive_url,uid)).json()
AttributeError: 'AlmaClass' object has no attribute 'dataarchive_url'
```
From how I see it, dataarchive_url is defined in _get_dataarchive_url but if you're just calling stage_data(), it's never invoked and therefore never defined? However, sometimes I also get this error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da_data/lava-test/lib/python2.7/site-packages/astroquery/alma/core.py", line 259, in stage_data
    if jdata['type'] != 'PROJECT':
KeyError: 'type'
```
which seems like it is making it past the `dataarchive_url` bit but then failing anyway. Perhaps the `_requests()` call fails and is empty?

Note that I am attempting to run this in Python 2.7.3 and had to change the stage_data function slightly. The only thing I needed to change was to change from the new string formatting `f"{variable}"` to the old `"{}".format(variable)` format. However, I did confirm that I see the same errors as above when running this in Python 3.6.7.

**Comment by alipnick** [comment]
A new development server has been setup for testing the new archive architecture. Using the latest commit for this issue (https://github.com/astropy/astroquery/pull/1644/commits/b514addebde0472c130e9d69e901444cb5b45212), I'm still having issues getting proprietary data to download. I can now login and get the new URLs successfully, but when I try to download the files using alma.download_files() I get bounced by 403 errors. So it seems like for some reason the authentication for logging in is not working for allowing downloads (or perhaps it's still a URL issue?).
```python
alipnick<1004> python
Python 2.7.3 (default, Jun 11 2013, 15:39:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.alma import Alma
>>> alma = Alma()
>>> alma.archive_url='https://almascience-dev.nrao.edu'
>>> alma.login('alipnick')
WARNING: No password was found in the keychain for the provided username. [astroquery.query]
alipnick, enter your password:
INFO: Authenticating alipnick on asa.alma.cl ... [astroquery.alma.core]
INFO: Authentication successful! [astroquery.alma.core]
>>> links = alma.stage_data('uid://A001/X1465/X1ea4')
>>> urls = links['URL']
>>> alma.download_files([urls[0]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da_data/lava-test/lib/python2.7/site-packages/astroquery/alma/core.py", line 507, in download_files
    raise ex
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://almascience-dev.nrao.edu/dataPortal/2019.1.00994.S_uid___A001_X1465_X1ea2_001_of_001.tar
```

**Comment by keflavich** [comment]
is it possible that's a server-side error?  i.e., that the new dev server
isn't synced to the login server?  Can you verify that you're able to
download proprietary data via the web interface?
-- 
Adam

**Comment by alipnick** [comment]
I can confirm that it works from a web browser. In fact, if I take the same link as provided in the Traceback above and put it in my browser it starts downloading the data.

**Comment by alipnick** [comment]
Maybe I spoke too soon. Let me trouble shoot with IT here. It seems to be very inconsistent from the web.

**Comment by alipnick** [comment]
It does not seem to be an issue here, it seems to be the original issue from above with URL construction missing the `sso` for proprietary data. When requesting proprietary data from astroquery, a list of links are provided that when used throw a 403 response due to missing credentials. Modifying the URL to include the `sso` string also fails with a `Too Many Redirects` Error. However, running it again works. Here is a minimal working example to show what I mean. Note that this behavior mimics what happens with a browser as well.
```python
alipnick<1005> python
Python 2.7.3 (default, Jun 11 2013, 15:39:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.alma import Alma

>>> alma = Alma()

>>> alma.archive_url = 'https://almascience-dev.nrao.edu'

>>> alma.login('alipnick')
WARNING: No password was found in the keychain for the provided username. [astroquery.query]
alipnick, enter your password:

INFO: Authenticating alipnick on asa.alma.cl ... [astroquery.alma.core]
INFO: Authentication successful! [astroquery.alma.core]

>>> links = alma.stage_data('uid://A001/X1465/X1e96')

>>> urls = links['URL']

>>> urls[0]
'https://almascience-dev.nrao.edu/dataPortal/2019.1.00994.S_uid___A001_X1465_X1e96_001_of_001.tar'

# Download fails due to missing authentication, 403 access forbidden
>>> alma.download_files([urls[0]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da_data/lava-test/lib/python2.7/site-packages/astroquery/alma/core.py", line 507, in download_files
    raise ex
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://almascience-dev.nrao.edu/dataPortal/2019.1.00994.S_uid___A001_X1465_X1e96_001_of_001.tar

# Creating new URL by adding '/sso' after /dataPortal in the link
>>> test_url = 'https://almascience-dev.nrao.edu/dataPortal/sso/2019.1.00994.S_uid___A001_X1465_X1e96_001_of_001.tar'

# First effort fails due to too many redirects
>>> alma.download_files([test_url])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da_data/lava-test/lib/python2.7/site-packages/astroquery/alma/core.py", line 499, in download_files
    continuation=continuation)
  File "/home/da_data/lava-test/lib/python2.7/site-packages/astroquery/query.py", line 231, in _request
    auth=auth, **req_kwargs)
  File "/home/da_data/lava-test/lib/python2.7/site-packages/astroquery/query.py", line 278, in _download_file
    auth=auth, **kwargs)
  File "/home/da_data/lava-test/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/da_data/lava-test/lib/python2.7/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/da_data/lava-test/lib/python2.7/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

# Running the same command again somehow works and the download begins
>>> alma.download_files([test_url])
Downloading URL https://almascience-dev.nrao.edu/dataPortal/sso/2019.1.00994.S_uid___A001_X1465_X1e96_001_of_001.tar to /users/alipnick/.astropy/cache/astroquery/Alma/2019.1.00994.S_uid___A001_X1465_X1e96_001_of_001.tar ...
|>--------------------------------------------------------------------------------------| 3.4M/1.8G ( 0.18%) ETA  2h 8m
```

**Comment by bsipocz** [comment]
This has been addressed for a long time now.
