### ISSUE TITLE
SkyView.get_image_list returning a list of bad URLs for a very specific coordinate

### ISSUE THREAD

**Issue by odysseus9672** [astropy/astroquery#1643]
I have no idea what is going wrong here. I suspect that the problem might by on NASA SkyView's end, but I do not know how to get the relevant information out of AstroQuery to report the issue to them. Regardless, I have a very specific query that isn't working in Astroquery 0.4. The code to reproduce it is:
```from astroquery.skyview import SkyView
import astropy.units as apu
URLs = SkyView.get_image_list('14.2508965 14.6271877', 
    ['SDSSu', 'SDSSg', 'SDSSr', 'SDSSi', 'SDSSz'], 
    coordinates="J2000", pixels="455,455", 
    scaling="Linear", sampler="Clip", 
    deedger="_skip_", height=180.18*apu.arcsec, 
    width=180.18*apu.arcsec)
```
Then wait for the query to complete. When I try to use any of the items in `URLs` to download a file, I get NASA SkyView's "File Not Found" page. If I nudge the coordinates by as little as an arcsecond, for example `'14.2510965 14.6271877'`, it works fine. Also adding another survey to the list, like `'DSS2 Red'`, forces it to return a list of good URLs. I suspect that something is being cached somewhere, and the cache has become invalid.

**Comment by keflavich** [comment]
Almost certainly this is a caching problem; I was able to access the files from that query without difficulty.  Try deleting the contents of `~/.astropy/cache/astroquery/SkyView/`.

**Comment by odysseus9672** [comment]
Indeed, that sorted the issue. These files should have been pretty old. Doesn't AstroQuery have a timeout/staleness algorithm to clean out old caches?

**Comment by keflavich** [comment]
No, unfortunately; see https://github.com/astropy/astroquery/issues/1531
