### ISSUE TITLE
Switch to use @pytest.mark.remote_data rather than @remote_data

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1660]
We should switch to use the remote_data pytest plugin directly, rather than through astropy

**Comment by pllim** [comment]
I gotta run a bunch of remote data tests for #1666, so I'll fold this into my PR for that.

**Comment by bsipocz** [comment]
for that module or for everything else, too? Would be nice to keep the rest separate if the PR is otherwise conesearch specific

**Comment by pllim** [comment]
As discussed on Slack, I put just the remote data changes in #1670. It touches all affected modules.
