### ISSUE TITLE
MPC format issue with satellites

### ISSUE THREAD

**Issue by JFerreira1994** [astropy/astroquery#1662]
Hello,

I was re-directed here from the astropy github with an issue I had using an astroquery package:

I was performing a task that required grabbing the MPC observations of several asteroids. I requested that the MPC format was maintained, as this was necessary for me, but there seems to be a bug with the way astropy parses satellite observations within these files. Rather than having one line with the observation and another with the satellite identification, both 80 characters long, astropy instead grabs these as a single 160-character long line, which was causing one of my tools to not read these observations correctly.

The step to reproduce this is quite simple, we just need to use:

obs = MPC.get_observations(Asteroid_number,get_mpcformat=True), and look for any line where the observation is identified with a capital "S".

Please let me know if this is indeed a bug within astropy, or if there is possibly some feature that allows to fix this.

Best regards,
João Ferreira

**Comment by bsipocz** [comment]
Could you please report the versions of astroquery and astropy used, as well as a full minimal failing example to help us reproduce the issue? 

cc @mommermi

**Comment by JFerreira1994** [comment]
The versions were Astropy 3.0 and Astroquery 0.3.10.

An example:

from astroquery.mpc import MPC

obs = MPC.get_observations(8,get_mpcformat=True)

obs.to_csv('mpcobs2/8' + '.obs', index=False,
                   header=False)

I chose here 8 as the asteroid number, because it's the first asteroid on the catalogues that I used for my work.

João Ferreira

**Comment by JFerreira1994** [comment]
2 notes to my previous comment:

1 - upgrading astropy to 4.0 and astroquery to 0.4 did not fix this bug, and I forgot one step in the code. Here is the correct version:

from astroquery.mpc import MPC

obs = MPC.get_observations(8,get_mpcformat=True)
obs = obs.to_pandas()
obs.to_csv('mpcobs2/8' + '.obs', index=False,
header=False)

João Ferreira

**Comment by bsipocz** [comment]
Hmm, this seems to be an upstream bug as there are certainly dubious lines in the raw data returned (a total of 111 for this asteroid), e.g.:
```
{'designation': None,
   'discovery_flag': None,
   'number': 8,
   'object_type': 'M',
   'observation_date': '2019 07 15.64141',
   'observatory_code': 'C51',
   'original_record': '00008         S2019 07 15.64141 14 48 28.25 -10 35 42.7                L~39qNC5100008         s2019 07 15.64141 1 - 3989.1521 - 5327.9248 - 1668.1501   ~39qNC51'}
```
So as a workaround for now we could easily just ignore these lines when outputing the mpc formated strings.

However @mommermi might have ways to report the issue upstream to MPC

**Comment by JFerreira1994** [comment]
I found a workaround by splitting the concerned lines in half, but my concern was on correcting this bug for future uses of MPC and for people unaware of it (I wasn't aware until someone else pointed it out to me).

I would like to know if any change is made in this regard. Thank you.

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by mkelley** [comment]
@JFerreira1994 If I understand this correctly, the origin of your problem is that the MPC uses two 80-character lines for observations made by spacecraft:

https://minorplanetcenter.net/iau/info/SatelliteObs.html

So, for these records, a single line up to 160 characters would be correct.

**Comment by JFerreira1994** [comment]
Hi, Michael 

I am not sure what triggered the revival of this issue message, I must have written it a long time ago (March of 2020, from what I gathered), and have found a solution since then. Thanks for the reply, and sorry for taking your time with this. 

Best regards, 
João
