### ISSUE TITLE
Simbad query_region time out

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1674]
While investigating #1672, I noticed this and I can reproduce this time out locally.
```python
>>> from astropy import units as u                                                             
>>> from astropy import coordinates as coord                                                        
>>> ICRS_COORDS_M42 = coord.SkyCoord("05h35m17.3s -05h23m28s", frame='icrs')                   
>>> response = simbad.core.Simbad.query_region_async(ICRS_COORDS_M42, radius=5 * u.deg, equinox=2000.0, epoch='J2000')  
# a long traceback
ReadTimeout: HTTPConnectionPool(host='simbad.u-strasbg.fr', port=80): Read timed out. (read timeout=60)
```

This is the request payload:
```python
{'script': 'votable {main_id,coordinates}\nvotable open\nquery coo 5:35:17.3 -80:52:00 radius=5.0d frame=ICRS equi=2000.0\nvotable close'}
```

**Comment by whjing** [comment]
I'm facing the same issue. How can I resolve it?

**Comment by keflavich** [comment]
Set `simbad.core.Simbad.TIMEOUT` to a larger number.  For me, this query worked with `TIMEOUT=180`.

@pllim is this query in the docs somewhere, or in the tests, such that there is something to fix?  Otherwise I'll close this.

**Comment by pllim** [comment]
It is one of your test cases though the parameters seem different from my post and I don't remember why I picked those original inputs.

https://github.com/astropy/astroquery/blob/88dd76ddf3c41b66cb62f9ec9712921202190f37/astroquery/simbad/tests/test_simbad_remote.py#L101-L106

I don't think that test is well designed because `assert response is not None` does not guarantee that it succeeded, only that it returned something. Don't you have to check the contents too? Are you 100% sure that test is even succeeding in CI?

**Comment by bsipocz** [comment]
> Are you 100% sure that test is even succeeding in CI?

yes. Whether they do something sensible, then the answer is definitely a NO, a lot of the cases we don't check for the content and many services return a 200 even when the result is an error page. Some modules are better than the others, but these few early ones I feel are still in a dire need of better thought out test coverage, etc.

**Comment by keflavich** [comment]
Yes so I think we can leave this issue open as a reminder to go back and look at that remote test... I'll do that next time I have >2m for this

**Comment by ManonMarchand** [comment]
I'll close since the change is merged.
