### ISSUE TITLE
AtomicLineList query spams UserWarnings about html parser in BeautifulSoup

### ISSUE THREAD

**Issue by Knusper** [astropy/astroquery#1677]
Doing atomic line list queries results in a lot of spam output:

Test:

 ```
 from astropy import units as u 
from astroquery.atomic import AtomicLineList
 AtomicLineList.query_object(wavelength_range, wavelength_type = 'Air', element_spectrum='He II')`
```

Results in 

> /home/ehere/miniconda3/envs/astroconda/lib/python3.6/site-packages/astroquery/atomic/core.py:191: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
> 
> The code that caused this warning is on line 191 of the file /home/ehere/miniconda3/envs/astroconda/lib/python3.6/site-packages/astroquery/atomic/core.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.
> 

and much more like this... and then comes the result...

**Comment by bsipocz** [comment]
I don't see any more UserWarnings for this example, and we now fail the CI for unmanaged warnings, so I'm closing the issue as resolved. Feel free to reopen if you still run into warnings.
