### ISSUE TITLE
Add constraints (or column_filters) keyword to query_region()

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astroquery#1684]
I was wondering if I could request a *region with constraints* using the [VizierClass](https://astroquery.readthedocs.io/en/latest/api/astroquery.vizier.VizierClass.html). Apparently it can not be done? There is the `query_constraints()` method which queries a *catalog* with constraints, and the `query_region` which queries a region without constraints.

Am I missing something and this in fact can be done? If  not could it be a feature request or is it just not possible?

**Comment by keflavich** [comment]
I'm not sure immediately - if it can be done in the web interface, it can be done here, but I'm not sure it can.

**Comment by Gabriel-p** [comment]
I checked and indeed it *can* be done using Vizier's interface. For example you can query a region here:

https://vizier.u-strasbg.fr/viz-bin/VizieR-3?-source=I/345/gaia2

and use the constraint `<19.0` for the `Gmag` column. It works as expected as far as I can see. Can this be done with `query_region()`?

**Comment by keflavich** [comment]
I think no.  You can query _any catalog_ with constriants:
`Vizier.query_constraints(catalog='I/345/gaia2', Gmag='>19')`

You can query a square region in the catalog:
`Vizier.query_constraints(catalog='I/345/gaia2', Gmag='>19', RA_ICRS='>41.0 & <42.0', DEC_ICRS='>6.0 & <7.0')`

You can query a region in the catalogs without constraints:
`Vizier.query_region(coordinates.SkyCoord.from_name('M81'), radius=10*u.arcmin, catalog='I/345/gaia2',)`

But I don't think you can do _both_ constraints and regions at the same time.  That said, I don't see any reason you shouldn't be able to, so maybe we just need to figure out the right combination of information to send... it's possible that if we send the constraint query info along with the region query, it would work.  I don't know!

**Comment by Gabriel-p** [comment]
Querying a square region of the catalog with `query_constraints()` is as far as I can see identical to querying a square region with `query_region()`. In this case then this feature is already present, right?

**Comment by keflavich** [comment]
Yeah, but I don't know if you can query a circular region with the constraints approach.  Also, the keywords you use aren't uniform - they change from catalog to catalog.

**Comment by jwoillez** [comment]
@Gabriel-p @keflavich You can actually do it with the following somewhat terrible syntax:

    v = Vizier(catalog='I/345/gaia2', column_filters={'Gmag': '<19'})
    tables = v.query_region(coordinates.SkyCoord.from_name('M81'), radius=10*u.arcmin)

The documentation can be found there: https://astroquery.readthedocs.io/en/latest/vizier/vizier.html#specifying-keywords-output-columns-and-constraints-on-columns

We could probably extend `query_region()` to accept a `constraints` (or `column_filters`) keyword, making the following equivalent to the code above:

    tables = Vizier.query_region(coordinates.SkyCoord.from_name('M81'), radius=10*u.arcmin,
        catalog='I/345/gaia2', constraints={'Gmag': '<19'})

@keflavich Thoughts?

**Comment by keflavich** [comment]
Ah, thanks @jwoillez, that's a great example use.  And, yes, we should support this approach - I'll leave this issue open as a feature request.
