### ISSUE TITLE
Can't XMatch two local tables/files

### ISSUE THREAD

**Issue by iskren-y-g** [astropy/astroquery#1687]
Hi,

I want to XMatch two local files, or two astropy Tables, however, it seems that cat2 is always expected from a remote url (request)? I tried to set XMatch.URL='file:///path/to/my/file/' or just to provide an astropy table as input to cat2, but neither worked. I get 
"No connection adapters were found for ... "

Is there a way around this?

Thanks!

**Comment by bsipocz** [comment]
Does the web interface lets you match two uploaded tables?

**Comment by iskren-y-g** [comment]
Yes it does: http://cdsxmatch.u-strasbg.fr/
You just have to upload the tables in their "Tables management" tab, and then select them from the "My store" in the main X-Match tab.
One can always write a function that uses two coordinate columns from two input tables to calculate the distance and given the choice of matching radius make a new table, but why reinventing the wheel ...
