### ISSUE TITLE
load_data don't load

### ISSUE THREAD

**Issue by agallenne** [astropy/astroquery#1690]
Hi,

Since about 3 days, the "load_data" function of the Gaia module is not working anymore, it is just stuck or waiting for something. Here is an example:

from astroquery.gaia import Gaia
Gaia.load_data(ids="4085919765884068736", retrieval_type="epoch_photometry")

I have updated the Astroquery package and the Gaia servers are all back up.

**Comment by jwoillez** [comment]
@agallenne Works for me now. Do you confirm?

**Comment by agallenne** [comment]
@jwoillez Yes, with some new warnings, but it works. The problem was apparently generated by the connection to the Gaia cluster database, and not to the python module.

**Comment by jwoillez** [comment]
@keflavich @bsipocz Issue can be closed.
