### ISSUE TITLE
importing syntax for simbad

### ISSUE THREAD

**Issue by jpdeleon** [astropy/astroquery#1696]
I have a simple question about importing.

Why
```python
import astroquery as aq

s = aq.simbad.Simbad()
s.query_region
```
results in `AttributeError: module 'astroquery' has no attribute 'simbad'`,

whereas
```python
from astroquery.simbad import Simbad

s = Simbad()
s.query_region
```
works fine?

I follow the first format and it works fine for e.g. `aq.vizier.Vizier` & `aq.mast.Observations` but does not for `aq.simbad.Simbad`.

**Comment by bsipocz** [comment]
> I follow the first format and it works fine for e.g. aq.vizier.Vizier & aq.mast.Observations but does not for aq.simbad.Simbad.

The main namespace is not populated, and I'm fairly certain that neither of those you list should work as you suggest. 
Please follow the guidelines from the docs of importing the classes that you use explicitly, in this case:
`from astroquery.simbad import Simbad`

**Comment by jpdeleon** [comment]
Oh you're right. Thank you. I will follow the importing guideline.
