### ISSUE TITLE
ALMA : Stage_data -- pb : retrieve all mousId instead of the specified one

### ISSUE THREAD

**Issue by PhilippeSalome** [astropy/astroquery#1704]
The case is the following : when there are several MousId in a  GroupOusId; like in the example below, the astroquery stage_data retrieves the products of all the mousId (not only the requested one).

The command below is suppose to grab 'uid://A001/X1354/X5a0’ only, but it lists all the products of the MousId X5a2 and X5a4 too (while this was not requested). 

In [5]: from astroquery.alma import Alma 
   ...: alma=Alma()  
   ...: ll=alma.stage_data('uid://A001/X1354/X5a0', expand_tarfiles=True) 

In [5]: for i in range(len(ll)): 
   ...:     print(ll[i]) 

……
----------------------- --------------------------------------------------- ---- ---------- ---------- --------------------- ------------------------------------------------------------------------------------------ -------------
uid___A002_Xd8978c_X88c 2018.1.01684.S_uid___A002_Xd8978c_X88c.asdm.sdm.tar ASDM 2486318080    UNKNOWN uid://A001/X1354/X5a4 https://almascience.eso.org/dataPortal/2018.1.01684.S_uid___A002_Xd8978c_X88c.asdm.sdm.tar          True

**Comment by bsipocz** [comment]
`stage_data` has been deprecated and removed, thus closing this issue.

Feel free to reopen if you still have this issue, and please include an updated example to reproduce.
