### ISSUE TITLE
Add pyvo as dependency

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1713]
At this point I think it's clear that pyvo is well maintained and more of our modules will rely on it. So to make life easier, I suggest to make it a required dependency. (We originally said to make that move once the `utils.tap` is factored out and `gaia` will use it, too, but maybe it's not necessarily to stick to that timeline.)

cc @keflavich @ceb8

**Comment by ceb8** [comment]
I think that sounds reasonable. It will also be a good indication that pyvo is the preferred VO interface for new modules that use VO protocols.

**Comment by bsipocz** [comment]
We depend on pyvo for a while, closing this issue now.
