### ISSUE TITLE
MAST: Kepler FFIs cannot be found

### ISSUE THREAD

**Issue by astrobatty** [astropy/astroquery#1714]
I don't know if this issue is related to `astroquery` or MAST API, but Kepler FFIs cannot be downloaded from the location which is given by MAST API.

If I want to access an FFI

```
from astroquery.mast import Observations

kplrObs = Observations.query_criteria(obs_id="kplr2009170043915_84", obs_collection="KeplerFFI")
kplrProds = Observations.get_product_list(kplrObs[0])
filteredProd = Observations.filter_products(kplrProds, extension='kplr2009170043915_ffi-cal.fits', 
                                        mrp_only=False)

Observations.download_products(filteredProd, mrp_only=False, cache=False)
```
I get the following HTTPError:

![image](https://user-images.githubusercontent.com/45241990/80869887-2d8d1500-8ca3-11ea-92bc-39fbf8ce7268.png)

However, FFIs are available [here]( https://archive.stsci.edu/pub/kepler/ffi/).

**Comment by scfleming** [comment]
This is a MAST problem and not an astroquery issue.  I have made a change that should restore access to Kepler FFI's through astroquery.  If you can confirm, then this can be closed.

**Comment by astrobatty** [comment]
It works now. Thanks!

**Comment by ceb8** [comment]
Hi @astrobatty, sorry to take so long to respond to this. Can you try your code again? I was able to download the file just fine with your code snippet so I think you had the bad luck to try it while the download server was down.
