### ISSUE TITLE
Default to verbose=False upon TapPlus instantiation

### ISSUE THREAD

**Issue by profjsb** [astropy/astroquery#1722]
When instantiating a subclass of the `TapPlus` class (e.g. `GaiaClass`), the connection info is printed to stdout:
```
>>> from astroquery.gaia import Gaia 
Created TAP+ (v1.2.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
Created TAP+ (v1.2.1) - Connection:
	Host: geadata.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
```
Since `Gaia = GaiaClass` and `GaiaClass` is a subclass of `TapPlus` this import statement appears to establish the relevant connections and show them using the default `verbose=True` for `TapPlus`. Since verbose-by-default statements can pollute log files which capture stdout, it would be good to have verbosity turned off by default (either in `GaiaClass` or `TapPlus` itself). Alternatively, this could be controlled in a config file.

I'm happy to make a PR to implement  `verbose=False` for `TapPlus` but I thought it was enough of a behavior change that it would be good to have a discussion of this first.

**Comment by bsipocz** [comment]
I would support this proposal, but let's ping the gaia folks @jcsegovia for their insight

**Comment by bsipocz** [comment]
(We have the switch to use tap from pyvo on the roadmap, so some behaviour change will definitely happen)

**Comment by profjsb** [comment]
Just a ping on this, @jcsegovia. Switching the default to `False` is still of interest.

**Comment by jpl-jengelke** [comment]
Please change the default to `False`. I feel like instantiating a subclass wrapping around `GaiaClass` just to turn off this intrusive print statement.

**Comment by keflavich** [comment]
:+1: I'm also in favor of defaulting to non-verbose.   A PR would be welcome.

**Comment by jpl-jengelke** [comment]
@keflavich -- Here is your pull request: https://github.com/astropy/astroquery/pull/2085

**Comment by jpl-jengelke** [comment]
Making this change I am a little concerned that there may be instances where verbosity is helpful to verify network connections. I should note the fact that this class instantiates in verbose mode is currently an oversight. It appears that in all other parts of Gaia the verbosity is explicitly set or defaults to False. So adding this change should serve to fulfill the original intent of the code. 

In reference to changing the default behavior, the Gaia core class also could be modified to accept a setting to change verbosity:
1. Possibly a config value to set verbosity
2. Alternately an environment variable to set verbosity. 
I don't know if there are such mechanisms in Astropy/Astroquery today that would allow implementing either of these solutions. I also don't think it's absolutely necessary.

**Comment by keflavich** [comment]
@jpl-jengelke there are configuration mechanisms in place that would allow what you suggest.  And, indeed, verbosity can be helpful for diagnosing network issues - but instantiation of the class is probably not the right time to do that.
