### ISSUE TITLE
alma.stage_data : isProprietary - always True ?

### ISSUE THREAD

**Issue by PhilippeSalome** [astropy/astroquery#1730]
It seems that the stage_data returns a line with the variable isProprietary = True even when the file is no longer proprietary. Check done : it is indeed possible to download the file from the ASA.

```
from astroquery.alma import Alma 
alma=Alma()  
ll=alma.stage_data('uid://A001/X1296/X3b8', expand_tarfiles=True)
```

returns (file line):
```
id    name    type     size    permission mous_uid          URL            isProprietary     byte                                                                                                                                                                                   
-----------
member.uid___A001_X1296_X3b8.NGC1068_sci.spw0_4_8_12_16_20_24_28_32.cube.I.manual.image.pbcor.fits member.uid___A001_X1296_X3b8.NGC1068_sci.spw0_4_8_12_16_20_24_28_32.cube.I.manual.image.pbcor.fits.tar PIPELINE_PRODUCT 26244012032    UNKNOWN     None https://almascience.eso.org/dataPortal/member.uid___A001_X1296_X3b8.NGC1068_sci.spw0_4_8_12_16_20_24_28_32.cube.I.manual.image.pbcor.fits.tar          True

In [8]: ll[0][7]                                                                                                                                      
Out[8]: True
```

**Comment by keflavich** [comment]
Well this is strange.  It looks like all of the contents of the tarball are _not_ proprietary, but the parent UID is?  that makes no sense.

```
In [5]: alma.is_proprietary('uid___A002_Xc59134_X1257')
Out[5]: False

In [6]: alma.is_proprietary('uid://A001/X1296/X3b8')
Out[6]: True
```

So, this is a real issue, but it's at least partly upstream.  I hope we can circumvent this with the ALMA refactor in #1689

**Comment by PhilippeSalome** [comment]
Hi, 

Thanks for your answer ! This is all very strange. I was wondering whether it could be due to the extension of the proprietary period that ALMA has decided. Maybe ESO/NRAO have changed something in the flags that unexpectedly induces this strange behavior. I was waiting for the end of the period to do the test again and come back to you. 

Cheers, 
Philippe

**Comment by PhilippeSalome** [comment]
Hi, 

Just to keep you posted : the extent of the ALMA proprietary period is now over. And unfortunately, the pb remains. I am afraid, you were right. There is a strange proprietary flag value that is returned but not consistent with the real status of the data. 

Cheers, 
Philippe

**Comment by bsipocz** [comment]
@keflavich - did the alma refactors fixed this?

**Comment by keflavich** [comment]
I suspect so, but it's difficult to verify things right now because of the state of ALMA.  I think this is best regarded as an upstream issue we couldn't do anything about anyway - the data were returned as queried, but they were wrong.  So I'm closing.
