### ISSUE TITLE
ValueError in launch_job

### ISSUE THREAD

**Issue by Blitzman** [astropy/astroquery#1735]
Hi!

I am launching the following simple query: 

```
query_text = '''SELECT TOP 50000 ra, dec, parallax, pmra, pmdec, radial_velocity
FROM gaiadr2.gaia_source
WHERE parallax > 0 AND
    radial_velocity IS NOT null
ORDER BY random_index
'''
```

to only fetch 50000 random stars with positive parallax and radial velocity present. I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    job = Gaia.launch_job(query_text)
  File "/home/albert/anaconda3/lib/python3.7/site-packages/astroquery/utils/tap/core.py", line 339, in launch_job
    results = utils.read_http_response(response, output_format)
  File "/home/albert/anaconda3/lib/python3.7/site-packages/astroquery/utils/tap/xmlparser/utils.py", line 42, in read_http_response
    result = APTable.read(data, format=astropyFormat)
  File "/home/albert/anaconda3/lib/python3.7/site-packages/astropy/table/connect.py", line 52, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "/home/albert/anaconda3/lib/python3.7/site-packages/astropy/io/registry.py", line 523, in read
    data = reader(*args, **kwargs)
  File "/home/albert/anaconda3/lib/python3.7/site-packages/astropy/io/votable/connect.py", line 73, in read_table_votable
    input = parse(input, table_id=table_id)
  File "/home/albert/anaconda3/lib/python3.7/site-packages/astropy/io/votable/table.py", line 137, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/home/albert/anaconda3/lib/python3.7/site-packages/astropy/io/votable/tree.py", line 3344, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:0: no element found
```

and I have no clue of what can be going on after a few searches. However, it seems to happen randomly when I request more than 40000 stars.

**Comment by keflavich** [comment]
My guess is that there is some missing data in the returned table - or it's an empty table - and we're not catching it neatly.   It might just be a temporary server issue, though.

cc @jcsegovia could you help, or identify the right person to help?

**Comment by Blitzman** [comment]
Bumping this issue up! We also get the same error when requesting <40.000 stars but only sporadically (very uncommon). Thanks!

**Comment by pllim** [comment]
Hack the code so that it saves whatever it gets back as plain text file rather than trying to parse. Then see why it is not parsing.

**Comment by stargaser** [comment]
I have seen this `ValueError` before! I think what may be happening is reaching a limit on the number of rows that the service provides as a synchronous query.

I ran your query successfully as an asynchronous query.
```
from astroquery.gaia import Gaia
query_text = """
    SELECT TOP 50000 ra, dec, parallax, pmra, pmdec, radial_velocity
    FROM gaiadr2.gaia_source
    WHERE parallax > 0 AND radial_velocity IS NOT null
    ORDER BY random_index
"""
job = Gaia.launch_job_async(query_text)
```
Note that you can get the URL for the job after it finishes, with `job.remoteLocation`, and you can open that up in a web browser...then in a shell you can use `curl` or `wget` to fetch a table from the results URL that is inside, if you want the VOTable. 

For workshops teaching pyvo we (the NASA VO group) have been recommending use of async queries, especially when the results get large.

**Comment by smoh** [comment]
Synchronous queries time out after 30 seconds and currently returns nothing if it fails in that time (which is undesirable but nothing a user can fix). The simplest solution is to run it as async as mentioned above. The randomness probably is dependent on whether it just finishes or not.

I queried the Gaia Helpdesk about this and suggested some error message be returned but I guess it has not been implemented yet.

From the client-side with current implementations, perhaps one can check the length of the data and return a message to the user as the length will be 0.

**Comment by bsipocz** [comment]
The error message has since been improved, and now shows that this is a timeout. 

```
HTTPError: Error 408: 
Job timeout/aborted.
```

So I'm closing this with the conclusion that the other commenters suggested: use the async methods for larger queries, but please do feel free to open an issue if there is any issues with the async version.
