### ISSUE TITLE
HTTPError: 404 Client Error: for ALMA astroquery

### ISSUE THREAD

**Issue by mjastro** [astropy/astroquery#1737]
Hi, 

recently somehow alma astroquery doesn't work properly with the following commands,
```
Alma.retrieve_data_from_uid(uids[0])
Alma.stage_data(uids[0]) 
```

all give the following error message :

```
HTTPError: 404 Client Error:  for url: https://almascience.eso.org/rh/submission/rh
```

"uids" is obtained by doing 
```
uids =  np.unique(test['Member ous id']), 
```
where 
```
test =Alma.query(**specified keywords**)
```

I wonder how I can fix the problem. I am using astroquery 0.4. Severl months ago, with 0.3, it certainly worked though... Thank you in advance for your help!

**Comment by keflavich** [comment]
Could you please specify what `**specfied_keywords**` are?  We can't debug this without knowing what parameters cause the problem.

The ALMA remote tests are presently (mostly) passing, so unless the ESO mirror was down, there's no obvious issue here.

Make sure you're on the latest version of astroquery - if you're using a version more than about a month old, it is likely that the ALMA archive interface has changed and that is the source of your problem.

**Comment by mjastro** [comment]
Thanks, I thought that I was on the very latest version, but I was not (0.4). With the 0.4.1.dev0, it worked well. I think this can be closed.

**Comment by alipnick** [comment]
I'm having this issue with astroquery version 0.4.1. 
```python
>>> from astroquery.alma import Alma
>>> alma = Alma()
>>> links = alma.stage_data('uid://A001/X133d/X3b63')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/alipnick/.local/lib/python3.6/site-packages/astroquery/alma/core.py", line 281, in stage_data
    req.raise_for_status()
  File "/opt/local/stow/Python3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://almascience.nrao.edu/asax//rh/data/expand/uid___A001_X133d_X3b63
```
The Traceback shows that the url has an extra "/" after "asax" that should not be there. Resetting the Alma.dataarchive_url seems to fix the issue:
```python
>>> alma.dataarchive_url = 'https://almascience.nrao.edu'
>>> links = alma.stage_data('uid://A001/X133d/X3b63')
>>>
```

**Comment by keflavich** [comment]
I can't reproduce this issue.  The original version works fine for me:
```python
>>> from astroquery.alma import Alma
>>> alma = Alma()
>>> links = alma.stage_data('uid://A001/X133d/X3b63')
>>> links
<Table length=25>
```

version:
```python
In [6]: astroquery.__version__
Out[6]: '0.4.2.dev6510'
```
