### ISSUE TITLE
Wrong id_type assigned

### ISSUE THREAD

**Issue by michaelaye** [astropy/astroquery#1742]
```python
from astroquery.jplhorizons import Horizons
obj = Horizons(id='Venus', location='568', epochs=["2020-06-19","2020-06-20"])
print(obj)
```
```
JPLHorizons instance "Venus"; location=568, epochs=['2020-06-19', '2020-06-20'], 
id_type=smallbody
```
Should be "majorbody" for a planet according to docs. Or was Venus demoted as well?? ;)

v 0.4

**Comment by bsipocz** [comment]
I'm not sure it ever worked, we don't seem to have a test for it. Might 

cc @mkelley

**Comment by mkelley** [comment]
There is no checking of the ID names.  `Horizons(id='Venus', id_type='smallbody')` searches for asteroids named Venus.  `Horizons(id='Venus', id_type='majorbody')` should find the planet.  A major issue with divining `id_type` from `id` is that there is a Jovian satellite (Horizons major body) and an asteroid named Io.  Maybe there are other examples.

**Comment by michaelaye** [comment]
i just realized that there is a logic flow bias towards small bodies. It's first trying smallbody, but when I force "majorbody", it replies as designed with confusion info.

**Comment by mkelley** [comment]
By number the solar system is biased to small bodies :)  But I concede that major bodies dominate by mass.  Do you recommend a documentation change, changing `id_type` to required, nothing, or something else?

**Comment by michaelaye** [comment]
hm, i'd think that searching for an asteroid by default is confusing for a general JPL Horizons tool (which is how this looks from the docs, even so it was funded by sbpy).
I'd wish for it to be neutral, could it not simply return the potentially confusing items always, like it does when I provide "Venus" with id_type="majorbody":

```

ValueError: Ambiguous target name; provide unique id:
  ID#      Name                               Designation  IAU/aliases/other   
  -------  ---------------------------------- -----------  ------------------- 
        2  Venus Barycenter                                                     
      299  Venus                                                                
     -248  Venus Express (spacecraft)                      VEX        
```
So, to keep id_type optional, one could return this list with an extra column that shows the required id_type (like for the Io confusion).

Or, (slightly less user-friendly, but ok i guess) demand the id_type. But, because in the Venus case, the result is still creating confusion, i'd consider it more efficiently for the overall process to just let the user deal with the confusion already in the first step, then the id_type can stay optional.

**Comment by bsipocz** [comment]
Maybe having this brief explanation https://github.com/astropy/astroquery/issues/1742#issuecomment-645423229 would be enough for the docs?

**Comment by michaelaye** [comment]
sure, if you want to leave it biased as it is. it will avoid the confusion of what's happening. Doesn't remove the surprise though that a general Horizons interface prefers small bodies?

**Comment by mkelley** [comment]
@michaelaye I agree that the default of smallbody isn't the best for a general tool.  I'd rather not make immediate breaking change.  @bsipocz, if we go that route would astroquery be OK with a deprecation warning?

Regarding the search, the results you got for Venus are all provided via JPL Horizons via the search query.  I don't think we should go beyond reflecting the Horizons interface functionality.  The Horizons [documentation](https://ssd.jpl.nasa.gov/?horizons_doc#selection) illustrates their query logic:
```
    Horizons> Io;         (Semi-colon tells Horizons its a small-body look-up)

    Horizons> 85          (No match on major body [at least right now], so
                           search "falls through" to small-body number look-up)

    Horizons> 85;         (Semi-colon tells Horizons its a small-body look-up)

    Horizons> NAME= Io;   (Keyword "NAME" tells Horizons its an asteroid or
                           comet small-body look-up)

    Horizons> ASTNAM= Io; (Keyword "ASTNAM" tells Horizons its an asteroid name)
```
Our `id_type='majorbody'` maps to the second example, which, strictly speaking is NOT a major body search.  But, if anything, that could be considered a default search.

**Comment by michaelaye** [comment]
> Our `id_type='majorbody'` maps to the second example, which, strictly speaking is NOT a major body search. But, if anything, that could be considered a default search.

i'm not following what happens when you set id_type='majorbody'. 
In Horizons (telnet), when i type in "Venus" without anything else, i get what i pasted above. Shouldn't this Horizons interface behave the same?

**Comment by michaelaye** [comment]
obviously one shouldn't making breaking changes because one lonely user demands it ;) I'm just thinking what's best for the future. I am teaching REU students this summer and am pushing more and more people to use standardized tools like astropy and what I and others develop around planetarypy, so we are discussing a lot about interfaces to existing web tools these days. and then a Horizons interface came up in my Venus project, which is why I am popping up out of nowhere, complaining. ;)

**Comment by bsipocz** [comment]
>  @bsipocz, if we go that route would astroquery be OK with a deprecation warning? 

of course, that sounds great. If a quick PR is possible I would wait for it for 0.4.1, which I'm planning to tag today (pending merging and fixing a few stuff).

**Comment by bsipocz** [comment]
> Regarding the search, the results you got for Venus are all provided via JPL Horizons via the search query. I don't think we should go beyond reflecting the Horizons interface functionality.

👍

**Comment by michaelaye** [comment]
i agree, but i hope we agree that it currently does NOT reflect the Horizons interface functionality.

**Comment by mkelley** [comment]
Let me propose we change the default `id_type` to `None` but keep the same behavior (default is a small-body search).  We also raise a `DeprecationWarning` indicating that this behavior will change in the future to match Horizons: "The system will then try to match against the major body list. If a match is found among the list of major bodies, it will be displayed. If no match is found among the major bodies, it will then continue on and match against the small-body database."

Thanks for the feedback, @michaelaye .

**Comment by mkelley** [comment]
@michaelaye , @bsipocz This issue should be addressed now.  Can we close it?

**Comment by bsipocz** [comment]
@mkelley - Sure, I'm closing it now. Feel free to close any issues that you find obsolete or resolved.
