### ISSUE TITLE
Vizier.query_region returns an empty table

### ISSUE THREAD

**Issue by jvines** [astropy/astroquery#1761]
Hi,

Something weird is happening, I'm trying to run the following:
```python
ra = 273.4778192516744
dec = 64.39743824424548

from astroquery.vizier import Vizier
import astropy.units as u
from astropy.coordinates import Angle, SkyCoord
cat = Vizier.query_region(
SkyCoord(
            ra=ra, dec=dec, unit=(u.deg, u.deg), frame='icrs'
        ), radius=3*u.arcmin
)
```
But it keeps returning an empty list, whereas if I change use another set of ra/dec it works correctly. If I use query_region_async I see an error regarding no server found. What could be happening??

Thank you.

**Comment by keflavich** [comment]
This is possibly a case of a bad cached query.

You can try clearing the cache with:
https://docs.astropy.org/en/stable/api/astropy.utils.data.clear_download_cache.html

or by removing files in
~/.astropy/cache/astroquery/Vizier/
(which is the default cache directory)

If that doesn't fix it, please show the exact exception you received.

**Comment by jvines** [comment]
Hi @keflavich ,

You're a life saver! Removing the files fixed the problem for me :D
Thank you very very much!
