### ISSUE TITLE
Mast: Add column filtering to astroquery.mast.Catalog.query_region

### ISSUE THREAD

**Issue by odysseus9672** [astropy/astroquery#1765]
The `astroquery.mast.Catalogs.query_region` function does not respond to the `columns` keyword argument to allow the user to select a subset of, or different set, of columns to download. Fixing this inconsistency would, hopefully, also allow the user to download data that isn't currently exposed (for example `nuv_fluxerr_auto`). Ideally, it should be possible to get every column described in the <A HREF="http://www.galex.caltech.edu/wiki/Public:Documentation/Appendix_A.1">MAST GALEX catalog schema</A>.

**Comment by ceb8** [comment]
The API which Astroquery uses to query the GALEX catalog does not allow the specification of columns and returns a fixed set of columns. So unfortunately this enhancement is not currently possible.
