### ISSUE TITLE
Gemini: add ability to create a logged in session

### ISSUE THREAD

**Issue by olyoberdorf** [astropy/astroquery#1778]
The GOA has user accounts.  It would be helpful to have a login() feature to allow people to use their account when accessing the GOA via astroquery.

**Comment by olyoberdorf** [comment]
I am implementing this via a login() method that will add your credentials to the session. This uses the same _login() approach as other modules in astroquery.

For example:

`gemini.Observations.login('someuser', 'somepassword')`

**Comment by bsipocz** [comment]
#1780 had added these.
