### ISSUE TITLE
simbad.query_object returns only first row in votable field "fe_h"

### ISSUE THREAD

**Issue by eloubrown** [astropy/astroquery#1781]
I am looking at a large sample of several thousand stars and gathering stellar parameters from GAIA and Pastel databases. For stars not included in those datasets I am using astroquery.simbad to gather data – specifically metallicities. I have added the votable field "fe_h". astroquery.simbad.query_object(target) only returns the first row of the Fe_H catalogue data (Teff, log(g) and Fe/H), even when there are multiple rows present. Where the first row does not actually contain a value for Fe/H, the query returns no result, whereas in many cases there is a valid result in the other rows. Can anyone help?

Thanks

**Comment by aoberto** [comment]
Hello,
From SIMBAD, It is quite difficult to give, and parse a list of data (that could have different fields), inside a list of objects. So we have decided, by construction, that SIMBAD will only give the latest entry when querying objects in Votable. I understand, that in your case, it is not very convenient, and It will surely evolve in the future. So I could suggest to use TAP through http://simbad.u-strasbg.fr/simbad/sim-tap or TOPCAT or pyvo. With this sort of query : 
```
SELECT * FROM mesFe_h JOIN ident 
USING(oidref) WHERE id  IN ('V* EK Psc','PG 1108+325','SDSS J040011.26-044546.3','EX OF WRONG NAME')
ORDER BY id
```
I hope it helps
