### ISSUE TITLE
RTS ONLY for JPL Horizons

### ISSUE THREAD

**Issue by XaviTorello** [astropy/astroquery#1799]
Will be great if the JPL Horizons Ephemerides could deal with RTS (rise-transit-set only)

The CGI uses the `rts_flag` property, but the batch processor seems to need the `R_T_S_ONLY` param.

More details at https://ssd.jpl.nasa.gov/?horizons_doc#rts

**Comment by bsipocz** [comment]
Has been addressed by https://github.com/astropy/astroquery/pull/1802
