### ISSUE TITLE
Alma.query_object finds irrelevant observations

### ISSUE THREAD

**Issue by heh15** [astropy/astroquery#1806]
I tried to search for ALMA observations for some LIRGs and ULIRGs using `Alma.query_object`.  However, it seems to return more projects than the online search results. I tested it with NGC 2623 with the following command:
```
results  = Alma.query_object('NGC 2623', science = True) 
len(table.unique(results, keys='proposal_id')['proposal_id'])
```

It returns 288 projects, with many projects (focused on high-z galaxies) clearly not including NGC 2623. However, when I search online, I only found 3 projects. My `astroquery` version is `0.42.dev0`.

**Comment by keflavich** [comment]
cc @andamian

**Comment by adeleplunkett** [comment]
I think something similar might happen with the example of Alma.query_region, from https://astroquery.readthedocs.io/en/latest/alma/alma.html.  It takes a very long time.  Can you please check if this works?  My astroquery version is 0.4.2.dev0.

`>>> from astropy import coordinates
>>> from astropy import units as u
>>> orionkl = coordinates.SkyCoord('5:35:14.461 -5:21:54.41', frame='fk5',
...                                unit=(u.hour, u.deg))
>>> result = Alma.query_region(orionkl, radius=0.034*u.deg)
>>> uid_url_table = Alma.stage_data(result['Member ous id'])
>>> # Extract the data with tarball file size < 1GB
>>> small_uid_url_table = uid_url_table[uid_url_table['size'] < 1]
>>> # get the first 10 files...
>>> filelist = Alma.download_and_extract_files(small_uid_url_table[:10]['URL'])`

**Comment by aida-ahmadi** [comment]
Is there an update on this @andamian? I am using `astroquery` version `0.4.2.dev6380` and running into the same issues mentioned above. 

For the example at https://astroquery.readthedocs.io/en/latest/alma/alma.html#querying-targets-and-regions I find len(m83_data) is 3460. @keflavich's example notebooks (e.g. https://nbviewer.jupyter.org/gist/keflavich/bb12b772d6668cf9181a) also give different outputs.

**Comment by andamian** [comment]
@aida-ahmadi & @heh15 - This is related to #1792. My understanding is that ALMA already has a patch for their TAP Web service that it's making its way to production. The ALMA ticket is still open.

If you are *really really stuck* you can use the hack below to access the *test* ALMA services that we run at the CADC. But a big WARNING: this is just a test environment: data might not be up-to-date, accurate or complete. You can use it for development but need to wait for ALMA services to access real data.
```
>>> from astroquery import alma
>>> from astropy import table
>>> client = alma.Alma()
>>> alma.core.ALMA_TAP_PATH = 'obscore'
>>> client.archive_url = 'https://alma.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/'
>>> results = client.query_object('NGC 2623', science = True)
>>> len(table.unique(result, keys='proposal_id')['proposal_id'])
3

**Comment by aida-ahmadi** [comment]
Thanks for the update @andamian!

**Comment by andamian** [comment]
@aida-ahmadi  & @heh15 - Good news: the ALMA patch has made it to the production servers. You get this now:

```
from astroquery.alma import Alma
>>> from astropy import table
>>> result = Alma.query_object('NGC 2623', science = True)
>>> len(table.unique(result, keys='proposal_id')['proposal_id'])
3
```
which I think is what you expect. I hope this solves the problem but please let me know if you have other issues.

And sorry for the delay.

**Comment by heh15** [comment]
Thanks for the help @andamian! The issue is now fixed for me.
