### ISSUE TITLE
astroquery.Vizier query yields EOF error for the VPHAS (large) catalog 

### ISSUE THREAD

**Issue by abulatek** [astropy/astroquery#1812]
I'm trying to access the [VPHAS catalog from VizieR](https://vizier.u-strasbg.fr/viz-bin/VizieR?-source=II/341) using astroquery, but the commands I have used to access other catalogs are not working for the VPHAS catalog (319,126,837 rows in total). The command runs successfully when I set `row_limit=50`. Here's the command I'm using: 

```
vphas_coords = Vizier(columns=['RAJ2000','DEJ2000'], row_limit=-1).query_constraints(catalog='II/341/vphasp')[0]
```

This yields an "EOFError: Ran out of input" immediately after the command is issued. 

I've attached a full error traceback in a text file in case it helps. I'm using `astroquery` version `0.4.2.dev0`. Please let me know if you need any additional information! 

[new_traceback.txt](https://github.com/astropy/astroquery/files/5159550/new_traceback.txt)

[edit: adding traceback here from the linked file]
```
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-5-f0cb4696b30a> in <module>
----> 1 vphas_coords = Vizier(columns=['RAJ2000','DEJ2000'], row_limit=319126837).query_constraints(catalog='II/341/vphasp')[0]

/anaconda3/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

/anaconda3/lib/python3.7/site-packages/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     24             verbose = kwargs.pop('verbose', False)
     25
---> 26             response = getattr(self, async_method_name)(*args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response

/anaconda3/lib/python3.7/site-packages/astroquery/vizier/core.py in query_constraints_async(self, catalog, return_type, cache, get_query_payload, **kwargs)
    510         response = self._request(
    511             method='POST', url=self._server_to_url(return_type=return_type),
--> 512             data=data_payload, timeout=self.TIMEOUT, cache=cache)
    513         return response
    514

/anaconda3/lib/python3.7/site-packages/astroquery/query.py in _request(self, method, url, params, data, headers, files, save, savedir, timeout, cache, stream, auth, continuation, verify, allow_redirects, json)
    253                                              json=json)
    254             else:
--> 255                 response = query.from_cache(self.cache_location)
    256                 if not response:
    257                     response = query.request(self._session,

/anaconda3/lib/python3.7/site-packages/astroquery/query.py in from_cache(self, cache_location)
    107         try:
    108             with open(request_file, "rb") as f:
--> 109                 response = pickle.load(f)
    110             if not isinstance(response, requests.Response):
    111                 response = None

EOFError: Ran out of input
```

**Comment by keflavich** [comment]
This is a question in part to the CDS team (@aoberto, @gilleslaindais) - what should we expect when querying huge tables like this?

**Comment by bsipocz** [comment]
@abulatek - The traceback is suspicious to me, could you try to clean the cache first (from~/.astropy/cache/astroquery/Vizier/)? Or even use `cache=False`

``vphas_coords = Vizier(columns=['RAJ2000','DEJ2000'], row_limit=319126837).query_constraints(catalog='II/341/vphasp', cache=False)[0]``

**Comment by abulatek** [comment]
Using `cache=False` seemed to work—thank you for the suggestion! It did take a while to run, but it succeeded eventually.

**Comment by bsipocz** [comment]
@abulatek - I'm closing this then with the assumption of having a corrupt cache, but please do reopen if you see this or anything similar again.

**Comment by gilleslandais** [comment]
Hi ..
to query large tables in VizieR without any constraints will throw a timeout. VizieR has indeed fixed timeout depending of the constraints set on queries. The limit in the VizieR common interface (used in astropy) is about few minutes.
The current position of the CDS to get a full catalogue consists to ask the CDS (cds-question@astro.unistra.fr) and to get URLs to get data by parts.
