### ISSUE TITLE
em_resolution improperly converted from kHz to m for ALMA

### ISSUE THREAD

**Issue by nbrunett** [astropy/astroquery#1816]
Should `_gen_spec_res_sql` in `astroquery/astroquery/alma/tapsql.py` also require a "center frequency" to properly convert the spectral resolution from kHz to meters? Following the derivation [here](https://pilasers.com/pages/how-to-convert-frequency-bandwidth-to-wavelength-bandwidth) it looks like you need the frequency at the center of the bandwidth, or alternatively the frequencies at the edges of the bandwidth since

![Screen Shot 2020-09-08 at 1 46 02 PM](https://user-images.githubusercontent.com/7672534/92510319-a6642680-f1d9-11ea-99dc-5182194bfeb5.png)
(taken from the link above).

It looks like what is there now effectively assumes the data are always measured at 30 Hz. E.g. in line 194
```python
interval*u.kHz.to(u.m, equivalencies=u.spectral()))
```
This trickles down to em_resolution, and maybe I'm missing some context around how em_resolution is defined, but it is not clear in the documentation [here](https://astroquery.readthedocs.io/en/latest/alma/alma.html#querying-by-other-parameters) that it would need to be multiplied by (1000 Hz ^ 2) / (nu_obs_hz ^ 2) to make it the actual spectral resolution as observed.

**Comment by keflavich** [comment]
@andamian I believe @nbrunett is correct; can you fix this?

**Comment by andamian** [comment]
Looking into it @nbrunett

**Comment by bsipocz** [comment]
Has this been fixed @andamian? (I don't see a trivial hint for a fix in the code, but I didn't dig too deep)

**Comment by andamian** [comment]
Fell off my radar - sorry. Going to take a fresh look at this.

**Comment by andamian** [comment]
Update: this is still work in progress as it might require coordination with related changes on the server side.

**Comment by andamian** [comment]
@nbrunett - please check that #3035 provides an acceptable solution for you. Very sorry it took so long - it required server changes which were delays because of various events. I'll close the ticket for now.
