### ISSUE TITLE
Frontpage content needs cleanup

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1821]
* looks like the paper link is markdown instead of rest?
* we should really explain to users what "continuous deployment" means, and what version of astroquery they should have

this is prompted by several consecutive reports on slack that were all solved by "upgrade astroquery" - we should have the docs more clearly spell this out.

**Comment by bsipocz** [comment]
💯 


Though I'm afraid this would not have helped in the last case where astroquery was almost 2 year old which I suspect might already be incompatible with the current upstream server.
