### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by andamian** [astropy/astroquery#1824]
Both `astropy` and `astroquery` are out of 3.5 so I don't see a reason to continue in supporting it.

**Comment by bsipocz** [comment]
Certainly code clear up is a bit overdue, but full agree that nothing new should support <3.6

**Comment by andamian** [comment]
Wrong project. Sorry.

**Comment by bsipocz** [comment]
no worries. We could have also transferred the issue :)
