### ISSUE TITLE
Readthedocs build failing as of September

### ISSUE THREAD

**Issue by ceb8** [astropy/astroquery#1851]
The readthedocs build list shows failures for since 1 month, 3 weeks before 10/12/20.

The error shown is `ModuleNotFoundError: No module named 'sphinx_astropy'`

**Comment by bsipocz** [comment]
RTD has been fixed by  https://github.com/astropy/astroquery/commit/37997088f60582aa3f980b0a0b91802cee5cbc5d

**Comment by bsipocz** [comment]
Thanks for spotting, this slipped through when #1805 got merged
