### ISSUE TITLE
DOC: Team page?

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1857]
I am just thinking that it would be nice to have a Team page for `astroquery` that states clearly which individuals or organizations are responsible for which sub-module listed at https://astroquery.readthedocs.io/en/latest/#available-services .

**Comment by bsipocz** [comment]
See https://github.com/astropy/astroquery/pull/1446 and #1444

**Comment by pllim** [comment]
Ah, thanks for pointing that out! I searched for "team" and didn't get any hits. Sorry for the noise.
