### ISSUE TITLE
Alma.query() doesn't return results

### ISSUE THREAD

**Issue by heh15** [astropy/astroquery#1863]
I tried to write a function for ALMA archival search using `Alma.query()` (which includes both functions of `Alma.query_region()` and `Alma.query_object()`). However, it turns out that `Alma.query()` doesn't return any result while `Alma.query_region()` or `Alma.query_object` behaves normally. Here is my code for comparison:  
```
from astropy import units as u
from astroquery.alma import Alma  
from astropy import coordinates  
Coord = coordinates.SkyCoord(187.27792*u.deg, 2.05239*u.deg,  
                                       frame='fk5')  
result1 = Alma.query_region(Coord, 20*u.arcsec)  
payload = {}  
payload['ra_dec'] = '12:29:06.6997 02:03:08.598, 0.0055'  
result2 = Alma.query(payload)  
print(len(result1), len(result2))
```
The two results are supposed to be the same. However, `Alma.query_region()` returns 2569 results while `Alma.query()` returns an empty table. Is this still an ALMA service problem or there are some changes in `Alma.query()` method?

**Comment by bsipocz** [comment]
cc @andamian @keflavich

**Comment by andamian** [comment]
@heh15 - that's happening because `query` expects degree units. This works fine:
```
>>> payload['ra_dec'] = '187.278 2.05239, 0.0055'
>>> len(Alma.query(payload))
2585
```
It's not hard to make it deal with the transformation and it's probably a good idea.

**Comment by heh15** [comment]
Thanks for the help! It works for me.

**Comment by alipnicky** [comment]
Not exactly the same but I'm finding that Alma.query() is producing incomplete results whereas Alma.query_tap() is complete. 

```python
>>> pids = alma.query({'proposal_id':'2019.*'})
>>> pids_pds = pids.to_pandas()
>>> len(pids_pds['member_ous_uid'].unique())
1745
>>>
>>> pids = alma.query_tap("select * from ivoa.obscore where proposal_id like '2019%'").to_table()
>>> pids_pds = pids.to_pandas()
>>> len(pids_pds['member_ous_uid'].unique())
2948
```
Am I missing something basic here?

**Comment by keflavich** [comment]
@alipnicky yes, `alma.query` returns only public by default.  Add `public=False` to get the private ones or `public=None` to get all.

**Comment by alipnicky** [comment]
Ah! Of course. 🤦‍♀️ Thanks for the quick answer!

**Comment by bsipocz** [comment]
@keflavich - shall we close this? The answer in https://github.com/astropy/astroquery/issues/1863#issuecomment-720784692 seems to address the issue, is there any actual action item remaining?
