### ISSUE TITLE
'public=True' in Alma.query() returns more results

### ISSUE THREAD

**Issue by heh15** [astropy/astroquery#1888]
When I ran 'Alma.query()', I found that if I set 'public=True', it returns more results than when I set 'public=False'. Here is an example of my code: 
```
from astropy.coordinates import Angle, SkyCoord
from astroquery.alma import Alma
import numpy as np

target = [SkyCoord(ra=187.27792*u.degree, dec=2.05239*u.degree, frame='icrs'), Angle(20*u.arcsec)]
cstr = target[0].fk5.to_string(style='decimal')
payload = {}
payload['ra_dec'] = '{:}, {:}'.format(cstr, target[1].deg)
test1 = Alma.query(payload, science=False, public=True)
test2 = Alma.query(payload, science=False, public=False)
print(len(np.unique(test1['obs_id'])), len(np.unique(test2['obs_id'])))
```
The 'public=True' returns 621 results while the other one returns 55 results. It doesn't make sense to me since I expect 'public=False' will return all projects whether it is public or not. Could you confirm if this is my problem or it is actually an issue of astroquery?

**Comment by bsipocz** [comment]
The `public=False` option indeed returns only the non public data, rather than all.
```
In [15]: np.unique(test2['obs_release_date'])                                                                                                                                                  
Out[15]: 
<MaskedColumn name='obs_release_date' dtype='object' length=30>
2020-11-20T00:00:00.000
2020-12-02T15:11:34.000
2020-12-04T04:37:00.000
2020-12-05T21:43:21.000
2020-12-06T23:51:45.000
2020-12-10T16:00:01.000
2020-12-13T15:08:03.000
2021-01-03T14:59:25.000
2021-01-16T16:36:58.000
2021-01-25T05:48:47.000
2021-01-28T20:22:44.000
2021-02-15T00:00:00.000
2021-03-13T09:40:37.000
2021-03-17T00:00:00.000
2021-04-13T12:55:25.000
2021-04-14T17:04:34.000
2021-04-16T14:14:31.000
2021-04-17T01:01:06.000
2021-04-17T04:02:19.000
2021-04-22T00:01:20.000
2021-04-22T05:51:16.000
2021-04-22T09:52:09.000
2021-04-22T16:00:18.000
2021-04-29T18:33:36.000
2021-04-30T19:05:33.000
2021-05-25T21:01:11.000
2021-06-14T00:25:05.000
2021-06-18T12:36:23.000
2021-06-26T11:03:13.000
3000-01-01T00:00:00.000
```

@andamian @keflavich - is this a side effect of the refactor in https://github.com/astropy/astroquery/pull/1689, or also a server side change? Based on docs we have, I also would have assumed that all data should be returned with `False`, though that first example doesn't seem to work for me any more, it returns an empty table independently of the value of the 'public' kwarg (https://astroquery.readthedocs.io/en/latest/alma/alma.html#querying-by-other-parameters)

**Comment by andamian** [comment]
This rings a bell and I recall fixing it - it could be in one of the outstanding PRs. I'll have to double-check.

**Comment by bsipocz** [comment]
If it's waiting for review, do ping me/us, so it's less likely to slip through (we've been quite busy with the intern PRs in this past many weeks, and I know that there is now a bit of backlog for the observatories).

**Comment by privong** [comment]
I just stumbled across this ticket, but I think it can be closed? The API docs indicate that `public=True` returns only public data, `public=False` returns only proprietary data, and `public=None` returns both. E.g., [0] for `Alma.query()`.

I am trying to confirm that this is the actual behavior with a current/recent version of astroquery, but my test queries are taking quite a while.

[0] https://astroquery.readthedocs.io/en/latest/api/astroquery.alma.AlmaClass.html#astroquery.alma.AlmaClass.query

**Comment by privong** [comment]
Okay, I was able to get queries to run.

```
from astroquery.alma import Alma
ptrue = Alma.query_object('NGC 7130', public=True)
pfalse = Alma.query_object('NGC 7130', public=False)
pnone = Alma.query_object('NGC 7130', public=None)
```

`len(ptrue)` = 26

`len(pfalse)` = 4

`len(pnone)` = 30

So this seems to be working according to the API docs.

**Comment by keflavich** [comment]
Thanks @privong, I'll consider this solved.
