### ISSUE TITLE
Unescaped URIs when making download requests in astroquery.mast are causing failed downloads

### ISSUE THREAD

**Issue by seweissman** [astropy/astroquery#1892]
@eteq reports that he is having trouble retrieving some files from this query:

```
from astroquery.mast import Observations
import astropy.units as u
obs_table = Observations.query_region("M32", radius=6*u.arcmin)
acs_table = obs_table[obs_table['instrument_name']=='ACS/WFC']
field2 = acs_table[(acs_table['provenance_name']=='HLA')&
                   (acs_table['target_name']=='MESSIER-032-FIELD2')&
                   (acs_table['filters']!='DETECTION')]
data_products_by_obs = Observations.get_product_list(field2)
dled = Observations.download_products(data_products_by_obs)
```
In the downloaded results there are catalog files that contain the text `dataset parameter is required` instead of the catalog data.

The issue appears to be that some MAST URIs contain query parameters and the URIs are not escaped when passed to `_download_file`. The resulting request to the MAST download service is ambiguous and arguments to the URI get dropped. An example URI is `mast:HLA/url/cgi-bin/getdata.cgi?download=1&filename=hst_13691_11_acs_wfc_f814w_daophot_trm.cat`.

I think this is the offending line. There may be other places in the astroquery.mast code where URIs need to be escaped:
https://github.com/astropy/astroquery/blob/c4dde9d99cf6297af2bfcf0cd7f35d29f114e23e/astroquery/mast/observations.py#L530

Tagging @ceb8 as requested!

**Comment by bsipocz** [comment]
The example above now downloads valid-looking fits files, so I'm closing the issue. Do reopen if you still run into problems.
