### ISSUE TITLE
'ObservationsClass' object has no attribute 'download_file'

### ISSUE THREAD

**Issue by muHashh** [astropy/astroquery#1898]
Astroquery==0.4.1 running on WSL2 Ubuntu 20.04 LTS. Observed the same behavhiour on native Ubuntu 20.10, and an external jupyter notebook server.

I am trying to download light curves (TESS) from MAST and it is telling me the function does not exist. I've tried using the newest dev version from Nov 10. Still the same.

Here is the exact error and the data URI I am using as the input:

![image](https://user-images.githubusercontent.com/16888732/99256802-dbaa7780-280d-11eb-9b34-0f9f6045d783.png)

**Comment by bsipocz** [comment]
This error is long gone,  if you still run into it though please feel free to reopen it, but then please add a copy-pasteable example rather than a screenshot so we can more easily go ahead to try to reproduce it.
