### ISSUE TITLE
An example where SkyView.get_images() fails with the 2MASS-J survey

### ISSUE THREAD

**Issue by KenMighell** [astropy/astroquery#1904]
The following code snippet 
```
from astroquery.skyview import SkyView
from astropy.coordinates import SkyCoord
from astropy import units as u
images = SkyView.get_images(position=SkyCoord(ra=290.381514 * u.deg, 
    dec=43.292988 * u.deg), survey='2MASS-J', radius=3.000 * u.arcmin)
```
produces the following exception "HTTP Error 404: Not Found"

If the radius argument value is changed from 3.000 * u.arcmin to 2.991 * u.arcmin  
or 3.001 * u.arcmin , the SkyView.get_images function works as expected.

If the survey argument value is changed from '2MASS-J' to '2MASS-K' or '2MASS-H',
the SkyView.get_images function works as expected.

The target is the object Kepler-138b.

**Comment by keflavich** [comment]
Could you try clearing your cache (remove files in `~/.astropy/cache/astroquery/skyview/`) and try again?  I think you had one unfortunate failure that got cached.

**Comment by KenMighell** [comment]
I removed all files in the cache (~/.astropy/cache/astroquery/skyview/).  I tried again and the problem is gone.  Looks like
an unfortunate failure got cached.  Thanks @keflavich  for this solution.  This issue can be closed.
