### ISSUE TITLE
Photo-z from SDSS

### ISSUE THREAD

**Issue by abhisek176** [astropy/astroquery#1907]
Can someone please let me know how to extract photo-z information from SDSS objID. I assume it's not yet implemented in astroquery?! Is there any other python tools. SQL query is tedious .. :(

**Comment by weaverba137** [comment]
Photometric redshifts are not one of the core data outputs of the SDSS pipelines; it's a *spectroscopic* survey after all. So it's not surprising that documentation is sparse. I know that some value-added catalogs exist with photometric redshift estimates, but then it's a question of which one.  @abhisek176, were you looking for a specific photo-z catalog, or were you assuming that photo-z measurements were a core data product?

**Comment by bsipocz** [comment]
> So it's not surprising that documentation is sparse. 

oh, sorry, I meant the sparse documentation for the module, it could still show an example to query the photometric tables and select the magnitude columns as well as `z`.

**Comment by weaverba137** [comment]
Ah, yes, that is possible in principle, but that's why I asked *which* photo-z catalog, and a corollary, which release.  If it's one that's already in the SDSS database, then it would be easy to write an example query and add it to the astroquery documentation.

**Comment by bsipocz** [comment]
But thinking about this a tiny bit more, maybe we should just close this issue, as we have https://github.com/astropy/astroquery/issues/948 already for the more generic expenditure of the docs. We have reasonably nice test coverage for the code, maybe we should just turn a few of those into narrative docs, too.

**Comment by weaverba137** [comment]
Indeed, that's a very similar issue.
