### ISSUE TITLE
XMatch.query issue with EDR3

### ISSUE THREAD

**Issue by jantoniadis** [astropy/astroquery#1912]
Running the following:

    from astroquery.xmatch import XMatch
    from astropy import units as u

    gaia_cross_matches = XMatch.query(
                       cat1=open('updated_pulsar_params.csv'),
                       cat2='vizier:I/350/gaiaedr3', max_distance=20*u.arcsec,
                        colRA1='raj', colDec1='decj',colRA2='ra_epoch2000',colDec2='dec_epoch2000',cache=True)

produces the following error:

```
HTTPError                                 Traceback (most recent call last)
<ipython-input-11-592a1ed7fcf4> in <module>
      2     cat1=open('updated_pulsar_params.csv'),
      3     cat2='vizier:I/350/gaiaedr3', max_distance=20*u.arcsec,
----> 4     colRA1='raj', colDec1='decj',colRA2='ra_epoch2000',colDec2='dec_epoch2000',cache=True)

~/opt/anaconda3/lib/python3.7/site-packages/astroquery/xmatch/core.py in query(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, area, cache, get_query_payload, **kwargs)
     71                                     colRA2, colDec2, area=area, cache=cache,
     72                                     get_query_payload=get_query_payload,
---> 73                                     **kwargs)
     74         if get_query_payload:
     75             return response

~/opt/anaconda3/lib/python3.7/site-packages/astroquery/xmatch/core.py in query_async(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, area, cache, get_query_payload, **kwargs)
    106         response = self._request(method='POST', url=self.URL, data=payload,
    107                                  timeout=self.TIMEOUT, cache=cache, **kwargs)
--> 108         response.raise_for_status()
    109
    110         return response

~/opt/anaconda3/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    938
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941
    942     def close(self):

HTTPError: 400 Client Error: Mauvaise Requête for url: http://cdsxmatch.u-strasbg.fr/xmatch/api/v1/sync

```

updated_pulsar_params.csv is a csv cat that has the following format: 

```
id,name,nref,raj,rajerr,raref,decj,decjerr,dref,pmra_radio,pmraerr,prref,pmdec_radio,pmdecerr,pdref,px,pxerr,pxref,posepoch,poseref,p0,p0err,p0ref,p1,p1err,p1ref,dm,dmerr,dmref,dist,pb,pberr,pbref,survey,surveyref,BinComp,BinCompref,Type,TypeRef,Assoc,raj_now,decj_now
8,J0024-7204ab,phl+16,6.034006249999999,0.0005,frk+17,-72.07988944444445,0.0005,frk+17,4.2,6.0e-01,frk+17,-2.9,5.0e-01,frk+17,,0.0,,51600.0,frk+17,0.0037046394947985,6.0e-16,frk+17,9.82e-21,9.0e-24,frk+17,24.37,2.0e-02,frk+17,2.54,,0.0,,misc,,,,,GC:47Tuc,,6.034006072724162,-72.0798893220397
9,B0021-72C,mld+90,5.959810833333333,0.0001,frk+17,-72.075418,0.0001,frk+17,5.2,1.0e-01,frk+17,-3.1,1.0e-01,frk+17,,0.0,,51600.0,frk+17,0.00575677999551635,1.4e-16,frk+17,-4.9850300000000006e-20,2.0e-24,frk+17,24.6,4.0e-03,frk+17,4.69,,0.0,,pksgc,,,,,"GC:47Tuc,XRS:[bgh+06]",,5.959810613848963,-72.07541786915355
```
The file is attached. 

The same call works fine with gaiadr2:

```
gaia_cross_matches = XMatch.query(
           cat1=open('updated_pulsar_params.csv'),
           cat2='vizier:I/345/gaia2', max_distance=20*u.arcsec,
            colRA1='raj', colDec1='decj',colRA2='ra_epoch2000',colDec2='dec_epoch2000',get_query_payload=False) 
```

[updated_pulsar_params.csv.zip](https://github.com/astropy/astroquery/files/5641982/updated_pulsar_params.csv.zip)

**Comment by fxpineau** [comment]
The CDS XMatch HTTP API response is supposed to be compliant with the [IVOA DALI](https://www.ivoa.net/documents/DALI/) recommandation.

**Comment by fxpineau** [comment]
@jantoniadis  @keflavich 

The CDS XMatch HTTP API response is supposed to be compliant with the [IVOA DALI](https://www.ivoa.net/documents/DALI/) recommendation.  
In case of error, a VOTable containing a detailed error message is returned in addition to the HTTP code (400 status here).  
It would help to print the fulll error message (or the full VOTable content) in case of failure.

In the particular case here, I suspect `colRA2='ra_epoch2000'` and `colDec2='dec_epoch2000'` to cause troubles: so far the user cannot choose the VizieR positional columns used for the cross-match. See [the faq](http://cdsxmatch.u-strasbg.fr/xmatch/doc/faq-poscols.html) of the CDS XMatch documentation.

**Comment by keflavich** [comment]
@fxpineau we'd appreciate help implementing that!  So, should there be an attached VOTable, even though there's an HTTPError?

**Comment by jantoniadis** [comment]
This does not seem to be an XMatch API issue. The following:
 
`curl -X POST -F request=xmatch -F distMaxArcsec=20.0 -F RESPONSEFORMAT=csv -F cat1=@updated_pulsar_params.csv -F colRA1=raj -F colDec1=decj -F cat2=vizier:I/350/gaiaedr3 http://cdsxmatch.u-strasbg.fr/xmatch/api/v1/sync > my_result.cs`

doesn't return an error.

**Comment by HNLala** [comment]
> Using `vizier:I/350/gaiaedr3`, positions at epoch J2000 (so the columns `ra_epoch2000` and `dec_epoch2000`) are used.

When I tried to run the query without specifying colRA2 and colDec2, I get the following error:
``` 
~/anaconda3/envs/py38/lib/python3.8/site-packages/astroquery/xmatch/core.py in query(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, area, cache, get_query_payload, **kwargs)
     68             Query results table
     69         """
---> 70         response = self.query_async(cat1, cat2, max_distance, colRA1, colDec1,
     71                                     colRA2, colDec2, area=area, cache=cache,
     72                                     get_query_payload=get_query_payload,

~/anaconda3/envs/py38/lib/python3.8/site-packages/astroquery/xmatch/core.py in query_async(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, area, cache, get_query_payload, **kwargs)
     98 
     99         self._prepare_sending_table(1, payload, kwargs, cat1, colRA1, colDec1)
--> 100         self._prepare_sending_table(2, payload, kwargs, cat2, colRA2, colDec2)
    101         self._prepare_area(payload, area)
    102 

~/anaconda3/envs/py38/lib/python3.8/site-packages/astroquery/xmatch/core.py in _prepare_sending_table(self, cat_index, payload, kwargs, cat, colRA, colDec)
    131         if not self.is_table_available(cat):
    132             if ((colRA is None) or (colDec is None)):
--> 133                 raise ValueError('Specify the name of the RA/Dec columns in' +
    134                                  ' the input table.')
    135             # if `cat1` is not a VizieR table,

ValueError: Specify the name of the RA/Dec columns in the input table.```

When I run it again after specifying the columns are 'ra_epoch2000' and dec_epoch2000', I get a 400 Error which returns the following message:

``` <INFO name="QUERY_STATUS" value="ERROR">
Message: Mandatory parameter "request" not found. Trace: cds.xmatch.exception.CmdParseException: Mandatory parameter "request" not found. at cds.xmatch.servlet.QueryParams.getMandatoryString(QueryParams.java:59) at cds.xmatch.servlet.QueryParams.getMandatoryString(QueryParams.java:67) at cds.xmatch.servlet.SyncXMatch.exec(SyncXMatch.java:578) at cds.xmatch.servlet.SyncXMatch.doGet(SyncXMatch.java:470) at javax.servlet.http.HttpServlet.service(HttpServlet.java:624) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:844)
</INFO>```

**Comment by fxpineau** [comment]
@keflavich 

> @fxpineau we'd appreciate help implementing that! 

I understand, but so far my python skills are very low.
I only have a small experience of python wrappers around Rust codes.

> So, should there be an attached VOTable, even though there's an HTTPError?

The output is a VOTable either if the query succeed and you asked for a VOTable output, or if the query fails.
You can try for example (missing `cat1` parameter):
```bash
curl -i -X POST -F request=xmatch -F distMaxArcsec=20.0 -F RESPONSEFORMAT=csv -F colRA1=raj -F colDec1=decj -F cat2=vizier:I/350/gaiaedr3 http://cdsxmatch.u-strasbg.fr/xmatch/api/v1/sync
```
(the `-i` prints the HTTP status), you should get something like:
```xml
HTTP/1.1 400 [...]
[...]

<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE version="1.2" [...]>
[...]
  <RESOURCE type="results">
    <INFO name="QUERY_STATUS" value="ERROR">
      Message: Missing parameter &quot;cat1&quot;.
      Trace:
      [...]
    </INFO>
  </RESOURCE>
</VOTABLE>
```
The first part is (more or less) the HTTP response header while the second part (starting at `<?xml` ...) is the HTTP response body.

@keflavich 

I vaguely remember a problem of cache of the list of tables available in the cross-match service. Can it be the origin of the problem here?

**Comment by HNLala** [comment]
@fxpineau 

"I/350/gaiaedr3" in XMatch().get_available_tables() returns False.

I tried to run the query with XMatch.query(..., cache=False) but the problem persisted.

I turned cache=False in  `get_available_tables(self, cache=True)` in core.py and the query works very well then. 

@keflavich 

Maybe, passing on the 'cache' user-input in this line will help: `return table_id in self.get_available_tables()`

**Comment by fxpineau** [comment]
@HNLala 

> When I run the query after specifying 'ra_epoch2000' and dec_epoch2000', I get a 400 Error which returns the following message:
> [...]
> When I tried to run the query without specifying colRA2 and colDec2, I get the following error:

In both cases the set of parameters sent to the xmatch service seems to be erroneous.

**Comment by HNLala** [comment]
> @fxpineau
> Cache seems to be the problem here.
> 
> "I/350/gaiaedr3" in XMatch().get_available_tables() returns False.
> 
> I tried to run the query with XMatch.query(..., cache=False) but the problem persisted.
> 
> I turned cache=False in `get_available_tables(self, cache=True)` in core.py and the query works very well then.
> 
> @keflavich
> 
> Maybe, passing on the 'cache' user-input in the line 167 will help: `return table_id in self.get_available_tables()`
> As the code returns False here, it goes to:
> 
> ```
>      if not self.is_table_available(cat):
>             if ((colRA is None) or (colDec is None)):
>                 raise ValueError('Specify the name of the RA/Dec columns in' +
>                                  ' the input table.')```
> ```
@fxpineau 
@jantoniadis 

After this, I guess the option without specifying colRA2 and colDec2 seems to be the correct one. The error message returned in that case from XMatch.query() doesn't take into account the cache bug.

**Comment by bsipocz** [comment]
The provided examples seem to work now, so I'm closing the issue. Please feel free to reopen if you think there are fixes that still need to be done.
