### ISSUE TITLE
sdss sql not parsing results correctly for old dr

### ISSUE THREAD

**Issue by HerculesJack** [astropy/astroquery#1924]
Hi, I was trying to do this with astroquery:

```
from astroquery.sdss import SDSS

SDSS.query_sql("select p.objid, p.ra, p.dec, p.PetroRad_r, p.PetroRadErr_r, p.r, p.err_r\n"
               "from galaxy p\n"
               "where p.objid=587731186203951236\n", timeout=0.1, data_release=7)
```

The same SQL command does return an object on the SDSS website, but it returns nothing with the astroquery code above.

![图片](https://user-images.githubusercontent.com/34429853/103553538-8bd05e80-4ee8-11eb-8f1a-deb803a985b6.png)

Then I tried this:

```
from astroquery.sdss import SDSS

SDSS.query_sql("select top 10 p.objid, p.ra, p.dec, p.PetroRad_r, p.PetroRadErr_r, p.r, p.err_r\n"+
               "from photoobj p\n"+
               "where p.objid>587731186203951235", timeout=1, data_release=7, cache=False)
```

And found the issue is probably because astroquery did not parse the result correctly.

![图片](https://user-images.githubusercontent.com/34429853/103553262-2c724e80-4ee8-11eb-9a82-c069d061c4ae.png)

I verified that the code below works for me. So maybe we just need to adjust the value of `skip_header` for different DR (presumably 0 for dr<10, and 1 for dr>=10). Hope this would help!

```
import io
import numpy as np
from astropy.table import Table
from astroquery.sdss import SDSS, SDSSClass

class SDSS2Class(SDSSClass):
    def _parse_result(self, response, verbose=False):
        """
        Parses the result and return either a `~astropy.table.Table` or
        `None` if no matches were found.

        Parameters
        ----------
        response : `requests.Response`
            Result of requests -> np.atleast_1d.

        Returns
        -------
        table : `~astropy.table.Table`

        """

        if 'error_message' in io.BytesIO(response.content):
            raise RemoteServiceError(response.content)
        arr = np.atleast_1d(np.genfromtxt(io.BytesIO(response.content),
                                          names=True, dtype=None,
                                          delimiter=',', skip_header=0,
                                          comments='#'))

        if len(arr) == 0:
            return None
        else:
            return Table(arr)

SDSS2 = SDSS2Class()
SDSS2.query_sql("select top 10 p.objid, p.ra, p.dec, p.PetroRad_r, p.PetroRadErr_r, p.r, p.err_r\n"+
                "from photoobj p\n"+
                "where p.objid=587731186203951236", timeout=1, data_release=6, cache=False)
```

![图片](https://user-images.githubusercontent.com/34429853/103553909-17e28600-4ee9-11eb-8405-c9e2be35e535.png)

**Comment by keflavich** [comment]
Thanks for noting this!  Would you be willing to submit the proposed change as a pull request?

**Comment by HerculesJack** [comment]
Sure, I'd be happy to do this. :)  Although I'm not sure if other functions calling `_parse_result` also need this change, so I'd need some time to check it.

**Comment by bsipocz** [comment]
Nice investigating. We seem to be testing with the whole range of DRs, but only locally. So if you could add some similar logic to the remote tests that would be great, and I think enough to make sure the parsing works for all cases.

**Comment by bsipocz** [comment]
Both code snippets above work as expected now (except the 0.1 timeout seems too small, if I don't have that kwarg it works, with it I timed out). Thank you @HerculesJack for reporting. If you still see these or any similar issues please let us know!
