### ISSUE TITLE
Extend CI: remote tests, crons, docs warnings

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1932]
After #1925 there are still a few things that need to be taken care of to get back to the CI level we had before:

- [x] add corn runs for remote data tests, see #1936
- [x] fix the docs build test so it fails when there are warnings. This probably requires APE17
- [ ] add back auto-deployment. 
- [x] use nightly astropy for devdeps

**Comment by pllim** [comment]
Not sure if you noticed but the oldest dependencies job runs astropy 4.1, not 3.1 as set in `tox.ini`. Example log: https://github.com/astropy/astroquery/runs/1685763696?check_suite_focus=true

**Comment by pllim** [comment]
For the nightly astropy, I thought @cadair set it up, but I don't know how to use it.
