### ISSUE TITLE
astroquery.alma table gives spatial resolution in units of degrees but should be arcseconds

### ISSUE THREAD

**Issue by adeleplunkett** [astropy/astroquery#1957]
```python
import astroquery
from astroquery.alma import Alma
from astropy import coordinates
from astropy import units as u

sourcecoords = coordinates.SkyCoord('11:01:51.796 -34:42:17.366', frame='fk5', unit=(u.hour, u.deg)) 
result = Alma.query_region(sourcecoords, radius=10.*u.arcsec)
result[0]['proposal_id','target_name','s_ra','s_dec','s_fov','s_resolution','is_mosaic']
```

The code returns a table that includes s_resolution (spatial resolution) with units of deg, but looking at the same project in the [ASAX](https://almascience.nrao.edu/asax/), the same angular resolution value should instead have units of arcsec.

**Comment by keflavich** [comment]
Yep, confirmed.  @andamian we might want to special-case this, or request that ALMA fix it if it's in the metadata we're receiving.

**Comment by andamian** [comment]
Also confirmed. It's a service problem as the `IVOA ObsCore` standard that the service follows specify the unit as `arcsec` so I prefer a fix there. I've open a ticket with `ALMA` (https://help.almascience.org/tickets/16017 - here for cross reference). Let's wait and see what they have to say about it first. We'll fix it here only if it cannot be done upstream.

@adeleplunkett - thanks for reporting.

**Comment by adeleplunkett** [comment]
I see there is an ICT ticket at ALMA for this now.  

In addition to the units issue, I have a more minor point.  I think that the documentation [here ](https://astroquery.readthedocs.io/en/latest/alma/alma.html) refers to this keyword as spatial_resolution, when it seems that it should be listed there as s_resolution.

**Comment by at88mph** [comment]
The example code returns this:
```python
<Row index=0>
 proposal_id   target_name        s_ra             s_dec               s_fov             s_resolution    is_mosaic
                                  deg               deg                 deg                 arcsec                
    str64         str256        float64           float64             float64              float64          str1  
-------------- ----------- ----------------- ------------------ -------------------- ------------------- ---------
2015.A.00005.S      TW_Hya 165.4659316011999 -34.70479648835318 0.011155972699501577 0.07160066640956847         F
```

Where the units show `arcsec`.  I remember correcting this in the `TAP_SCHEMA` some time ago.

**Comment by bsipocz** [comment]
@at88mph - off topic: I've added you to the archive maintainers team, you should have triage access now and be able to close/tag/milestone/etc issues and PRs now.

**Comment by at88mph** [comment]
Understood.  Thank you @bsipocz.
