### ISSUE TITLE
astroquery.mast.Observations.download_products not downloading file

### ISSUE THREAD

**Issue by s-goldman** [astropy/astroquery#1979]
When trying to download Spitzer data the `astroquery.mast.Observations.download_products` creates a directory structure for the first couple directories but then stops and doesn't download the file. Downloading HST data this way is working fine, and the html link for downloading the data works fine.
 
<img width="1872" alt="Screen Shot 2021-02-03 at 2 30 51 PM" src="https://user-
<img width="1869" alt="Screen Shot 2021-02-03 at 2 30 51 PM" src="https://user-images.githubusercontent.com/32876747/106799688-8a03d300-662d-11eb-8cbf-0d8f02cc8d03.png">

**Comment by ceb8** [comment]
Hi @s-goldman! Can you provide a code snippet that demonstrates this issue?

**Comment by s-goldman** [comment]
@ceb8  Thanks for looking into this!
`from astroquery.mast import Observations`
`data_products = Observations.get_product_list('19000129592')`
`manifest = Observations.download_products(data_products, productType="SCIENCE")`

**Comment by ceb8** [comment]
@s-goldman  There definitely is some kind of bug going on there. I'll look into it, but as a work-around you can do:

```
for p in data_products: 
    if p['productType'] == "SCIENCE": 
        Observations.download_file(p["dataURI"])
```

**Comment by s-goldman** [comment]
I'm just glad to hear I'm not crazy. Thanks for the tip, i'll give that a try.
