### ISSUE TITLE
Simbad ConnectionError (same of Issue #1408, closed)

### ISSUE THREAD

**Issue by SilvioLeccia** [astropy/astroquery#1983]
Hello!
I have the same problem reported by dagnic in issue #1408 (closed).
When I try to  query Simbad to get info on classification on objects from their position in the sky, sometimes, it fails with:
 "ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))".
I don't perform several queries in 1 second, and before Christmas I didn't have this error and I worked with a list of 1000 sources. Now every 5/10 sources I have to restart the code due to the "connectionError".
Can someone give me an help on how to solve?
Cheers,
Silvio

**Comment by keflavich** [comment]
cc @aoberto

**Comment by aoberto** [comment]
Hello Silvio, 
I could not see any issue from Simbad. Can you give an example of your code, the astroquery version, and sources where it fails ? But it seems that for issue #1408 the error, was from python connector

regards

**Comment by SilvioLeccia** [comment]
Thank you for your answer.

The code have to take a list of sources, from ra & dec perform the query, while some diagnostic plot are displayed.

The code doesn't fails on a specific object. When it fails, I restart from the same object and I have no problems for 5/6 stars, then fails again. 
I think that I am on one source for 10-15 seconds, so... my rate is about 1 query every 10s.

The astro query was installed in December 2020,  I don't remember the version... how I can check it?

Here a snippet of the code:

So I make this import:
from astroquery.simbad import Simbad
from astroquery.vizier import Vizier

[...]
if(len(indexSourceid)>0):
        for i in indexSourceid:
            if (performQuery == 'Yes'):
                catalog_list = Vizier.find_catalogs('Samus')
                print(' ')
                print(' ')
                print(' ')
                print('******************* SIMBAD  QUERY RESULT ************************************')
                print(' ')
                query = customSimbad.query_region(coord.SkyCoord(ra=dataToUse['ra'][i], dec=dataToUse['dec'][i],
                                    unit=(u.deg, u.deg)),
                                   radius=5/3600 * u.degree)
                if(query is None):
                    print('No object found in 5 arcsec')
                else:
                    for jjj in range(len(query['MAIN_ID'])):
                        print('Id: '+str(query['MAIN_ID'][jjj])+ ' RA: '+str(query['RA'][jjj])+' DEC: '+str(query['DEC'][jjj])+ ' O_type: '+str(query['OTYPE'][jjj]))
                print(' ')
                result2 = Vizier.query_region(coord.SkyCoord(ra=dataToUse['ra'][i], dec=dataToUse['dec'][i],
                                    unit=(u.deg, u.deg)),
                                   radius=5/3600 * u.degree,catalog=["B/gcvs/gcvs_cat"])
                result3 = Vizier.query_region(coord.SkyCoord(ra=dataToUse['ra'][i], dec=dataToUse['dec'][i],
                                    unit=(u.deg, u.deg)),
                                   radius=5/3600 * u.degree,catalog=["B/vsx/vsx"])
                print('******************* Vizier  QUERY RESULT ************************************')
                print(' ')
                if(len(result2)<1):
                
                    print(' ')
                    print('No object found in 5 arcsec in B/gcvs/gcvs_cat')
                    print(' ')
                else:
                    interesting_table = result2['B/gcvs/gcvs_cat']
                    for kkk in range(len(interesting_table['VarName'])):
                        print('VarName '+str(interesting_table['VarName'][kkk]) +  'Period B/gcvs/gcvs_cat: '+str(interesting_table['Period'][kkk]))
                if(len(result2)<1):
                    print(' ')
                    print('No object found in 5 arcsec in B/vsx/vsx')
                    print(' ')
                else:    
                    interesting_table2 = result3['B/vsx/vsx']  
                    for zzz in range(len(interesting_table2['Name'])):  
                        print('Name '+str(interesting_table2['Name'][zzz]) +  'Period B/vsx/vsxt: '+str(interesting_table2['Period'][kkk]))
                print(' ')
    
                print(' ')
                print('**********************************************************************************')
                print(' ')
                print(' ')
                print(' ')

**Comment by aoberto** [comment]
To be sure to have to latest version of astroquery, you can try to upgrade it (depends on how you installed it, may be : `sudo pip install --upgrade astroquery`.
I tried a simpler code derived from yours, and I get all the answers, no Connection errors (see bellow). Some users, get also this error, if the `Simbad` object was created in a loop, and, just moving the code in a function .... I was asking some of your positions giving errors, to check if we can see a pattern, of empty/crowded regions.
I am using python 3.7.4.


``` python
import astropy.coordinates as coord
import astropy.units as u
from astroquery.simbad import Simbad
import time

dataToUse={}
dataToUse['ra']=[]
dataToUse['dec']=[]
for i in range(0,20):
    dataToUse['ra']+=[i];
    dataToUse['dec']+=[i];
customSimbad=Simbad()
customSimbad.add_votable_fields('otype')
for i in range(0,20):
        print(' ')
        print(' ')
        print('******************* SIMBAD  QUERY RESULT ************************************')
        print(' ')
        query = customSimbad.query_region(coord.SkyCoord(ra=dataToUse['ra'][i], dec=dataToUse['dec'][i],
                            unit=(u.deg, u.deg)),
                           radius=500/3600 * u.degree,cache=None)
        time.sleep(.300)
        if(query is None):
            print('No object found in 500 arcsec')
        else:
            for jjj in range(len(query['MAIN_ID'])):
                print('Id: '+str(query['MAIN_ID'][jjj])+ ' RA: '+str(query['RA'][jjj])+' DEC: '+str(query['DEC'][jjj])+ ' O_type: '+str(query['OTYPE'][jjj]))
        print(' ')
        print('**********************************************************************************')
        print(' ')
```

**Comment by SilvioLeccia** [comment]
Thank you for your work and interest on this topic.

At the end of message  a list of 40 objects. Where there is the arrow, is where I have the connection problem.  I underline that where I restart the code, the first source is which had the connection problems, and in the new run, I have no problem until the next stop.
I updated, as suggested, the astroquery and now I have astroquery-0.4.1.

In the morning I'll try putting the query in a function... and I'll update the issue.
Thank you again.
Cheers.

152.44848771356115 | -63.55771658524639
272.51498916758277 | -25.8607933539938
295.8724390993335 | 23.17793783313293
201.08843300459972 | -64.93204182790481
89.13874180866146 | 1.7090554044907391
226.13796419255718 | -60.594686322520026
249.6585022879222 | -48.50453122995669
269.1674623383946 | -29.01284792211738
226.69024804417592 | -58.49421488369191
121.70355145838147 | -32.8848326896893.          <---
268.8148181852018 | -30.993139383641076
283.88201955975524 | -30.855972420361798
95.56049812342653 | 17.839052995893663
207.95540418235865 | -59.84203731034166
314.88034853697343 | 30.309626853588824
108.39717640574628 | -9.83592892777402
240.28708428479754 | -48.443509155030746
141.58415528635584 | -31.615726326387122
138.95075797911656 | -52.502350413998464.    <--
95.96418153512846 | 17.013175735965195
280.7233826171862 | -28.628976953045356
156.8742892821474 | -59.35958966351219
287.9443387791677 | 11.608370763208951
285.74466372066234 | 9.503543591931814
259.72363861042544 | -19.992881390640132
96.8552095270396 | 1.1922536546224505
210.9206133332345 | -21.317413241767877.            <--
247.8623262210346 | -43.25409383476701
293.0524285426343 | 8.932320298675732
283.79210433102133 | -10.962734092075396
298.6506011956531 | -53.315561532799876
122.88374248065057 | -28.35493506915611
169.04177757992747 | -62.64260635159519
244.964124259241 | 5.2972092263243695
273.684906177034 | -37.63930766447949
254.11531707736182 | -24.068646933037584
101.98330919455086 | -7.413842349522265
257.8229476184545 | -23.274586970332543
263.7473587601049 | -44.83491356979891
205.55971913634573 | 28.42064527897887

**Comment by bsipocz** [comment]
I too have no issues running @aoberto's script. The one above it is not copy-pasteable, so I couldn't reproduce the issue.

Without a reproduced error, it's really difficult to see whether there is anything we could do about it. Also, vectorization was suggested in the other issue, and for `query_region` that in fact works. Please try to feed a vector Skycoord rather than looping through objects one by one.

(I don't think that caching is playing a role here, but you could also try to clear the cache from `~.astropy/cache/astroquery/Simbad`
