### ISSUE TITLE
Coordinates of identifier divided by two

### ISSUE THREAD

**Issue by mapfiable** [astropy/astroquery#1990]
I've already asked the question on [stackoverflow](https://stackoverflow.com/q/66152929/5472354), but I just realized that it probably makes much more sense to ask here.

I'm trying to use `astroquery` to find objects in my images. For some images it works, for others it doesn't and I don't understand why. E.g. for the commented out `qry` it works, but for the other one, the coordinates seem to have been divived by two. What's going on here?

```
from astroquery.simbad import Simbad


custom_simbad = Simbad()
custom_simbad.remove_votable_fields('coordinates')
custom_simbad.add_votable_fields(
    'ra(d)', 'dec(d)', 'coo_err_maja', 'coo_err_mina', 'coo_err_angle',
    'flux(V)', 'flux_error(V)'
)

qry = "region(rotatedbox, 239.6645 -19.13481, 2.208d 2.208d, 18.77721) & " \
      "Vmag < 11.0 & Vmag > -27.0"

# this one works
# qry = "region(rotatedbox, 61.374 +18.62462, 2.210d 2.210d, 162.20635) & " \
#       "Vmag < 11.0 & Vmag > -27.0"

objects = custom_simbad.query_criteria(qry).as_array()
print(objects[['RA_d', 'DEC_d']])
```

Results:

```
[(117.9486170008536, -9.3056044051835)
 (117.9874858113787, -9.1988994115738) 
 (117.7279, -9.3656)
...
```

~~Btw I also don't understand why there are seemingly sometimes two coordinates for one object. Are they listed twice?~~

**EDIT:** ignore that last bit; that was just me missinterpreting how the results were printed...

**Comment by keflavich** [comment]
I don't see the duplication problem. In the example you've listed, each coordinate is unique.

However, neither query appears to be hitting the correct part of the sky.  Maybe this is a problem with the region syntax.  @aoberto - can you chime in on this

**Comment by mapfiable** [comment]
Thanks for checking! 

> I don't see the duplication problem. In the example you've listed, each coordinate is unique.

I'm not sure what you are referring to. The main issue that I have is that I want to look for objects in the `239.6645 -19.13481` region, but all the results are around `117.9486170008536, -9.3056044051835`, so roughly half of that. It seems like the coordinates of the identifier are divided by two before searching the area around it defined by the FOV. Are you saying you don't see any double coordinate entries for a single object either (i.e. `(117.9874858113787, -9.1988994115738) (117.7279, -9.3656)`)?

**Comment by keflavich** [comment]
For the other case, too, though, I see wrong coordinates returned.  e.g.:
```
In [66]: Simbad.query_criteria("region(rotatedbox, 61.374 +18.62462, 2.210d 2.210d, 162.20635)")
Out[66]:
<Table length=606>
          MAIN_ID                  RA           DEC      RA_PREC DEC_PREC COO_ERR_MAJA COO_ERR_MINA COO_ERR_ANGLE COO_QUAL COO_WAVELENGTH     COO_BIBCODE         RA_d        DEC_d     COO_ERR_MAJA_2 COO_ERR_MINA_2 COO_ERR_ANGLE_2  FLUX_V FLUX_ERROR_V
                                "h:m:s"       "d:m:s"                         mas          mas           deg                                                      deg          deg           mas            mas             deg         mag
           object                str13         str13      int16   int16     float32      float32        int16       str1        str1             object         float64      float64       float32        float32          int16      float32   float32
---------------------------- ------------- ------------- ------- -------- ------------ ------------ ------------- -------- -------------- ------------------- ------------ ------------ -------------- -------------- --------------- ------- ------------
                   HD 187245 19 49 22.5240 -07 45 52.162       8        8       29.070       25.300            90        C                1998A&A...335L..65H 297.34385000  -7.76448940         29.070         25.300              90    9.37        0.030
                   HD 186474 19 44 55.8945 -08 33 59.363      14       14        0.046        0.037            90        A              O 2018yCat.1345....0G 296.23289405  -8.56648985          0.046          0.037              90    9.76        0.020
```

Are you sure any of your queries with `region`s worked?

**Comment by mapfiable** [comment]
Oohh, that's really weird. For the other one it works for me:

```
[(60.6581286463427, 17.3443885901759) (60.9126700660543, 19.4550121388048)
 (60.4968063428871, 18.786957673443) (60.7924587248379, 18.6687406351119)
...
```

When I transform those back to my image coordinates, it looks fine (although a bit shifted, but that's probably because of the not 100% correct pointing).

How can I check which `astroquery` version I am running? Anything else that might help?

**Comment by keflavich** [comment]
I don't think this is an astroquery issue, though I'm not 100% sure - astroquery doesn't change anything about the criteria query.  Try running these criteria queries directly on SIMBAD.

**Comment by mapfiable** [comment]
You're right. There seems to be a problem [with SIMBAD](http://simbad.u-strasbg.fr/simbad/sim-sam?Criteria=region%28rotatedbox%2C+239.6645+-19.13481%2C+2.208d+2.208d%2C+18.77721%29+%26+Vmag+%3C+11.0+%26+Vmag+%3E+-27.0&submit=submit+query&OutputMode=LIST&maxObject=10000&CriteriaFile=):
![grafik](https://user-images.githubusercontent.com/48512334/107654997-72f35f80-6c83-11eb-8584-bd1dd976fde1.png)

**Comment by aoberto** [comment]
Hello, I confirm there is an issue here in Simbad during parsing coordinates from input.
I will dig into and fix it as soon as possible.
Anais

**Comment by mapfiable** [comment]
Thanks a lot!

**Comment by aoberto** [comment]
Thanks for having reported this issue, the query using box/rotatedbox are now correct. Sorry about that.
Anais

**Comment by mapfiable** [comment]
No worries, thank you! However, I cannot confirm it on my end. The results for my query are still off.

**Comment by mapfiable** [comment]
@keflavich ok so, I found a new issue. Not sure if this is related to the changes made how SIMBAD handles box/rotatedbox queries now but the following query seems to work in [SIMBAD](http://simbad.u-strasbg.fr/simbad/sim-sam?Criteria=region%28rotatedbox%2C+53.77369+%2B17.36241%2C+2.208d+2.208d%2C+159.63966%29+%26+Vmag+%3C+11.0+%26+Vmag+%3E+-27.0&submit=submit+query&OutputMode=LIST&maxObject=10000&CriteriaFile=), but not with `astroquery`:

```
qry = "region(rotatedbox, 53.77369 +17.36241, 2.208d 2.208d, 159.63966) & " \
      "Vmag < 11.0 & Vmag > -27.0"
```
Returns:

```
[(303.982651818056, -9.5326888798152)
 (304.3807178493444, -9.327842642186)
 (304.043111662604, -9.585983289729) 
...
```

![image](https://user-images.githubusercontent.com/48512334/108344512-82bbf800-71dd-11eb-9564-e3b7526874ea.png)

**Comment by mapfiable** [comment]
Hi, sorry for bothering again, but I still get the wrong results using `astroquery`. Are there any updates?

**Comment by keflavich** [comment]
@aoberto can you address this?

**Comment by bsipocz** [comment]
I think this has been fixed at some point, at least all the examples from above seem to work as expected for me. Feel free to reopen and include a new failing example if you find it otherwise.
