### ISSUE TITLE
vizier.query_region gives error rather than no object found

### ISSUE THREAD

**Issue by biqingfor** [astropy/astroquery#1993]
I have a script that uses query_region to search for objects within certain sq deg of a catalogue. Field centre RA and DEC provided. I am getting "TableLists can only be indexed with the ""named keys and integers.” error. After some testings, it seems that the error comes from the field centre falls outside the survey catalogue region.  I would have thought that the warning should be “no object found” and return this as an output rather than giving me the error.

**Comment by keflavich** [comment]
Could you please include a specific example that fails in this way?

**Comment by jwoillez** [comment]
@keflavich I have a fix for that one. It seems the behavior changed on the VizieR side. It's the same issue as in e.g. #1991 and probably some more. I had to work on #1992 to understand what was going on...

**Comment by biqingfor** [comment]
Yes, here is a specific example. Note, I set the timeout to be a large value because the connection to vizier in Strasbourg is not good for whatever reason. It is not relevant here but thought I would mention. I am now using a mirror site. As you can see, I tried with a declination of -5.0, which didn't give me an error. 

from astropy import units as u
from astropy.coordinates import SkyCoord
from astroquery.vizier import Vizier
from astroquery.vizier import conf
import astropy.coordinates as coord

conf.server = 'vizier.cfa.harvard.edu'

ra_deg = 254.75
dec_deg = -59.9
#dec_deg = 5.00

Vizier.ROW_LIMIT = -1

nhicat = Vizier(columns=['HIPASS', 'RAJ2000', 'DEJ2000', 'RVsp', 'Speak', 'Sint', 'RMS', 'Q', 'cf', 'ext'], catalog = 'VIII/89/nhicat', vizier_server=conf.server, timeout=1000)

nhicat_result = nhicat.query_region(coord.SkyCoord(ra=ra_deg, dec=dec_deg, unit=(u.deg, u.deg), frame='icrs'), width=[6*u.deg])
print (nhicat_result['VIII/89/nhicat'])

**Comment by jwoillez** [comment]
@biqingfor `nhicat_result` is an `Empty TableList`. Unless you know there should be targets within 5deg of the specified coordinate, I would say we have an expected behavior. Can you please check?

Also note that you should use `width=6*u.deg` instead.
