### ISSUE TITLE
vizier.query_region output errors with the FIRST catalogue

### ISSUE THREAD

**Issue by hyeinyoon** [astropy/astroquery#2001]
Hi, I have a script that searches for all objects within a certain sky coverage. I found Vizier.query_region returns only 50 objects with the FIRST catalogues (VIII/92/first14) even if I choose different directions of the sky. I have checked that the query works well and returns correct outputs with other catalogues (e.g. NVSS - VIII/65/nvss, a few thousands objects are found). I am wondering if it can be fixed by editing the script from my side. 

The key lines that I used for the script as below:

catalogue='VIII/92/first14'
Vizier.ROW_LIMIT = -1    
v = Vizier(columns=['FIRST', '_RAJ2000', '_DEJ2000', 'p(S)', 'Fpeak', 'Fint', 'Maj', 'Min'], catalog = catalogue, timeout=10000)
first_result = v.query_region(coord.SkyCoord(ra=ra_deg, dec=dec_tdeg, unit=(u.deg, u.deg), frame='icrs'), width=[6*u.deg])

**Comment by keflavich** [comment]
This issue is addressed in the documentation:
https://astroquery.readthedocs.io/en/latest/vizier/vizier.html#get-a-whole-catalog
