### ISSUE TITLE
astroquery.alma appears to return an incomplete and duplicated antenna listing

### ISSUE THREAD

**Issue by jmangum** [astropy/astroquery#2005]
Using the following:
```
from astroquery.alma import Alma
alchemi_data = Alma.query(payload={'project_code':'2017.1.00161.L'},public_data=False)
alchemi_data['antenna_arrays'][1057]
```
...it appears that the antenna_arrays listing contains multiple instances of a given antenna (but on different antenna pads)...
```
Out[6]: 'A001:DA44 A001:DV07 A002:DA46 A002:DA51 A005:DV25 A007:DV05 A008:DA42 A008:DV07 A010:DA50 A010:DV13 A011:DV21 A015:DA64 A016:DA44 A016:DV11 A022:DV23 A023:DA41 A023:DA42 A024:DA49 A025:DA46 A025:DV02 A026:DA57 A027:DV06 A033:DA53 A034:DA50 A034:DA55 A035:DA43 A035:DA47 A036:DA45 A039:DV14 A040:DA51 A040:DA55 A042:DV08 A043:DA60 A044:DV03 A044:DV11 A045:DV01 A047:DV15 A048:DA62 A048:DV02 A049:DA47 A049:DV03 A050:DV13 A058:DA41 A058:DA43 A060:DV17 A062:DV10 A066:DV04 A068:DA65 A069:DV16 A070:DA48 A070:DA62 A072:DV20 A073:DA54 A073:DA59 A074:DV09 A075:DA52 A075:DV18 A076:DA59 A076:DA63 A082:DA52 A082:DA54 A083:DV22 A085:DA48 A085:DA63 A086:DA58 A086:DV...'
```
Several antennas are repeated in the above listing (i.e. DV07).  Is this listing the combination of all antenna pad:antenna pairs that were observed in all sessions observed for a given scheduling block?

Also, it appears that the listing is incomplete, as the string ends with "...".

**Comment by keflavich** [comment]
@jmangum have you verified that the antenna number issue is an astroquery issue, not an ALMA archive issue?

The `...` issue is real, apparently.  @andamian, where are string limit lengths being imposed?  Is that upstream or in our tooling here?

**Comment by jmangum** [comment]
@keflavich I am not sure how I would check the ALMA archive side of this issue.  The antenna_arrays column does not seem to be provided with the ALMA archive web interface.

**Comment by andamian** [comment]
`Alma.help_tap()` shows that the size of `antenna_arrays` field is limited to 660 which is the size of the `...` values. I'm going to enquire ALMA developers about that limitation.

**Comment by alipnick** [comment]
Hi all, the solution for this should be implemented in an ALMA archive release coming out at the end of May.

**Comment by bsipocz** [comment]
The referenced alma release is long done, so I'm closing this issue now, please do reopen (and update the code snippet to reproduce the issue) is it's still relevant.
