### ISSUE TITLE
Cone-search for all known non-sidereal targets 

### ISSUE THREAD

**Issue by schirmermischa** [astropy/astroquery#2007]
Hello, I'm writing a tool to overlay all known non-sidereal targets from the MPC over an astrometrically calibrated FITS image with known DATE-OBS. Reading the astroquery documentation, I do not find a suitable tool in the MPC class. I can only make queries for a specific object. Would it be possible to implement a cone search within some search radius, at a given RA / DEC / DATE-OBS and geographic location?

**Comment by keflavich** [comment]
@dmcollom @mommeri @mkelley can any of you help address this?

**Comment by mkelley** [comment]
Hi @schirmermischa

That can be done with the SkyBoT service: https://astroquery.readthedocs.io/en/latest/imcce/imcce.html

If you'd rather use the Minor Planet Center, they have the MPChecker, but this is not implemented in astroquery: https://minorplanetcenter.net/cgi-bin/checkmp.cgi

**Comment by bsipocz** [comment]
I'm closing this now. The feature request for MPChecker is tracked in a separate issue: https://github.com/astropy/astroquery/issues/1811
