### ISSUE TITLE
astroquery fails to authenticate with MAST API token

### ISSUE THREAD

**Issue by havok2063** [astropy/astroquery#2016]
When trying to download a file behind MAST auth access, e.g. url="https://mast.stsci.edu/portal_jwst/Download/file?uri=mast:JWST/product/jw00736-o039_t001_miri_ch3-medium_s3d.fits", astroquery fails with an HTTP 401 "unauthorized for url" error.  However, it works successfully when I try a raw get with `requests`, passing in my MAST_API_TOKEN manually.   I'm using `astroquery=0.4.2.dev6635`.  The above url also works in the browser.   

Fails:
```
from astroquery.mast import Observations
uri = "mast:JWST/product/jw00736-o039_t001_miri_ch3-medium_s3d.fits"
result = Observations.download_file(uri, base_url='https://mast.stsci.edu/portal_jwst/Download/file')
result
('ERROR',
 'HTTPError: 401 Client Error: Unauthorized for url: https://mast.stsci.edu/portal_jwst/Download/file?uri=mast:JWST/product/jw00736-o039_t001_miri_ch3-medium_s3d.fits',
 'https://mast.stsci.edu/portal_jwst/Download/file?uri=mast:JWST/product/jw00736-o039_t001_miri_ch3-medium_s3d.fits')
```

Succeeds:
```
import os
import requests
url="https://mast.stsci.edu/portal_jwst/Download/file?uri=mast:JWST/product/jw00736-o039_t001_miri_ch3-medium_s3d.fits"
auth_token = os.environ.get('MAST_API_TOKEN', '')
r = requests.get(url, headers={'Authorization':f'Bearer {auth_token}'})
r
<Response [200]>
```

**Comment by havok2063** [comment]
Can anyone help with this?

**Comment by bsipocz** [comment]
cc @ceb8

**Comment by ceb8** [comment]
@havok2063 What happens when you log into mast via astroquery? Does it seem to recognize you?

**Comment by havok2063** [comment]
@ceb8 Well don't I feel stupid.  🤦  I had assumed that `Observations` would automatically look for my token and use it to authenticate internally before each request.  Or I had once known about `Observations.login` but forgot.  Once I actually manually log in, it does recognize me, and downloading is successful.

**Comment by bsipocz** [comment]
@havok2063  -  is there any place in the docs that need improvement, something that would have helped you?

**Comment by ceb8** [comment]
@havok2063 oh good! yeah, it doesn't look for a token every time, only if you log in.

**Comment by ceb8** [comment]
I'm going to go ahead and close this issue, but please do comment if you have documentation suggestions and I will add them.

**Comment by havok2063** [comment]
@bsipocz Yeah I think so.  As a user I mainly start at Getting Started or jump straight to Downloading Data.  One reason I missed it entirely was that it was hard to find the [Accessing Proprietary Data](https://astroquery.readthedocs.io/en/latest/mast/mast.html#accessing-proprietary-data) section.  It's sort of buried at the bottom.  I think adding a note in this section that clarifies to the user that `astroquery` does not actively perform token lookup would help.  

But, actually, it looks like there is some local session persistence because when I start up a brand new ipython terminal and use `Observations`, it does recognize me without explicitly logging in.  Perhaps that's why I thought it performed a lookup.   I think the last paragraph in "Accessing Proprietary Data" is getting at that, but I interpreted that paragraph as having to do with MAST auth tokens in general and not how `astroquery.mast.Observations` behaves.    So maybe moving that paragraph to the top and retooling to clarify that "you'll need to manually log in but afterwards it will remember you for x amount of time or until your token expires" would be helpful.

Additionally, it might be useful to add a general note in the Getting Started section that most of the examples given are for public data, but for proprietary data, authentication is needed, please see the [linked section], etc.   Otherwise my eye/brain never makes it to the bottom of the docs.

**Comment by havok2063** [comment]
Actually nevermind about the persistence in a different terminal.  It doesn't do that.  It finds any cached file whether you are logged in or not.  The other confusing thing is if I'm not logged in, it behaves successfully and returns a "result".  I have to examine the result before knowing whether it failed due to authentication or some other error, where I was half expecting it to raise an error.  But I can understand why returning a response tuple makes sense.

**Comment by ceb8** [comment]
Ah yes, the caching is checking for downloaded files so that happens before any authentication with the server, so it's not going to distinguish between files you downloaded requiring proprietary or not.
