### ISSUE TITLE
Is there a way to reduce entries from multi-star systems to a single entry?

### ISSUE THREAD

**Issue by mapfiable** [astropy/astroquery#2019]
When using `astroquery` to search an area in the sky for objects that satisfy certain criteria, it of course returns all the objects that do--as it should--, including stars from binary systems. In an image however, binary systems usually only appear as a single point source, which is all I am interested in: identifying the point source as a solar system. I don't care if the system has more than one star, in fact, it is a problem for me that the "same" position is identified twice. Is there any smart way to reduce the dataset returned by `astroquery` to only include one entry per solar system?

**Comment by keflavich** [comment]
In short, no, because the results from astroquery depend entirely on which service you're querying.  Each service will return entirely different types of data - for some services, you might get only single systems, while from other services, you might get multiple entries for a binary.  SIMBAD may distinguish between these.  However, for unresolved binaries, the conventional standard in astronomy, in my experience, is to refer to a binary system as a single star - so you're usually getting the results you've asked for here by default.

**Comment by mapfiable** [comment]
I see. Thanks a lot for the super fast reply! 

I don't specify any catalog so I assume every relevant catalog is searched, no? So that way entries might also double. Would it make sense to use the identifiers to see which entries point to the same solar system? Otherwise I might just use the coordinates, define some reasonable offset objects must have and reduce my data that way.

**Comment by keflavich** [comment]
You can't use astroquery without specifying a service - are you querying vizier?  MAST? IRSA? ESA? etc.  They all return entirely different types of result.

Yes, coordinate-based selection probably is what you're looking for

**Comment by mapfiable** [comment]
As far as I understand, I don't (conciously) specify one. Here's the query that I use:

```
qry = "region(rotatedbox, 61.374 +18.62462, 2.210d 2.210d, 162.20635) & " \
      "Vmag < 11.0 & Vmag > -27.0"
```
Does this maybe imply a certain catalog or is there a default one? Sorry for my ignorance!

**Comment by keflavich** [comment]
You are using the SIMBAD service.  They have a very specific curated catalog.

**Comment by mapfiable** [comment]
Oh, I'm sorry, I didn't know that's what you meant. I thought you meant which catalog I specify *within* SIMBAD. Obviously, I'm not very savvy yet in all this. Them being curated, what does that mean for me?

**Comment by keflavich** [comment]
The SIMBAD catalog is its own unique thing, and is one catalog afaik - it is curated by a team of scientists at CDS.  You should look into their documentation if you want to know more about how individual stars are stored.  Try looking up a known binary system and see how it is reported.


Curated also means that it contains strong selection biases - not all stars are in SIMBAD.

**Comment by mapfiable** [comment]
Thank you, this is some very good information! Would you recommend a different catalog instead? I don't care so much about very faint objects, although I can't really give you a magnitude range. Now that you mention their selection bias, I already did observe that for some of the clearly visible objects no match was found. I couldn't really explain it.

I thought SIMBAD had the option to specify the catalog because you can use the "cat" keyword for their queries. In their (unfortunately not so user-friendly) [documentation](http://simbad.u-strasbg.fr/guide/sim-fsam.htx#Sotypes) they have the following examle:

>```dec > 85 & (cat = 'hip' | cat = 'ppm') & radvel > 10```
 Get all objects having a declination over 85 deg, a radial velocity over 10 km/sec and being in either the hipparcos or the ppm catalog. 

So because of that and because the EDS page also has vizer and aladin there, I thought you would be able to put vizier, MAST, IRSA, ESA, in the query as well. It's all a bit overwhelming.

**Comment by keflavich** [comment]
I can't really offer further advice; it depends totally on what you're trying to learn.

Vizier is what you want if you want to search the full contents of specific catalogs.  SIMBAD contains measurements from some catalogs, which allows the search you highlighted, but it doesn't guarantee - afaik - that the whole catalog is included.

**Comment by aoberto** [comment]
I would recommend this documentation http://simbad.u-strasbg.fr/guide/simbad.htx to understand which objects/catalogues are in SIMBAD. 
The criteria we called `cat=` means that we kept the name coming from a specific catalogue, but the catalogue may not be fully ingested in SIMBAD. 
For binaries, you can use the criteria `otypes='**' ` to select only parent system (defined as it for at least one catalogues that we have ingested).
I hope it helps.

**Comment by mapfiable** [comment]
No worries, @keflavich, thank you! I might give vizier a shot in the future then.

Thanks a lot, @aoberto! When I use `otypes='**'`, does that mean I will only search for binary systems, or will I also find single-star systems? Which is the catalog this criterion is defined for? If I use it, but don't limit the serach to that catalog, will it still work? Out of curiosity: Why are certain catalogs not fully ingested in SIMBAD?

**Comment by aoberto** [comment]
The aim of SIMBAD is to give a bibliography on objects in the sky. So the objects in a large catalogue that do not have any other publication, usually are not in SIMBAD (in practice, it could be a bit more complex, historic catalogues, depending on the size of the catalogue ...).
The critrion `otypes='**'` will use an information associated to published catalogues (HD, WDS, ...) or papers that claim this object as a _"Double or multiple star"_, and then you will not have single star.
You can see this information on top of the web page of an object in the _"Other object types: "_ section.

So, if you would like to have all stars, but only one for each multiple system, I could suggest `(otypes='*' & parents=0) ` but he information of parent/child is quite recent, is not yet complete. But it could give you a good result.
I am sorry, but I think, the better is to do it by your own afterwards.

**Comment by mapfiable** [comment]
Thank you @aoberto for the elaborate response. I will try out `(otypes='*' & parents=0)` and see what works best!

**Comment by bsipocz** [comment]
OK, so let's close this issue here as this is neither about an astroquery bug or feature. 

@mapfiable - if you are not a member of it yet, I would suggest checking out the "python users in astronomy" facebook group. It has many thousand astronomers as members, and questions like this are well suited for that forum as people there may have different tricks and tips to do what you aim to do here.

As Adam mentioned above, in astroquery we do return data that you could otherwise access with the given archives' or data providers' platforms, and it's up to the user what and how to handle that data further for the work.

**Comment by mapfiable** [comment]
Thanks for the suggestion @bsipocz, I didn't know about that group. I will check it out! I wasn't really sure if this was the appropriate place to ask this kind of question, but I didn't know where else to turn. I thought about stackoverflow, but I fear that `astroquery` is still to obscure for that platform. I knew that here I would at least reach the right people straight away. In a way though I guess you could still see this as kind of a feature request, since it would be nice to be able to search for solar systems only, regardless of the number of stars that comprise it. But I understand now that this is highly dependend on the database searched, of course the database needs to offer this kind of information in the first place.
