### ISSUE TITLE
Versioning needs some attention

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astroquery#2028]
There are some issues with the versioning of this package:

* Girhub lists 0.3.9 as [the latest](https://github.com/astropy/astroquery) release (from 2018)
* The [Releases](https://github.com/astropy/astroquery/releases) section shows 0.3.10 and 0.4.0 as tagged but not released
* The installed version from [conda-forge](https://anaconda.org/conda-forge/astroquery) is 0.4.1
* The version in [pip](https://pypi.org/project/astroquery/) is also 0.4.1 (with no description given)

**Comment by keflavich** [comment]
See https://github.com/astropy/astroquery/issues/1604

**Comment by Gabriel-p** [comment]
Thank you. I understand from that this will be smoothed out when #1604 is addressed, so closing

**Comment by keflavich** [comment]
The reminder doesn't hurt.  The age of #1604 does. 😱

**Comment by bsipocz** [comment]
Please follow the documentation about the supported ways to install astroquery, how to get the releases. It is very clear about that releases are distributed on pypi and NOT on GitHub, please use those versions, installed by pip.
