### ISSUE TITLE
Add more narrative to customized Simbad queries

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2039]
It comes up from time to time of how to do a simbad query just for galaxies/stars/e.g. We do have some examples in the docs, but the narrative is not really detailed out which makes the discovery of the example a bit difficult. 

E.g. just adding "object type" somewhere in https://astroquery.readthedocs.io/en/latest/simbad/simbad.html#query-based-on-any-criteria

**Comment by ManonMarchand** [comment]
Looks solved to me. There's an entire paragraph on otypes

**Comment by bsipocz** [comment]
Indeed, #2701 has addressed this.
