### ISSUE TITLE
Alma remote tests are stuck

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2045]
The alma remote tests are seemingly stuck, both locally and in CI. One mocked tests are also failing with a legitime looking `FileNotFoundError` 

I didn't have the time to investigate, cc-ing the alma experts instead: @keflavich @andamian

**Comment by andamian** [comment]
I'll take a look. They should hit our test servers at the CADC so it's likely something wrong there. Thanks @bsipocz

**Comment by bsipocz** [comment]
This is kind of blocking the cron testing, so I go ahead and temporarily remote the running of the affected tests.

**Comment by bsipocz** [comment]
Hmm, locally I cannot reproduce this anymore, so maybe one of the more recently merged files, or something upstream has fixed this (it was still stuck the last time the cron tests were run. If they pass through the alma tests the next time I'll close this issue.

**Comment by bsipocz** [comment]
I lost track whether the affected tests got  fixed or skipped, but either way I don't see any of the remote tests being stuck (but there are a lot of them skipped). The slowest two were 51s and 33s which is OK, so I go ahead and close this issue for now.

**Comment by andamian** [comment]
Sorry - started a couple of times to look at this and every time got stuck with running any `astroquery` tests (includingin my environment and while trying to figure out what was wrong I got side tracked by other priorities. Haven't touched the tests so it was probably something wrong on the test servers. We've had a recent release and most likely that has fixed the issue. Sometimes it pays off to wait but that was definitely not my intention.

FYI, this was the error that I was seeing in my local env:
```
Exception: Error retrieving astropy-helpers from PyPI:
  DistutilsError("Command '['/Users/adriand/Documents/work/github/astroquery/.tox/py39/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/w4/pkjw20_n4j37m0lv5bnz6k6w0000gr/T/tmpytvlret5', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==2.0.11']' returned non-zero exit status 1.")
```

**Comment by bsipocz** [comment]
Certainly, my favourite test failures and issues are the ones that are self-healing without interaction :) I may tend to open github issues for them, but the main purpose is to document, and close off if they go away. With the infra team we will though think about better ways to run remote tests to pick up genuine issues sooner, as the current approach is not working very well (the cron is basically failing all the time, and some of the issues are genuine ones).

Your error on the other hand is an interesting one. We need to revamp the infrastructure, but the old ways should still work, and it should not try to download helpers from pypi. I suppose cleaning the git repo and rebuilding should fix it, e.g. trigger it with a `python setup.py test -P alma`
