### ISSUE TITLE
astroquery.vo_conesearch

### ISSUE THREAD

**Issue by Long-linlin** [astropy/astroquery#2048]
File "D:/Pythonwork/Lib/site-packages/astroquery/vo_conesearch/core.py", line 62
    def query_region(self, coordinates, radius, *, verb=1,
                                                                         ^
SyntaxError: invalid syntax
the comma before 'verb' is an error

**Comment by bsipocz** [comment]
What is your python version?

**Comment by Long-linlin** [comment]
> What is your python version?

python 2.7

**Comment by bsipocz** [comment]
Astroquery is python3 only for a while. You may have success using an older version, but I would think many modules would not work due to changes in the remote APIs
