### ISSUE TITLE
Cannot run  python setup.py test cleanly without mocpy installed

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#2061]
**Expectation**

I expect affected tests to be skipped if `mocpy` is not installed when I run `python setup.py test`.

**Reality**

`NameError: name 'MOC' is not defined`

**Comment by bsipocz** [comment]
yes, somehow both that one and vamdclib started to cause issues for me, too, not sure what has changed with pytest (these got passed the collection before).

**Comment by pllim** [comment]
Ops, look like you already brought it up in #1745 . I should have checked. Sorry.

**Comment by bsipocz** [comment]
Ahh, good catch, I didn't remember that open issue, but run into this problem yesterday. 😅
