### ISSUE TITLE
Vizier query_region not working with Astropy list as input

### ISSUE THREAD

**Issue by PierreKervella** [astropy/astroquery#2064]
The example provided in [this documentation page](https://astroquery.readthedocs.io/en/latest/vizier/vizier.html) is not working as expected:

`from astroquery.vizier import Vizier`
`agn = Vizier(catalog="VII/258/vv10",columns=['*', '_RAJ2000', '_DEJ2000']).query_constraints(Vmag="10.0..11.0")[0]`
`Vizier(catalog="II/246", column_filters={"Kmag":"<9.0"}).query_region(agn, radius="30s", inner_radius="2s")`
Out: Empty TableList

A few additional elements:
- The query using a list was working in a previous astroquery version.
- I checked that the query does not work with either an input list of SkyCoord or an Astropy table containing '_RAJ2000' and '_DEJ2000' columns.
- The query_region with a single object as input (e.g., SkyCoord) is working as expected.

Thank you in advance for your help.

**Comment by jwoillez** [comment]
Hello @PierreKervella, we had some recent changes with Vizier. Can you make sure you have the current version of astroquery from the main branch? The example works for me with that one.

**Comment by PierreKervella** [comment]
Bonjour @jwoillez, just to be sure, I reinstalled from scratch anaconda and then astroquery using:
`git clone https://github.com/astropy/astroquery.git`
The installed version of astroquery is 0.4.2.dev6703 (is it the right one ?)
Unfortunately the result of the sample of commands in my original post is still the same: `Empty TableList.`

**Comment by jwoillez** [comment]
This is the good version. Can you try clearing your cache in `~/.astropy/cache/astroquery/Vizier` and run the script again?

**Comment by PierreKervella** [comment]
I cleaned the cache directory of Vizier, but without effect. I see the two new Vizier pickle cache files being created after I enter the commands, but the result is still Empty TableList. If it may help, my installed version of astropy is 4.2.1.

**Comment by jwoillez** [comment]
Can you post the debug messages after turning them on?

    from astroquery import log
    log.setLevel("DEBUG")

**Comment by PierreKervella** [comment]
I noticed that there was a problem in my astroquery installation: v0.4.1 was the default version in conda, although `conda list` showed v0.4.2. So I removed v0.4.1 using
`conda remove astroquery`
then installed v0.4.2.dev6703 using
`pip install --pre astroquery`
`print(astroquery.__version__)`
0.4.2.dev6703
and now I have the expected behavior:
`Out[3]: 
TableList with 1 tables:
	'0:II/246/out' with 16 column(s) and 13 row(s)`
It would be good to update the default conda repository to v0.4.2 so that it installs directly with Vizier.
Thank you very much for your help @jwoillez !
