### ISSUE TITLE
vamdc dependency is blocked by pypi

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2066]
Basically, I could not upload the release to had to roll it back from `main`. It looks very much like https://github.com/pypa/twine/issues/430, but I had no time yet to investigate. The following is the error message I got:

```
Invalid value for requires_dist. Error: Can't have direct dependency: "vamdclib @ git+https://github.com/keflavich/vamdclib-1.git ; extra == 'all'"
```

**Comment by bsipocz** [comment]
Hmm, PEP440 kind of answers this, so I suppose we better remove the hack around the vamdclib dependency with the conclusions that in the future we cannot have modules with non-released dependencies:
 
```
Public index servers SHOULD NOT allow the use of direct references in uploaded distributions. Direct references are intended as a tool for software integrators rather than publishers.
```

**Comment by keflavich** [comment]
My vote is that we deprecate vamdclib. 

We then remove it entirely as a dependency and just slap warnings at the import part of the module saying that you need hacks to use it.

If I had more time I'd propose another approach, but I want the minimum effort here, and until we have users really asking for this, it's not worth much time.

**Comment by keflavich** [comment]
yes
