### ISSUE TITLE
XMMNewton download fails (possible memory leak)

### ISSUE THREAD

**Issue by SamSweere** [astropy/astroquery#2075]
The newest version of astroquery (0.4.2) seems to have introduced a bug when downloading xmm-Newton data. 

When running the following code:
``` python
from astroquery.esa.xmm_newton import XMMNewton as xmm
xmm.download_data("0762470101", level="PPS", extension="FTZ", filename="tafile", verbose=True)
```
I can see the data being downloaded as my network activity goes up. However, once the file is (probably) downloaded and it should write it to a file the memory usage goes up quite significantly. My memory consumption went up with +-8gb and stayed there.

Downgrading astroquery to 0.4.1 solved the problem.

**Comment by keflavich** [comment]
@lvalerom do you have any idea what's happening here?  This may be related to #1759?

**Comment by keflavich** [comment]
@SamSweere "downgrading" astroquery is not recommended - older versions are generally not compatible with new APIs.  I don't see any changes recently that could have caused your issue.

That said, the XMM Newton tool was not using the proper download machinery.  https://github.com/astropy/astroquery/pull/2087 fixes that and should make the downloads go more smoothly (and will show a progressbar by default).

**Comment by SamSweere** [comment]
Indeed the update fixed the problem. Thanks!
