### ISSUE TITLE
astroquery.sdss Your_browser_sent_an_invalid_request (query_region)

### ISSUE THREAD

**Issue by astroryan97** [astropy/astroquery#2082]
Hi, 

I have a list of RA and DEC positions for ~3633 objects from the NVSS that I want to query for in the SDSS and eventually download image cutouts. However, when I run the query I receive the following error message:

```
Your_browser_sent_an_invalid_request
------------------------------------
                     </body></html>
```

My question is why do I get the initial error message? I have another test file that runs and returns a query with no issues.

My code is as follows:
```
import pandas as pd
from astroquery.sdss import SDSS
from astropy import coordinates as coords
from astropy import units as u

file = "data.txt"
colnames = ['ra', 'dec', 'nvss flux']
df = pd.read_csv(file, sep=" ", header = None, names = colnames)

pos = coords.SkyCoord(df['ra'], df['dec'], unit = "deg", frame = 'icrs')

xid = SDSS.query_region(pos, radius = 0.1*u.arcsec, data_release = 16, 
                            photoobj_fields=['ra','dec','objid','run','rerun','camcol','field','type','u','g','r','i','z'])
```
The data files are below:
[sdss_compact_1_data_1.txt](https://github.com/astropy/astroquery/files/6673315/sdss_compact_1_data_1.txt)
[test_list.txt](https://github.com/astropy/astroquery/files/6673316/test_list.txt)

Also, when I run each position individually in a loop it sometimes it returns `None`. Although I attribute this to there being nothing near the position I'm querying.

**Comment by keflavich** [comment]
Could you give a minimal example too?  do you get that "your browser sent an invalid request" on the first entry in the list, or only if you run the loop or run for all positions?

**Comment by astroryan97** [comment]
> Could you give a minimal example too? do you get that "your browser sent an invalid request" on the first entry in the list, or only if you run the loop or run for all positions?

Thanks for your fast response. 

The "your browser sent an invalid request" error message appears when I run the query on the whole list of positions. When I run queries one by one I do get some results (about 25-50 in all). But I usually get 'None', which I assume means that there is no object in the SDSS near the position I'm querying, and that's fine because I'm not expecting the NVSS and SDSS to overlap much anyways. 

The odd thing is that error only happens with the larger list of from my post above, and not in my short test list. In total I have 49 different input lists which range in size from several hundred to several thousand (with a total of ~68,000 sources). I was hoping to avoid running a long loop and just querying all sources at once (per input list). I will try running queries on other input lists I have and see what the results are.

**Comment by keflavich** [comment]
It's possible that there are limits imposed by the SDSS server.  These limitations are only sometimes documented.  You might try to get some constraints on the limit by running with 1, 10, 100... items, or perhaps ask SDSS what their limits are.

Note that the astroquery sdss service _does_ search over a list of positions:
https://github.com/astropy/astroquery/blob/main/astroquery/sdss/core.py#L1012-L1023

though just browsing that, I note that there's a bug - the 'radius' is actually treated as a box.

**Comment by bsipocz** [comment]
The above example is working without producing the error on the current `main` branch, so I'm closing this issue now. Please feel free to reopen if you still experience this error or similar errors with the latest version.
