### ISSUE TITLE
How to query for frequencies?

### ISSUE THREAD

**Issue by santiagogil96** [astropy/astroquery#2097]
Say I want to obtain every observation whose spectral window contain the frequency 96.261 GHz. In the ALMA archive site I can accomplish this by typing the desired value in the frequency constraint in the search box. However, using 

Alma.query({'frequency':'96.261'}) or 
Alma.query_tap("select * from ivoa.obscore WHERE frequency=96.261")

seems to only filter for the tuned frequency of the observation, and thus returns nothing.
How can I search for every observation that contains the frequency I want?

**Comment by keflavich** [comment]
@santiagogil96 Please submit this question to the ALMA helpdesk (https://help.almascience.org/) and the ALMA helpdesk team will assist you there.

**Comment by santiagogil96** [comment]
> @santiagogil96 Please submit this question to the ALMA helpdesk (https://help.almascience.org/) and the ALMA helpdesk team will assist you there.

Thank you for your response. Will do.

**Comment by bsipocz** [comment]
Closing this as it was an upstream question. That being said, if there is a pull request with a documentation example of how to construct  a TAP query for this, it would be a welcomed addition.
