### ISSUE TITLE
Fix mocking in ALMA tests

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2103]
#2020 introduced the need to update the mocking in tests ` test_download_data` and `test_download_and_extract`

Without knowing anything about the data model of the downloads my workarounds for the tests looks rather hacky, so I would leave this issue to be addressed by the alma experts @keflavich  and @andamian.

Bottom line: 2 remote tests are failing currently, they need to be fixed!

**Comment by andamian** [comment]
I will try to run the tests myself. They run against our test servers.

**Comment by bsipocz** [comment]
Thanks! 
It really is just to add more info in the Mock call, I just didn't know what the right content I need to put in there that mirrors the behaviour of the server. (I tried the fits file name, but it wasn't really right as it didn't trigger doubling the downloads, and was very much not right for the second test.)

**Comment by bsipocz** [comment]
I think these have been fixed about a year ago, closing the issue.
