### ISSUE TITLE
ALMA: How can one get publication data?

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#2104]
The ALMA archive shows publication data associated with each observation, but there is no such column in the return from the ALMA astroquery search.  How can we access that information?

**Comment by keflavich** [comment]
ah... `bib_reference` was there the whole time.  That's the answer.

**Comment by bsipocz** [comment]
> ah... bib_reference was there the whole time. That's the answer. 

can you pop a short example in the docs page, so we don't run into it again? :)

**Comment by andamian** [comment]
`Alma.help()` groups all the queryable attributes. This is the section for `Publications`:
```
Publication
  Bibcode                           bibcode                             bib_reference
  Title                             pub_title                           pub_title
  First author                      first_author                        first_author
  Authors                           authors                             authors
  Abstract                          pub_abstract                        pub_abstract
  Year                              publication_year                    pub_year
```
