### ISSUE TITLE
MNT: tests should use temporary files and delete them

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2107]
When using pytest directly, rather than the astropy test runner, quite a few tests are creating files that are not cleaned up after the run. The repo should be left clean of these once the tests are run. I have these after a full run with `--remote-data`.

```
	J6FL25S4Q.vot
	J6FL25S4Q.vot.fits.gz
	J6FL25S4Q.vot.jpg
	X0MC5101T.vot
	astroquery/xmatch/tests/data/http_result.csv
	doctests.py
	file.png
	filename.tar
	int_data/
	moc.fits
	tarfile_lightcurves.tar
	target.xml
	w0ji0v01t_c2f.fits.gz
```

edit: maybe add a command at the end of the remote-data tests that lists everything that got generated during the run? maybe even test that no new files are hanging around?

**Comment by ViviCoder** [comment]
This issue also makes some tests fail with `PermissionError` when the package is installed in a system location.
See for example https://ci.debian.net/data/autopkgtest/unstable/amd64/a/astroquery/21354351/log.gz

**Comment by javier-ballester** [comment]
After merge #2461 I cannot seem to recreate this dumping of files. Are you using this command to run the tests? 

python setup.py test -P esa,esasky,gaia,utils.tap -R

**Comment by bsipocz** [comment]
@javier-ballester - the files only show up when running the tests directly with pytest as it runs them directly from the repo source tree rather than from a temp copy like the astropy test runner (when you run it via setup.py)

**Comment by jdavies-st** [comment]
It seems that the `astroquery.esasky.ESASky.get_images()` and `astroquery.esasky.ESASky.get_images_sso()` methods are responsible for the dumping of

```
$ ls int_data/scw/0042/004200100010.001/
compton_events.fits.gz		jmx2_anode_histo.fits.gz	sc_gti.fits.gz
ibis_deadtime.fits.gz		jmx2_deadtime.fits.gz		sc_hk.fits.gz
ibis_diag.fits.gz		jmx2_events.fits.gz		sc_modes.fits.gz
ibis_gti.fits.gz		jmx2_gain_corr.fits.gz		sc_orbit_param.fits.gz
ibis_hk.fits.gz			jmx2_gti.fits.gz		sc_time.fits.gz
ibis_mce.fits.gz		jmx2_hk.fits.gz			spi_acs.fits.gz
isgri_events.fits.gz		jmx2_mode.fits.gz		spi_block.fits.gz
jmx1_anode_histo.fits.gz	omc_gti.fits.gz			spi_gti.fits.gz
jmx1_deadtime.fits.gz		omc_hk.fits.gz			spi_hk.fits.gz
jmx1_events.fits.gz		omc_science_param.fits.gz	spi_oper.fits.gz
jmx1_gain_corr.fits.gz		omc_shots.fits.gz		spi_science_hk.fits.gz
jmx1_gti.fits.gz		picsit_histo_simh.fits.gz	spi_science_param.fits.gz
jmx1_hk.fits.gz			picsit_histo_sish.fits.gz	swg.fits
jmx1_mode.fits.gz		picsit_spti.fits.gz
```

into the cwd of the test runner, even if one uses `tmp_path` for the files the tests explicitly create.  @imbasimba any idea where, how or why these files are produced?  It's not clear to me at all in the code in `esasky.core`.  Perhaps they are specified server side?

**Comment by imbasimba** [comment]
Nice troubleshooting @jdavies-st. It seems like a bug to me. I'm guessing this one is probably the offender in the case of `int_data`:
https://github.com/astropy/astroquery/blob/a750c432d6000343157ad5d2a2a5fcd439c6fa8d/astroquery/esasky/core.py#L1495

If I'm reading it correctly, I think it should be something like:
`maps.append(fits.open(zip.extract(info.filename, path=mission_directory)))`

**Comment by jdavies-st** [comment]
Thanks @imbasimba! That looks promising.  I'll try it out.  I have a branch I'm working on right now fixing some of these temp files that are left behind elsewhere in `astroquery`, so I'll give it a try.
