### ISSUE TITLE
Fix docs examples for xmm newton

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2120]
The examples for e.f. `get_epic_images` are not complete, neither the narrative docs nor the docstring examples are copy-pasteable. While the logic of the examples are clear the current solution is not testable. 

The docstring examples, therefore, got removed in #2119

**Comment by lvalerom** [comment]
Hi @bsipocz, you are right. The example for `get_epic_images` is not copy-pasteable. The function needs an already downloaded observation. The step to download the observation could be added to the docs like:

```
from astroquery.esa.xmm_newton import XMMNewton
XMMNewton.download_data('0405320501')
...
XMMNewton.get_epic_images('0405320501.tar', band=[1,2], instrument=['M1'])
```
