### ISSUE TITLE
Replace *_async functions with an "async" keyword parameter.

### ISSUE THREAD

**Issue by demitri** [astropy/astroquery#213]
The "async" options should be a keyword parameter, not a parallel set of functions. You already essentially chose that "sync" is the default behavior (which is the correct choice!). While different results are returned, I think this is exposing an implementation detail in the API.

As for reading files into memory, this is I think non-standard behavior and a "surprise" - the user should not be worried about how that works. (Users shouldn't have to write the memory blobs to files!) Instead, files should be written to the astropy cache. Future query requests should check the local cache before reading from the web. (Kinda related to the above.)

**Comment by keflavich** [comment]
Closing because it's too late to make this change now.
