### ISSUE TITLE
astroquery.splatalogue.utils.minimize_table does not work on some molecules within some frequency ranges

### ISSUE THREAD

**Issue by djeff1887** [astropy/astroquery#2135]
For a subset of molecules (at least SiO, OCS, and C18O), when attempting to apply `minimize_table` to an `astroquery.splatalogue.Splatalogue.query_lines` table, I receive the following error in certain frequency ranges: `AttributeError: 'Column' object has no attribute 'mask'`. Below is an example of a script that causes this issue:
```
from astroquery.splatalogue import utils, Splatalogue
import astropy.units as u

query_table=Splatalogue.query_lines(100*u.GHz, 200*u.GHz, chemical_name=' SiO ', energy_max=1840, energy_type='eu_k', line_lists=['JPL','CDMS','SLAIM'], show_upper_degeneracy=True)

minimize_table=utils.minimize_table(query_table)
```
The issue appears to arise from the `merge_frequencies` function in `utils`, since I have found a temporary work-around that does not cause this error by setting the `merge` parameter to `False` in the `minimize_table` call. The issue does not arise for other frequency ranges, such as increasing the maximum frequency in the example to 500 GHz. Why that's the case isn't readily clear.

**Comment by keflavich** [comment]
The lack of masks is because there are no masked data on that column in the range you selected.  This is a pretty easy fix; PR forthcoming.
