### ISSUE TITLE
Using specobj_fields with query_crossid()

### ISSUE THREAD

**Issue by astroryan97** [astropy/astroquery#2142]
I have a huge list of SDSS objects that I am trying to obtain `photoobj` and `specobj` information for using the `query_crossid()` method. I can obtain the desired `photoobj` data no problem. But when I try to include a list of desired `specobj_fields` I get a `ValueError` (see below for a working example and the full error message). 

**My question is: does this error message simply mean that there is no (complete) `specobj` data available for that object? Or is there something wrong with my code that is causing the error?**

A working minimal example is as follows,

```
import numpy as np
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.io import fits
from astropy.table import Table
from astroquery.sdss import SDSS

specobj_fields = ['specObjID', 'z']
photoobj_fields = ['modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i', 'modelMag_z', \
                              'extinction_u', 'extinction_g', 'extinction_r', 'extinction_i', 'extinction_z', \
                              'deVAB_u', 'deVAB_g', 'deVAB_r', 'deVAB_i', 'deVAB_z', \
                              'mCr4_u', 'mCr4_g', 'mCr4_r', 'mCr4_i', 'mCr4_z', \
                              'petroR50_u', 'petroR50_g', 'petroR50_r', 'petroR50_i', 'petroR50_z', \
                              'petroR90_u', 'petroR90_g', 'petroR90_r', 'petroR90_i', 'petroR90_z']

ra = 170.805579
dec = -1.182146
coord = SkyCoord(ra, dec, frame='icrs', unit='deg')

result = SDSS.query_crossid(coord, photoobj_fields = photoobj_fields, specobj_fields = specobj_fields, data_release = 16)

print(result)
```
With the resulting error message as follows

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-33-2fc2ccbcbbb7> in <module>
>       4 dec = gal_zoo_2_meta['dec'][0]
>       5 
> ----> 6 result = SDSS.query_crossid(SkyCoord(ra, dec, frame='icrs', unit='deg'), photoobj_fields = photoobj_fields, specobj_fields = specobj_fields, data_release = 16) #, photoobj_fields = photoobj_fields, ,specobj_fields = specobj_fields
>       7 display(result)
> 
> ~\anaconda3\lib\site-packages\astroquery\utils\class_or_instance.py in f(*args, **kwds)
>      23         def f(*args, **kwds):
>      24             if obj is not None:
> ---> 25                 return self.fn(obj, *args, **kwds)
>      26             else:
>      27                 return self.fn(cls, *args, **kwds)
> 
> ~\anaconda3\lib\site-packages\astroquery\utils\process_asyncs.py in newmethod(self, *args, **kwargs)
>      27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
>      28                 return response
> ---> 29             result = self._parse_result(response, verbose=verbose)
>      30             self.table = result
>      31             return result
> 
> ~\anaconda3\lib\site-packages\astroquery\sdss\core.py in _parse_result(self, response, verbose)
>     860         if 'error_message' in io.BytesIO(response.content):
>     861             raise RemoteServiceError(response.content)
> --> 862         arr = np.atleast_1d(np.genfromtxt(io.BytesIO(response.content),
>     863                                           names=True, dtype=None,
>     864                                           delimiter=',', skip_header=1,
> 
> ~\anaconda3\lib\site-packages\numpy\lib\npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, like)
>    2120             # Raise an exception ?
>    2121             if invalid_raise:
> -> 2122                 raise ValueError(errmsg)
>    2123             # Issue a warning ?
>    2124             else:
> 
> ValueError: Some errors were detected !
>     Line #63 (got 4 columns instead of 1)
>     Line #125 (got 2 columns instead of 1)
>     Line #126 (got 2 columns instead of 1)
>     Line #132 (got 2 columns instead of 1)
>     Line #133 (got 3 columns instead of 1)
>     Line #134 (got 2 columns instead of 1)
>     Line #136 (got 4 columns instead of 1)
>     Line #137 (got 2 columns instead of 1)
>     Line #140 (got 2 columns instead of 1)

Thank you for your assistance.

**Comment by bsipocz** [comment]
This has been fixed in the current `main` branch (while I can reproduce the error with 0.4.5). Thank you @astroryan97 for reporting it.
