### ISSUE TITLE
Issue with spatial constraints in Alma.query

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroquery#2147]
The following script:

```python
import matplotlib.pyplot as plt
from astroquery.alma import Alma
from astropy.coordinates import SkyCoord
archive = Alma.query({'spatial_resolution': '0..0.5', 'galactic':'0..360 -2..2'})
coords = SkyCoord(archive['gal_longitude'], archive['gal_latitude'], frame='galactic')
plt.scatter(coords.l.deg, coords.b.deg)
plt.savefig('distribution.png')
```

produces the following plot:

![distribution](https://user-images.githubusercontent.com/314716/133170651-f96e9b3d-c71d-464f-98b5-2a8d60a2e105.png)

I would have expected all sources to lie between -2 and 2 in latitude, so it seems there is a bug somewhere along the way?

**Comment by bsipocz** [comment]
cc @andamian
