### ISSUE TITLE
Update of the SSD APIs

### ISSUE THREAD

**Issue by altairgomes** [astropy/astroquery#2151]
Recently,  the SSD web service has sent e-mails to the mail list regarding updates to the web service. The migration to the new service will be on September 27 and may affect the JPL Horizons and JPL SBDB queries. It follows the content of the e-mails:

I don't know how this will affect astroquery, but I think it's important.

Sent by Alan Chamberlain on September 13
"""
The SSD website has been significantly upgraded over the past few years with the following goals.

 * improved site navigation designed to make it easier to find content of interest
 * providing new content and tools
 * using APIs behind most tools to allowing direct programmatic access to data
 * improved look using commonly used frameworks supported on the most used browsers

Migration to the upgraded website is planned for September 27, 2021 in the morning (Pacific time).

Most users will not need to take any specific action.  Users with bookmarked URLs to the
current website should be automatically redirected to new corresponding pages.

If you have or use tools that scrape content from the current website, such tools will likely
fail after the migration.  It is important to understand that such tools are not supported.
If you are such a user and are concerned about the implications of the new website,
please let us know what tool(s) you use so we can provide alternative APIs or ideas.

Many new APIs are already available via our API server at https://ssd-api.jpl.nasa.gov/.
Only a few remain to be released and they should be released in the next few days.
A separate announcement will be sent once the remaining APIs have been released.

The new website requires JavaScript. If you use a browser with JavaScript disabled,
you will not be able to use many tools and will not be able to navigate via the menus.
Similarly, if you use a very old browser (e.g., IE8 or earlier), you are also likely
to have trouble using the new tools.  For the vast majority of SSD website users, there
should be no issues with your browser.
"""

Sent by Alan Chamberlain on September 15
"""
Two new APIs are available for accessing the Horizons system.

 1. https://ssd-api.jpl.nasa.gov/doc/horizons.html
 2. https://ssd-api.jpl.nasa.gov/doc/horizons_file.html

The first API is likely to be most useful for most users.  Those familiar with the current
Horizons batch CGI script will find the first API requires modifying only a single query
parameter.

Please see the above URLs for complete documentation.
"""

**Comment by keflavich** [comment]
Thanks @altairgomes.

@mommermi @mkelley @migueldvb  do you know if we need to update anything?

**Comment by mkelley** [comment]
If there are no other volunteers, I'll work on this next week.  I don't know how easy it will be yet, but it should be an improvement overall.

**Comment by bsipocz** [comment]
@mkelley - can this be closed, or there are anything left out from #2154?

**Comment by mkelley** [comment]
I think this is addressed.
