### ISSUE TITLE
Pending correction to ALMA TAP metadata for `bandwidth`

### ISSUE THREAD

**Issue by privong** [astropy/astroquery#2157]
I noticed that the `bandwidth` column of ALMA archive queries purports to be in GHz but is actually in Hz. I have brought this up with @alipnick and a ticket has been filed to fix this upstream. Per @keflavich's request, I am opening an issue here, so that the documentation can be re-generated (i.e., the `Alma.help_tap()` output) after the metadata is fixed upstream.

**Comment by keflavich** [comment]
@andamian just want to make sure this is on your radar - will you be able to handle it?

**Comment by andamian** [comment]
Yes. I'm doing it now along with other small issues.

**Comment by andamian** [comment]
I put the fix in the documentation and the general help in PR #2224 . `help_tap` is displaying the information from the server and that is going to be fixed when the service is patched sometimes in December (so I was told). @privong - thanks for pointing this out.
