### ISSUE TITLE
Zcut: Internal Server Error for url

### ISSUE THREAD

**Issue by tonypahl** [astropy/astroquery#2178]
I'm having trouble running Zcut in any capacity. Here's the most basic test I could think of, but any command I attempt to run returns the same error. I also had this issue on the 0.4.3 build of astroquery, and upgraded to the dev version to see if it could be reproduced.

```python
import astroquery
from astroquery.mast import Zcut
```

```python
astroquery.__version__
```

    '0.4.4.dev7033'

```python
Zcut.get_surveys(coordinates = SkyCoord(0, 0, unit=u.deg))
```

    ---------------------------------------------------------------------------

    HTTPError                                 Traceback (most recent call last)

    /tmp/ipykernel_104849/456011550.py in <module>
    ----> 1 Zcut.get_surveys(coordinates = SkyCoord(0, 0, unit=u.deg))
    

    ~/miniconda3/envs/zcut/lib/python3.7/site-packages/astroquery-0.4.4.dev7033-py3.7.egg/astroquery/mast/cutouts.py in get_surveys(self, coordinates, radius)
        365                   "radius": radius.deg}
        366 
    --> 367         response = self._service_api_connection.service_request_async("survey", params)
        368         response.raise_for_status()  # Raise any errors
        369 

    ~/miniconda3/envs/zcut/lib/python3.7/site-packages/astroquery-0.4.4.dev7033-py3.7.egg/astroquery/utils/class_or_instance.py in f(*args, **kwds)
         23         def f(*args, **kwds):
         24             if obj is not None:
    ---> 25                 return self.fn(obj, *args, **kwds)
         26             else:
         27                 return self.fn(cls, *args, **kwds)

    ~/miniconda3/envs/zcut/lib/python3.7/site-packages/astroquery-0.4.4.dev7033-py3.7.egg/astroquery/mast/services.py in service_request_async(self, service, params, page_size, page, **kwargs)
        270             params[prop] = value
        271         catalogs_request.extend(self._build_catalogs_params(params))
    --> 272         response = self._request('POST', request_url, data=catalogs_request, headers=headers)
        273         return response
        274 

    ~/miniconda3/envs/zcut/lib/python3.7/site-packages/astroquery-0.4.4.dev7033-py3.7.egg/astroquery/mast/services.py in _request(self, method, url, params, data, headers, files, stream, auth, cache)
        180             raise TimeoutError("Timeout limit of {} exceeded.".format(self.TIMEOUT))
        181 
    --> 182         response.raise_for_status()
        183         return response
        184 

    ~/miniconda3/envs/zcut/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
        951 
        952         if http_error_msg:
    --> 953             raise HTTPError(http_error_msg, response=self)
        954 
        955     def close(self):

    HTTPError: 500 Server Error: Internal Server Error for url: https://mast.stsci.edu/zcut/api/v0.1/survey

**Comment by dr-rodriguez** [comment]
I suspect this is an uncaught error when querying coordinates that are not in the supported surveys. If for example I run ```Zcut.get_surveys(coordinates = SkyCoord(189.38, 62.22, unit=u.deg))``` I get a valid response.
I'll ask our developers to see if they can provide a better error message for this case.
