### ISSUE TITLE
The radius in SkyView get_image_list is actually diameter

### ISSUE THREAD

**Issue by ysBach** [astropy/astroquery#2190]
The code (copied below) seems to use `radius` as the size of the field of view to query. 

If my understanding is correct, the code should be updated such that 
(1) the name of it should be `diameter` rather than `radius`, to avoid backward incompatible change
(2) change the code to use `2*radius` for size

The code:
```python
# https://github.com/astropy/astroquery/blob/main/astroquery/skyview/core.py#L253
# original code
        if radius is not None:
            size_deg = str(radius.to(u.deg).value)
        elif width and height:
            size_deg = "{0},{1}".format(width.to(u.deg).value,
                                        height.to(u.deg).value)

# Change to
        # either 
        if diameter is not None:
            size_deg = str(diameter.to(u.deg).value)

        # or
        if radius is not None:
            size_deg = str(2*radius.to(u.deg).value)
```
How do you think?

**Comment by keflavich** [comment]
Yeah, this is right - the `size_deg` is interpreted as width/height, according to [the docs](https://skyview.gsfc.nasa.gov/current/help/fields.html#size), so we should set `size_deg=2*radius`.
