### ISSUE TITLE
Fix MAST download products tests to limit test download to a minimum amount

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2209]
As the comment says in the code the current test is now ideal as it both takes too long and downloads way too much data.
Ideally, the fix is just to choose another OBSID that corresponds to a very small set of file(s). The test has been marked to be skipped for the time being.

https://github.com/astropy/astroquery/pull/2174#discussion_r748654667

cc @jaymedina

**Comment by bsipocz** [comment]
I'm marking this critical, as the mast remote tests now extremely slow (I started a testrun for only the mast module ~25mins ago and it's not yet halfway through). I haven't directly checked on how much data they actually download, but I don't recall any fixes has been made to this original issue, so my guess would be that it's a lot.

Pinging @astrojimig and @snbianco to get this on the radar

**Comment by snbianco** [comment]
Just to clarify, is this issue specifically for the `test_observations_download_products` test? Or for all of the mast remote tests in general?

**Comment by bsipocz** [comment]
I think the remote tests and also the documentation would hugely benefit of a full audit (there are a couple of related issues opened about those, too). That particular test function was problematic 2.5 years ago, but I'm not sure if that's the worst offending one atm.

I would recommend using `--durations` to see which ones are the worst, though that of course doesn't monitor total download sizes during the runs (back when the issue has been opened, I was watching the size of the temp test directory while the tests were running)

**Comment by bsipocz** [comment]
E.g. today tests were a bit faster than yesterday, but 13mins for the module, without the doctests, is still too long:

```
=========================================================================== slowest 15 durations ===========================================================================
168.58s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_catalogs_query_region
92.97s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_tesscut_get_cutouts[spoc]
64.80s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_tesscut_get_cutouts[tica]
54.74s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_zcut_get_cutouts
54.61s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_zcut_download_cutouts
40.00s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_observations_query_criteria
38.40s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_tesscut_get_cutouts_mt
35.28s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_observations_query_criteria_async
29.50s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_tesscut_download_cutouts[spoc]
26.54s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_tesscut_download_cutouts[tica]
23.59s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_tesscut_download_cutouts_mt
23.11s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_catalogs_query_region_async
17.92s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_observations_download_file
16.82s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_observations_query_region_count
14.00s call     astroquery/mast/tests/test_mast_remote.py::TestMast::test_mast_service_request_async
========================================================================= short test summary info ==========================================================================
SKIPPED [1] astroquery/mast/tests/test_mast_remote.py:294: Tests should not download this much data. Skipping until revised.
FAILED astroquery/mast/tests/test_mast_remote.py::TestMast::test_resolve_object - AssertionError: assert 0.0002 == 0
FAILED astroquery/mast/tests/test_mast_remote.py::TestMast::test_catalogs_query_region - assert 34396 == 3
FAILED astroquery/mast/tests/test_mast_remote.py::TestMast::test_catalogs_query_object - AssertionError: assert '60112519' in <MaskedColumn name='MatchID' dtype='str9' length=96>\n  7542452\n 87056568\n101253750\n 52010793\n  1642507\n 38460340\n 5326...  ...
====================================================== 3 failed, 93 passed, 1 skipped, 4 errors in 803.23s (0:13:23) =======================================================
```

**Comment by bsipocz** [comment]
(note the assert failure in the catalog query, fixing the test will likely solve the duration issue, too)
