### ISSUE TITLE
NED query does not return all available spectra

### ISSUE THREAD

**Issue by dcolombo** [astropy/astroquery#2213]
I have tried to use astroquery to download HI spectra from NED. Unfortunately, I am having a few issues with it. For example, by doing:

```
from astroquery.ned import Ned
Ned.get_spectra('NGC6060’)
```

I get:

```
[[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x11e1dbfd0>]]
```

Similarly, by calling the spectra list: 

```
Ned.get_image_list("NGC6060", item='spectra') 
```

I get:

```
['http://ned.ipac.caltech.edu/spc1/2000/2000UZC...C......0F/16/CGCG_1603.7+2138:S:UBVR:f2000.fits.gz']
```

According to this output only the first spectra in https://ned.ipac.caltech.edu/cgi-bin/NEDspectra?objname=NGC+6060&extend=never&detail=0&preview=1&numpp=20&refcode=ANY&bandpass=ANY&line=ANY&hconst=73.0&omegam=0.27&omegav=0.73&corr_z=1 has been downloaded. However, the spectra available in Ned for NGC6060 are three (and I am actually interested in the last 2).

Is there something I am missing?

I am using astroquery version 0.4.3.

**Comment by keflavich** [comment]
@dcolombo it looks like this is simply because there are no FITS files for the 2nd or 3rd entries, they are only available as ASCII files!  We do not have tools made to extract the "Author ASCII" or "NED ASCII" format files.

**Comment by bsipocz** [comment]
I'm closing this with #2217, but please feel free to reopen if there is an idea for a more complex solution.
