### ISSUE TITLE
IrsaDust.get_extinction_table -- dust values contaminated by galaxies

### ISSUE THREAD

**Issue by pbrown801** [astropy/astroquery#2220]
A student and I have found that the Schlegel dust maps are contaminated by the IR light of nearby host galaxies.  Additionally, the recommended values for the regions around the SMC, LMC, and M31 were given in the appendix, not in the maps read by IrsaDust.get_extinction_table     In the tables on the github listed below are coordinates, updated A_V values, uncertainties, and the radius around which we recommend using our updated values.  An accepted AJ paper describing the process is attached.

The table and code to read it is posted at 
https://github.com/pbrown801/AV

Note these A_V values are on the Schlafly & Finkbeiner 2011 system. 

[AV.pdf](https://github.com/astropy/astroquery/files/7558595/AV.pdf)

**Comment by keflavich** [comment]
@pbrown801 Is this issue related to astroquery?  Are you proposing an interface to a different database?

**Comment by pbrown801** [comment]
This issue is related to the astroquery search IrsaDust.get_extinction_table for dust extinction values from the Schlegel maps, namely that the maps are contaminated with nearby galaxies.  For full openness, maybe there should be an additional query that assumes my values are better so that people wanting the Schlegel values get the Schlegel values even if there is an issue. But perhaps the existing query to the Schlegel maps could be modified so that if someone searches for a MW reddening near the SMC, LMC, and M31 they get the values recommended in the Schlegel appendix.  NED had something like this implemented.  

 The method I've implemented is to search my file (a small database of ~50 lines with coordinates) to see if I have an update before pulling the Schlafly/Schlegel value from the above search.  That could be a separate query.  I'd like to hear others' thoughts on what could/should be done.

**Comment by keflavich** [comment]
Astroquery provides an interface to the `IrsaDust.get_extinction`.  We do not take responsibility for what is hosted on that service.  If you have reason to believe that the values given by that service are incorrect, you should contact them directly.

If the NED service you mentioned provides a local-to-galaxy correction, we could provide an interface to that, and possibly even find a way to link it to the `get_extinction` method in `IrsaDust`.  But astroquery is not the place to correct measurements in databases; astroquery results should reflect what is in the database.

**Comment by bsipocz** [comment]
Given the comment above and no response to it since I suggest to close this issue. It can be reopened if it's shown to be an issue with astroquery rather than about the upstream data product.
