### ISSUE TITLE
Gallery examle no10 downloads large amount of data

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2222]
The "Retrieve Hubble archival data of M83 and make a figure" example (https://astroquery.readthedocs.io/en/latest/gallery.html#example-10) downloads an awful lot of data (I've stopped the run at 6+GB, it wasn't clear how much longer would it go), which is totally unnecessary for showcasing an astroquery functionality. It would be great to rephrase or even totally exchange that example to involve only a small amount of data.

This is related to #863, #1905 and even may be even #307 (the latter only if we decide to go with a sphinx gallery approach for the examples)

cc @jaymedina @tomdonaldson

**Comment by keflavich** [comment]
We could remove & deprecate the astroquery gallery in favor of examples that use astroquery on learn.  All of these use it:
![image](https://user-images.githubusercontent.com/143715/142701745-408828b8-244e-45b0-a0aa-2562752e105a.png)


I can't find a way to link to learn.astropy.org with search filtered by astroquery, but that seems more sustainable than the gallery.

So I suggest we make this Issue a checklist for transitioning examples to learn?

**Comment by bsipocz** [comment]
I'm OK with the idea, though it's not clear how stable and reliable that page is in practice.
But basically, my goal is to remove all broken code from this repo. And if examples keep failing somewhere downstream then it's not my problem any more :)
