### ISSUE TITLE
Nasa Exoplanet Archive `query_object` method suddenly produces InvalidTableError

### ISSUE THREAD

**Issue by annazuckerman** [astropy/astroquery#2239]
I have previously many times used the following snippet of code to query for exoplanetary properties from the NASA Exoplanet Archive:
```
from astroquery.nasa_exoplanet_archive import NasaExoplanetArchive 
planet_properties = NasaExoplanetArchive.query_object(planet_name) # planet_name is a string, ie. 'kepler-69b'.

```
However, this recently started producing the following error:
`InvalidTableError: 'aliastable' is not a valid table`

I have tried updating the import statement to 
`from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive`
as I believe this was recently updated, but that does not solve the issue.

I apologize if the issue is on my end, but I would very much appreciate any information about what might be causing this (and how to solve). Thanks in advance.

**Comment by AWehrhahn** [comment]
I am having the same problem. As far as I can tell the Nasa Archive renamed the table to "object_aliases". However just renaming the table in the query now fails with an SQL Error:
```astroquery.exceptions.InvalidQueryError: ORA-00933: SQL command not properly ended```

**Comment by bsipocz** [comment]
cc @rickynilsson

**Comment by AWehrhahn** [comment]
Looks like they discontinued the SQL interface for the new TAP interface for this table.

**Comment by AWehrhahn** [comment]
I tried querying the object_aliases table manually, which gives me a result. However it only has one column "resolved_name", so it doesn't actually give me the alias of the system?

**Comment by rickynilsson** [comment]
@AWehrhahn, @annazuckerman - yes, that table unfortunately not only changed name, but the API was also doing something specific for that table that hasn't yet been implemented in our TAP service, so there isn't a straightforward fix. I will look at this later today or tomorrow and get back to you. Apologies for the inconvenience!

**Comment by rickynilsson** [comment]
@bsipocz - it doesn't seem like the same functionality will be available through TAP in the near future. I'm thinking we just have the method call the Simbad.query_objectids method? What do you think?

**Comment by bsipocz** [comment]
> I'm thinking we just have the method call the Simbad.query_objectids method?

maybe along with a deprecation if all that the method is doing now is to call simbad (I haven't followed this closely, so am not sure which method we're talking about). Bottom line, it's more than OK to use other modules.

**Comment by rickynilsson** [comment]
It's not what it's doing currently — we are/were running our own name parser and then returning aliases from our databases, but I was thinking we could use Simbad as an interim solution. However, from a later meeting yesterday I found out we have a not yet widely announced service that can be tweaked to return aliases in the format we used before, so I'll work on that this week (instead of any interim Simbad solution).

**Comment by AWehrhahn** [comment]
Has there been any progress on this?

**Comment by rickynilsson** [comment]
> Has there been any progress on this?

The holidays got in the way, but I should pick this back up. Feel free to work on an interim Simbad solution if you'd like, since my bandwidth will be limited for at least another 2 weeks.

**Comment by bsipocz** [comment]
@annazuckerman @AWehrhahn - This issue has been fixed and until a fully-fledged release is made you can get the a dev version including the fix with `pip install -U --pre astroquery`
