### ISSUE TITLE
Simbad query and query_id fail

### ISSUE THREAD

**Issue by Tonione** [astropy/astroquery#2244]
I have encountered trouble with simple Simbad queries. I'm on python3.8 on mac OS, with astropy (5.0) and astroquery (0.4.4).

Simple queries such as 
`
from astroquery.simbad import Simbad
obj=Simbad.query_object('Kepler-235')
`
or
`
from astroquery.simbad import Simbad
name=Simbad.query_objectids('Kepler-235')
`
result both in the same error:
`/opt/anaconda3/lib/python3.8/site-packages/astroquery/simbad/core.py:135: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): java.lang.NullPointerException`

Did anyone encounter the same issue? I

**Comment by keflavich** [comment]
I can't reproduce this error.  It may have been a temporary service issue.  Please try again.  If it persists, try querying with the cache disabled:
```python
from astroquery.simbad import Simbad
obj=Simbad.query_object('Kepler-235', cache=False)
```
If that works (and querying with cache enabled does not), you will need to clear your cache.

**Comment by Tonione** [comment]
Hi, thank you so much for taking the time to look into it. I have no optional argument 'cache' in `Simbad.query_object` so I cannot check it out. How would proceed to clear the cache otherwise? Thanks again.

**Comment by keflavich** [comment]
Remove files in your `~/.astropy/cache/astroquery/Simbad/` directory.

This conversation has revealed a bug, though: `simbad.query_object()` should pass the `cache` argument on, but it does not.

**Comment by aoberto** [comment]
Hello, do you think that we could have a maximum duration for the cache ? For instance, like 1 day ?

**Comment by aframosp** [comment]
I have the same issue as described by @Tonione, this time for `simbad.query_objects()`. Removing the cache directory helps only momentarily, because the error is happening every ~10 min if I try some queries continiously.

**Comment by keflavich** [comment]
@aoberto cache expiration has been a wishlist item for a while.

However, the problem reported here seems to be a real one involving caching failed queries; we should _never_ cache failed queries.

**Comment by aoberto** [comment]
@aframosp Ho yes, I found the origin of the NullPointer, and fix it (I hope) at least it should avoid the wrong behavior, sorry for that.
@keflavich Yes, of course, this is better, but I do not know which one is easier to do

**Comment by keflavich** [comment]
Not caching failures is both a bit easier and more critical.  Even though the upstream part of this issue is solved, I'd like to leave it open until I fix the caching issue.

**Comment by keflavich** [comment]
https://github.com/astropy/astroquery/pull/2187 was the solution to this issue.  I'm not entirely sure, but this issues may be solved already.  Without a clearer MWE (which is hard to make, since the issue is fundamentally upstream), it is hard to test.

@aoberto is there a query we could run against SIMBAD that would reliably fail with exactly this error so we can add a test of how astroquery handles the error?

**Comment by bsipocz** [comment]
cache timeout has been worked on and we have two abandoned WIP PRs for some fixes. Maybe they can be warmed up and wrapped up? 

@ceb8 - would you think https://github.com/astropy/astroquery/pull/1634 need much more work?
