### ISSUE TITLE
async interface is unintuitive

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#225]
Currently, the objects returned by `_async` are poorly labeled (i.e., have bad `repr`s) and are unintuitive to use.

We need to:
- [x] fix the reprs for the returns from `_async` methods
- [ ] make `parse_result` a public method
- [ ] include demos of how to use `_async` methods

**Comment by bsipocz** [comment]
@keflavich - I think we can close this now, or do you have an updated action items list of things that still need improving?

**Comment by keflavich** [comment]
Nah, let's close this.
