### ISSUE TITLE
Decrease import time by not importing TestRunner

### ISSUE THREAD

**Issue by EfremBraun** [astropy/astroquery#2266]
I've noticed that astroquery take a long time to import. For example, `from astroquery.heasarc import Heasarc` takes 0.9 seconds on my laptop. That's a little longer than it takes to import ALL of numpy, scipy, matplotlib, astropy, pandas, sklearn, bokeh, and PySide6.

This can be rather frustrating for certain users (e.g., when these packages are embedded into GUIs where the end-user doesn't know that there's a background Python process importing packages which is what's causing the delay to the application startup).

I looked into why this might be, and I found a package named Tuna (https://github.com/nschloe/tuna; see how to use it for examining imports at https://stackoverflow.com/a/51300944). The biggest single-item contributions to the long import time that I see is that 0.3 seconds is spent importing Dask and 0.17 seconds is spent importing Astropy's TestRunner.

I suspect that both of these are unnecessary, and removing them from imports might not be too hard. I've already reported the Dask issue to the main Astropy repo. The TestRunner issue can be fixed within astroquery though. The issue is the line `from ._astropy_init import *` in https://github.com/astropy/astroquery/blob/main/astroquery/__init__.py. https://github.com/astropy/astroquery/blob/main/astroquery/_astropy_init.py has the line `from astropy.tests.runner import TestRunner`. If this is only used for developer testing, I don't think this needs to be imported by users.

See https://github.com/astropy/astropy/issues/12801 for more details.

**Comment by bsipocz** [comment]
I'm sorry that you have to deal with frustrated users, but propagating that frustration is not really the solution. Have you considered displaying some info during the startup of your GUI of what your backend does?

FYI: the test runner is public API as it provides `astroquery.test()`. I'm sorry that you think it's unuseful, in fact it's being used in troubleshooting scenarios along with users.

Also, astroquery is working with remote servers, so a one-timer 0.17s is honestly doesn't seem anywhere near significant.'

**Comment by bsipocz** [comment]
Btw, as I see your tuna report that 0.17s includes the import of astropy which also includes the import of numpy. So I very much don't see anything to do there as neither of those packages are optional if you want to run an actual query...

**Comment by EfremBraun** [comment]
> Btw, as I see your tuna report that 0.17s includes the import of astropy which also includes the import of numpy. So I very much don't see anything to do there as neither of those packages are optional if you want to run an actual query...

You're right. If I run `import numpy` before `from astroquery.heasarc import Heasarc`, the import time of the latter statement goes down by 0.1 seconds. So it's only around 0.07 seconds that gets taken up by the TestRunner import.

**Comment by EfremBraun** [comment]
> I'm sorry that you have to deal with frustrated users, but propagating that frustration is not really the solution. Have you considered displaying some info during the startup of your GUI of what your backend does?
> 
> FYI: the test runner is public API as it provides `astroquery.test()`. I'm sorry that you think it's unuseful, in fact it's being used in troubleshooting scenarios along with users.
> 
> Also, astroquery is working with remote servers, so a one-timer 0.17s is honestly doesn't seem anywhere near significant.'

If a user only runs `from astroquery.heasarc import Heasarc`, I don't think that `astroquery.test()` would need to be exposed though, no?

And from a UI perspective, users expect a small lag when clicking a "conduct query" button. Users get frustrated when applications are slow to startup though. Saving 0.07 seconds from startup is not something I'm going to fight for though. Thank you anyway.

**Comment by bsipocz** [comment]
🤷 

According to your own report posted on the other issue, the whole of the 0.17s is for astropy and numpy and NOT for the testrunner. So I don't see that changing our public API would in fact help you with lowering that startup time.

As I said above, I'm sorry that you deal with frustrated GUI users who expect instantaneous startup. Please try to educate them rather than propagate their frustration upstream and complain about things that are actually in place for user support.
