### ISSUE TITLE
Gaia.launch_job_async output_file parameter enhancement

### ISSUE THREAD

**Issue by jaokeeffe** [astropy/astroquery#2276]
Would be nice to specify the output folder rather than just the file - that way you could use the unique jobid filename generated by the request and also specify where in the filesystem you want it written. If I use the output_file parameter then I need to use a random number generator in the filename to prevent multiple simultaneous requests clobbering each other. Or perhaps there is a better way?

**Comment by eerovaher** [comment]
Including the directory in the filename seems to work just fine, as long as the directory already exists.

**Comment by jaokeeffe** [comment]
Yes that works - that wasn't what I was referring to - the issue is you can use the output_file parameter in two ways:
1. omit it and the output will be called <jobid>-result.csv and will be dropped into the current directory
2. specify it with a filename or a fully qualified path and filename.

But if you want to keep the jobid filename (so that it is unique during multiple concurrent runs) but also want it written into a different path to the one you are running the script from - then you need to create a random filename, then specify it in the call  using the output_file parameter, and then rename the file using the jobid from the job object returned.

No big deal and I have written code to do this but thought it might be useful!

**Comment by eerovaher** [comment]
I see now, you want to only change the directory without changing the filename.

The `launch_job()` and `cone_search()` methods together with their async versions return an `astroquery.utils.tap.model.job.Job` instance that has an `outputFile` attribute, so it should be possible to achieve what you want with something like
```python
job = Gaia.launch_job_async(...)
filename = job.outputFile
os.rename(filename, os.path.join('new_directory', filename))
```
However, the `query_object()` and `query_object_async()` methods do not return a `Job` instance but return the query results as an `astropy.table.Table` instead, and the simple solution outlined above does not work. It is possible to populate the metadata of the `Table` with information about the query, such as the output file name or the ADQL query that was actually executed, but that metadata can persist even if the `Table` is modified, so I'm not too sure if that's actually desirable.

**Comment by jaokeeffe** [comment]
Thanks - yeah that's essentially what I ended up doing.
