### ISSUE TITLE
Issue with MPC.get_ephemeris/.query_object connection for asteroids

### ISSUE THREAD

**Issue by ABattson** [astropy/astroquery#2277]
The 'MPC.get_ephemeris' and 'MPC.query_object' functions seems to be entirely non-functional for asteroids. For example, when I input 
result = MPC.query_object('asteroid', name='ceres')
 I get the error 
SSLError: HTTPSConnectionPool(host='minorplanetcenter.net', port=443): Max retries exceeded with url: /web_service/search_orbits?name=ceres&limit=1&json=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
This occurs when requesting any asteroid information, even if I only request it once for a single object. I'm not sure if the issue is on this end or the cgi.minorplanetcenter.net end. Two days ago I was using these functions perfectly normally. Any advice?

**Comment by mkelley** [comment]
Hi @ABattson , this appears to be an issue with the MPC's website.  There is a notice at http://minorplanetcenter.net/ 

> 2022 Feb 01 13:21
> SSL Certificate Expiration
> The MPC is aware and in the process of fixing the issue with the expiration of the MPC SSL Certificate. This has affected a number of services but the NEOCP can still be accessed via HTTP.

**Comment by ABattson** [comment]
Thanks @mkelley! I think they just posted that.
