### ISSUE TITLE
Catalog-based queries

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#228]
We need to supply a multi-object query interface for services like Vizier and SIMBAD that allow searches towards multiple objects.  Right now, the only way to do that with astroquery is to submit a series of requests, which may appear to the host server as a DOS attack and should therefore be discouraged.

**Comment by bsipocz** [comment]
We kind of doing this, and there are other, more specific issues that track the need of vectorizing more queries for specific modules.
