### ISSUE TITLE
Vizier.query_ Not Performing Consistently

### ISSUE THREAD

**Issue by TheWalrusKookookachoo** [astropy/astroquery#2286]
My issue is that Vizier.query is not running consistently, either due to a glitch in astroquery or at the Vizier end.
I am currently using Vizier.query_object(STAR_NAME, radius=field_of_view * u.deg, catalog = 'SDSS12') to identify objects with characteristics.  STAR_NAME = 'J005620.31+120157.0'  field_of_view = 0.001 for all objects - this is small enough to uniquely identify objects but large enough to always identify and object.  
Beginning today, this returns Empty TableList.  Expanding field_of_view = 0.002 will return the targeted object but is too large to be suitable for the general case.
I began using Vizier.query_object a couple days ago because Vizier.query_object() was returning Empty TableList, which was odd because it had worked fine the past two thousand times (no exaggeration) that I ran the code.      
Something appears to be going on that has adversely impacted my ability to use my code.

**Comment by bsipocz** [comment]
I get a non-empty TableList for this query, so closing this issue now. Please feel free to reopen if you still experience the problem using the latest versions.

```
In [10]: from astroquery.vizier import Vizier

In [11]: STAR_NAME = 'J005620.31+120157.0'

In [12]: field_of_view = 0.001

In [13]: Vizier.query_object(STAR_NAME, radius=field_of_view * u.deg, catalog = 'SDSS12')
Out[13]: 
TableList with 1 tables:
	'0:V/147/sdss12' with 23 column(s) and 1 row(s) 
```
