### ISSUE TITLE
Add bug report issue template

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2297]
I'm not a fan of checklist and templates, and would be very much against doing the checklists core does, but rather like the way how e.g. scikit-learn handles their issues: https://github.com/scikit-learn/scikit-learn/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml

E.g. communicate that a copy pasteable failing example is necessary to do anything with a bug/issue report. So, I think we should do that one, and with the new github boxes it's actually a reasonably good experience compared to the previous filled out issue blobs.

**Comment by keflavich** [comment]
OK I'm on board with trying this.  I agree, though, I really don't like having extra hoops to jump through when I want to file an issue - so let's try it out and, if it's an OK experience for us, let's go ahead with it.  I don't want to scare away issue posting, though - even if we're getting somewhat "noisy" issues some of the time, they usually reflect a real problem with either astroquery, an upstream service, or the workflow or documentation.

**Comment by bsipocz** [comment]
> even if we're getting somewhat "noisy" issues

My bigger problem is with the less noisy ones, where it's already a few back&forth before getting to a copy-pasteable code example or half usable trackeback

**Comment by bsipocz** [comment]
Also, this may be a good tool to communicate that clearing the cache/upgrading the version may solve issues.
