### ISSUE TITLE
MNT: define supported version range for BS4

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2302]
Currently, we only test with the latest release of beautifulsoup, I suppose it wouldn't hurt though to limit it to the version that was current when the oldest supported python version came out. 

I also wonder whether using e.g. pypi-timemachine would be a preferable thing for the oldest dependencies test? E.g we limit versions by date, by default rather than letting CI pick up new versions for the packages where we don't limit version numbers? (E.g. all would be fixed to a date back in the past, except a few cases where our minimal is newer than that date?) 

cc @pllim and @astrofrog whether you think this logic could work well for integration test purposes?

**Comment by pllim** [comment]
I will have to defer to @astrofrog , as I am not familiar with the timemachine. What is the issue that prompted this? Usually bs4 is pretty stable?

**Comment by bsipocz** [comment]
> What is the issue that prompted this?

Being pedantic. There was a PR where the "old" dependency test was failing on a BS4 line (only because that finished the fastest, the rest of the jobs got cancelled after that), but it's not a BS4 issue, nevertheless I checked which version was picked up and was shocked that it's the most recent :)

I just feel if the purpose of the old dependency CI test is the want to cover user setups where they use old versions of stuff, then we better test with old versions of everything to give us a chance to pick up any issues. In practice, we don't really test that old versions anyway, as python can be extremely ancient at places that are stuck with old "stable" servers with some ancient long term OS release and "no update" policies. (python2, and 3.4 is still a thing out there for those stuck on old debians or centOS-es, so we certainly won't cater for all...)

**Comment by pllim** [comment]
Docker image is a way to go if you really want to "freeze" everything. In general, it is a good idea to have minversion and test against it, just the problem is there are too many to keep track of (the infamous "dependency hell"). So, while in principle, I think it is a good idea, I do not have a fool-proof way to do this, except maybe using a Docker image that you can control.

**Comment by bsipocz** [comment]
Yeah, I would like to find a way that's not docker, thus have high hopes for pypi-timemachine. At least I expect it to work quite OK for a simple, pure-python package and dependencies as astroquery.
Anyway, let's see whether Tom has any insight from the integration tests part, maybe something is already working there that could be reused.

**Comment by astrofrog** [comment]
I think it could work nicely - note that you might also be interested in tox-timemachine which uses pypi-timemachine to provide a simple option you pass to tox: https://pypi.org/project/tox-timemachine/

**Comment by bsipocz** [comment]
Oh, sweet, I didn't know about tox-timemachine.

**Comment by astrofrog** [comment]
Note that tox-timemachine also has a bisect option for tracking down causes of failures when upstream packages are updated :)
