### ISSUE TITLE
`radius` kwarg in SkyView.get_images() sets the side length of square not radius

### ISSUE THREAD

**Issue by drtobybrown** [astropy/astroquery#2312]
This is set by the following code
```
if radius is not None:
    size_deg = str(radius.to(u.deg).value)
elif width and height:
    ...
```
I think the easiest fix is to change the kwarg name to size / length / or similar.

**Comment by eerovaher** [comment]
Isn't this a duplicate of #2190?

**Comment by drtobybrown** [comment]
Yes… I should have searched more thoroughly

-- 
Plaskett Fellow
Herzberg Astronomy & Astrophysics Research Centre
National Research Council of Canada
drtobybrown.com <https://drtobybrown.com/>
@drtobybrown <https://twitter.com/DrTobyBrown>
Pronouns: He/him/his

**Comment by bsipocz** [comment]
Closing as duplicate
