### ISSUE TITLE
catalogs.query_object fails for galex

### ISSUE THREAD

**Issue by mbadenas** [astropy/astroquery#2334]
I would like to run this example from the [Reference notes](https://astroquery.readthedocs.io/en/latest/mast/mast.html) using astroquery 0.4.6: 
 
`catalog_data = Catalogs.query_object("158.47924 -7.30962", catalog="Galex")`

but I keep getting the following error: 

 ```
RemoteServiceError: Cannot open database "GR6Plus7" requested by the login. The login failed.
Login failed for user 'webaccess'.
```

Does anyone know how to solve this?

**Comment by keflavich** [comment]
@mbadenas it is helpful if you can provide a full minimal working example when you encounter errors like this.

@ceb8 I can reproduce it:

```python

>>> from astroquery.mast import Catalogs
>>> catalog_data = Catalogs.query_object("158.47924 -7.30962", catalog="Galex")

Traceback (most recent call last):
  File "<ipython-input-35-c19b1e5897ea>", line 1, in <module>
    catalog_data = Catalogs.query_object("158.47924 -7.30962", catalog="Galex")
  File "/home/adam/repos/astroquery/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/adam/repos/astroquery/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "/home/adam/repos/astroquery/astroquery/mast/collections.py", line 53, in _parse_result
    results_table = self._current_connection._parse_result(response, verbose=verbose)
  File "/home/adam/repos/astroquery/astroquery/mast/discovery_portal.py", line 291, in _parse_result
    raise RemoteServiceError(result.get('msg', "There was an error with your request."))
RemoteServiceError: Cannot open database "GR6Plus7" requested by the login. The login failed.
Login failed for user 'webaccess'.

```

**Comment by bsipocz** [comment]
It all works for me without issue, and the doctests also pass without issues. Could you try and clear the cache and retry?

**Comment by keflavich** [comment]
I confirm that the problem doesn't recur (I didn't even clear the cache).  I'm going to mark this as upstream & solved.

**Comment by keflavich** [comment]
@mbadenas could you try again and confirm that it works now?  It looks like this was a temporary server issue.

**Comment by mbadenas** [comment]
@keflavich it works well now! The MAST API to the GALEX catalog must have been down temporarily. 

Thank you very much everyone for helping with this problem!
