### ISSUE TITLE
contribution idea: Planetary Ring Node

### ISSUE THREAD

**Issue by emolter** [astropy/astroquery#2356]
Hi there,

I'd like to add the functionality to query the ephemeris tools in SETI's [Planetary Ring Node](https://pds-rings.seti.org/tools/).  This would be useful because the Horizons query tool does not provide ephemeris information on rings like the opening angle, periapsis, or ascending node, and it's helpful in my research to be able to quickly find this information.  I read the contributing guidelines and it looks like everything I want to do can be implemented straightforwardly with the Astroquery tools.

Would this contribution be of interest?

Thanks very much for your response,
Ned

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by bsipocz** [comment]
@emolter - I'm not familiar with this science field to know how many potential users would be for such a module, but @mkelley, the maintainer of the solarsystem modules may be able to comment on it. 
I see no reasons why this could not be a submodule under `astroquery.solarsystem`, maybe an `astroquery.solarsystem.pds`?

**Comment by emolter** [comment]
Thanks @bsipocz !  I went ahead and started building this.  I submitted a draft pull request [here](https://github.com/astropy/astroquery/pull/2358).  At this stage I have a minimum working example written that can make and parse a basic query and return the relevant data as astropy tables.  I tested it for each of the six ring systems in the solar system.

I read the astroquery [API specification page](https://astroquery.readthedocs.io/en/latest/api.html) and the [contributing guidelines](https://github.com/astropy/astroquery/blob/main/CONTRIBUTING.rst), but I still have a few questions about how exactly various things should be implemented to fit best into astroquery style.  What is the best avenue to get those questions answered?

**Comment by bsipocz** [comment]
>  but I still have a few questions about how exactly various things should be implemented to fit best into astroquery style. What is the best avenue to get those questions answered?

If you would leave comments on the PR code, I think that would be the best way to start those discussions

**Comment by mkelley** [comment]
Addressed in #2358
