### ISSUE TITLE
Failing ESA remote tests

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2359]
Some tests are failing due to relatively recent changes to the default file saving mechanism in tapplus. Some of this were discussed already in the relevant PR, but I'm opening this issue so the problem is not hidden in a  merged PR: https://github.com/astropy/astroquery/pull/2311#issuecomment-1081441659

I don't think the PR introduced any issues for the users, nevertheless, the tests should be fixed. To reproduce the failures:

``python setup.py test -P esa,esasky,gaia,utils.tap -R``

cc @jespinosaar 

related issues for tracking remote failures: #2203

**Comment by jespinosaar** [comment]
cc @esdc-esac-esa-int
