### ISSUE TITLE
Update SDSS to Prominently Feature DR17

### ISSUE THREAD

**Issue by jsobeck** [astropy/astroquery#2365]
Would it be possible to update the astroquery sdss module to default to the most recent data release of SDSS, DR17.  The main change should occur here: https://github.com/astropy/astroquery/blob/main/astroquery/sdss/__init__.py. I could do a quick PR for this (and it could merged with admin approval).  Thank you for your help.

**Comment by bsipocz** [comment]
I would be OK with changing the default, but paging the others, here, too. Let's wait for their input before you open a PR.

@weaverba137 @keflavich - would you prefer to change the default? This would certainly mean necessary changes to the docs and tests, so certainly is a bit more involved than changing the int in the init.

**Comment by keflavich** [comment]
I have no objection.  Is DR17 inclusive of previous data releases?  If so, it seems that it would make the most sense to update to the latest when it's available.

**Comment by jsobeck** [comment]
The answer to this question is yes (but there is some nuance).  The final acquisition of imaging data occurred in 2009 while the final spectroscopic data were taken in 2021.  DR17 is inclusive of all spectroscopic data from SDSS (see the publicly accessible site here: https://data.sdss.org/sas/dr17/).  The DR17 release also contains all prior imaging data (see https://www.sdss.org/dr17/imaging/; note that the imaging data were frozen in an earlier release). The SAS and Skyserver sites, which serve as access points for astroquery, appropriately direct users.

**Comment by weaverba137** [comment]
I second what @jsobeck said.  I am available to assist & review as needed.

**Comment by bsipocz** [comment]
@jsobeck - that sounds like a good plan. Please do run the remote tests for the module, too to  make sure all those are fixed in the PR, as CI is not running them: `python setup.py -P sdss -R`

**Comment by weaverba137** [comment]
I suggest incorporating changes from #2477, unless a PR for this has already been submitted?

**Comment by bsipocz** [comment]
There is no PR open yet, so please feel free to go ahead and include this in #2477.

**Comment by jsobeck** [comment]
Hi Ben,

I want to do the PR, but wanted to make sure that I was following
appropriate guidelines/etiquette.

Sorry to be so timid on this (and maybe I will ping you on Slack),
Jen
<< On Maternity Leave through first week of March 2022>>
<<MWF availability through Summer 2022>>
Jennifer Sobeck, Ph.D.
System Scientist
Maunakea Spectroscopic Explorer
CFH Corporation
