### ISSUE TITLE
JPL SBDB query fails when returned properties have complex units with exponential involved

### ISSUE THREAD

**Issue by jianyangli** [astropy/astroquery#2368]
For the objects that have properties that involve complex units, such as asteroid Bennu which has density and thermal inertia etc. to be returned, `SBDB` reports an error because the exponential in the units uses '^' rather than '**'.

```
from astroquery.jplsbdb import SBDB
sbdb = SBDB.query('bennu', phys=True)
```

Also it looks like `astropy.units.Unit` doesn't recognize decimal points when it's in the exponential.  The decimal point has to be put inside a pair of parentheses.  While this is an `astropy` issue, it affects how `SBDB` would parse units.

```
import astropy.units as u
print(u.Unit('m**(0.5)'))
print(u.Unit('m**0.5'))
```

astroquery==0.4.7.dev7713

**Comment by bsipocz** [comment]
Thanks for the report. Could you please open a separate one for astropy, too about the unit parsing? We keep this one to track the sbdb specific part.

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by jianyangli** [comment]
Just submitted the issue to astropy.
https://github.com/astropy/astropy/issues/13127
Thank.

**Comment by jianyangli** [comment]
The unit parsing error in `astropy` wasn't a bug.  Adding `format='ogip'` to `u.Unit` would solve the problem.  The related astropy issue has been closed.
