### ISSUE TITLE
Catalog not available for XMatch

### ISSUE THREAD

**Issue by prajwel** [astropy/astroquery#2393]
Hi,

I am trying to use the following catalogue in XMatch: https://vizier.u-strasbg.fr/viz-bin/VizieR-3?-source=V/154&-out.max=50&-out.form=HTML%20Table&-out.add=_r&-out.add=_RAJ,_DEJ&-sort=_r&-oc.form=sexa

When I try, `XMatch.is_table_available('vizier:V/154/sdss16')`, the output is `False`. 

Perhaps I am doing it wrong. Could you please let me know the correct way to access the catalogue? Thank you.

**Comment by bsipocz** [comment]
Not sure what goes wrong for you, I cannot reproduce the issue

```
In [2]: XMatch.is_table_available('vizier:V/154/sdss16')
Out[2]: True
```

Do try to clean the cache, by default it's located at `~/.astropy/cache/astroquery`.

**Comment by prajwel** [comment]
Thank you, the cache is the problem. My current one looks like this. 
```Python
matching = [s for s in XMatch.get_available_tables() if "sdss" in s]
matching
```
```
['j/apj/749/10/sdss-obs',
 'J/ApJ/907/123/sdss_sz',
 'j/apj/907/123/sdss_sz',
 'V/147/sdss12',
 'v/147/sdss12',
 'II/294/sdss7',
 'ii/294/sdss7',
 'J/PAZh/44/124/sdss-bc',
 'j/pazh/44/124/sdss-bc',
 'J/AJ/143/52/sdss_cl',
 'j/aj/143/52/sdss_cl',
 'V/139/sdss9',
 'v/139/sdss9',
 'J/A+A/597/A134/psb_sdss',
 'j/a+a/597/a134/psb_sdss',
 'sdss7',
 'J/A+A/569/A124/guv_sdss',
 'j/a+a/569/a124/guv_sdss',
 'J/MNRAS/406/1595/sdssh',
 'j/mnras/406/1595/sdssh',
 'J/PAZh/44/124/sasdssbc',
 'j/pazh/44/124/sasdssbc',
 'II/306/sdss8',
 'ii/306/sdss8',
 'J/ApJ/699/800/sdss',
 'j/apj/699/800/sdss',
 'J/MNRAS/482/4570/gaiasdss',
 'j/mnras/482/4570/gaiasdss',
 'J/A+A/544/A81/snsdss',
 'j/a+a/544/a81/snsdss'] 
```

**Comment by prajwel** [comment]
@bsipocz Is it a good idea to change the default `cache=True` to `cache=False` for XMatchClass functions? Maybe it's just me, but I got confused by the errors and spent some time figuring out what went wrong. 😄

**Comment by bsipocz** [comment]
I don't think it's a good idea to change the defaults, in the big picture having the cache is more useful than harmful, but unfortunately, there are a few issues that have to be addressed, including getting the cache timeout (we have some draft PRs for that). 

I'll add a section to the opening page of the docs for troubleshooting, add will add the "clean you cache" as one of the tips.
