### ISSUE TITLE
BUG: alma ignores timeout

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2405]
The remote tests timeout in the alma module after running for hours (locally it's all good) which highlights the issue that the timeout configitem is not used in the module.

Having a functional timeout would be useful beyond the test suite.

cc @andamian

**Comment by andamian** [comment]
Not sure this is relevant anymore although some tests are taking longer than they should. More importantly at the moment is that some of them are failing and for good reasons: a change to the PI column and a server side overflow on field concatenation. We'll follow those first and when they pass again we'll look if the timeout issue is still relevant or not.

**Comment by bsipocz** [comment]
Yes, I think I haven't seen this particular issue for a while now, so I'm closing this. If I see stalled test runs, I'll reopen and we can investigate further.
