### ISSUE TITLE
MPC observatory codes not updated

### ISSUE THREAD

**Issue by ziriuz84** [astropy/astroquery#2412]
I'm using Astropy 5.0.4 and Astroquery 0.4.6. It seems that Observatory codes are not updated. In my city we have 4 observatory codes. The oldest ones (126 and K78) are working well, the newer ones (M16 and M17) return this error
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sirio/Progetti/asteroidpy/env/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/sirio/Progetti/asteroidpy/env/lib/python3.8/site-packages/astroquery/mpc/core.py", line 714, in get_observatory_location
    raise LookupError('{} not found'.format(code))
LookupError: M16 not found`

I searched newer observatory codes in Obscode.html on MPC site and they are present

**Comment by bsipocz** [comment]
I'm afk so can't test this right now, but my first suggestion would be to try and clean the cache (default is ~.astropy/cache/astroquery, you delete that directory as is)

**Comment by ziriuz84** [comment]
Ok, it worked, thanks a lot. There's an automatic process to delete cache that is too old or once that obscode are downloaded they will never be updated on the pc?

**Comment by bsipocz** [comment]
Some improvements to the caching infra is in the works indeed, hopefully it will resolve cases like this.
