### ISSUE TITLE
ENH: make remote tests more roboust by rerunning them

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2424]
In the latest cron remote-data test run there have been a couple of timeouts and other temporary fluke-looking failures (e.g. I don't see the failing vo_conesearch, sdss). 

So a way to rerun just the failing set of tests would be extremely useful for us. It would be great if there would be a purpose pytest plugin for it, if not we may need to parse the name of the individual tests from the output of the first run.

**Comment by bsipocz** [comment]
E.g. rerunning the cron job that run yesterday resulted in 9 fewer tests failing.

**Comment by Cadair** [comment]
Sunpy uses this iirc https://pypi.org/project/pytest-rerunfailures/
