### ISSUE TITLE
Gaia archive is offline until the 13th of June

### ISSUE THREAD

**Issue by juramaga** [astropy/astroquery#2433]
Hi, I am attempting a simple cone search of the Gaia archive:

`import astropy.units as u
from astropy.coordinates import SkyCoord
from astroquery.gaia import Gaia

coord = SkyCoord(ra=280, dec=-60, unit=(u.degree, u.degree), frame='icrs')
width = u.Quantity(0.1, u.deg)
height = u.Quantity(0.1, u.deg)
r = Gaia.query_object_async(coordinate=coord, width=width, height=height)`

But I am getting the following error (I am using astroquery version 0.4.5):

> ---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Input In [12], in <cell line: 8>()
      6 width = u.Quantity(0.1, u.deg)
      7 height = u.Quantity(0.1, u.deg)
----> 8 r = Gaia.query_object_async(coordinate=coord, width=width, height=height)
     10 r.pprint(max_lines=12, max_width=130)

File ~/opt/anaconda3/envs/ciao-4.14/lib/python3.8/site-packages/astroquery/gaia/core.py:487, in GaiaClass.query_object_async(self, coordinate, radius, width, height, verbose, columns)
    463 def query_object_async(self, coordinate, radius=None, width=None,
    464                        height=None, verbose=False, columns=[]):
    465     """Launches a job (async)
    466     TAP & TAP+
    467 
   (...)
    485     The job results (astropy.table).
    486     """
--> 487     return self.__query_object(coordinate, radius, width, height, async_job=True, verbose=verbose, columns=columns)

File ~/opt/anaconda3/envs/ciao-4.14/lib/python3.8/site-packages/astroquery/gaia/core.py:432, in GaiaClass.__query_object(self, coordinate, radius, width, height, async_job, verbose, columns)
    404 query = """
    405         SELECT
    406           {row_limit}
   (...)
    429                       'columns': columns, 'table_name': self.MAIN_GAIA_TABLE or conf.MAIN_GAIA_TABLE, 'ra': ra, 'dec': dec,
    430                       'width': widthDeg.value, 'height': heightDeg.value})
    431 if async_job:
--> 432     job = self.launch_job_async(query, verbose=verbose)
    433 else:
    434     job = self.launch_job(query, verbose=verbose)

File ~/opt/anaconda3/envs/ciao-4.14/lib/python3.8/site-packages/astroquery/gaia/core.py:892, in GaiaClass.launch_job_async(self, query, name, output_file, output_format, verbose, dump_to_file, background, upload_resource, upload_table_name, autorun)
    853 def launch_job_async(self, query, name=None, output_file=None,
    854                      output_format="votable", verbose=False,
    855                      dump_to_file=False, background=False,
    856                      upload_resource=None, upload_table_name=None,
    857                      autorun=True):
    858     """Launches an asynchronous job
    859 
    860     Parameters
   (...)
    890     A Job object
    891     """
--> 892     return TapPlus.launch_job_async(self, query=query,
    893                                     name=name,
    894                                     output_file=output_file,
    895                                     output_format=output_format,
    896                                     verbose=verbose,
    897                                     dump_to_file=dump_to_file,
    898                                     background=background,
    899                                     upload_resource=upload_resource,
    900                                     upload_table_name=upload_table_name,
    901                                     autorun=autorun)

File ~/opt/anaconda3/envs/ciao-4.14/lib/python3.8/site-packages/astroquery/utils/tap/core.py:432, in Tap.launch_job_async(self, query, name, output_file, output_format, verbose, dump_to_file, background, upload_resource, upload_table_name, autorun)
    429             print(f"Saving error to: {suitableOutputFile}")
    430         self.__connHandler.dump_to_file(suitableOutputFile,
    431                                         response)
--> 432     raise requests.exceptions.HTTPError(response.reason)
    433 else:
    434     location = self.__connHandler.find_header(
    435         response.getheaders(),
    436         "location")

HTTPError: OK

**Comment by eerovaher** [comment]
The Gaia archive is offline until the 13th of June in preparation for Data Release 3, see https://gea.esac.esa.int/archive/ There isn't anything `astroquery` can do about that.

**Comment by juramaga** [comment]
Ok Thanks. I had started to suspect that since I could not load Gaia data in ESASky either.

**Comment by bsipocz** [comment]
DR3 is out, so I'm closing this issue now.
