### ISSUE TITLE
Query of Horizon has a Key Error : KeyError: 'Azimuth_(a-app)'

### ISSUE THREAD

**Issue by dcazeneuve** [astropy/astroquery#2434]
Running the following line of code, using SORA-astro, on a AWS cloud server, with ARM infrastructure and running on Debian, return an error. This does not happen when using a laptop for the exact same line of code.

```
from sora.body import *

asteroid = Body(name='Peraga', spkid=554, orbit_class='asteroid',ephem='horizons')
```
The error:
```
~/.venvs/3.7/lib/python3.7/site-packages/astroquery/jplhorizons/core.py in _parse_horizons(self, src)
   1257         rename = []
   1258         for col in data.columns:
-> 1259             data[col].unit = column_defs[col][1]
   1260             if data[col].name != column_defs[col][0]:
   1261                 rename.append(data[col].name)

KeyError: 'Azimuth_(a-app)'
```

**Comment by mkelley** [comment]
What version of astroquery is this on your AWS instance and the laptop?  I suspect it just needs to be updated (I'm looking at v0.4.6 and the line numbers are slightly different than you show here), but maybe the problem is elsewhere.

**Comment by dcazeneuve** [comment]
You are right. When I did `pip install --pre astroquery[all]`, I thought it would install the latest astroquery. 
To obtain the latest version, I used ` pip install --pre astroquery[all] --upgrade` as said in the documentation.

**Comment by bsipocz** [comment]
@dcazeneuve - I take your response as the upgrade actually fixed the issue. If that's not the case, please feel free to reopen. Thanks!
