### ISSUE TITLE
DALQueryError: Failed to obtain JDBC Connection; nested exception is java.sql.SQLRecoverableException: Listener refused the connection with the following error:

### ISSUE THREAD

**Issue by mjastro** [astropy/astroquery#2437]
Hi,

 I am getting the following error message when I try to do an ALMA query for a test (I believe I am using the latest version: '0.4.7.dev7761')
 I wonder whether this is an issue on my end or anything else. 

 Thanks for any help that you could offer!

When I type the following:
`rslt = Alma.query(payload=dict(pi_name='Ginsburg, Adam'))`

The terminal gives me: 

> DALQueryError: Failed to obtain JDBC Connection; nested exception is java.sql.SQLRecoverableException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
  Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
  Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor

**Comment by keflavich** [comment]
I don't see this error.   It might have been a temporary issue?  Which server were you connecting to?
```
>>> Alma.dataarchive_url
'https://almascience.nrao.edu/'
```
You could change that to ESO/Japan/NRAO and see if the problem persists.

**Comment by mjastro** [comment]
Thanks, yes it seems to be a temporary issue - I was using the ESO server. 
When I get this issue again, I will try to change the server.

Thanks again!
