### ISSUE TITLE
UCD keyword as an attribute for columns in Vizier search

### ISSUE THREAD

**Issue by alessandropeca** [astropy/astroquery#2471]
It would be nice to see the `ucd` keyword for each column of a catalog when querying. For example, doing something like:

```
from astroquery.vizier import Vizier
cat_name = "J/A+A/528/A122/xrtcat"
cat = Vizier(columns=['**'], row_limit=-1).get_catalogs(cat_name) 
cat = cat[0] 
print(cat0.info)
```

It returns column names with all the info like name, type, unit, etc... But it does not return the `ucd` keywords. Since they are standard, it would be nice to have the `ucd` keyword for each column, so that one could look for specific quantities.

Is that already possible in some way?

**Comment by keflavich** [comment]
Yes!  The full votable is parsed by astropy and stored in the metadata of each column.  For example, in your case:

```python
>>> cat['Xpos'].meta['ucd']
'POS_CCD_X'
```

**Comment by alessandropeca** [comment]
> Yes! The full votable is parsed by astropy and stored in the metadata of each column. For example, in your case:
> 
> ```python
> >>> cat['Xpos'].meta['ucd']
> 'POS_CCD_X'
> ```

Wonderful! That's what I needed thank you!
