### ISSUE TITLE
UKIDSS catalog query fails for non-public data

### ISSUE THREAD

**Issue by eztean** [astropy/astroquery#250]
Hi Adam & Tom,
I'm testing UKIDSS queries with the new version of astroquery, and it seems that there's a problem for non-public data. The following example

```
    from astropy.coordinates import Galactic
    from astropy import units as u
    from astroquery.ukidss import Ukidss
    u_obj = Ukidss(username='xxx', password='xxx', community='xxx')
    cat = u_obj.query_region(Galactic(l=10.625, b=-0.38,  
                 unit=(u.deg, u.deg)),radius=6 * u.arcsec, 
                 database='UKIDSSDR8PLUS', programme_id='GPS')
```

returns the error `InvalidQueryError: Service returned with an error!` within the function `_check_page()`. I notice that the result of the query (it can be seen in `response.content`) is the same as if I were not logged in, so for some reason the query is not identifying the login. Using DR7 instead, the query works:

```
    cat = u_obj.query_region(Galactic(l=10.625, b=-0.38,  
                 unit=(u.deg, u.deg)),radius=6 * u.arcsec, 
                 database='UKIDSSDR7PLUS', programme_id='GPS')
```

By the way, maybe this is not related, but if I set the `database = 'UKIDSSDR8PLUS'`, when initializing the object `u_obj`, and then i don't use the `database` keyword in `query_region`, the database is automatically set to the default `UKIDSSDR7PLUS`, which I assume is not desired.

**Comment by bsipocz** [comment]
``The original UKIDSS project is now complete, and all the data is public``

Therefore I'm closing this issue.
