### ISSUE TITLE
DOC: restructure mast docs to be quicker

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2505]
This is somewhat a bittersweet issue, as the docs grow as large that testing the mast documentation currently takes a very long time, 15 minutes in the latest cron job. 
I would love to see if there are any ways to cut back with e.g. selecting other, much smaller datasets and queries for the examples, etc.
If there are no ways to cut back, then it would be great to just docs that in this issue, so we know it's been checked, etc.

cc @jaymedina @tomdonaldson

**Comment by bsipocz** [comment]
Oh, and the 15min is into the middle of the docs as it got stopped at an actual doctest failure (as the defaults for invalid/missing data has been changed from `--` to `-99.0`). So now I flag it as an actual bug, and am unsure about the total timing (whether the double running by pytest-rerunfailures would result in a double time or not, either case even the 7.5 mins would be a bit long and thus would be awesome to be cut back on).

**Comment by jaymedina** [comment]
We were actually discussing doing a documentation overhaul for `astroquery.mast` so we will definitely keep optimization in mind. I'll make sure to add this issue to my ticket.

**Comment by bsipocz** [comment]
@snbianco has done a good job in #3122 and now testing the docs is done in 4.5 minutes on my network. So I'll mark this fixed when merging that PR, but obviously, any more reactors that trim the timing while not taking away useful information from the docs are always welcome!
