### ISSUE TITLE
BUG: MPC no results for some named asteroids

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2531]
These are examples from the test suite that used to work. cc @mkelley. 
I think this is a separate issue from #2466

```
In [9]: MPC.query_object(target_type='asteroid', name='vesta')
Out[9]: []

In [10]: MPC.query_object(target_type='asteroid', name='pallas')
Out[10]: []

In [11]: MPC.query_object(target_type='asteroid', name='ceres')
Out[11]: 
[{'absolute_magnitude': '3.33',
  'aphelion_distance': '2.983',
  'arc_length': 80743,
  'argument_of_perihelion': '73.63703',
  'ascending_node': '80.2685812',
  'critical_list_numbered_object': False,
  'delta_v': 10.5,
  'designation': None,
  'earth_moid': 1.58476,
  'eccentricity': '0.078501',
  'epoch': '2022-01-21.0',
  'epoch_jd': '2459600.5',
  'first_observation_date_used': '1801-01-02.0',
  'first_opposition_used': '1801',
  'inclination': '10.58769',
  'jupiter_moid': 2.09089,
  'km_neo': False,
  'last_observation_date_used': '2022-01-26.0',
  'last_opposition_used': '2022',
  'mars_moid': 0.93083,
  'mean_anomaly': '291.37566',
  'mean_daily_motion': '0.2142473',
  'mercury_moid': 2.17533,
  'name': 'Ceres',
  'neo': False,
  'number': 1,
  'observations': 7372,
  'oppositions': 122,
  'orbit_type': 0,
  'orbit_uncertainty': '0',
  'p_vector_x': '-0.88197013',
  'p_vector_y': '0.3308949',
  'p_vector_z': '0.33561474',
  'perihelion_date': '2022-12-07.30429',
  'perihelion_date_jd': '2459920.8043',
  'perihelion_distance': '2.5489058',
  'period': '4.6',
  'pha': False,
  'phase_slope': '0.15',
  'q_vector_x': '-0.43512388',
  'q_vector_y': '-0.84529791',
  'q_vector_z': '-0.31006235',
  'residual_rms': '0.64',
  'saturn_moid': 6.36519,
  'semimajor_axis': '2.76604',
  'tisserand_jupiter': 3.3,
  'updated_at': '2022-06-02T15:52:39Z',
  'uranus_moid': 15.8905,
  'venus_moid': 1.8372}]
```

**Comment by bsipocz** [comment]
Note that the test was tried to be worked around in https://github.com/astropy/astroquery/pull/2526/files#r969995161, nevertheless I still see it failing locally.

**Comment by bsipocz** [comment]
This seems to be an upstream problem, as I see empty returns directly on the server, too:

https://minorplanetcenter.net/web_service/search_orbits?name=Vesta
https://minorplanetcenter.net/web_service/search_orbits?name=Eros
https://minorplanetcenter.net/web_service/search_orbits?name=Pallas

vs 

https://minorplanetcenter.net/web_service/search_orbits?name=Ceres


cc @mkelley - who would you think to be a good person to ping about this at MPC? Could you please report this?

**Comment by mkelley** [comment]
I can confirm that it isn't working with those examples, but is working for Ceres.  I've opened a help desk ticket on this.

**Comment by bsipocz** [comment]
I've tried a few others and they worked, so far it's only Vesta, Pallas, and Eros that are but working. 

Anyway, thanks for reporting it upstream.

**Comment by mkelley** [comment]
They have fixed the issue upstream.

**Comment by bsipocz** [comment]
> They have fixed the issue upstream.

wonderful, thank you!
