### ISSUE TITLE
DOC: Esasky to cut back download for documentation

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2552]
There is some repetition in the esasky docs, and while I try to finish up #1971, the doctest already runs for 10+ minutes and downloads 1G+ data. Both should ideally be cut back. 

cc @imbasimba

**Comment by imbasimba** [comment]
Wow! Yeah, these docs were not designed with limited data useage in mind. I'll allocate some time later in the week or next week to see if I can update the examples to download fewer and smaller files.

**Comment by bsipocz** [comment]
Thanks. It's somewhat contradictional to cut back on documentation, but I like to think that it's very valuable to be able to run the actual snippets we have in there, thus the tradeback.

Also, this is not at all urgent, and let me just finish up enabling the doctesting on the current one, I'm almost ready, but it slowed down now that I'm more than halfway through as I'm waiting for the test to run :)

**Comment by imbasimba** [comment]
Agreed :)

**Comment by imbasimba** [comment]
I had to deal with new high priority tasks there for a while, but I finally got around to improve the docs: https://github.com/astropy/astroquery/pull/2614

**Comment by bsipocz** [comment]
Got addressed, I just forgot to cross-link. Thanks again!
