### ISSUE TITLE
DOC: alma.get_data_info() function does not take 'obs_id' argument

### ISSUE THREAD

**Issue by Toma-Bad** [astropy/astroquery#2553]
Hi all,

The example from [https://astroquery.readthedocs.io/en/latest/alma/alma.html#downloading-fits-data](https://astroquery.readthedocs.io/en/latest/alma/alma.html#downloading-fits-data) does not work. The **alma.get_data_info** function takes as argument strings in the **'member_ous_uid'** column in the results table, the example on the provided link shows the function taking as argument strings from the **'obs_id'** column in the results table. If using the example provided at the link, the following error is returned:

`WARNING: Error accessing info about file : NotFoundFault: uid://A001/X8a9/X2c.source.S255_NIRS3.spw.25 [astroquery.alma.core]`

This was done using astroquery version 0.4.7.dev8076
All the best,
Toma

**Comment by bsipocz** [comment]
cc @keflavich @andamian - could you have a look at the example, something goes wrong already in L8, and thus `uid_url_table` is empty.

**Comment by keflavich** [comment]
I can reproduce the error.  The example should be modified to:
```python
uid_url_table = alma.get_data_info(result['member_ous_uid'][0])
```
I'll push a fix
