### ISSUE TITLE
TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by iHD992** [astropy/astroquery#2572]
When sending big querys to the gaia database, I get a timeout error. Is there a workaround?

Example code:
```
from astroquery.gaia import Gaia

Gaia.MAIN_GAIA_TABLE = "gaiadr3.gaia_source"

query = "select L, B, parallax, parallax_over_error, mass_flame, age_flame from gaiadr3.gaia_source inner join gaiadr3.astrophysical_parameters using (source_id) where age_flame is not null"

job = Gaia.launch_job_async(query, dump_to_file=True, output_format='csv')# 

file = job.outputFile
print(file)
```

**Comment by callous4567** [comment]
If you make an account and log in, the query time-out for asyncs goes from 90 minutes to 120- a paltry increase but might be worth a shot. Alternatively, it might also be worth making an account for the following reason: the number of rows you can get is limited if you aren't logged in, which your example code doesn't seem to imply as being the case. 

See the Gaia/Cosmos FAQ. If you make an account and log in for the query, you can get as many rows as you like (though there is still a timeout for the query- 2 hours I believe.) I'm unsure as to whether that might fix your issue- it might though. 

Alternatively, you could also try to split your query into parts. If the table made from the "age_flame is not null" fits into your user space, you can first extract that, and then join that to gaia_source in a second query. 

That's all I can say- I'm not that good with Astroquery but hopefully it gives some food for thought. Try making a login!

**Comment by iHD992** [comment]
Logging in solved the problem, Thanks.
