### ISSUE TITLE
NASA Exoplanet Archive - Microlensing tabl

### ISSUE THREAD

**Issue by rpoleski** [astropy/astroquery#2573]
Hi,

Can we add Microlensing table from [NASA Exoplanet Archive](https://exoplanetarchive.ipac.caltech.edu/)? There is `astropy/astroquery/tree/main/astroquery/ipac/nexsci` but it contains only Planetary Systems table. Myself and @maksicel can translate column names, but we don't have experience with how astroquery is written. Can someone help us?

**Comment by bsipocz** [comment]
Have you checked the examples in https://astroquery.readthedocs.io/en/latest/ipac/nexsci/nasa_exoplanet_archive.html? there is one microlensing one.

**Comment by rpoleski** [comment]
Yes, we have. This example is querying main table for planets found using microlensing method. The [Microlensing table](https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=ML&constraint=ml_modeldef=1) has different columns and a few records per planet.

**Comment by rickynilsson** [comment]
@rpoleski - the Microlensing table can be accessed by for example:
```
from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive
NasaExoplanetArchive.query_criteria(table='ml')
```

For a list of tables that can currently be queried, you can check the `TAP_TABLES` attribute:
```
NasaExoplanetArchive.TAP_TABLES
['superwasptimeseries',
 'kelttimeseries',
 'transitspec',
 'emissionspec',
 'ps',
 'pscomppars',
 'keplernames',
 'k2names',
 'ukirttimeseries',
 'ml',
 'object_aliases',
 'k2pandc']

```

**Comment by bsipocz** [comment]
Maybe an example for the docs would be useful about `TAP_TABLES`?

**Comment by rickynilsson** [comment]
Yes, I agree @bsipocz, I can add that.

**Comment by rpoleski** [comment]
Ok, thanks @rickynilsson.
I was able to find [`query_object()` documentation](https://astroquery.readthedocs.io/en/latest/api/astroquery.ipac.nexsci.nasa_exoplanet_archive.NasaExoplanetArchiveClass.html#astroquery.ipac.nexsci.nasa_exoplanet_archive.NasaExoplanetArchiveClass.query_object), which says 

```
table : ["ps" or "pscomppars"], optional
```

which for me means that only these two options are available. There is also no documentation for `TAP_TABLES`.
