### ISSUE TITLE
ESA JWST remote test failues

### ISSUE THREAD

**Issue by ceb8** [astropy/astroquery#2590]
Three exception tests in `astroquery/esa/jwst/tests/test_jwsttap.py` (function `test_query_target_error`) are failing because the exception returned is not the expected exception. I have verified that when performing the test manually I do get the expected exception.

**Comment by jespinosaar** [comment]
I can take care of this, thanks for noticing @ceb8 !
@esdc-esac-esa-int

**Comment by jespinosaar** [comment]
It has been fixed in PR #2597
