### ISSUE TITLE
MAINT: delete outdated gh-pages branch

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2592]
The redirect from astroquery.astropy.org is now working and pointing to the RTD, and I turned of the pages in the settings of this repo, too.

I would suggest deleting the branch as is, too.

cc @keflavich

**Comment by keflavich** [comment]
Agreed.   Should I do that?

**Comment by bsipocz** [comment]
Sure, I just didn't want to do it without you knowing about it.

**Comment by keflavich** [comment]
Done.  Verify that it's gone, then we can close this?
