### ISSUE TITLE
Topographic position disallowed in vectors query but would be useful for tracking

### ISSUE THREAD

**Issue by earthshrink** [astropy/astroquery#2599]
With these example definitions
```
DSN_goldstone = '257@399'
SSN_millstone = {'lon':-71.490967, 'lat':42.617442, 'elevation':0.127}
epochs = {'start': '1998-01-23 06:00:00', 'stop': '1998-01-23 12:00:00', 'step': '1m'}
spacecraft='NEAR'
```
the call `Horizons(id=spacecraft, location=DSN_goldstone, epochs=epochs).vectors()` returns topocentric range and range rate representative of Doppler tracking from DSN Goldstone in this case. The equivalent call `Horizons(id=spacecraft, location=SSN_millstone, epochs=epochs).vectors()`, to compare radar range from MIT's Haystack is refused with `ValueError: cannot use topographic position in statevectors query`, solely because of its location argument format.

This seems inconsistent, and perhaps the first query should be also blocked for violating the spirit of the vectors query. However, I feel the Horizons topocentric range and range rate would be a reliable reference for cross-checking radar or telemetry tracking of satellites.

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by mkelley** [comment]
Sorry for the delay while I'm on travel, and will be through the rest of the week.  I have not looked at Horizons in detail about this, but I think this second call should be possible with Horizons's SITE_COORD parameter, right?  In other words, this is a limitation of astroquery not Horizons.  If so, I don't think this is difficult to fix, just as long as it is covered with a good test case.

**Comment by earthshrink** [comment]
That's correct. Please see [near_millstone.q](https://github.com/earthshrink/flyby-analysis/blob/master/near/near_millstone.q) for my working query for the Millstone radar example above, and [query.py]( https://github.com/earthshrink/flyby-analysis/blob/master/bin/query.py) for the script that runs it and outputs to a `csv` file.
The danger is that astroquery `vectors()` without the site prefix (257 for DSS 25 at Goldstone) obtains geocentric data, whereas the site prefix and site coord return topocentric. Users may need to be advised not to mix the two kinds of data.

**Comment by m-stclair** [comment]
#2625 will address this issue
