### ISSUE TITLE
BUG: deprecation is not working properly of astroquery.ned

### ISSUE THREAD

**Issue by mjibrown** [astropy/astroquery#2621]
When I run Ned.query_region on 2MASX J09121949-2410213 I get an error message ModuleNotFoundError: No module named 'astroquery.ned.core'. I can successfully run the code on other galaxies but then it fails on this particular galaxy (which I can find successfully via the web interface). 

The code and errors follow.

import numpy as np
import astropy
import astroquery
import gc
from astropy import units as u

from astroquery.ned import Ned

gc.enable()

result_table = Ned.query_region('NGC 1316', radius=0.002 * u.deg)
print(result_table)

result_table = Ned.query_region('2MASX J03224178-3712295', radius=0.002 * u.deg)
print(result_table)

result_table = Ned.query_region('2MASX J09121949-2410213', radius=0.002 * u.deg)
print(result_table)

ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/3j/hzyn188n7v1cg171vg7tcghhf63ztm/T/ipykernel_70119/248764035.py in <module>
      5 print(result_table)
      6 
----> 7 result_table = Ned.query_region('2MASX J09121949-2410213', radius=0.002 * u.deg)
      8 print(result_table)
      9 

~/opt/anaconda3/lib/python3.9/site-packages/astroquery/ipac/ned/core.py in query_region(self, coordinates, radius, equinox, get_query_payload, verbose)
    137         """
    138         # for NED's object near name/ near region
--> 139         response = self.query_region_async(coordinates, radius=radius,
    140                                            equinox=equinox,
    141                                            get_query_payload=get_query_payload)

~/opt/anaconda3/lib/python3.9/site-packages/astroquery/ipac/ned/core.py in query_region_async(self, coordinates, radius, equinox, get_query_payload)
    203         if get_query_payload:
    204             return request_payload
--> 205         response = self._request("GET", url=Ned.OBJ_SEARCH_URL,
    206                                  params=request_payload, timeout=Ned.TIMEOUT)
    207         return response

~/opt/anaconda3/lib/python3.9/site-packages/astroquery/query.py in _request(self, method, url, params, data, headers, files, save, savedir, timeout, cache, stream, auth, continuation, verify, allow_redirects, json, return_response_on_save)
    313                                              json=json)
    314             else:
--> 315                 response = query.from_cache(self.cache_location)
    316                 if not response:
    317                     response = query.request(self._session,

~/opt/anaconda3/lib/python3.9/site-packages/astroquery/query.py in from_cache(self, cache_location)
    112         try:
    113             with open(request_file, "rb") as f:
--> 114                 response = pickle.load(f)
    115             if not isinstance(response, requests.Response):
    116                 response = None

ModuleNotFoundError: No module named 'astroquery.ned.core'

**Comment by bsipocz** [comment]
This is unexpected, thanks of reporting. 

The namespace got restructured a few releases ago, and the old location should raise a DeprecationWarning, but nevertheless, the import should still work. We'll look into fixing that.

In the meantime, please update your imports, and use the ned module from  `astroquery.ipac.ned` as opposed from the top namespace.

**Comment by bsipocz** [comment]
Oh, I take it back and first ask what your astroquery version is, and to ask you to please remove the cache as it maybe a caching issue (located at ~/.astropy/cache/astroquery).

**Comment by mjibrown** [comment]
Hi Brigitta, 

Thank you for the prompt reply and useful fix - clearing the cache with astropy.utils.data.clear_download_cache() seemed to do the trick. 

I did have to reinstall astropy / astroquery recently after some stuff got corrupted during a conda upgrade, so I presume this issue has to do with the new astroquery seeing an old cache. I am using astroquery 0.4.6 but had been using 0.4.3 until recently. 

Best regards,

Michael.

Associate Professor Michael Brown
School of Physics and Astronomy
Monash University 
Clayton
Victoria 3800
Australia
Phone: +61 3 9905 4498
Mobile: +61 420 989 973
Astronomical Society of Australia Council
Chair of the Monash Science Equity, Diversity & Inclusion Committee <https://www.monash.edu/science/about/gender-equity-and-inclusion>
Monash LGBTIQ Ally <https://www.monash.edu/students/support/lgbtiqa/ally-network>
I am a Monash Mental Health First Aid Ambassador <https://www.monash.edu/students/support/health/mental-health/resources/ambassadors>
