### ISSUE TITLE
astroquery.alma authentication redirect page no longer exists

### ISSUE THREAD

**Issue by tristanashton** [astropy/astroquery#2630]
While rebuilding from the cyberattack that shut down ALMA's systems, several authentication pages have been consolidated and/or removed. Astroquery is configured for the address `asa.alma.cl` (in `__init__.py`), which is then augmented with `/rh/forceauthentication` in the `_login()` function in `core.py` to create the full login address. This page (`asa.alma.cl/rh/forceauthentication`) no longer exists- it has been replaced with a local version that uses the URL `https://almascience.nrao.edu/rh/forceauthentication
`
I've edited my local copy to use this URL by adding `almascience.nrao.edu` to `auth_urls` on line 14 in `__init__.py`:

`auth_urls = ['almascience.nrao.edu', 'asa.alma.cl', 'rh-cas.alma.cl']`

This allows me to log in with the Alma object, and circumvents the issue. I suspect the same effect and solution will be observed for users wanting to access the other ARCs at `almascience.eso.org` and `almascience.nao.ac.jp`

I recommend making this change to accommodate the new authentication redirect in ALMA's systems.

**Comment by bsipocz** [comment]
cc @keflavich @andamian - could you please check whether this is the only change we need to make after the attack?

**Comment by keflavich** [comment]
I made this modification to my own login scripts locally during the hack-driven shutdown, but I had assumed the asa.alma.cl services would come back online.  @andamian, do you have news?  If not, we should implement the suggested changes.

**Comment by andamian** [comment]
I am double-checking with ALMA.

**Comment by tristanashton** [comment]
My suggested solution might be imperfect- adding the `almascience.nrao.edu` url works fine on one of my machines, but returns a series of `urllib3.exceptions.NewConnectionError: Failed to establish a new connection: [Errno -2] Name or service not known` errors when I make the same edit on a different installation elsewhere. I'm not sure why this happens, and I'm not familiar enough with the code to troubleshoot effectively, so extra testing may be needed

**Comment by tristanashton** [comment]
Hi all, is there an update on this ticket?

**Comment by andamian** [comment]
I've pinged ALMA again for confirmation of the proper solution. 
Sorry for the delay.

**Comment by andamian** [comment]
@tristanashton - apologies again for the delay. I've finally managed to confirm the proper URLs with ALMA but I don't have the means to test it with proprietary data. Could you please try the small changes in https://github.com/astropy/astroquery/pull/2670 and see if that works for you? Login and access proprietary data. Thanks!

**Comment by tristanashton** [comment]
@andamian - It doesn't look like the changes were successful- I updated astroquery which downloaded a new distro (astroquery-0.4.7.dev8076), but when I try to log in to an Alma object I just get the same error again:

`astroquery.exceptions.LoginError: Could not log in to any of the known ALMA authorization portals: ['asa.alma.cl', 'rh-cas.alma.cl']`

I also noticed that the rh/forceAuthentication redirect is still present in core.py, which is the original issue. Have I flubbed the download/update somehow (entirely possible) or did the URL change not get committed?

**Comment by adeleplunkett** [comment]
Hi, I have a related question. I updated my __init__.py file, as described above by @tristanashton , and it seems to let me authenticate. However, if I search for a project for which I have public and proprietary data, I only see the public data.  

```
alma = Alma()
alma.login("adeleplunkett", store_password=True)
myquery=alma.query(payload=dict(proposal_id='2019.1.00912.S')) 
## note: including ,data_rights='Proprietary' made no difference
myquery.to_pandas()['data_rights'].unique() 
```

As a check, if I use the TAP protocol instead, as in:

```
def query_proposal_id(proposal_id):
    """Queries for an ALMA project code like 2012.1.00123.S or a the id authors need
       to put into their publications ADS/JAO.ALMA#2012.1.00123.S"""

    query = f""" 
            SELECT *  
            FROM ivoa.obscore  
            WHERE obs_publisher_did like '%{proposal_id}%' 
            """    
    
    return service.search(query).to_table().to_pandas()

proposal_id = '2019.1.00912.S'
tapq = query_proposal_id(proposal_id)
tapq['data_rights'].unique()

```
Then I do see 'Public' and 'Proprietary' data listed.  Any ideas why I can't see the Proprietary data in the first case?  If it has to do with the current situation described above about the authentication mechanism, please tell me, so I'll know that I just need to wait until it's resolved.  But, if you have any other suggestions, it's greatly appreciated.  Thanks!

**Comment by andamian** [comment]
@adeleplunkett you need to pass `public=None` to `query` in order to return both (`True` for public only is the default, `False` for proprietary only and `None` for both).

**Comment by tristanashton** [comment]
@andamian I can't seem to pull the patch into my installation. Running `pip install --pre astroquery` just yields a bunch of "Requirement already satisfied" messages and doesn't update. Is there a different way to grab the pre-release?

**Comment by bsipocz** [comment]
If you have astroquery already installed, you need to allow `pip` to upgrade the version.

```pip install -U --pre astroquery``

**Comment by tristanashton** [comment]
For some reason that wasn't working either, so I removed my installation and tried a fresh download, but I ended up with the same version as before: astroquery-0.4.7.dev8076. I thought that maybe the version number hadn't changed, but it's still unable to log in to the authorization portals. I also tried a completely fresh installation on a different machine, and it grabbed version 0.4.7-dev8076 as well

**Comment by tristanashton** [comment]
I ran a totally fresh installation, and was able to log in!  I believe this is working now- I'm going to run some tests on my machine and will update this ticket if I see any issues, but for now this looks like a success.
