### ISSUE TITLE
BUG: failing remote tests Q1 2023

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2634]
In the latest remote-data test run on GHA we see 60 failing tests, affecting the following modules listed at the end of the issue. A large portion of them about unclosed files, ideally those should be properly handled, too, but there are some genuine looking parsing errors, etc, too pointing to potentially user affecting bugs/upstream changes.

Use this issue as a tracking one, add references to the PR to the checkboxed list below.

https://github.com/astropy/astroquery/actions/runs/3844350578/jobs/6547381260#step:5:9988

- [ ] astroquery.alma
- [ ] astroquery.esa.xmm_newton
- [ ] astroquery.esasy
- [ ] astroquery.eso
- ~[x] astroquery.magpis (this maybe resolved upstream, cannot reproduce locally on 23/01/24)~
- [ ] astroquery.mast
- [x] astroquery.mpc fixed upstream
- [x] astroquery.sdss #2654 
- [x] astroquery.simbad #2637 
- ~[x] astroquery.vizier (this maybe resolved upstream, cannot reproduce locally)~
- [ ] astroquery.vo_conesearch
- [x] docs/cadc #2648
- [x] docs/esa/iso #2648
- [x] docs/esasky #2648
- [x] docs/eso #2648
- [x] docs/heasarc #2652 
- [x] docs/imcce #2652
- [x] docs/ipac/ned #2648
- [x] docs/jplhorizons #2648
- [x] docs/jplsbdb #2648
- [ ] docs/mast

**Comment by bsipocz** [comment]
cc @pllim - could you have a look at the vo_conesearch failures, please?

**Comment by pllim** [comment]
If you are talking only about these, they are just warnings. You can ignore them. The conesearch validator try to grab the recommended parameters for test queries for a service when available and then it makes sense (in this case, the recommended search radius is deemed too large). So, it falls back to some hardcoded default. No harm done.

FAILED vo_conesearch/validator/tests/test_validate.py::TestConeSearchValidation::test_validation[True] - astropy.utils.exceptions.AstropyUserWarning: Failed to retrieve test query parameters for ivo://cds.vizier/i/252,4, using default: SR=0.11451621372724685 is too large, using SR=0.1 for ivo://cds.vizier/i/252,4

FAILED vo_conesearch/validator/tests/test_validate.py::TestConeSearchValidation::test_validation[False] - astropy.utils.exceptions.AstropyUserWarning: Failed to retrieve test query parameters for ivo://cds.vizier/i/252,4, using default: SR=0.11451621372724685 is too large, using SR=0.1 for ivo://cds.vizier/i/252,4

FAILED vo_conesearch/validator/tests/test_validate.py::TestConeSearchValidation::test_url_list[True] - astropy.utils.exceptions.AstropyUserWarning: Failed to retrieve test query parameters for ivo://cds.vizier/i/252,4, using default: SR=0.11451621372724685 is too large, using SR=0.1 for ivo://cds.vizier/i/252,4

FAILED vo_conesearch/validator/tests/test_validate.py::TestConeSearchValidation::test_url_list[False] - astropy.utils.exceptions.AstropyUserWarning: Failed to retrieve test query parameters for ivo://cds.vizier/i/252,4, using default: SR=0.11451621372724685 is too large, using SR=0.1 for ivo://cds.vizier/i/252,4

**Comment by bsipocz** [comment]
@pllim - sure enough these are warnings, but it would be nice to handle them in the tests rather than blanket ignore `AstropyUserWarning`s for the module.

**Comment by pllim** [comment]
Alas, I really don't have time to do this, especially given we already agree `vo_conesearch` is going to be deprecated in favor of something over at `pyvo`. If you really don't like the warning, you can skip those tests. Sorry.

**Comment by bsipocz** [comment]
This issue has been outdated now as there are significantly fewer failing remote tests now (though it's still a disturbingly large number for windows). So I'm going ahead and close this tracking issue now and will consider to open a new one for Q3.
