### ISSUE TITLE
Catalogs.query_object returns data for the wrong star

### ISSUE THREAD

**Issue by pmaxted** [astropy/astroquery#2641]
```
>>> from astroquery.mast import Catalogs
>>> Catalogs.query_object('WASP-3', radius=0.001, catalog='TIC')
<Table masked=True length=1>
    ID           ra             dec        ... wdflag      dstArcSec
   str9       float64         float64      ... int64        float64
--------- --------------- ---------------- ... ------ -------------------
715677988 83.162492515507 7.54537790157609 ...      0 0.02982868249131487
```

This is the wrong star, WASP-3 is TIC 27848472 according to SIMBAD and the MAST portal.
The actual coordinates of WASP-3 are 278.631773297363, 35.6615247759849.
The correct star is returned if I use an alternative identifier for this star ('BD+35 3293')

**Comment by keflavich** [comment]
@pmaxted Do you get the same result if you query MAST via the web interface?  If so, you should report the issue directly to their archive.

**Comment by pmaxted** [comment]
If I query TIC v8.2 using the MAST portal web interface I get the correct star - see screenshot attached.

![MAST_screenshot](https://user-images.githubusercontent.com/19465694/212931966-6cd735d1-ae38-4acc-8d56-dd56cd384053.png)

**Comment by keflavich** [comment]
OK this definitely sounds like a bug, then.  @ceb8 ?

**Comment by bsipocz** [comment]
Cc @jaymedina

**Comment by Bwoltz** [comment]
Huh, not sure if this is the issue, but the format of the query changes the result I get on the MAST web portal.

**query 1**: "`WASP-3 r=0.001`"  [[link](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22TIC%22%2C%22inputText%22%3A%22WASP-3%20r%3D0.001%22%2C%22paramsService%22%3A%22Mast.Catalogs.Tic.Cone%22%2C%22title%22%3A%22TICv8.2%3A%20WASP-3%20r%3D0.001%22%2C%22columns%22%3A%22*%22%7D)]

![image](https://user-images.githubusercontent.com/32148318/214750014-6b423f84-6cfe-456b-83af-192b0c5eb522.png)

These results agree with `astroquery`.


**query 2** (@pmaxted's query): "`WASP-3, r=0.001`" <-- (notice the comma) [[link](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22TIC%22%2C%22inputText%22%3A%22WASP-3%2C%20r%3D0.001%22%2C%22paramsService%22%3A%22Mast.Catalogs.Tic.Cone%22%2C%22title%22%3A%22TICv8.2%3A%20WASP-3%2C%20r%3D0.001%22%2C%22columns%22%3A%22*%22%7D)]

![image](https://user-images.githubusercontent.com/32148318/214751016-dcb6397e-e8d7-4b3e-b7cd-3ed97ce2a1fe.png)



Judging from the examples MAST gives (see "Show Examples..." below the search bar on the MAST portal)

![image](https://user-images.githubusercontent.com/32148318/214751458-b38ab016-a7f7-4713-ae04-9c12be9aa508.png)

It *looks* like the intended format is to use space delimited parameters to query individual objects and comma delimiters for each object. Which matches query 1.

Again, not sure if that is the issue. If you're confident this is wrong there may be some technical issue going on. But it looks like MAST agrees with `astroquery`.

**Comment by Bwoltz** [comment]
Huh, not sure if this is the issue, but the format of the query changes the result I get on the MAST web portal.

**query 1**: "`WASP-3 r=0.001`"  [[link](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22TIC%22%2C%22inputText%22%3A%22WASP-3%20r%3D0.001%22%2C%22paramsService%22%3A%22Mast.Catalogs.Tic.Cone%22%2C%22title%22%3A%22TICv8.2%3A%20WASP-3%20r%3D0.001%22%2C%22columns%22%3A%22*%22%7D)]

![image](https://user-images.githubusercontent.com/32148318/214750014-6b423f84-6cfe-456b-83af-192b0c5eb522.png)

These results agree with `astroquery`.


**query 2** (@pmaxted's query): "`WASP-3, r=0.001`" <-- (notice the comma) [[link](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22TIC%22%2C%22inputText%22%3A%22WASP-3%2C%20r%3D0.001%22%2C%22paramsService%22%3A%22Mast.Catalogs.Tic.Cone%22%2C%22title%22%3A%22TICv8.2%3A%20WASP-3%2C%20r%3D0.001%22%2C%22columns%22%3A%22*%22%7D)]

![image](https://user-images.githubusercontent.com/32148318/214751016-dcb6397e-e8d7-4b3e-b7cd-3ed97ce2a1fe.png)



Judging from the examples MAST gives (see "Show Examples..." below the search bar on the MAST portal)

![image](https://user-images.githubusercontent.com/32148318/214751458-b38ab016-a7f7-4713-ae04-9c12be9aa508.png)

It *looks* like the intended format is to use space delimited parameters to query individual objects.

Again, not sure if that is the issue. If you're confident this is wrong there may be some technical issue going on, but it looks like MAST agrees with `astroquery`.

**Comment by pmaxted** [comment]
I checked the discovery paper for WASP-3, which states "WASP-3b transits its host star USNO-B1.0 1256−0285133". The 1SWASP identifier is 1SWASP J183431.62+353941.4. 

This star is certainly **not** TIC 715677988, which appears to be a [quasar](http://simbad.cds.unistra.fr/simbad/sim-id?Ident=Gaia+DR2+3334228054423044736&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id)(?!). According to the TIC data itself, this object is far too faint to have ever been observed by the WASP survey, apart from being in completely the wrong part of the sky.

Is the backend for MAST built on astroquery?

**Comment by Bwoltz** [comment]
I understand. I'm not saying you're wrong, I'm just trying to figure out where exactly the problem lies.

>Is the backend for MAST built on astroquery?
No. From what I understand, astroquery provides a series of wrappers for various APIs (as well as some data structures and other tools that make dealing with astronomical data easier). MAST is a standalone project.

In order to root cause this a little more, I would try to query the MAST API directly without astroquery and see what results come back. If they're wrong, I would report this to the MAST team like @keflavich suggested above.

I can do so later after work (unless someone beats me to it).

**Comment by pmaxted** [comment]
OK, I have sent an e-mail to archive@stsci.edi to make them aware of this issue.

**Comment by scfleming** [comment]
Just confirming MAST is aware, and we are pretty sure of the problem (it's related to caches on our end).  It is definitely not astroquery-related and we will work to fix it as soon as possible.

**Comment by bsipocz** [comment]
Thanks @scfleming for investigating and letting us know.

**Comment by bsipocz** [comment]
The OP example now returns the expected star, so I think this has been resolved upstream. Do feel free to reopen if you keep running into this issue (after clearing the astroquery cache):

```
In [1]: >>> from astroquery.mast import Catalogs
   ...: >>> Catalogs.query_object('WASP-3', radius=0.001, catalog='TIC')
Out[1]: 
<Table masked=True length=1>
   ID           ra              dec          pmRA   ...     e_Dec_orig     raddflag wdflag      dstArcSec      
  str8       float64          float64      float64  ...      float64        int64   int64        float64       
-------- ---------------- ---------------- -------- ... ------------------ -------- ------ --------------------
27848472 278.631773297363 35.6615247759849 -6.06885 ... 0.0294562177680164        1      0 0.005020250641799152
```
