### ISSUE TITLE
MAINT: move cron tests to day least affected by planned maintanence downtimes

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2643]
cc @jespinosaar @andamian @keflavich - if you know of the typical days that alma, esa, etc does routine downtimes, please let me know, as I try to move the crons from the current Monday to a day least likely to run into issues.
(I'm thinking of maybe Sunday is a good one?)

**Comment by andamian** [comment]
I'll check with ALMA. Sundays sounds OK unless they use the same line of thinking, i.e. Sundays are quieter.

**Comment by bsipocz** [comment]
I'm open for moving to any other timeslots, so far only Mon and Tue are out.

**Comment by andamian** [comment]
Fridays are best for ALMA: system maintenance tends to take place during the weekend and new deployments during the week (less likely on Fridays for obvious reasons)

**Comment by jespinosaar** [comment]
Hi @bsipocz , Sundays are better for us and we don't expect many downtimes. Thanks for telling us!
