### ISSUE TITLE
BUG: MAST MSA product table returns no results

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2646]
This has been set up for the tests and now causing errors as the response has changed from the expected 6 results to None

Is this change expected (if yes, then the tests need refactoring), or something is going wrong upstream?

```
    def msa_product_table():
        # Pull products for a JWST NIRSpec MSA observation with 6 known
        # duplicates of the MSA configuration file, propID=2736
       products = mast.Observations.get_product_list("87602009")
```

cc @jaymedina

**Comment by snbianco** [comment]
I can no longer find this `obsid` in the portal, so I'm guessing that something changed internally. In any case, the bug in the test suite was fixed with the refactoring I did a few months ago.
