### ISSUE TITLE
Querying Simbad for rotational velocity

### ISSUE THREAD

**Issue by BarbaraSO** [astropy/astroquery#2679]
Hi,
How can I get all the rotational velocity ('rot') measurements from simbad using astroquery?
When querying an identifier with 'rot' as a votable field, the result table shows only one measurement of the rotational velocity, I assume it's the latest one. However, I would like to have all the measurements available, which for this identifier I think there were 3. 
Below I show the piece of code I wrote in python to get the results for this identifier:

from astroquery.simbad import Simbad
customSimbad = Simbad()
customSimbad.get_votable_fields()
customSimbad.add_votable_fields('rot')
customSimbad.get_votable_fields()

result_table = customSimbad.query_object("gaia_dr2 3946945413106333696")

**Comment by aoberto** [comment]
Hello, 
No there is currently no way to get all external mesaurements for an object through astroquery.simbad.

I can suggest you to use the TAP service interface to get what you want using [pyvo](https://pyvo.readthedocs.io/en/latest/) module.
Here is an example how to query Simbad-TAP with astropy.
https://github.com/aoberto/sharing-notebook/blob/main/pyvo-Simbad-Tap.ipynb

And the dedicated query for you would be:
`SELECT myname, main_id AS "simbadName", mesRot.* FROM basic JOIN ident ON oid=ident.oidref JOIN mesRot ON oid=mesRot.oidref RIGHT JOIN ' + full_qualified_table_name + ' ON myname=id`

that will give you:
```
myname            simbadName       bibcode       mespos nbmes  oidref qual upvsini vsini  vsini_err vsini_err_prec vsini_prec
                                                                                              km / s                                    
---------------------------- ---------- ------------------- ------ ----- ------- ---- ------- ------ --------- -------------- ----------
gaia dr2 3946945413106333696  *  11 Com 1970CoAsi.239....1B      3    10 1909584    D           10.0        --             --          0
gaia dr2 3946945413106333696  *  11 Com 1970CoKwa.189....0U      2    -- 1909584    D       <   19.0        --             --          0
gaia dr2 3946945413106333696  *  11 Com 2015A&A...574A..50J      1    -- 1909584                2.96      1.15              2          2
```

**Comment by ManonMarchand** [comment]
Hi Barbara, I'll add the `close?` label to this issue but don't hesitate to add more comments if you need clarification or if you have any further questions.
