### ISSUE TITLE
ALMA: What kind of region is s_region?

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#2687]
@andamian What kind of region is the `s_region` returned by ALMA?

```python
from astroquery.alma import Alma
from astropy import units as u, constants
from astropy.coordinates import SkyCoord
import regions

rslt = Alma.query_region(SkyCoord(25*u.deg, 0*u.deg, frame='galactic'), radius=1*u.deg)

rslt['s_region'][0]
# 'Polygon ICRS 279.506917 -7.744253 279.505574 -7.744000 279.504420 -7.743274 279.503525 -7.741969 279.503269 -7.740639 279.503525 -7.739308 279.504420 -7.738004 279.505574 -7.737278 279.506917 -7.737024 279.508470 -7.737368 279.509576 -7.738165 279.510308 -7.739308 279.510564 -7.740639 279.510308 -7.741969 279.509414 -7.743274 279.508260 -7.744000'
```

This doesn't look like any of the standard serialization formats handled by `regions` (https://astropy-regions.readthedocs.io/en/stable/region_io.html).

Is it a standard format that we could (should) handle in `regions`?  Or can we provide some helper here in astroquery to parse it as a `region`?  e.g.

```python
def parse_region(reg):
    spl =reg.split()
    if spl[0] == 'Polygon':
        csys = spl[1]
        points = SkyCoord([(float(spl[ii]), float(spl[ii+1]))*u.deg
                  for ii in range(2, len(spl), 2)], frame=csys.lower())
        return regions.PolygonSkyRegion(points)
```

**Comment by andamian** [comment]
I'm going to cc @at88mph as he's been playing with this recently.

**Comment by at88mph** [comment]
ALMA's ObsCore service outputs the `s_region` column in an STC-S string in the ICRS frame, as per the specification at https://www.ivoa.net/documents/ObsCore/20170509/REC-ObsCore-v1.1-20170509.pdf (4.12).  You're right, it does not appear to conform to the three main formats supported by the `Regions` class, but can be easily parsed into a `PolygonSkyRegion` instance as described.

**Comment by bsipocz** [comment]
I believe this can be close here as it's already upstreamed to regions?

**Comment by andamian** [comment]
Do you have a reference if it's upstreamed? I was tasked to trying to find a solution to it. thanks

**Comment by bsipocz** [comment]
@andamian  - Would https://github.com/astropy/regions/issues/21 be sufficient?

**Comment by andamian** [comment]
Oh. I see, it comes back to us (CADC) since there are no updates on that issue since 2018. But yes, I think it belongs upstream. thanks

**Comment by bsipocz** [comment]
Yes, I have cross dependent issues that bites back to me often 😅
