### ISSUE TITLE
NED query does not return new hi spectra

### ISSUE THREAD

**Issue by yu-astro** [astropy/astroquery#2694]
I am using `Ned.get_image_list` to download the latest hi spectrum of galaxies. I ran the following code:
```
from astroquery.ipac.ned import Ned
spectra_list = Ned.get_image_list('UGC05990', item='spectra',file_format='author-ascii')
spectra_list
```
It return:
```
['http://ned.ipac.caltech.edu/spc1/2000/2000UZC...C......0F/10/CGCG_1049.8+3445:S:UBVR:f2000.txt',
 'http://ned.ipac.caltech.edu/spc1/1986/1986AJ.....91..732B/UGC_05990:S:HI:bg1986.txt',
 'http://ned.ipac.caltech.edu/spc1/2007/2007SDSS6.C...0000:/1983/SDSS_J105238.34+342859.3:S.txt']
```
But when I go to [https://ned.ipac.caltech.edu/byname?objname=UGC05990&hconst=67.8&omegam=0.308&omegav=0.692&wmap=4&corr_z=1](https://ned.ipac.caltech.edu/byname?objname=UGC05990&hconst=67.8&omegam=0.308&omegav=0.692&wmap=4&corr_z=1)
<img width="736" alt="image" src="https://user-images.githubusercontent.com/126140360/228591493-1e5a07fe-0f48-43d8-b103-6edd020ee33b.png">
I found that the latest data is from 2018, but `Ned.get_image_list` does not return.

So is it because  `Ned.get_image_list` get data from [https://ned.ipac.caltech.edu/cgi-bin/NEDspectra?objname=UGC+5990&extend=never&detail=0&preview=1&numpp=20&refcode=ANY&bandpass=ANY&line=ANY&hconst=73.0&omegam=0.27&omegav=0.73&corr_z=1](https://ned.ipac.caltech.edu/cgi-bin/NEDspectra?objname=UGC+5990&extend=never&detail=0&preview=1&numpp=20&refcode=ANY&bandpass=ANY&line=ANY&hconst=73.0&omegam=0.27&omegav=0.73&corr_z=1) ? Because I found in this page the data from 2018 is unavailable.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/126140360/228592333-cb9ef8eb-ff02-4e32-8ae8-b2f64ac22d33.png">

If this is the reason, how should I do it?

the `astroquery ` version is  0.4.6

**Comment by bsipocz** [comment]
@yu-astro - I'm following this up with the ned developers. We apparently using the older, `cgi-bin` interface in astroquery, that doesn't return everything, it's not yet clear whether we need to switch to the new interface, or it's an internal bug at NED. Either case, I also received this comment that may very much affect your use case, and completeness of the datasets you're looking for:

> Also NED stopped curating images and spectra data in 2019.

**Comment by bsipocz** [comment]
> Also NED stopped curating images and spectra data in 2019.
 
 and for this we may need to add a warning for the users anyway.
