### ISSUE TITLE
Level 2 JWST association json files no longer returned for MAST queries

### ISSUE THREAD

**Issue by jdavies-st** [astropy/astroquery#2695]
It seems level 2 JWST associations (`_asn.json`) files are not being returned via the `astroquery.mast` interface, but they are via MAST web interface.  An example:

```python
from astroquery.mast import Observations
from astropy.table import vstack
import numpy as np


obs_table = Observations.query_criteria(proposal_id="2016", obs_collection="JWST", instrument_name="NIRSPEC/IFU", target_name="M-81-NIRSPEC")
product_list = [Observations.get_product_list(obs) for obs in obs_table]
products = vstack(product_list)
# Get rid of guide star fluff
mask = np.char.find(products["dataURI"], "_gs-") == -1
products = products[mask]
```
And now I have 394 products of all the level 2 and level 3 science and info products.

```
In [11]: len(products)
Out[11]: 394
```

But the only associations included are the level 3 associations:

```
In [12]: mask = np.char.find(products["dataURI"], "_asn.json") != -1

In [13]: np.sum(mask)
Out[13]: 2

In [32]: print(products[mask])
  obsID   obs_collection dataproduct_type                 obs_id                 ... size parent_obsid    dataRights    calib_level
--------- -------------- ---------------- -------------------------------------- ... ---- ------------ ---------------- -----------
101660509           JWST             cube jw02016-o016_t016_nirspec_g395h-f290lp ... 3512    101660509 EXCLUSIVE_ACCESS           3
101660510           JWST             cube jw02016-o016_t016_nirspec_g235h-f170lp ... 3512    101660510 EXCLUSIVE_ACCESS           3
```

Meanwhile with the same search on the MAST web interface, it shows the level 2 associations (_asn.json), not just the level 3 ones.

<img width="1036" alt="Screen Shot 2023-03-30 at 15 25 48" src="https://user-images.githubusercontent.com/17088869/228853255-eca15826-710d-493f-847b-b64b30f02d0a.png">

This used to work in astroquery.  I've tried with being less restrictive on my initial search (just prop id and instrument), and I've also checked with other non-proprietary proposal id, such as CEERS 1345.  Same result of level 2 assocations missing.  This was working fine on March 9, 2023 when I downloaded the CEERS 1345 level 2 associations via astroquery.

Thanks!

**Comment by bsipocz** [comment]
cc @jaymedina

**Comment by snbianco** [comment]
I retried this code and it looks like the level 2 associations are being returned now!

```
from astroquery.mast import Observations
import numpy as np

obs_table = Observations.query_criteria(proposal_id="2016", obs_collection="JWST", instrument_name="NIRSPEC/IFU", target_name="M-81-NIRSPEC")
products = Observations.get_product_list(obs_table)

# Get rid of guide star fluff
mask = np.char.find(products["dataURI"], "_gs-") == -1
products = products[mask]

mask = np.char.find(products["dataURI"], "_asn.json") != -1
print(np.unique(products[mask]['calib_level']))
```

I'll go ahead and close this ticket.
