### ISSUE TITLE
SDSS Queries failing with error

### ISSUE THREAD

**Issue by temuller** [astropy/astroquery#2706]
I am currently having issues with the queries, even with the basic example:

```
from astroquery.sdss import SDSS
from astropy import coordinates as coords
pos = coords.SkyCoord('0h8m05.63s +14d50m23.3s', frame='icrs')
xid = SDSS.query_region(pos, spectro=True)
print(xid)
```

```
                                        htmlhead                                        
----------------------------------------------------------------------------------------
                                                          <title>Skyserver Error</title>
                                                             </head><body bgcolor=white>
<h2>An error occured</h2><H3 BGCOLOR=pink><font color=red><br></font></H3></BODY></HTML>

```
Not sure if this is an issue with astroquery (v0.4.6), the SDSS server or my institute. Thanks in advance.

**Comment by eerovaher** [comment]
I can't replicate the error.

**Comment by bsipocz** [comment]
@temuller - 0.4.2 is very old, please upgrade to something more recent. Your example works for me both with 0.4.6 or with the dev version (which is also pip installable with `pip install --pre -U astroquery`). Thanks.

**Comment by temuller** [comment]
For some reason, astroquery.SDSS is now working with version 0.4.6. Not sure what happened.
I'll close this issue for now, but will re-open it if this happens again. Thanks for the help.
