### ISSUE TITLE
Add service: Database of Charged Cosmic Rays (CRDB)

### ISSUE THREAD

**Issue by cdeil** [astropy/astroquery#271]
The [Database of Charged Cosmic Rays](http://lpsc.in2p3.fr/cosmic-rays-db/) has implemented a REST API (see description [here](https://lpsc.in2p3.fr/cosmic-rays-db/_dialog_rest.php)) that allows one to retrieve tons of cosmic ray spectrum measurements as USINE and GALPROP format ASCII files.

It would be very nice to implement a USINE and / or GALPROP reader and then add a `astroquery.crdb` query interface.

Here's an example [usine](https://gist.github.com/cdeil/11174955) and [galprop](https://gist.github.com/cdeil/11174936) format ascii file that I got via these commands:

```
wget 'http://lpsc.in2p3.fr/cosmic-rays-db/rest.php?num=C&energy_type=EKN&format=usine' --output-document=example.usine
wget 'http://lpsc.in2p3.fr/cosmic-rays-db/rest.php?num=C&energy_type=EKN&format=galprop' --output-document=example.galprop
```

I won't assign to myself because I'll be very busy in the next few weeks, but when I get some free time I'll try and implement this. Of course I'm happy if someone beats me to it!

**Comment by keflavich** [comment]
Closing - the URL referenced is dead.
