### ISSUE TITLE
HTTP ERROR 500 when querying asynchronously

### ISSUE THREAD

**Issue by chenjunzhan** [astropy/astroquery#2714]
When I do a cone search using an asynchronous query, I get the following error (the synchronous query does not have this error, but only shows the first two thousand rows of query results)

![image](https://user-images.githubusercontent.com/48664039/234298633-424d34fe-f618-4958-831a-d48a4dbc5bfa.png)

**Comment by chenjunzhan** [comment]
I haven't found a solution yet, so I hope I can get some advice.

**Comment by cosmoJFH** [comment]
A new release of the Gaia archive has recently been carried out. We have checked that the previos issue can not be reproduce with the following example:

```
from astroquery.gaia import Gaia
import warnings

 warnings.filterwarnings('ignore')

query="SELECT * FROM gaiadr3.gaia_source WHERE 1 = CONTAINS(POINT('ICRS', ra, dec), CIRCLE('ICRS', 40, 40, 0.1))"

j1 = Gaia.launch_job_async(query=query, output_file="cone_1.vot.gz", output_format="votable_gzip", dump_to_file=True, verbose=False)

 j2 = Gaia.launch_job_async(query=query, output_file="cone_2.vot", output_format="votable", dump_to_file=True, verbose=False)
```
