### ISSUE TITLE
Alma: TAP limitations?

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#2726]
@at88mph @andamian I've encountered a few issues when trying to run my own TAP queries

```
>>> Alma.query_tap("select * from ivoa.obscore WHERE (gal_latitude < 1.5) AND"
>>>               " (gal_latitude > -1.5) AND (gal_longitude < 9) and (gal_longitude > 2) AND science_observation='T'"
>>>               " AND data_rights='Public'")

DALQueryError: ORA-01489: result of string concatenation is too long
 ORA-01489: result of string concatenation is too long
```

```
>>> Alma.query_tap("select * from ivoa.obscore WHERE (gal_latitude < 1.5) AND"
>>>                " (gal_latitude > -1.5) AND (gal_longitude < 90) and (gal_longitude > 1) AND science_observation='T'"
>>>                " AND data_rights='Public'")

DALFormatError: ValueError: 503946:16: XML or text declaration not at start of entity
```

These are pretty big queries, so I suspect these are different varieties of "your results are too large", but they're not particularly human-readable.  Can we include some guidance in the documentation about what might constitute a too-large query?

Curiously, this query, which resulted in 53863 hits, worked:
```
Alma.query_tap("select * from ivoa.obscore WHERE (gal_latitude < 1) AND"
               " (gal_latitude > -1) AND science_observation='T'"
               " AND data_rights='Public'")
```
What's the difference?  It looks like going off the galactic plane by a tiny bit results in invalid queries, but in-plane, the size limit is huge.

I've labeled this 'documentation' because we need clearer error messages and/or guidelines about what queries are allowed; I don't think any code changes are needed except maybe error message changes.

**Comment by bsipocz** [comment]
We still see this with remote tests.

**Comment by mjastro** [comment]
Do you know if there is any further follow-up on this issue? I see that #458 is closed, but it would be great to know whether there is a way to fix it... 

Thanks a lot for any help or comments you could offer!!

**Comment by at88mph** [comment]
Hi @mjastro.  There is a patch submitted to the ALMA maintainers now that will **hopefully** be in the next release, which is the August 2023 release.

**Comment by mjastro** [comment]
@at88mph thank you very much!
