### ISSUE TITLE
Dropping python 3.7 support

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2742]
Before I drop support, would like to see some input from the bigger teams in astroquery. Would you mind if we drop it?
(most big packages are dropping 3.8 (numpy, scipy, etc) in the upcoming releases, and dropped 3.7 a while ago already, and some of the infrastructure packages we use are dropping support, too. So while we can keep going, it's a tiny bit easier if we could do it without workarounds, or to use nice new features)

@astropy/astroquery-archive-maintainers

**Comment by keflavich** [comment]
I'm good with that.

**Comment by jd-au** [comment]
+1 Looks like 3.7 loses security support very soon, so its a good time to drop support.

**Comment by andamian** [comment]
Yes, that works for 3.7 since it will reach its end of life soon.

We found it easier to justify to our users (and convince them to update their environments) if we follow Python release schedule but we don't rush it until something stops working. We have to be mindful that users sometimes run software on systems that are out of their control and a Python upgrade might require an OS upgrade with sys admin intervention and other complications.

**Comment by ceb8** [comment]
I'm good with this.

**Comment by mkelley** [comment]
Sounds good to me.

**Comment by bsipocz** [comment]
> We have to be mindful that users sometimes run software on systems that are out of their control and a Python upgrade might require an OS upgrade with sys admin intervention and other complications.

Yes, that's why I'm not suggesting to follow drop schedule the big libraries follow and endorse. But at some point we need to start dropping as the infrastructure we're using is also slowly doing it. (nothing extra urgent just yet)

**Comment by jaymedina** [comment]
This seems reasonable. We've already dropped support for 3.7 in Astrocut too.

**Comment by jespinosaar** [comment]
Hi all, I think we can drop the support, yes, I have been testing with our modules and Python >= 3.8 and seems to be working.

**Comment by bsipocz** [comment]
@jespinosaar - it's less about testing, more about whether you know your end users being stuck on an old version?

**Comment by bsipocz** [comment]
OK, so my tentative plan is then to do this once I tag a v0.4.7 release, sometimes over the summer.
