### ISSUE TITLE
error while querying NRAO data

### ISSUE THREAD

**Issue by ashishkalyan** [astropy/astroquery#2750]
Hi,

I am trying to download NRAO archive data using astroquery package but getting an error while querying. Here is a Python snippet that produces the error,

=======================================================

code snippet:

from astroquery.nrao import Nrao
import astropy.coordinates as coord
result_table = Nrao.query_region("04h33m11.1s 05d21m15.5s")
print(result_table)

===========================================================

Error:

File ~/.local/lib/python3.8/site-packages/astroquery/nrao/core.py:414, in NraoClass._parse_result(self, response, verbose)
    412     return self._parse_html_result(response, verbose=verbose)
    413 else:
--> 414     raise ValueError("Unrecognized response type; it does not appear "
    415                      "to be VO-XML or HTML")

ValueError: Unrecognized response type; it does not appear to be VO-XML or HTML

=====================================================
Thanks

**Comment by keflavich** [comment]
The NRAO module no longer exists.  It was deprecated because NRAO shut down the archive service.  Unfortunately, we do not have an interface to the latest version of the NRAO archive yet.
