### ISSUE TITLE
Simbad query not returning hierarchical membership information

### ISSUE THREAD

**Issue by alexandergagliano** [astropy/astroquery#2753]
Hi all, 

I'm looking at sub-structure of a galaxy (SDSSCGB 350.4), and the simbad website describes both the hierarchical probability of membership as 75% and shows the parent id [here](https://simbad.cds.unistra.fr/simbad/sim-id?Ident=SDSS+J161244.67%2B281710.0&NbIdent=query_hlinks&Coord=16+12+44.6834655456%2B28+17+10.383319500&parents=1&siblings=4&submit=siblings&hlinksdisplay=h_all).

However, when I try to query simbad with astroquery (v0.4.6), the hierarchical "MEMBERSHIP" field is blank:

```
from astroquery.simbad import Simbad
Simbad.add_votable_fields('membership')
result_table = Simbad.query_region("SDSSCGB 350.4")
print(result_table['MEMBERSHIP'])
```

Is this a bug and is there a way to get the parent id through astroquery in addition to the membership probability? Thanks!

**Comment by ManonMarchand** [comment]
are you looking for something like this? It gets every object with a single parent around this galaxy

```
Simbad.query_criteria("region(circle,  SDSSCGB 350.4, 2m)", parents=1)
```

See Simbad's documentation here : http://simbad.cds.unistra.fr/simbad/sim-fsam 

It's also written in the url you linked (which is how I usually build my most complex queries: go on the website, look at the link, retroengineer what the pertinent criteria could be)

**Comment by alexandergagliano** [comment]
The pyvo solution is great! Thanks, this is exactly what I was looking for.
