### ISSUE TITLE
SkyView.get_images: boolean comparison of a quantity raises a ValueError in astropy 5.3

### ISSUE THREAD

**Issue by ycopin** [astropy/astroquery#2756]
In astropy 5.3, `bool(quantity)` now [raises an error](https://github.com/astropy/astropy/pull/14124). As a consequence, the [boolean comparison](https://github.com/astropy/astroquery/blob/227ded66f139a69646f4666dc06a8202a2cb1a1d/astroquery/skyview/core.py#L257) in `SkyView.get_image_list` will raise an error:
```
        elif width and height:
```
It should probably be replaced by
```
         elif None not in (width, height):
```
As a mitigation, one can revert to astropy < 5.3.

**Comment by keflavich** [comment]
Thanks for the report.  Would you be interested in submitting the proposed fix as a PR?  We should also add a test to cover this case.

**Comment by ycopin** [comment]
https://github.com/astropy/astroquery/pull/2757, my 1st PR, don't hesitate to feedback.

**Comment by bsipocz** [comment]
I think the current code with the error is correct, otherwise what would a bool height and width actually mean?

**Comment by keflavich** [comment]
A bool `height` and `width` should not be allowed.  `height` and `width` must be quantities.  I think the suggested PR has the right fix.
