### ISSUE TITLE
Astroquery.gaia use of “=“ and number of columns returned verses selected.

### ISSUE THREAD

**Issue by JosephKarpinski** [astropy/astroquery#2758]
Hi,

Maybe there’s something I’m missing, but I can’t get this to work using a Vizier catalog table.
Astroquery0.4.7.dev8479.
Works using the Vizier web page.
Ideas?

https://vizier.cds.unistra.fr/viz-bin/VizieR?-source=IV/38

See attached

![IMG_6635](https://github.com/astropy/astroquery/assets/37123616/479d0978-4fe7-4cf4-a866-b0eef71a13bd)

<img width="1184" alt="Screenshot 2023-06-26 at 12 42 33 PM" src="https://github.com/astropy/astroquery/assets/37123616/027e789e-3a5a-485f-b7c9-7d10e670a010">
<img width="1339" alt="Screenshot 2023-06-26 at 12 44 13 PM" src="https://github.com/astropy/astroquery/assets/37123616/5295b0c0-aa17-41c7-8ab1-d46d256c0900">
![IMG_6634](https://github.com/astropy/astroquery/assets/37123616/645c66b2-1036-4c90-a25b-4e339a227811)

**Comment by keflavich** [comment]
Please post code directly rather than screenshots of code; it's hard to read this and reproduce the issue.

**Comment by JosephKarpinski** [comment]
from astroquery.vizier import Vizier

from astropy.table import Table

Vizier.ROW_LIMIT = 1

#result = Vizier.query_constraints(catalog='IV/38')    #  TESS Input Catalog v8.0 1,727,987,580

#result = Vizier.query_constraints(catalog='IV/38', columns=['TIC', 'GAIA']) 

#result = Vizier.query_constraints(catalog='IV/38') 



#result = Vizier.query_constraints(catalog='IV/38', timeout=600, column_filters={'GAIA':'=3344445506744055424'}) 

result = Vizier.query_constraints(catalog='IV/38', timeout=600, column_filters={'GAIA':'>4145312630908049151', 'GAIA':'<4145312630908049153'}) 

#result = Vizier(catalog='IV/38', columns=['TIC', 'GAIA'], timeout=600).query_constraints(GAIA=5877444388466340992)

#result = Vizier(catalog='IV/38', timeout=600).query_constraints(GAIA>4145312630908049151, GAIA<4145312630908049153)

#result = Vizier.query_constraints(catalog='IV/38', timeout=1200, column_filters={'GAIA':'>0'}, columns=['tic', 'gaia'])

**Comment by JosephKarpinski** [comment]
None of the above commented queries work correctly.

**Comment by keflavich** [comment]
The `column_filters` keyword argument needs to be passed to `Vizier`, not to `query_constraints`.  e.g.:

```python
Vizier(column_filters={'GAIA':'3344445506744055424'}).query_constraints(catalog='IV/38')
```

Alternatively, you could pass the constraint directly like you did in one example:
```python
result = Vizier(catalog='IV/38', columns=['TIC', 'GAIA']).query_constraints(GAIA=3344445506744055424)
```

I do confirm, however, that I don't get a result from these queries.  I tried reproducing through the browser and got the following error, which indicates that this is a server-side error:
```
The following problems were encountered in this VizieR run:
**** 
**** --POSTGRES MSG db=1
**** Report from: stdb_pg,     Status: STDB_ERR 
****ERROR:  canceling statement due to statement timeout 
If you can't find a solution, [report to CDS](mailto:cds-question@unistra.fr?Subject=VizieRerror%20%28%40vizier.cds.unistra.fr%29&Cc=cds-question%40unistra.fr) and insert into your message the following details:
.errorfile=/tmp/VR1788135.err (2023-06-26T20:18:09)
-4
-from=-2
-ref=VIZ6499f2651b3779
-ref=VIZ6499f2651b3779
-out.max=50
-out.form=HTML Table
-out.add=_RAJ,_DEJ
-sort=_r
-oc.form=sexa
-c.eq=J2000
-c.r=  2
-c.u=arcmin
-c.geom=r
-source=[IV/38/tic](https://vizier.cfa.harvard.edu/viz-bin/VizieR?-source=IV/38/tic)
-order=I
-out.orig=standard
-out=TIC
-out=RAJ2000
-out=DEJ2000
-out=TYC
-out=UCAC4
-out=2MASS
-out=GAIA
GAIA=3344445506744055424
-out=S/G
-out=Ref
-out=pmRA
-out=e_pmRA
-out=pmDE
-out=e_pmDE
-out=r_pm
-out=Teff
-out=s_Teff
-out=logg
-out=s_logg
-out=[M/H]
-out=e_[M/H]
-out=Rad
-out=s_Rad
-out=Mass
-out=s_Mass
-out=LClass
-out=Dist
-out=s_Dist
-out=Ncont
-out=Rcont
-out=e_Mass
-out=E_Mass
-out=e_Rad
-out=E_Rad
-out=e_logg
-out=E_logg
-out=e_Dist
-out=E_Dist
-out=r_Dist
-out=e_Teff
-out=E_Teff
-out=r_Teff
-out=e_RAJ2000
-out=e_DEJ2000
-out=RAOdeg
-out=DEOdeg
-out=e_RAOdeg
-out=e_DEOdeg
-out=Sloan
```

**Comment by JosephKarpinski** [comment]
That's a Vizier web page 60 seconds timeout error.
I override it in the Python example above,  timeout=600.
Did not see a timeout option on the web page.

**Comment by keflavich** [comment]
That's because the configuration item in astroquery is a client timeout - i.e., it's how long your computer will wait for a response from the server.  The timeout error we're seeing on the website is a server-side timeout that does not appear to be configurable.  This is a CDS-side issue and probably needs a CDS helpdesk ticket to resolve.

**Comment by JosephKarpinski** [comment]
<img width="1168" alt="Screenshot 2023-06-26 at 4 53 29 PM" src="https://github.com/astropy/astroquery/assets/37123616/544ec0b8-4256-4b41-94e8-218f7f3ab76e">

**Comment by JosephKarpinski** [comment]
Other issue, specify two columns, get all columns.

<img width="1344" alt="Screenshot 2023-06-26 at 5 07 34 PM" src="https://github.com/astropy/astroquery/assets/37123616/a3255b99-22e0-4f9e-82c4-96311cda714c">

**Comment by JosephKarpinski** [comment]
Will try similar code against a small Vizier table

**Comment by JosephKarpinski** [comment]
Contacted CDC Vizier support:

cds-question@unistra.fr

Hi,

I’m trying to access “https://vizier.cds.unistra.fr/viz-bin/VizieR?-source=IV/38 “ via the portal web page and Python astroquery.vizier.
The web portal times out after 60 seconds when specifying a single row qualified by a qualified Gaia value.
Is there a way of overriding the timeout value?

Astroquery.vizier works on small Vizier tables when using a qualified column value.

Seems to timeout on the server side returning empty results against the above catalog table when specifying a qualified Gaia value.

Have opened an issue with Github.astroquery. Their tests results point to a server side issue.

Astroquery.gaia use of “=“ and number of columns returned verses selected.#2758

The column_filters keyword argument needs to be passed to Vizier, not to query_constraints. e.g.:

Vizier(column_filters={'GAIA':'3344445506744055424'}).query_constraints(catalog='IV/38')
Alternatively, you could pass the constraint directly like you did in one example:

result = Vizier(catalog='IV/38', columns=['TIC', 'GAIA']).query_constraints(GAIA=3344445506744055424)
I do confirm, however, that I don't get a result from these queries. I tried reproducing through the browser and got the following error, which indicates that this is a server-side error:

The following problems were encountered in this VizieR run:
**** 
**** --POSTGRES MSG db=1
**** Report from: stdb_pg,     Status: STDB_ERR 
****ERROR:  canceling statement due to statement timeout 
If you can't find a solution, [report to CDS](mailto:cds-question@unistra.fr?Subject=VizieRerror%20%28%40vizier.cds.unistra.fr%29&Cc=cds-question%40unistra.fr) and insert into your message the following details:
.errorfile=/tmp/VR1788135.err (2023-06-26T20:18:09)
-4
-from=-2
-ref=VIZ6499f2651b3779
-ref=VIZ6499f2651b3779
-out.max=50
-out.form=HTML Table
-out.add=_RAJ,_DEJ
-sort=_r
-oc.form=sexa
-c.eq=J2000
-c.r=  2
-c.u=arcmin
-c.geom=r
-source=[IV/38/tic](https://vizier.cfa.harvard.edu/viz-bin/VizieR?-source=IV/38/tic)
-order=I
-out.orig=standard
-out=TIC
-out=RAJ2000
-out=DEJ2000
-out=TYC
-out=UCAC4
-out=2MASS
-out=GAIA
GAIA=3344445506744055424
-out=S/G
-out=Ref
-out=pmRA
-out=e_pmRA
-out=pmDE
-out=e_pmDE
-out=r_pm
-out=Teff
-out=s_Teff
-out=logg
-out=s_logg
-out=[M/H]
-out=e_[M/H]
-out=Rad
-out=s_Rad
-out=Mass
-out=s_Mass
-out=LClass
-out=Dist
-out=s_Dist
-out=Ncont
-out=Rcont
-out=e_Mass
-out=E_Mass
-out=e_Rad
-out=E_Rad
-out=e_logg
-out=E_logg
-out=e_Dist
-out=E_Dist
-out=r_Dist
-out=e_Teff
-out=E_Teff
-out=r_Teff
-out=e_RAJ2000
-out=e_DEJ2000
-out=RAOdeg
-out=DEOdeg
-out=e_RAOdeg
-out=e_DEOdeg
-out=Sloan

**Comment by keflavich** [comment]
for the column selection issue, pass that argument direct to Vizier:
```python
Vizier(row_limit=5, columns=['GAIA','RAJ2000']).query_constraints(catalog='IV/38')[0]
```

**Comment by JosephKarpinski** [comment]
Update:

My guess is that querying the 1.7 billion row Vizier table by Gaia source_id times out since it is not an index field. TIC_ID is an index field as are Ra and Dec. Since we are trying to lookup the associated TIC_ID give a known Gaia source_id, that’s never going to work given the size of the table. But we also know Ra and Dec values from Gaia. May try querying the Vizier table using those two index fields while waiting for a Vizier help desk response. Assuming Gaia source_id was not made an index because of null values.
________________________________

**Comment by JosephKarpinski** [comment]
This is what I wanted:

<img width="1735" alt="Screenshot 2023-06-27 at 4 12 27 PM" src="https://github.com/astropy/astroquery/assets/37123616/8dbf3763-6060-4ce1-a975-16e85a743179">



No reply from Vizier help desk yet.



from astroquery.vizier import Vizier

from astropy.table import Table


xRa  = 263.8292170824
xDec = -50.53091926887

result = Vizier(row_limit=5, timeout=600, columns=['TIC', 'GAIA', 'RAJ2000','DEJ2000'], column_filters={'RAJ2000':str(xRa), 'DEJ2000':str(xDec)}).query_constraints(catalog='IV/38')[0]

print(result)


   TIC             GAIA            RAJ2000         DEJ2000    
                                     deg             deg      
---------- ------------------- --------------- ---------------
1517176209 5946383355188239104 263.82921708248 -50.53091926887

**Comment by JosephKarpinski** [comment]
Thank you!
