### ISSUE TITLE
rename cds into MOCserver

### ISSUE THREAD

**Issue by ManonMarchand** [astropy/astroquery#2764]
Hello astroquery, 

# the issue

Currently, the module that allows access to the MOCserver is named CDS. This is pretty vague because at the CDS we also have other services (vizier, simbad, hips2fits, sesame, xmatch...). 

It also makes the MOCserver module really hard to find for newcomers. 

# the question

How hard would it be to rename the `cds` module into `mocserver` ?

**Comment by bsipocz** [comment]
I'm fully in support for such a rename, and there is some similar precedent of restructuring (less about rename, but moving around things in the namespace). We just need to provide a long deprecation period.

> How hard would it be to rename the cds module into mocserver ?

It should rather straightforward. Move and rename what is currently there, and then create a new `cds` module, with an import and deprecation in it. E.g. `astroquery.irsa` can be an example.

Also, if you would prefer, you can move all CDS modules under CDS. We did that for IPAC about a year ago. I suspect it would affect a lot of users though, as my suspicion is that there are a lot of usage for `simbad` and `vizier`. That being said, if that brings any benefits to CDS, I would be in support of such a restructuring.

**Comment by ManonMarchand** [comment]
Thanks for the answer and the tips on how to proceed, you'll receive a PR soon 🙂 

I'd rather not change the other modules but thanks for the proposition!

@bmatthieu3 : just keeping you in the loop

**Comment by ManonMarchand** [comment]
PS: internally we see that more than 40% of queries come from astroquery. For VizieR only, the total is around 1M queries a day.

**Comment by bsipocz** [comment]
Wow, that's a lot 🤯 . If you see any ways to optimise stuff, so let us know, and of course PRs are always welcome.

**Comment by ManonMarchand** [comment]
Closing as the PR is on its way

**Comment by bsipocz** [comment]
> Closing as the PR is on its way

@ManonMarchand - we tend to follow the workflow that merging PR is the trigger for closing an issue (as technically this is still outstanding until the PR is merged). Github allows cross linking, so the closure can be done automatically (https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
