### ISSUE TITLE
AtomicLineList parsing issue

### ISSUE THREAD

**Issue by shahbandeh** [astropy/astroquery#2767]
Hi Astroquery, I'm getting the following error with the AtomicLineList today, and not sure how to proceed. It was working fine on Tuesday. Could it be related to yesterday's update for the CDMS table? 
```
from astropy import units as u
from astropy.units import Quantity
from astroquery.atomic import AtomicLineList
AtomicLineList.query_object(wavelength_range=(0.5 * u.um, 1 * u.um), wavelength_type='vacuum',element_spectrum='H')
```
```
/Users/mshahbandeh/miniconda3/envs/June/lib/python3.11/site-packages/astroquery/atomic/core.py:309: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 309 of the file /Users/mshahbandeh/miniconda3/envs/June/lib/python3.11/site-packages/astroquery/atomic/core.py. To get rid of this warning, pass the additional argument 'features="html5lib"' to the BeautifulSoup constructor.

  bs = BeautifulSoup(response.text, 'html5')
/Users/mshahbandeh/miniconda3/envs/June/lib/python3.11/site-packages/astroquery/atomic/core.py:249: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 249 of the file /Users/mshahbandeh/miniconda3/envs/June/lib/python3.11/site-packages/astroquery/atomic/core.py. To get rid of this warning, pass the additional argument 'features="html5lib"' to the BeautifulSoup constructor.

  data = StringIO(BeautifulSoup(response.text, 'html5').find('pre').text.strip())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 4
      2 from astropy.units import Quantity
      3 from astroquery.atomic import AtomicLineList
----> 4 AtomicLineList.query_object(wavelength_range=(0.5 * u.um, 1 * u.um), wavelength_type='vacuum',element_spectrum='H')

File ~/miniconda3/envs/June/lib/python3.11/site-packages/astroquery/atomic/core.py:165, in AtomicLineListClass.query_object(self, wavelength_range, wavelength_type, wavelength_accuracy, element_spectrum, minimal_abundance, depl_factor, lower_level_energy_range, upper_level_energy_range, nmax, multiplet, transitions, show_fine_structure, show_auto_ionizing_transitions, output_columns, cache, get_query_payload)
    163 if get_query_payload:
    164     return input
--> 165 table = self._parse_result(response)
    166 return table

File ~/miniconda3/envs/June/lib/python3.11/site-packages/astroquery/atomic/core.py:249, in AtomicLineListClass._parse_result(self, response)
    248 def _parse_result(self, response):
--> 249     data = StringIO(BeautifulSoup(response.text, 'html5').find('pre').text.strip())
    250     # `header` is e.g.:
    251     # "u'-LAMBDA-VAC-ANG-|-SPECTRUM--|TT|--------TERM---------|---J-J---|----LEVEL-ENERGY--CM-1----'"
    252     # `colnames` is then
    253     # [u'LAMBDA VAC ANG', u'SPECTRUM', u'TT', u'TERM', u'J J',
    254     #  u'LEVEL ENERGY  CM 1']
    256     header = data.readline().strip().strip('|')

AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by keflavich** [comment]
The CDMS change should not have affected the atomic line list tools at all.

The response from this query is:
```html
'<HTML>\n<HEAD><TITLE>Query results</TITLE></HEAD>\n<BODY BACKGROUND="dot_yellow.gif">\n<CENTER><H2>Query results</H2></CENTER>\n<P>\n*** ERROR: request form contains no information.\n    The client and server are not communicating. properly.\n    Please restart your browser or reboot your computer.\n    If this does not help, report the problem to p.vanhoof@oma.be.\n<BR><HR><BR>\n<a HREF=index.html><img src=left_arrow.gif width=25 height=25 align=middle hspace=8 alt="GO"></a>Back to the <a HREF=index.html>request form</a>.\n</BODY>\n</HTML>\n'
```

I'm guessing this is an upstream change.

**Comment by keflavich** [comment]
This works:
```python
payload = AtomicLineList.query_object(wavelength_range=(5000,10000)*u.AA, wavelength_type='vacuum',element_spectrum='H', get_query_payload=True)
import requests
resp = requests.post(AtomicLineList.FORM_URL, data=payload)
resp.text
```
so the problem is somewhere in the metadata / header data.  I've tried changing user-agents and that didn't fix it.  Unclear what's going on.

**Comment by bsipocz** [comment]
Could you add a full copy-pasteable example in the OP, so we can easily reproduce the issue?

**Comment by shahbandeh** [comment]
> Could you add a full copy-pasteable example in the OP, so we can easily reproduce the issue?

Added.

**Comment by bsipocz** [comment]
Whether this is an upstream change or not, we should gracefully handle empty query responses (which I double checked, `atomic` does already), as well as errors, so I would certainly call this at least one bug.

(similar issue: https://github.com/astropy/astroquery/issues/1838, but https://github.com/astropy/astroquery/issues/2212 is for the same problem for `sdss`)

**Comment by pvh513** [comment]
I maintain the Atomic Line List and this failure has undoubtedly been caused by the fact that it has moved to a new virtual server with a new URL. The old URL should be automatically forwarded to the new one (and that certainly works if you go directly to the website in your browser) but I guess some use cases have been overlooked. Can you post here how the Atomic Line List is called by astropy? Other sites or scripts may be experiencing similar problems. The new URLs for the websites are https://linelist.pa.uky.edu/atomic/ and https://linelist.pa.uky.edu/newpage/

**Comment by keflavich** [comment]
Thanks @pvh513 .  We should change the URL.  The surprising thing is that the redirect isn't being respected.  It seems that the post to the CGI URL is returning HTTP 200 instead of 302, as it should be for a redirect.

**Comment by pvh513** [comment]
I can contact the sysadmins to see if we can fix this. They have been helpful. But I would need a bit more detail for that so that they know what to do. In the long run it would be better to update the URLs, but fixing the forwarding would fix the problem for everybody immediately.

**Comment by bsipocz** [comment]
@keflavich - while the URL is not fix, would you have any capacity to fix the error handling on the parsing side? Then once it's done we should fix the url :)

**Comment by pvh513** [comment]
I have notified the sysadmins of this ticket. So if you post more details here about what is going wrong, we can look into that

**Comment by pvh513** [comment]
To be completely clear, there are not supposed to be any server-side changes in functionality other than the automatic forward. The sysadmins posted this:

as far as I can tell, accessing the CGI scripts at the old URLs returns a 302 redirect to the current URL for the CGI script.  That is, as far as I know, the proper way to handle it on the server side.

curl -i -X POST https://www.pa.uky.edu/~peter/atomic/query.cgi
HTTP/1.1 302 Found
Date: Fri, 07 Jul 2023 12:51:21 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16
Strict-Transport-Security: max-age=31536000; includeSubDomains
Location: https://linelist.pa.uky.edu/atomic/query.cgi
