### ISSUE TITLE
astroquery.mpc.MPC.get_observations() raises an exception when trying to parse radar data

### ISSUE THREAD

**Issue by aripollak** [astropy/astroquery#2804]
This command fails: `python -c 'from astroquery.mpc import MPC; MPC.get_observations(612094)'` with error `ValueError: Invalid character at col 0 in angle 'C'`. It looks like the astroquery code is not expecting radar data, which is a slightly different format and is spread across two rows.

```
from astroquery.mpc import MPC
MPC.get_observations(612094)
```

* [Human-readable version of that asteroid](https://minorplanetcenter.net/db_search/show_object?utf8=%E2%9C%93&object_id=612094)
* [Description of the format of the raw radar data](https://www.minorplanetcenter.net/iau/info/RadarObs.html)

<details><summary>Full Backtrace</summary>
<pre>
Traceback (most recent call last):
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angle_formats.py", line 307, in parse
    found_angle, found_unit = self._thread_local._parser.parse(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/utils/parsing.py", line 116, in parse
    return self.parser.parse(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/extern/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/extern/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
                ^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/extern/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angle_formats.py", line 157, in t_error
    raise ValueError(f"Invalid character at col {t.lexpos}")
ValueError: Invalid character at col 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ari/venv/lib/python3.11/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astroquery/mpc/core.py", line 1294, in _parse_result
    coo = SkyCoord(ra=data['RA'], dec=data['DEC'],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate.py", line 339, in __init__
    skycoord_kwargs, components, info = _parse_coordinate_data(
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate_parsers.py", line 254, in _parse_coordinate_data
    valid_components.update(_get_representation_attrs(frame, units, kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate_parsers.py", line 645, in _get_representation_attrs
    valid_kwargs[frame_attr_name] = repr_attr_class(value, unit=unit)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angles.py", line 667, in __new__
    self = super().__new__(cls, angle, unit=unit, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angles.py", line 140, in __new__
    angle = [Angle(x, unit, copy=False) for x in angle]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angles.py", line 140, in <listcomp>
    angle = [Angle(x, unit, copy=False) for x in angle]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angles.py", line 118, in __new__
    angle, angle_unit = form.parse_angle(angle, unit)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angle_formats.py", line 399, in parse_angle
    return _AngleParser().parse(angle, unit, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/venv/lib/python3.11/site-packages/astropy/coordinates/angle_formats.py", line 312, in parse
    raise ValueError(f"{str(e)} in angle {angle!r}") from e
ValueError: Invalid character at col 0 in angle 'C'

</pre>
</details>

**Comment by bsipocz** [comment]
The radar data snippet from the observations table:

```
1999 07 18.96198 | 19 36 10.88 | +39 10 19.1 |   | 046 – Klet Observatory, Ceske Budejovice | MPS 5646
-- | -- | -- | -- | -- | --
1999 07 19.131944 | C |   | 25 3 | 253 – Goldstone DSS 14, Fort Irwin | JP LRS
1999 07 19.131944 |   | -    1553 | 60 25 3 | 253 – Goldstone DSS 14, Fort Irwin | JP LRS
1999 07 19.201389 | C |   | 25 3 | 253 – Goldstone DSS 14, Fort Irwin | JP LRS
1999 07 19.201389 |   | -    1616 | 60 25 3 | 253 – Goldstone DSS 14, Fort Irwin | JP LRS
1999 07 19.220833 | 19 36 23.76 | +41 00 27.9 |   | 673 – Table Mountain Observatory, Wrightwood | MPS 5646
1999 07 19.223438 | 19 36 23.26 | +41 01 34.7 |   | 673 – Table Mountain Observatory, Wrightwood | MPS 5646

```

cc @mkelley

**Comment by mkelley** [comment]
Thanks for the report (and I'll be sure to set my github status next time I'm unavailable).

I suppose these values (RA and Dec) should be masked in the output table.  The observational data are parsed with `astropy.io.ascii`, so these lines would need to be filtered out and handled separately, or the observational data would need to be parsed line by line to handle special cases like this.

What I find curious is that spacecraft observations also use a 2-line format, but they are returned as a single entry in the JSON results.  For anyone curious, find observatory code 245 (Spitzer Space Telescope) in https://www.minorplanetcenter.net/search_db/observations?number=144&object_type=P&table=observations and compare to observatory code 253 (Goldstone) for the above object in https://www.minorplanetcenter.net/search_db/observations?number=612094&table=observations .  The Goldstone results are returned as two entries, whereas the Spitzer results are returned as one:

A 2-line Spitzer observation:
```
0144P         S2007 07 09.96065 22 09 45.458-06 24 54.06                63355245
0144P         s2007 07 09.96065 2 -0.44276278 -0.02756464 -0.02981825   63355245
```
becomes:
```json
{"designation":null,"discovery_flag":null,"number":144,"object_type":"P","observation_date":"2007 07 09.96065","observatory_code":"245","original_record":"0144P S2007 07 09.96065 22 09 45.458-06 24 54.06 633552450144P s2007 07 09.96065 2 -0.44276278 -0.02756464 -0.02981825 63355245"}
```

But this radar observation:
```
z2094J99N02W  r1999 07 19.131944C                        5000       253 JPLRS253
z2094J99N02W  R1999 07 19.131944               -    15534500   8560 253 JPLRS253
```
becomes:
```json
[{"designation":null,"discovery_flag":" ","number":612094,"object_type":"M","observation_date":"1999 07 19.131944","observatory_code":"253","original_record":"z2094J99N02W r1999 07 19.131944C 5000 253 JPLRS253"},
{"designation":null,"discovery_flag":" ","number":612094,"object_type":"M","observation_date":"1999 07 19.131944","observatory_code":"253","original_record":"z2094J99N02W R1999 07 19.131944 - 15534500 8560 253 JPLRS253"}]
```

I'll open a help desk ticket with the MPC to see if this is an error before.  If so, I think it should be addressed before we can proceed with a fix for this issue.

**Comment by mkelley** [comment]
I've heard back from the MPC and they will likely filter the radar observations from their output as the data returned does not have much meaning.  I'll provide an update when that is finalized.

**Comment by bsipocz** [comment]
Wonderful, thank you for the update.

**Comment by mkelley** [comment]
This has been resolved:
```
>>> MPC.get_observations(612094, cache=False)
<QTable length=180>
number  desig   discovery note1 note2 ...         DEC           mag   band observatory
                                      ...         deg           mag                   
 str5    str8      str1    str1  str1 ...       float64       float64 str1     str3   
------ -------- --------- ----- ----- ... ------------------- ------- ---- -----------
 z2094 1999 NW2         *    --     C ... -15.066361111111112    15.4   --         704
 z2094 1999 NW2        --    --     C ... -14.950277777777776    15.7   --         704
 z2094 1999 NW2        --    --     C ... -14.833527777777778    16.1   --         704
 z2094 1999 NW2        --    --     C ... -14.717194444444445    15.9   --         704
 z2094 1999 NW2        --    --     C ... -14.600722222222222    15.7   --         704
 z2094 1999 NW2        --    --     C ...  -5.777666666666667    15.2   --         704
 z2094 1999 NW2        --    --     C ...  -5.650638888888889    15.4   --         704
 z2094 1999 NW2        --    --     C ...  -5.524305555555555    15.6   --         704
 z2094 1999 NW2        --    --     C ...  -5.396888888888889    17.1   --         704
 z2094 1999 NW2        --    --     C ...  -5.256861111111111    16.2   --         704
 z2094 1999 NW2        --    --     C ...  -5.126888888888889    16.4   --         704
   ...      ...       ...   ...   ... ...                 ...     ...  ...         ...
 z2094 1999 NW2        --    --     C ...   47.05880555555555    20.5    V         G96
 z2094 1999 NW2        --    --     C ...   47.05847222222222    20.8    V         G96
 z2094 1999 NW2        --    --     C ...   46.52930555555555    21.1    R         H01
 z2094 1999 NW2        --    --     C ...   46.52488888888889    20.4    R         H01
 z2094 1999 NW2        --    --     C ...   46.51841666666667    20.9    R         H01
 z2094 1999 NW2        --    --     C ...   46.51638888888889    20.9    R         H01
 z2094 1999 NW2        --     2     C ...  46.497683333333335    21.2    R         568
 z2094 1999 NW2        --     2     C ...   46.49716111111111    21.0    R         568
 z2094 1999 NW2        --     2     C ...            46.49665    21.2    R         568
 z2094 1999 NW2        --    --     C ... -10.381675000000001   24.29    G         T12
 z2094 1999 NW2        --    --     C ... -10.387238888888888   24.21    G         T12
 z2094 1999 NW2        --    --     C ...  -35.52546666666667   22.37    G         T12
```

**Comment by aripollak** [comment]
@mkelley looks like this is failing again. A banner on https://minorplanetcenter.net says it's currently in `MPC Preparation Mode`, but based on https://minorplanetcenter.net/iau/info/MPCOpStatus.html I'm not sure that's supposed to change how the data is returned.

**Comment by bsipocz** [comment]
@aripollak - the example, `>>> MPC.get_observations(612094, cache=False)`, keeps working for me. Are you sure you have the latest dev version? (pip installed with the `--pre` option?)

**Comment by aripollak** [comment]
It's working again now; I first tried it about 2 hours ago and saved an unparseable cache file, but after clearing my astroquery cache it works.
