### ISSUE TITLE
Turn all "TODO" items in source code into official Issues

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#281]
There are many instances of "TODO" in comments in the source.  Each should be given its own issue (or simply resolved) and the TODO marked with the issue #.

**Comment by Phantsure** [comment]
i think few of the above mentioned have been completed already, if this issue should be updated then should be marked tick.(didn't check all but to point a few fermi/tests/test_fermi.py, utils/common.py, etc )

**Comment by bsipocz** [comment]
There are still plenty of `"TODO"` left, at least in these files:
```
astroquery/sdss/tests/test_sdss.py
astroquery/sdss/tests/test_sdss.py
astroquery/sdss/core.py
astroquery/irsa_dust/tests/test_irsa_dust.py
astroquery/irsa_dust/core.py
astroquery/nrao/core.py
astroquery/query.py
astroquery/ukidss/tests/test_ukidss.py
astroquery/alfalfa/tests/test_alfalfa.py
astroquery/alma/tests/test_alma_remote.py
astroquery/alma/core.py
astroquery/utils/commons.py
astroquery/fermi/core.py
astroquery/fermi/core.py
astroquery/fermi/core.py
astroquery/eso/tests/test_eso_remote.py
astroquery/eso/tests/data/vvv_sgra_form.html
astroquery/eso/core.py
astroquery/eso/core.py
astroquery/vizier/tests/test_vizier.py
astroquery/gama/core.py
docs/api.rst
```

**Comment by Phantsure** [comment]
#1397 added for  `astroquery/alfalfa/tests/test_alfalfa.py 35(42)`
This way right?

**Comment by bsipocz** [comment]
This more of less happened over the years. Now we have both the TODOs and the separate issues, so I'm closing this tracking issue.
