### ISSUE TITLE
wrong values on gaia id when ADQL TAP query in gaia and upload table (works with gaia interface)

### ISSUE THREAD

**Issue by giorgio-grag** [astropy/astroquery#2813]
If I use astroquery gaia with the following query (the votable contains about 10000 record of coordinates and magnitude)

```
from astropy.table import Table
from astroquery.gaia import Gaia
import pandas as pd

Gaia.login(user='gmazzacu', password='xxxxxx')

job = Gaia.upload_table(upload_resource=r'C:\Users\giorgio\Downloads\analisys_data.vot',
                        table_name="t1", format="VOTable")

numStelle = 1000000
job = Gaia.launch_job(query=f"""
            select top {numStelle} 
            g2.source_id as Source, dr2toedr3.dr2_source_id, dr2toedr3.dr3_source_id, g2.ra, g2.dec,
            DISTANCE(
                POINT(u.ra, u.dec),
                POINT(g2.ra, g2.dec)
            ) * 3600. AS d2d0
            from user_gmazzacu.t1 as u left outer join gaiadr2.gaia_source as g2
            on  1 = CONTAINS(
                    POINT(u.ra, u.dec),
                    CIRCLE(g2.ra, g2.dec, 25 / 3600.)
                )
            and  u.Median_magnitude + 21.92 - g2.phot_g_mean_mag < 4
            left outer JOIN gaiaedr3.dr2_neighbourhood AS dr2toedr3
            ON dr2toedr3.dr2_source_id = g2.source_id
            left outer join gaiadr3.vari_summary as g3
            on dr2toedr3.dr3_source_id = g3.source_id
                      
""", verbose=True )    
```
it return a wrong gaia_ids
	Source	dr2_source_id	dr3_source_id	ra	dec	d2d0
0	5781900165177022336	5781900165177022464	5781900165177022464	236.38048649702463	-74.85578621518394	16.15224404575615
1	5781900165177019008	5781900165177019392	5781900165177019392	236.41908279720144	-74.85269710226933	22.597090105178218
2	5781900165179347968	5781900165179347968	5781900165179347968	236.38181920476774	-74.85823856149432	17.79566330498827
3	5781900160883858432	5781900160883858432	5781900160883858432	236.38632709165276	-74.85300780866383	13.965275611378505

If I made the same ADQL query from archive gaia site it give the correct values
Source | dr2_source_id | dr3_source_id | radeg | decdeg | d2d0
5781900165177022336 | 5781900165177022336 | 5781900165177022336 | 236.38048649702463 | -74.85578621518394 | 16.15224404575615
5781900165177019008 | 5781900165177019008 | 5781900165177019008 | 236.41908279720144 | -74.85269710226933 | 22.597090105178218
5781900165179347968 | 5781900165179347968 | 5781900165179347968 | 236.38181920476774 | -74.85823856149432 | 17.79566330498827

**Comment by bsipocz** [comment]
cc @jespinosaar

**Comment by jespinosaar** [comment]
cc @esdc-esac-esa-int

**Comment by giorgio-grag** [comment]
I get that the to_pandas function give me problem.
job.get_results() works fine
       Source          dr2_source_id    ...        d2d0       
                  
       int64               int64        ...      float64      
------------------- ------------------- ... ------------------
5781900165177022336 5781900165177022336 ...  16.15224404575615
5781900165177019008 5781900165177019008 ... 22.597090105178218
5781900165179347968 5781900165179347968 ...  17.79566330498827
5781900160883858432 5781900160883858432 ... 13.965275611378505

after use the to_pandas function, give me the wrong data:
                     Source        dr2_source_id  ...        dec       d2d0
0       5781900165177022336  5781900165177022464  ... -74.855786  16.152244
1       5781900165177019008  5781900165177019392  ... -74.852697  22.597090
2       5781900165179347968  5781900165179347968  ... -74.858239  17.795663
3       5781900160883858432  5781900160883858432  ... -74.853008  13.965276

I have the Version: 1.5.2 pandas and the last stable of astroquery

**Comment by giorgio-grag** [comment]
it works with pandas 2.0.3 version, not a astroquery problem.
