### ISSUE TITLE
Add tests for MultiDark

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#282]
Even though MultiDark has not been merged (https://github.com/astropy/astroquery/pull/267), we can add tests for it in a separate PR branched off of @agroener's branch.

This would be a great GSOC candidate PR to attempt.

Note that the remote queries are easier to write than the non-remote queries.

**Comment by souravsingh** [comment]
I wish to do this.How do I start?

**Comment by keflavich** [comment]
@souravsingh First, try using the multidark module and see if you can get some good results.  If you succeed, try turning the examples into tests that look like those in other modules.  The best references for this are probably the SIMBAD, ESO, and ALMA modules.  Try setting up a remote test first.  We can offer you feedback & guidance along the way once you've gotten started.

**Comment by agroener** [comment]
@adamginsburg Actually - the multidark module is (or should be) deprecated.

The multidark project (multidark.org) has been part of the cosmosim project (cosmosim.org) for quite some time now. I have some tests for cosmosim already written. I'll push them up after work today if at all possible. 

@souravsingh There are a couple of things I would like to update about this package though. I'll try to create an issue for what I'd like (mainly: 1) finish the text/email alerts for jobs which complete successfully, and 2) trying to use multithreading, such that queries being run do not eat up a terminal session). More details to follow this evening.

**Comment by agroener** [comment]
This issue should be closed (See cosmosim tests issue https://github.com/astropy/astroquery/issues/457).

**Comment by keflavich** [comment]
Thanks @agroener, I had forgotten about the renaming.  Let's move further discussion to #457 as suggested.
