### ISSUE TITLE
BUG: magpis is broken: 404

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2827]
We started to see 404 responses, even though the main URL seems to be live (https://third.ucllnl.org/cgi-bin/gpscutout)

```
import astropy.units as u
from astropy.coordinates import SkyCoord
from astroquery.magpis import Magpis
image = Magpis.get_images(SkyCoord(10.5, 0.0, unit=(u.deg, u.deg), frame='galactic'), image_size='1 arcmin')
```

cc @keflavich

**Comment by keflavich** [comment]
I see problems on their web page - even though the main URL is live, it's unresponsive.  Looks like a server error.  I'll inform them

**Comment by keflavich** [comment]
Rick White confirmed that there was an issue and they have now fixed it.  I verified using the website that this is fixed, but still need to check astroquery.

**Comment by bsipocz** [comment]
yeap, all good now.
