### ISSUE TITLE
[DOCS] Fix README typos

### ISSUE THREAD

**Issue by singodiyashubham87** [astropy/astroquery#2865]
There are some typos in the README file which need to be fixed, Kindly assign me this issue so that I can fix them.

![image](https://github.com/astropy/astroquery/assets/93720428/f290e4ad-56c3-4f19-8f3c-a18acac97402)

**Comment by keflavich** [comment]
What typos?  You're welcome to write a pull request, but your screenshot has underlined in red text that is correct in its present form.

**Comment by singodiyashubham87** [comment]
@keflavich 
> "much:" will be replaced by "much;"
> "e.g." will be replaced by "e.g.,"

**Comment by keflavich** [comment]
These are not errors, they are flexible conventions.  In the former case, the colon is intended as the second phrase is a consequence of the former, though a semicolon would also be fine here.  In the latter case, there are two conventions for commas after `e.g.` and `i.e.`, and both are allowed as long as they are used consistently.  Let's leave it as is.
