### ISSUE TITLE
Feature: Adding contributors section to the README.md file

### ISSUE THREAD

**Issue by Kalyanimhala** [astropy/astroquery#2868]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/astropy/astroquery/assets/147402107/807e9cad-e35f-49a4-9513-a51dd3b1271a)

**Comment by Kalyanimhala** [comment]
@keflavich  kindly assign me this issue, I want to work on it. Thank You!

**Comment by bsipocz** [comment]
Contributors are accessible on the right-hand side on github landing page, effectively the same url the readme is rendered into, so I'm closing this as something unnecessary. You are welcome to work on astroquery, but please pick something from the couple hundreds of already identified issues as those would indeed improve the package.
