### ISSUE TITLE
Make web interactions "replayable" for testing purposes

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#287]
Following https://github.com/astropy/astroquery/pull/286#issuecomment-37168846, a great suggestion by @jwoillez.

What we need is a way to run our command-line interactions and save the response of the website at each step, which means both the http headers and the html that is returned.  Then we can save these and "replay" them as tests offline.  This will greatly simplify the process of writing offline tests.

Add to this suggestion as you see fit!

**Comment by bsipocz** [comment]
I'm not sure this is still on the table. @keflavich?

**Comment by keflavich** [comment]
Nah, let's close this.
