### ISSUE TITLE
(Doc Style) Long text in the side menu overlaps with the main text in the docs

### ISSUE THREAD

**Issue by zoghbi-a** [astropy/astroquery#2875]
A page like [the following](https://astroquery.readthedocs.io/en/latest/api/astroquery.mast.MastMissionsClass.html#astroquery.mast.MastMissionsClass) in the documentation shows the text from the side menu overlapping with text in the main text.

**Comment by bsipocz** [comment]
Yeap, this is a known bug with the astropy sphinx scheme, switching it out for the pydata one will solve the issue. (#2416)

**Comment by zoghbi-a** [comment]
Thanks. Feel free to delete this issue.

**Comment by bsipocz** [comment]
I'm closing this then as a duplicate as I don't expect anyone would cook up a solution that is different from #2416.
