### ISSUE TITLE
OverflowError in SDSS.query_sql

### ISSUE THREAD

**Issue by jkrick** [astropy/astroquery#2879]
I have a function which queries SDSS which is no longer working.

My function looks something like:
`    # Define the query
    query = "SELECT TOP " + str(num) + " specObjID, ra, dec, z FROM SpecObj \
    WHERE ( z > 0.0 AND z < 2.0 AND class='QSO' AND zWARNING=0 )"

     res = SDSS.query_sql(query, data_release = 16)
`

And the full traceback: 

`OverflowError                             Traceback (most recent call last)
Cell In[17], line 24
     18 #now get some "normal" QSOs for use in the classifier
     19 #there are ~500K of these, so choose the number based on
     20 #a balance between speed of running the light curves and whatever 
     21 #the ML algorithms would like to have
     23 num_normal_QSO = 50
---> 24 get_SDSS_sample(coords, labels, num_normal_QSO)
     26 # remove duplicates and attach an objectid to the coords
     27 sample_table = clean_sample(coords, labels)

File /stage/irsa-staff-jkrick/fornax-demo-notebooks/light_curves/code_src/sample_selection.py:346, in get_SDSS_sample(coords, labels, num, verbose)
    343 if num>0:
    344     print("query", query)
--> 346     res = SDSS.query_sql(query, data_release = 16)
    347     print('res', res)
    349     SDSS_coords = [SkyCoord(ra, dec, frame='icrs', unit='deg') for ra, dec in zip(res['ra'], res['dec'])]

File /opt/conda/lib/python3.11/site-packages/astroquery/utils/class_or_instance.py:25, in class_or_instance.__get__.<locals>.f(*args, **kwds)
     23 def f(*args, **kwds):
     24     if obj is not None:
---> 25         return self.fn(obj, *args, **kwds)
     26     else:
     27         return self.fn(cls, *args, **kwds)

File /opt/conda/lib/python3.11/site-packages/astroquery/utils/process_asyncs.py:29, in async_to_sync.<locals>.create_method.<locals>.newmethod(self, *args, **kwargs)
     27 if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28     return response
---> 29 result = self._parse_result(response, verbose=verbose)
     30 self.table = result
     31 return result

File /opt/conda/lib/python3.11/site-packages/astroquery/sdss/core.py:1045, in SDSSClass._parse_result(self, response, verbose)
   1043     for id_column in ('objid', 'specobjid', 'objID', 'specobjID', 'specObjID'):
   1044         if id_column in arr.columns:
-> 1045             arr[id_column] = arr[id_column].astype(np.int64)
   1047 if len(arr) == 0:
   1048     return None

OverflowError: Python int too large to convert to C long`

**Comment by bsipocz** [comment]
This is a genuine bug as e.g. `12111502248447856640` overflows int64. But we can still use uits instead. PR is coming.
