### ISSUE TITLE
Trying to use Yale Bright Stars Catalog but failing to do so

### ISSUE THREAD

**Issue by StandinKP** [astropy/astroquery#2888]
Hi, I am trying to load the Yale bright stars catalog with the following code but it is always printing list index out of range. I am able to browse the catalog using the online vizier web query tool but failing to do so through the code. Am I doing anything wrong? 
    
Here is the vizier link if need reference: `http://vizier.cds.unistra.fr/cgi-bin/VizieR?-source=V/50` 
```from astroquery.vizier import Vizier

catNum = 'V/50/catalog'

try:
    v = Vizier(columns=['*'], row_limit=-1, vizier_server="vizier.cds.unistra.fr")
    Q = v.query_region(SkyCoord(ra = raImage, dec = decImage, unit = (u.deg, u.deg)), radius = str(boxsize)+'m', catalog=catNum, cache=False)
    print(Q[0])
except Exception as e:
    print(e)
    print('I cannnot reach the Vizier database. Is the internet working?')```

**Comment by keflavich** [comment]
You haven't given us enough information to be sure, but you are almost certainly just querying regions on the sky where there are no entries in the catalog.

**Comment by StandinKP** [comment]
I'll try redoing that. Thanks
