### ISSUE TITLE
Fix name of RingNode class

### ISSUE THREAD

**Issue by matthewtiscareno** [astropy/astroquery#2896]
The name of the `RingNode` class refers to the PDS Ring-Moon Systems Node (of which I'm the manager), commonly abbreviated as the RMS Node.  Our previous name was the PDS Rings Node.  The current class name is incorrect.  Our first preference would be `RMSNode`, and second preference would be `RingsNode`.

All references to the RMS Node in documentation should also be updated.

**Comment by bsipocz** [comment]
We can do a rename and it doesn't have to come with a deprecation if done before v0.4.7 is tagged (so in the coming few weeks).

cc @emolter

**Comment by emolter** [comment]
Thanks Brigitta, I will work on it early next week - I'm at a conference
this week

**Comment by bsipocz** [comment]
at AGU? too bad I didn't manage to get my travel sorted out :(

**Comment by emolter** [comment]
yes, Matt and I were at AGU and we discussed this change there. Please let me know if this looks good to you

**Comment by bsipocz** [comment]
Fixed in #2900
