### ISSUE TITLE
TapPlus parse simbad fail with non ascii char

### ISSUE THREAD

**Issue by qq332982511** [astropy/astroquery#2916]
```python
from astroquery.utils.tap.core import TapPlus
simbad = TapPlus(url="http://simbad.u-strasbg.fr/simbad/sim-tap")
rst = simbad.launch_job("SELECT title FROM ref WHERE oidbib='423320'")
print(rst.get_results().to_pandas().to_string())
```
error log:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 13: ordinal not in range(128)
```

**Comment by bsipocz** [comment]
I'm afraid this is an upsteam issue, the returned VOtable seems to violate the votable linter. I'm inclined to close this issue as we can't do much about it in astroquery and as I detail it out below, it doesn't involve any of the functionalities from here.

Some other issues: Please not the big red warning at the top of the documentation, we do not support direct usage of TapPlus, please use PyVO instead. (but this doesn't effect the problem, the `UnicodeDecodeError` just as present with it.

cc @ManonMarchand for the upstream simbad issue (it also present on the branch of #2856) 

Here is the votable, if that's of any help:

```
<?xml version="1.0" encoding="utf-8"?>
<VOTABLE version="1.3" xmlns="http://www.ivoa.net/xml/VOTable/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.3 http://www.ivoa.net/xml/VOTable/v1.3">
<RESOURCE type="results">
<INFO name="QUERY_STATUS" value="OK"/>
<INFO name="PROVIDER" value="CDS">SIMBAD TAP Service</INFO>
<INFO name="QUERY" value="SELECT title FROM ref WHERE oidbib='423320'"/>
<TABLE name="result_S1704486906566">
<FIELD arraysize="*" datatype="char" name="title" ucd="meta.title" xtype="adql:CLOB">
<DESCRIPTION>Title</DESCRIPTION>
</FIELD>
<DATA>
<BINARY>
<STREAM encoding='base64'>
AAAASkRldGVjdGlvbiBvZiC0IFNjdXRpIFB1bHNhdG9ycyBpbiB0aGUgRWNsaXBz
aW5nIEJpbmFyaWVzIE9ic2VydmVkIGJ5IFRFU1Mu
</STREAM>
</BINARY>
</DATA>
</TABLE>
</RESOURCE>
</VOTABLE>
```

**Comment by ManonMarchand** [comment]
Thanks for the report and the perfect minimal example. 

The error is upstream indeed. This field should be unicodechar and not char. 

While waiting for the fix to be done on our side (might take a few days), note that you can open this votable with topcat (its parser is more permissive on types) or get the table in an other format through pyvo (fits, json and csv should work)

**Comment by aoberto** [comment]
this should be solved now, sorry for the delay

**Comment by bsipocz** [comment]
Thanks @aoberto!
