### ISSUE TITLE
Problem with astroquery in docker container

### ISSUE THREAD

**Issue by lupecsan** [astropy/astroquery#2930]
When I run this simple piece of code:
`import astropy.units as u
from astropy.coordinates import SkyCoord
from astroquery.vizier import Vizier

# Definir las coordenadas y el radio de búsqueda
coord = SkyCoord(ra=180.0, dec=30.0, unit=(u.deg, u.deg), frame='icrs')
radio_de_busqueda = 5.0 * u.arcsec

# Consultar el Catálogo Gaia DR3 utilizando Vizier
v = Vizier(columns=['RA_ICRS', 'DE_ICRS', 'Plx', 'e_Plx', 'Gmag', 'e_Gmag', 'BPmag', 'e_BPmag', 'RPmag', 'e_RPmag', 'angDist'])
v.ROW_LIMIT = -1  # Para obtener todos los resultados

resultado = v.query_region(coord, radius=radio_de_busqueda, catalog='I/355/gaiaedr3')`

I always receive this error message:

PermissionError: [Errno 13] Permission denied: '/.astropy'

I tried to include these lines of code:  
`cache_folder='./cache_astropy'
Vizier.cache_location=cache_folder`

but the result was always the same. On the other hand, when I run a GAIA catalogue search like this:
`Gaia.cone_search_async(coord, radius=u.Quantity(1.0, u.deg))`
It woks without problem.
So, I don't know how to resolve this issue in docker.

Any idea?

Thanks.

**Comment by ManonMarchand** [comment]
Hi! 

Looks like you don't have writing rights at `'./cache_astropy'` in this container. You can try to either point `Vizier.cache_location` to an other folder where you can write or to disable the cache functionality with: 

```python
resultado = v.query_region(coord, radius=radio_de_busqueda, catalog='I/355/gaiaedr3', cache=False)
```

(it works with the other module because it does not try to cache)

**Comment by bsipocz** [comment]
yeap, I fully agree with the comment above, and since there is nothing we can do about it in astroquery I'm closing this issue.

Please feel free to report back in case you keep running into issues even when the cache is turned off or you changed the location as some modules may have cache-related bugs.

**Comment by lupecsan** [comment]
Thank you very much.

Regards
