### ISSUE TITLE
Alma().retrieve_data_from_uid producing " Invalid URL '' " error

### ISSUE THREAD

**Issue by georgebendo** [astropy/astroquery#2938]
Alma is having problems with data retrieval from the ALMA Science Archive.  Here is an example script with an example uid (although I have having identical problems with many but not all other uids):

from astroquery.alma.core import Alma
uid='uid://A002/X5a9a13/Xe5'
downloadAlma=Alma()
downloadAlma.cache_location='.'
downloadAlma.retrieve_data_from_uid(uid)

Here is the output:

WARNING: AstropyDeprecationWarning: The name SIA_PARAMETERS_DESC is deprecated in v1.5 for SIA v2 services, use SIA2_PARAMETERS_DESC instead. [pyvo.dal.sia2]
INFO: Downloading files of size 8.299755815000001 Gbyte... [astroquery.alma.core]
INFO: Found cached file .\member.uid___A002_X5a9a13_Xe5.README.txt with expected size 9511. [astroquery.query]
INFO: Found cached file .\2012.1.00139.S_uid___A002_X5a9a13_Xe5_001_of_001.tar with expected size 2405376. [astroquery.query]
Traceback (most recent call last):

  Cell In[1], line 5
    downloadAlma.retrieve_data_from_uid(uid)

  File ~\anaconda3\lib\site-packages\astroquery\alma\core.py:789 in retrieve_data_from_uid
    downloaded_files = self.download_files(file_urls)

  File ~\anaconda3\lib\site-packages\astroquery\alma\core.py:663 in download_files
    check_filename = self._request('HEAD', file_link, auth=auth)

  File ~\anaconda3\lib\site-packages\astroquery\query.py:317 in _request
    response = query.request(self._session,

  File ~\anaconda3\lib\site-packages\astroquery\query.py:71 in request
    return session.request(self.method, self.url, params=self.params,

  File ~\anaconda3\lib\site-packages\requests\sessions.py:573 in request
    prep = self.prepare_request(req)

  File ~\anaconda3\lib\site-packages\requests\sessions.py:484 in prepare_request
    p.prepare(

  File ~\anaconda3\lib\site-packages\requests\models.py:368 in prepare
    self.prepare_url(url, params)

  File ~\anaconda3\lib\site-packages\requests\models.py:439 in prepare_url
    raise MissingSchema(

MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

If I use get_data_info to get the links for this specific uid, the third entry is '', which looks like it is causing retrieve_data_from_uid to crash.

**Comment by bsipocz** [comment]
The traceback above suggest that you are not using the most recent version of the libraries. Please upgrade your astroquery (and pyvo, too).

That being said, I see a different traceback which maybe an actual problem with the code.

**Comment by bsipocz** [comment]
@georgebendo - please update your versions as you example works with the latest releases from pypi:

```
In [1]: import pyvo

In [2]: import astroquery

In [3]: print(pyvo.__version__, astroquery.__version__)
1.5 0.4.7.dev9069

In [4]: 
   ...: 
   ...: from astroquery.alma.core import Alma
   ...: uid='uid://A002/X5a9a13/Xe5'
   ...: downloadAlma=Alma()
   ...: downloadAlma.cache_location='.'
   ...: downloadAlma.retrieve_data_from_uid(uids=uid)

INFO: Downloading files of size 8.299755815000001 Gbyte... [astroquery.alma.core]
INFO: Found cached file ./member.uid___A002_X5a9a13_Xe5.README.txt with expected size 9511. [astroquery.query]
INFO: Found cached file ./2012.1.00139.S_uid___A002_X5a9a13_Xe5_001_of_001.tar with expected size 2405376. [astroquery.query]
INFO: Found cached file ./2012.1.00139.S_uid___A002_X5a9a13_Xe5_auxiliary.tar with expected size 62791680. [astroquery.query]
INFO: Continuing download of file ./2012.1.00139.S_uid___A002_X828760_X533.asdm.sdm.tar, with 1445115904 bytes to go (88.82565386566564%) [astroquery.query]
Downloading URL https://almascience.nrao.edu/dataPortal/2012.1.00139.S_uid___A002_X828760_X533.asdm.sdm.tar to ./2012.1.00139.S_uid___A002_X828760_X533.asdm.sdm.tar ...
|===>------------------------------------------------------------------------------------------------|  60M/1.6G ( 3.72%) ETA  1m34s^C
-
```
