### ISSUE TITLE
mast.Observations.query_criteria radius is a factor of ~10 bigger than supplied value

### ISSUE THREAD

**Issue by JordanDSilva** [astropy/astroquery#2946]
I use 
`
from astroquery.mast import Observations
from astropy.coordinates import SkyCoord

coord = SkyCoord(53.17644, -27.70218, frame = "icrs", unit = "deg")
rad = 0.01
Observations.query_criteria(coordinates=coord,
                                                radius = rad,
                                                project="HST",
                                                dataproduct_type=["IMAGE", "image"]
                                                )
`

Setting rad=0.01 and the final footprint ends up being basically 0.1 degrees in each direction. Any help much appreciated. Thanks.

**Comment by bsipocz** [comment]
cc @astrojimig

**Comment by astrojimig** [comment]
Hi - If I understand your question correctly, this is not a bug! HST images from WFPC2, for example, can have fields of view up to ~2.7 arcminutes (0.045 degrees), which is considerably larger than your search radius. The "s_ra" and "s_dec" column that are returned by `Observations.query_criteria()` are the center position of each image, but do not capture the full extent of the image. From the center coordinate alone, the returned results may seem like they fall outside of your search radius, but your coordinates do fall within the full field of view of the HST image.

[Here is the same search performed in the MAST web portal, for example. ](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22CAOMFILTERED%22%2C%22inputText%22%3A%5B%7B%22paramName%22%3A%22intentType%22%2C%22niceName%22%3A%22intentType%22%2C%22values%22%3A%5B%22science%22%5D%2C%22valString%22%3A%22science%22%2C%22isDate%22%3Afalse%2C%22facetType%22%3A%22discrete%22%2C%22displayString%22%3A%22science%22%7D%2C%7B%22paramName%22%3A%22obs_collection%22%2C%22niceName%22%3A%22obs_collection%22%2C%22values%22%3A%5B%22HST%22%5D%2C%22valString%22%3A%22HST%22%2C%22isDate%22%3Afalse%2C%22separator%22%3A%22%3B%22%2C%22facetType%22%3A%22discrete%22%2C%22displayString%22%3A%22HST%22%7D%2C%7B%22paramName%22%3A%22s_ra%22%2C%22niceName%22%3A%22s_ra%22%2C%22values%22%3A%5B%7B%22min%22%3A53.161658333333%2C%22max%22%3A53.1907875%7D%5D%2C%22valString%22%3A%22%5B53.161658333333%2C%2053.1907875%5D%22%2C%22isDate%22%3Afalse%2C%22facetType%22%3A%22numeric%22%2C%22min%22%3A53.161658333333%2C%22max%22%3A53.1907875%2C%22displayString%22%3A%22%5B53.161658333333%2C%2053.1907875%5D%22%7D%2C%7B%22paramName%22%3A%22s_dec%22%2C%22niceName%22%3A%22s_dec%22%2C%22values%22%3A%5B%7B%22min%22%3A-27.716955555556%2C%22max%22%3A-27.683622222222%7D%5D%2C%22valString%22%3A%22%5B-27.716955555556%2C%20-27.683622222222%5D%22%2C%22isDate%22%3Afalse%2C%22facetType%22%3A%22numeric%22%2C%22min%22%3A-27.716955555556%2C%22max%22%3A-27.683622222222%2C%22displayString%22%3A%22%5B-27.716955555556%2C%20-27.683622222222%5D%22%7D%2C%7B%22paramName%22%3A%22dataproduct_type%22%2C%22niceName%22%3A%22dataproduct_type%22%2C%22values%22%3A%5B%22image%22%5D%2C%22valString%22%3A%22image%22%2C%22isDate%22%3Afalse%2C%22facetType%22%3A%22discrete%22%2C%22displayString%22%3A%22image%22%7D%5D%2C%22position%22%3A%22undefined%2C%20undefined%2C%20undefined%22%2C%22paramsService%22%3A%22Mast.Caom.Filtered%22%2C%22title%22%3A%22MAST%3A%20%20Advanced%20Search%201%22%2C%22tooltip%22%3A%22science%3B%20HST%3B%20%5B53.161658333333%2C%2053.1907875%5D%3B%20%5B-27.716955555556%2C%20-27.683622222222%5D%3B%20image%3B%20%22%2C%22columns%22%3A%22*%22%2C%22columnsConfig%22%3A%22Mast.Caom.Cone%22%7D) The AstroView window shows the footprints of each individual HST image. Many of them overlap with your coordinates, despite the center position being outside of your initial search radius. This makes the spatial footprint covered by the results much larger than your initial search radius.

The search radius assumes units of degrees unless it's supplied as an astropy Quantity object. You could use `rad = 1*u.arcsec`, for example, if you want to specify different units.
I hope that helps!
