### ISSUE TITLE
Quantity error in SkyView.get_images() with width and height

### ISSUE THREAD

**Issue by ixakalabadie** [astropy/astroquery#2948]
Hello,

I get a ValueError when running the following code:
```
from astroquery.skyview import SkyView
import astropy.units as u

SkyView.get_images(position='M17', survey=['NVSS'], height=10*u.arcmin, width=10*u.arcmin)
 ```
The error is `ValueError: Quantity truthiness is ambiguous, especially for logarithmic units and temperatures. Use explicit comparisons.` and it occurs in  `SkyViewClass.get_image_list()`:
```
--> elif width and height:
    size_deg = "{0},{1}".format(width.to(u.deg).value, height.to(u.deg).value)
```
If I remove the units I get the error `AttributeError: 'int' object has no attribute 'to'` in the next line and if I remove the width and height parameters it works fine.

I think it would be enough to change `elif width and height:` for `elif width is not None and height is not None`. The same `if` statement is found again below in the same file.

Thanks,
Ixaka Labadie

**Comment by keflavich** [comment]
I agree with your suggested fix.  Could you submit that change as a pull request?

**Comment by keflavich** [comment]
Actually, this is a duplicate of #2756 and #2757

**Comment by ixakalabadie** [comment]
Thanks, I see that you are into it. I will close the issue.
