### ISSUE TITLE
Bug in units for NASA Exoplanet Archive results

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroquery#2949]
Using astroquery 0.4.7.dev9069, I ran into an incorrect unit in the NASA Exoplanet Archive module today:

```python
>>> from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive as NEA

>>> result = NEA.query_object('K2-141 b')

>>> result['pl_trandur']
[  nan   nan   nan 0.868 0.94 ] d
```

The `pl_trandur` column is the transit duration, noted as "T_14" on the [rendered webpage](https://exoplanetarchive.ipac.caltech.edu/overview/k2-141%20b), with units of hours (fifth row from the bottom):

<img width="1410" alt="Screen Shot 2024-02-13 at 10 00 39" src="https://github.com/astropy/astroquery/assets/3497584/f7d67132-6f7a-4a60-9329-4700caa5c5e4">

I dug into the source and I'm not sure why it doesn't work with the existing logic. I also checked that the Exoplanet Archive table claims units of hours, and it does. Should we put a one-off fix for this column in `_fix_units`, here?

https://github.com/astropy/astroquery/blob/ab7fdaa48b7197df781671ce34a03527269bef4b/astroquery/ipac/nexsci/nasa_exoplanet_archive/core.py#L534-L535

Related to: #2130, #2218

**Comment by bsipocz** [comment]
cc @rickynilsson

**Comment by rickynilsson** [comment]
I'll look into this.

**Comment by bmorris3** [comment]
Any updates? Thanks!

**Comment by bmorris3** [comment]
Friendly reminder @rickynilsson.

**Comment by rickynilsson** [comment]
@bmorris3 - There seems to be an inconsistency in the units for Transit Duration in the Exoplanet Archive, which are in units of hours in the overviews and PS ICE table, but in units of days in the underlying db table (and hence in TAP queries used by astroquery's Exoplanet Archive module). As you say, it should be hours everywhere. I've brought it up with the team and we'll fix the unit in the underlying db as soon as possible. Thanks for bringing this to our attention.

**Comment by rmhuch** [comment]
Hi! I ran into this exact problem today.. wondering if there is an estimated timeline when this will be fixed? Thanks!

**Comment by rickynilsson** [comment]
Yeah, it's been fixed in dev and waiting for merge into production next week or so.
