### ISSUE TITLE
New Splatalogue breaks astroquery interface

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#2956]
Example:
```python
>>> Splatalogue.query_lines(1*u.GHz, 2*u.GHz)
Traceback (most recent call last):
  Cell In[239], line 1
    Splatalogue.query_lines(1*u.GHz, 2*u.GHz)
  File ~/repos/astroquery/astroquery/utils/class_or_instance.py:25 in f
    return self.fn(obj, *args, **kwds)
  File ~/repos/astroquery/astroquery/utils/process_asyncs.py:29 in newmethod
    result = self._parse_result(response, verbose=verbose)
  File ~/repos/astroquery/astroquery/splatalogue/core.py:480 in _parse_result
    result = ascii.read(response.text.split('\n'), delimiter=':',
  File ~/mambaforge/envs/py39forge/lib/python3.9/site-packages/astropy/io/ascii/ui.py:426 in read
    dat = reader.read(table)
  File ~/mambaforge/envs/py39forge/lib/python3.9/site-packages/astropy/io/ascii/core.py:1451 in read
    raise InconsistentTableError(errmsg)
InconsistentTableError: Number of header columns (1) inconsistent with data columns (2) at data line 13
Header values: ['<!-- start of nrao-header.html -->']
Data values: ['<a href="http', '//www.nrao.edu/">']
```

Announced and deployed the same day:
https://science.nrao.edu/enews/17.2/

This is a severely breaking change, such that the existing code is likely now of zero value.  

I used splatalogue a lot, so I may want to write a new module if the upstream interface comes back online (presently, the new splatalogue does not function at all), but in the meantime I recommend people switch to the JPL and CDMS line lists.

**Comment by keflavich** [comment]
I might have jumped to conclusions too soon - it may just be that splatalogue is down.  The web interface doesn't work right now, so the test above isn't really a test of the API.

**Comment by bsipocz** [comment]
@keflavich - please label the issues, so we don't need to triage our own ones :)

**Comment by keflavich** [comment]
yep, my bad.  

I have a fix in progress - will push when I get a basic test passing

**Comment by keflavich** [comment]
I'm labeling this a bug because, while it's upstream's fault, it does break our code (and it won't ever be fixed upstream)
