### ISSUE TITLE
The number of links returned from gaia.load data does not match the number of ids passed in

### ISSUE THREAD

**Issue by NorthMh** [astropy/astroquery#2973]
When I tried to download a relatively large number of the spectral data of gaia XP, I found that the download totals did not match the ids list.  for example: if the batchsize of ids is 1000, then I'll probably only get about 940-960 spectral data.

   After debugging, I found that the number of data returned from the **gaia.load_data** method does not match the number of ids entered.

   The ids I used had already been checked from the gaia Archive database, which were all **"xp sampled = True"**, so I don't understand why  the issue  happened

Here is the partial code that I use
```
def process_data(data, id_list, _property, csv_id, savepath):
    cnt = 0
    begin = csv_id + 1
    end = csv_id + len(data)
    print("loading...")
    datalink = Gaia.load_data(data,
                              data_structure='COMBINED',
                              retrieval_type='XP_SAMPLED',
                              format='votable'
                              )
    outputs = [i for i in datalink[list(datalink.keys())[0]]]
    print(len(outputs))  # Found the issue 
    for table in outputs:

        array = table.array
        with open(f'{savepath}/{id_list[csv_id]}.csv', "w",
                  newline="",
                  encoding="utf-8") as csvfile:
            print(f"\rprocessing download {begin}~{end} [{cnt + 1}]/[{len(data)}]")
            writer = csv.writer(csvfile)
            if _property:
                writer.writerow(["wavelength", "flux"])
            for k in range(array.size):
                writer.writerow([array[k][0], array[k][1]])
        csv_id += 1
        cnt += 1


def search(id_list, batch_size,save_Spectrum_Path,_property ):
    index = 0
    csv_id = 0
    while index < len(id_list):
        if index + batch_size <= len(id_list):
            data = id_list[index:index + batch_size]
        else:
            data = id_list[index:len(id_list)]
        process_data(data, id_list, _property, csv_id, save_Spectrum_Path)
        # pool.apply_async(process_data, args=(data, id_list, _property, csv_id,save_Spectrum_Path), error_callback=err_call_back)  Used when multiple processes
        index += batch_size
        csv_id += batch_size
        time.sleep(10)
```
ps: The remaining code is the function code to query for ids and the function code to save and I didn't list here.
If you can solve my problem, I would appreciate it!

**Comment by cosmoJFH** [comment]
Hi @NorthMh, I've repeated the steps you described:

1. In https://gea.esac.esa.int/archive/ I executed the query 

SELECT TOP 1000 source_id FROM gaiadr3.gaia_source where has_xp_sampled = 'True' order by source_id

2. I download the results as a csv file

3. Then I executed the following simple script

```
from pandas import *
from astroquery.gaia import Gaia

data = read_csv("1711188152417O-result.csv")
source_ids=data['source_id'].tolist()
len(source_ids) # --> 1000
datalink = Gaia.load_data(source_ids,data_structure='COMBINED', retrieval_type='XP_SAMPLED',format='votable')
outputs = [i for i in datalink[list(datalink.keys())[0]]]
print(len(outputs))  # --> 1000
```

The result shows 1000 spectra.

**Comment by NorthMh** [comment]
@cosmoJFH , thanks for trying !
For me, I've tested it many times before, but I couldn't return the same amount of data. 
Below is one of the output
```
INFO: Login to gaia data server [astroquery.gaia.core]
INFO: OK [astroquery.utils.tap.core]
30000 files are going to be downloaded 
loading...
948 --> # outputs number , however batchsize is 1000
processing download 1~1000 [1]/[1000]
processing download 1~1000 [2]/[1000]
processing download 1~1000 [3]/[1000]
.....
```
I don't know whether it is a question of whether the link is unstable or is my error with code

**Comment by NorthMh** [comment]
I finally found the cause of the problem, and it turned out that some of my data had been duplicated. I have modified the ASQL code and now it runs smoothly with correct results！(It's really important to check the preparations carefully)

The issue has been resolved.
