### ISSUE TITLE
Enabling 'extra_precision' for ephemeris with refraction results in KeyError

### ISSUE THREAD

**Issue by joebro1907** [astropy/astroquery#2977]
When enabling `extra_precision` with `refraction`, the output column quantities don't match the expected value, which leads to a KeyError crash:
 
```
from astroquery.jplhorizons import Horizons
eph = Horizons(id = id, location = location, epochs = epochs.jd)
ephem = eph.ephemerides(refsystem ="ICRF", skip_daylight = True, refraction = True, extra_precision = True)
```

This results in:

```
     1470         rename = []
     1471         for col in data.columns:
-> 1472             data[col].unit = column_defs[col][1]
     1473             if data[col].name != column_defs[col][0]:
     1474                 rename.append(data[col].name)

KeyError: 'R.A._(rfct-app)'
```

**The fix is simply done by adding** 

```
'R.A._(rfct-app)': ('RA_app', 'deg')
'DEC_(rfct-app)': ('DEC_app', 'deg')
'Azimuth_(r-app)': ('AZ', 'deg')
'Elevation_(r-app)': ('EL', 'deg')
```

**to the `eph_columns` dictionary in the `astroquery/jplhorizons/__init__.py```**

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by mkelley** [comment]
Thanks for the report and suggested fix.  The "rfct" versions seem to be undocumented, so I'm curious if they are intended variants.  Regardless, I can add them to the column list.
