### ISSUE TITLE
IRSA query_region fails when using columns keyword

### ISSUE THREAD

**Issue by clgreenwell** [astropy/astroquery#2978]
Trying to select specific columns using the Irsa.query_region fails, returning:

> TypeError: IrsaClass.query_region_async() got an unexpected keyword argument 'columns'

This happens for me when using the example snippet on [https://astroquery.readthedocs.io/en/latest/ipac/irsa/irsa.html](https://astroquery.readthedocs.io/en/latest/ipac/irsa/irsa.html):

```
from astroquery.ipac.irsa import Irsa
table = Irsa.query_region("HIP 12", catalog="allwise_p3as_psd", spatial="Cone", columns="ra,dec,w1mpro")

```

**Comment by clgreenwell** [comment]
Just to add this is with version "latest" - the "stable" version has selcols instead, which does work.

**Comment by keflavich** [comment]
The 'columns' keyword is deprecated since https://github.com/astropy/astroquery/pull/2837, but the keyword is present in main.  

The error you're receiving is an indication that you're not using the most recent version, which you noted.  Please only use the most recent version following the [installation instructions](https://astroquery.readthedocs.io/en/latest/#installation).

I'm closing this as we do not expect older versions to continue functioning.

**Comment by clgreenwell** [comment]
Thanks, but the problem is that the documentation page for the "latest" version (0.4.7, linked above) uses the keyword columns so it fails, but documentation for "stable" (0.4.6) correctly has selcols.

**Comment by keflavich** [comment]
There does seem to be a bug on the 0.4.7 version that has already been fixed in the latest prerelease.

`selcols` still works but is deprecated:
```
In [2]: from astroquery.ipac.irsa import Irsa
   ...: table = Irsa.query_region("HIP 12", catalog="allwise_p3as_psd", spatial="Cone", selcols="ra,dec,w1mpro")
WARNING: AstropyDeprecationWarning: "selcols" was deprecated in version 0 and will be removed in a future version. Use argument "columns" instead. [warnings]
```

**Comment by bsipocz** [comment]
v0.4.7 is currently the "stable" version and it does work with `columns` as it's documented. I suspect you might have tried the example with an older version.

**Comment by clgreenwell** [comment]
Thanks for your help - so it's actually selcols that's deprecated not columns. I will check my version and make sure it's up to date.
