### ISSUE TITLE
https://astroquery.readthedocs.io/en/latest/utils/tap.html#using-tap-to-connect-other-tap-services

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astroquery#2984]
Hi,

I think that the example at:

https://astroquery.readthedocs.io/en/latest/utils/tap.html#using-tap-to-connect-other-tap-services

is using obsolete terminology

get_name() should be get_qualified_name()

print(tables[0].get_name())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TapTableMeta' object has no attribute 'get_name'

>>> print(tables[0].get_qualified_name())
J_AA.J/A+A/635/A13/table1

The full example is:

from astroquery.utils.tap.core import TapPlus
tap = TapPlus(url="https://TAPVizieR.cds.unistra.fr/TAPVizieR/tap")
#Inspect tables
tables = tap.load_tables()
for table in (tables):
print(table.get_name())

See https://astroquery.readthedocs.io/en/latest/utils/tap.html#getting-public-tables which uses get_qualified_name()

I am happy to edit the docs but I would need some dummy guide to what I need to fork i.e. link. 
Best regards, Richard

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by richardgmcmahon** [comment]
I have a pull request:

https://github.com/richardgmcmahon/astroquery/pull/1

**Comment by bsipocz** [comment]
@richardgmcmahon - welcome as a PR contributor! 
However, I'm afraid, you will need to open a new one against the main repo rather than the master branch in your fork. (you may be able to edit the current one and change the  "base" branch, I'm not exactly sure though that the right one will be in the dropdown).

**Comment by richardgmcmahon** [comment]
@bsipocz Thanks, here is my second attempt. It might still not be correct but I want to get it right since I have a few other Astropy docs suggestions to propose.

https://github.com/astropy/astroquery/pull/2985

I deleted my old forked version which had used the master terminology and moved to main terminology. I reforked and made a rgm-1 branch.
