### ISSUE TITLE
Alma get_data_info() not working

### ISSUE THREAD

**Issue by YayeAwa** [astropy/astroquery#2988]
Hi,

There seems to be a small problem with ALMA's get_data_info function
I try to execute these lines but the request doesn't go through and I get no error in return

from astroquery.alma import Alma
t = Alma.get_data_info("uid://A001/X158f/Xb41", expand_tarfiles=True)

Thanks for your help

**Comment by mjastro** [comment]
I am also getting this issue (from early this week) and wondering about what causes this problem.

**Comment by keflavich** [comment]
What is the issue?  I can't produce any problem:
```python
In [1]: from astroquery.alma import Alma
   ...: t = Alma.get_data_info("uid://A001/X158f/Xb41", expand_tarfiles=True)

In [2]: t
Out[2]:
<Table length=109>
                         ID                                                                              access_url                                                     service_def ... content_qualifier link_auth link_authorized
                                                                                                                                                                                    ...
                       object                                                                              object                                                          object   ...       object        object        bool
--------------------------------------------------- ------------------------------------------------------------------------------------------------------------------- ----------- ... ----------------- --------- ---------------
                              uid://A001/X158f/Xb41                                     https://almascience.nrao.edu/dataPortal/member.uid___A001_X158f_Xb41.README.txt             ...                       false            True
                              uid://A001/X158f/Xb41                         https://almascience.nrao.edu/dataPortal/2021.1.00013.S_uid___A001_X158f_Xb41_001_of_001.tar             ...                       false            True
                              uid://A001/X158f/Xb41                          https://almascience.nrao.edu/dataPortal/2021.1.00013.S_uid___A001_X158f_Xb41_auxiliary.tar             ...                       false            True
                              uid://A001/X158f/Xb41                        https://almascience.nrao.edu/dataPortal/2021.1.00013.S_uid___A002_Xf160b6_X56eb.asdm.sdm.tar             ...                       false            True
                              uid://A001/X158f/Xb41                        https://almascience.nrao.edu/dataPortal/2021.1.00013.S_uid___A002_Xf20692_X51a6.asdm.sdm.tar             ...                       false            True
                              uid://A001/X158f/Xb41                        https://almascience.nrao.edu/dataPortal/2021.1.00013.S_uid___A002_Xf1948b_X449b.asdm.sdm.tar             ...                       false            True
                              uid://A001/X158f/Xb41                       https://almascience.nrao.edu/dataPortal/2021.1.00013.S_uid___A002_Xf1bb4a_X1160e.asdm.sdm.tar             ...                       false            True
                              uid://A001/X158f/Xb41                        https://almascience.nrao.edu/dataPortal/2021.1.00013.S_uid___A002_Xf1ecde_X44f9.asdm.sdm.tar             ...                       false            True
2021.1.00013.S_uid___A001_X158f_Xb41_001_of_001.tar         https://almascience.nrao.edu/dataPortal/member.uid___A001_X158f_Xb41.J1617-5848_bp.spw25.mfs.I.mask.fits.gz             ...                       false            True
2021.1.00013.S_uid___A001_X158f_Xb41_001_of_001.tar           https://almascience.nrao.edu/dataPortal/member.uid___A001_X158f_Xb41.J1617-5848_bp.spw25.mfs.I.pb.fits.gz             ...                       false            True
2021.1.00013.S_uid___A001_X158f_Xb41_001_of_001.tar           https://almascience.nrao.edu/dataPortal/member.uid___A001_X158f_Xb41.J1617-5848_bp.spw25.mfs.I.pbcor.fits             ...                       false            True
```

**Comment by YayeAwa** [comment]
Nothing is returned as error. The request remains blocked
for your information, here's my version of astroquery: '0.4.8.dev9251'

**Comment by keflavich** [comment]
I need more information in order to help.  If there's no error message, what is the nature of the problem?  What response do you expect, and what responders do you get?  See my example above.

**Comment by YayeAwa** [comment]
Okay, when I do
`>>> from astroquery.alma import Alma
>>> t = Alma.get_data_info("uid://A001/X158f/Xb41", expand_tarfiles=True)

`
I expect a response like your example. but I don't get the python prompt.
I'd like to loop over the "t" result to browse all the fits files and download them if I want.

**Comment by keflavich** [comment]
Ahhh, ok, that indicates an upstream timeout problem.  It should cause a local timeout error, but that seems not to be happening in your case.  @andamian is there possibly an issue here where timeouts aren't happening when they should be?

**Comment by andamian** [comment]
Not aware. It would happen upstream (`PyVO`) but I can't reproduce it and I've tried all 3 locations. I'm wondering if it was something transient. @YayeAwa - still no luck?

**Comment by YayeAwa** [comment]
Yes, it's working again. I'm getting the results I expected.
`t = Alma.get_data_info("uid://A001/X158f/Xb41", expand_tarfiles=True)
 t
<Table length=109>
                        ID                         ... link_authorized
                                                   ...                
                      object                       ...       bool     
-------------------------------------------------- ... ---------------
                             uid://A001/X158f/Xb41 ...            True
                             uid://A001/X158f/Xb41 ...            True
                             uid://A001/X158f/Xb41 ...            True
                                               ... ...             ...
2021.1.00013.S_uid___A001_X158f_Xb41_auxiliary.tar ...            True
2021.1.00013.S_uid___A001_X158f_Xb41_auxiliary.tar ...            True
2021.1.00013.S_uid___A001_X158f_Xb41_auxiliary.tar ...            True
`
But I'd like to understand what happened so I can anticipate the next time.
Thanks to all.

**Comment by andamian** [comment]
@YayeAwa - I'm not sure. It could have been a transient error along the way or one of the servers were down. Have you tried several times?

**Comment by YayeAwa** [comment]
Yes, I've just tried it several times on 2 different servers.
Now I'm sure the service is back on my side.
