### ISSUE TITLE
Object equivalencies

### ISSUE THREAD

**Issue by low-sky** [astropy/astroquery#299]
It would be nice to have functionality that would allow you to test whether two names refer to the same object.

```
astroquery.is_same_object('M33','NGC 598')
True

astroquery.is_same_object('M33','M31')
False
```

**Comment by bsipocz** [comment]
This is out of scope for astroquery, we provide access to webservices and archives, but don't implement functionality on top of them.
If you know any services that do this, and we already have modules for them, examples for the docs how to do such a comparison is always welcome.
