### ISSUE TITLE
Add documentation to ESA Herschel website about existence of Astroquery

### ISSUE THREAD

**Issue by jkrick** [astropy/astroquery#2996]
I spent a little while on the ESA Herschel website (http://archives.esac.esa.int/hsa/whsa/) and could not find a good way to access Herschel data with python.   Good thing I work with @bsipocz  who helped point me to the existence of astroquery's herschel module.   I would recommend that a link to astroquery be added to the above Herschel website.

A suggestion for where to put that astroquery link: I was looking for it under "HSA User Guide" in the top tab bar

Secondly, I would recommend removing the outdated, messy method included in section 1.5 under "HSA User Guide" titled "Python script to execute an asynchronous query and wait until the results are available"

Thanks astroquery for having a solution to accessing Herschel data in the first place!

**Comment by jespinosaar** [comment]
Dear @jkrick , @bsipocz , many thanks for the suggestion. We are going to include this in our TODO list and let you know when we work on it. Maybe you already know it, but there is some documentation in the astroquery manual:
https://astroquery.readthedocs.io/en/latest/esa/hsa/hsa.html

**Comment by keflavich** [comment]
This is really a upstream issue - there's no action for us to take here, and the ESA team is aware of the problem (maybe you've made your own ticket), so I'm closing this.  We appreciate the positive feedback!
