### ISSUE TITLE
Connection timed outwhile using astroquery.gaia

### ISSUE THREAD

**Issue by Alakay2** [astropy/astroquery#2999]
It is about same #2989  connection timeout issue in gaia.query. This time I tried some curl commands. I am using examples given on gaia website (https://www.cosmos.esa.int/web/gaia-users/archive/programmatic-access#CommandLine_Tap)

I am getting following outpur using:

HTTP/1.1 200 Connection established

HTTP/1.1 303 303
Date: Fri, 26 Apr 2024 06:17:23 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_jk/1.2.43
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Set-Cookie: JSESSIONID=2C11ED106004ADC0B76EC24BC637CC76; Path=/tap-server; Secure; HttpOnly
Location: https://gea.esac.esa.int/tap-server/tap/async/1714112243125O
Transfer-Encoding: chunked
Content-Type: text/plain;charset=ISO-8859-1

Location: https://gea.esac.esa.int/tap-server/tap/async/1714112243125O

Is this a normal expected output? As per your suggestions, I can use access gaia catalog via ipac.irsa module but I am using this under other packages like eleanor and tglc. I think it is due to the institute proxy network, while using personal network everything works. Can you suggest me some way to add proxy settings in astroquery:gaia files, or any other solution?

**Comment by keflavich** [comment]
I'm closing this as a duplicate / unrelated.  The original issue posted in #2989 seems to be resolved:
```
In [1]: import astropy.units as u
   ...: from astropy.coordinates import SkyCoord
   ...: from astroquery.gaia import Gaia
   ...: coord = SkyCoord(ra=280, dec=-60, unit=(u.degree, u.degree), frame='icrs')
   ...: width = u.Quantity(0.1, u.deg)
   ...: height = u.Quantity(0.1, u.deg)
   ...: r = Gaia.query_object_async(coordinate=coord, width=width, height=height)
INFO: Query finished. [astroquery.utils.tap.core]
```

The other parts of this issue are related to curl, not astroquery.

@Alakay2 please limit issues posted on the astroquery issue tracker to those related to astroquery, not the upstream services.
