### ISSUE TITLE
Astroquery's CASDA query for RACS-MID DR1 cutout images

### ISSUE THREAD

**Issue by astro-fermi** [astropy/astroquery#3001]
Hello,

I am trying to download the cutout image for an object using the RACS-MID DR1 catalog, which was recently released (https://ui.adsabs.harvard.edu/abs/2024PASA...41....3D/abstract). I followed the example on Astroquery's CASDA website (https://astroquery.readthedocs.io/en/latest/casda/casda.html#cutouts). Since I am interested in RACS-MID DR1 data rather than RACS-DR1, I replaced the command
np.char.startswith(public_data['filename'], 'RACS-DR1_'
with
np.char.startswith(public_data['filename'], 'RACS-MID1_'

and was able to download the desired cutout. The beam size of the downloaded cutout image is 25"x25". However, when I tried to download the cutout image from the CASDA cutout website (https://data.csiro.au/domain/casdaCutoutService), the downloaded cutout fits has a beam size of 13.29" x 9.39", i.e., smaller, hence higher resolution. I cannot understand why Astroquery's CASDA module did not find this smaller beam-size cutout image. At least, it should download cutouts with all available beam sizes.

Please help. Thanks in advance.

**Comment by bsipocz** [comment]
cc @jd-au

**Comment by jd-au** [comment]
HI astro-fermi,

The RACS-mid data release at https://doi.org/10.25919/p524-xb81 consists of two sets of images, the main mosaiced images and the 25" set which is designed to match the RACS-low catalogue. So for each tile there are two files e.g.

- RACS-MID1_0000-37.fits
- RACS-MID1_0000-37_25arcsec.fits

The CASDA cutout website uses the criteria `filename LIKE 'RACS-MID1%.fits' and filename NOT LIKE 'RACS-MID1%arcsec.fits'` to select just the main mosaiced images from the RACS-mid dataset. 

To do the same in the CASDA Astroquery module use:
`subset = public_data[((public_data['obs_collection'] == 'The Rapid ASKAP Continuum Survey') & #
                      (np.char.startswith(public_data['filename'], 'RACS-MID1_')) & #
                      (np.invert(np.char.endswith(public_data['filename'], 'arcsec.fits')))
                     )]
`

Note the use of `subset[:1]` in the next line restricts to just the first result from the subset list. You can remove the `[:1]` to produce cutouts for every match.

Cheers,
James.

**Comment by astro-fermi** [comment]
I just checked that with the suggested commands; I can download the cutout with the smaller beam size. Many thanks for your help.
