### ISSUE TITLE
Simbad Query returns wrong (?) error values

### ISSUE THREAD

**Issue by FCapomax** [astropy/astroquery#3020]
I'm using astroquery to simbad.query_region and obtain the magnitudes of the Stars in the region in certain bands (B,V,R).
I have replicated my problem with query_object, since the result is the same:

```
from astroquery.simbad import Simbad

simbad = Simbad()
simbad.TIMEOUT = 180
simbad.add_votable_fields("flux(B)","flux(V)","flux(R)","flux_error(b)","flux_error(v)","flux_error(r)", "otype","sptype")

object = "UCAC4 440-052370"

result_table = simbad.query_object(object)
print(result_table["MAIN_ID","FLUX_B","FLUX_ERROR_b","FLUX_V","FLUX_ERROR_v","FLUX_R","FLUX_ERROR_r"])
```

the output is :

```
    MAIN_ID      FLUX_B FLUX_ERROR_b FLUX_V FLUX_ERROR_v FLUX_R FLUX_ERROR_r
                  mag                 mag                 mag               
---------------- ------ ------------ ------ ------------ ------ ------------
UCAC4 440-052370 15.632           -- 14.717           -- 14.604        0.020
```

my problem is that while the magnitude values agree with those found in a in-browser query of simbad, for most sources the error values are not returned, and when they are they do not agree with what i find if i look up that MAIN_ID in browser. 
Here is what i mean (square brackets are error values):

![simbadscreenshot](https://github.com/astropy/astroquery/assets/127304902/00ef131e-2c74-4e5d-976d-18ad6b56a350)

I thought i was searching the wrong fields, but if the synthax was wrong, it should return an error.

**Comment by ManonMarchand** [comment]
Yes, sorry the simbad module uses an old syntax that is broken (should be fixed by #2954).
What works for now are custom TAP queries. For your use case, it would look like this:

```python
from astroquery.simbad import Simbad
query = """
SELECT main_id, filter, flux, flux_err, flux.bibcode as flux_bibcode, otype, sp_type
FROM basic
JOIN flux ON oidref = oid
WHERE main_id = 'UCAC4 440-052370'
"""
result = Simbad.query_tap(query)
print(result)
```
```
<Table length=10>
    main_id      filter    flux   flux_err     flux_bibcode    otype  sp_type
     object      object  float32  float32         object       object  object
---------------- ------ --------- -------- ------------------- ------ -------
UCAC4 440-052370      i    14.201     0.06 2012yCat.1322....0Z      *        
UCAC4 440-052370      r    14.429     0.02 2012yCat.1322....0Z      *        
UCAC4 440-052370      g    15.131     0.04 2012yCat.1322....0Z      *        
UCAC4 440-052370      V    14.717     0.01 2012yCat.1322....0Z      *        
UCAC4 440-052370      B    15.632     0.01 2012yCat.1322....0Z      *        
UCAC4 440-052370      R    14.604     0.13 2012yCat.1322....0Z      *        
UCAC4 440-052370      G 14.479252  0.00277 2022yCat.1355....0G      *        
UCAC4 440-052370      K      12.5    0.026 2003yCat.2246....0C      *        
UCAC4 440-052370      H    12.574    0.026 2003yCat.2246....0C      *        
UCAC4 440-052370      J    13.068    0.023 2003yCat.2246....0C      *        
```

Where `select` allows to chose the columns you want (a list of available columns can be read with `Simbad.list_columns()`). Since the chosen columns are in the `basic` and `flux` (see the output of the column list for their descriptions) tables we have to join them together (you can see how to to the join with `Simbad.list_linked_tables("flux") ` for example).
We selected the object in the last line with `WHERE`. This prints all the fluxes known in SIMBAD for this star but you could restrict to some filters with ` AND filter IN ('B', 'V', 'R')` at the end of the string.

Note that I also added the reference to the paper in which the flux is measured with an alias "flux_bibcode" here.

Hope it helps

**Comment by FCapomax** [comment]
Thank you, it helped a lot!
It is slightly more complicated to query this way (didn't really now ADQL) but it gives the right results.

**Comment by FCapomax** [comment]
(Sorry first time using github issue tracker, i closed the post without the response:)

Thank you, it helped a lot!
It is slightly more complicated to query this way (didn't really now ADQL) but it gives the right results.

**Comment by FCapomax** [comment]
(first time using github issue tracker, sorry for the opening-closing):

Thank you, it helped a lot!
It is slightly more complicated to query this way (didn't really now ADQL) but it gives the right results.

**Comment by ManonMarchand** [comment]
No worries. Here is a link for ADQL : https://cds.unistra.fr/help/documentation/simbad-more/adql-simbad/ (even if the graph on top is a tiny bit outdated)

And if you're still stuck with adql queries for SIMBAD, the team behind [cds-question@unistra.fr](mailto:cds-question@unistra.fr) will be happy to help.
