### ISSUE TITLE
BUG: CI -- no space left on device

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#3032]
The remote-data cron job is now running into a no space left on device error, apparently some of the tests 1) download too much 2) don't clean-up after themselves.

https://github.com/astropy/astroquery/actions/runs/9424065170/job/25963658462

I haven't had the chance to look into the changes, it seems to affect only the last cronjob, so the first things to check is PRs merged in in the past two weeks.

**Comment by Bwoltz** [comment]
@bsipocz Would it be possible for someone with the right privileges to access the test bed remotely and investigate? That could maybe help identify troublemakers for case 2)?

**Comment by bsipocz** [comment]
@Bwoltz - This is more like a reminder issue for a maintainer to know where to start. Remote tests can be run locally, so no need for logging into the CI machines, etc.
