### ISSUE TITLE
BUG: alma test downloads 850+Mb of data

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#3044]
Might be (one of) the reason(s) for #3032, aka running out of diskspace in the CI job. This test is around like forever, but as we add more modules and tests, the numbers add up very quickly.

In the temporary test path, this one is a big outlier, is there maybe a much smaller test file that we could use in the test?

`866M	test_retrieve_data0`

cc @andamian @keflavich

**Comment by keflavich** [comment]
Might a good solution be to clean up afterward - i.e., include deleting the files as part of the test?  I think it will be difficult to test data retrieval from ALMA on anything smaller.

**Comment by bsipocz** [comment]
The cleanup is already happening, but it's typically at the end of the test run, which doesn't help with running out of space (we have ~10-14G total).

The test in fact doesn't seem to do anything, besides downloading the `uid`, so hopefully there are some dummy uid-s out there?

An easy alternative is to mark the test, we already have the `bigdata` marker (though that would add the risk of never to run said tests and therefore not noticing potential issues)

**Comment by keflavich** [comment]
OK, I leave that to @andamian - I'm not sure any dummy UIDs exist in the archive, but that seems like something very reasonable to do.  In the meantime, `@bigdata` seems like the right (temporary?) workaround.

**Comment by andamian** [comment]
Looking into it now.

**Comment by andamian** [comment]
@keflavich, @bsipocz - since the test does not look at the downloaded data, is there a way to download it into a black hole, i.e. `/dev/null`? I've tried to specify that as the cache directory but it's trying to create it.

**Comment by bsipocz** [comment]
not sure if that would work on windows, plus it still takes unreasonably long time to dummy download almost a Gb to not have any look at it.

At the moment it's flagged as bigdata test and I've turned those off by default in the CI, so the urgency has passed.

**Comment by andamian** [comment]
I couldn't find anything smaller but flagging it as bigdata is the way to go and I'm OK with that. Should we close it then?

**Comment by bsipocz** [comment]
Yes, if there is nothing smaller, then we can't do much about it here, so I'm just closing this as a won't fix.
If a test `uid` ever comes into existence we may remember to reopen this and switch the test to use it :)
