### ISSUE TITLE
Bug in rows limitation in module vizier

### ISSUE THREAD

**Issue by xhaubois** [astropy/astroquery#3053]
Hello,
I have astropy 5.1 . It seems the module vizier has a bug in the limitation of rows.
When I manually set it to Vizier.ROW_LIMIT=100 or Vizier.ROW_LIMIT=-1 , I still get  50 rows as returned by Vizier..query_constraints.
I put what I do below. Can you help please?
Thanks,

```python
from astroquery.vizier import Vizier

Vizier.ROW_LIMIT=100
jsdc=("II/346")
tab = Vizier(catalog=jsdc).query_constraints(Rmag="-10.0..5.0",UDDR="1.0..50.0",DEJ2000="-90..10")[0]
```

**Comment by keflavich** [comment]
Try instead:
```python
Vizier(catalog=jsdc, row_limit=100).query_constraints(Rmag="-10.0..5.0",UDDR="1.0..50.0",DEJ2000="-90..10")[0]
```

https://github.com/astropy/astroquery/issues/3018 is related

**Comment by xhaubois** [comment]
Fixed it. Thanks!
