### ISSUE TITLE
Add a plot and an image to the docs

### ISSUE THREAD

**Issue by cdeil** [astropy/astroquery#307]
It would be very nice if the [Astroquery gallery](http://astroquery.readthedocs.org/en/latest/gallery.html) contained a plot (e.g. a Herzsprung-Russel-Diagram or whatever) and an image (e.g. the Galactic center region).

That's what I expected when I clicked "gallery". :-)

@keflavich If you don't want images in the repo because of the file size, then maybe an independent IPython notebook and a link to nbviewer would be better?

**Comment by gracca** [comment]
My Python skills are rather poor, but I'll be glad to contribute! No problems with changing the docstrings to English. I'll see how to make the pull request.

**Comment by keflavich** [comment]
Thanks @gracca!  Do you need help making the pull request?

@cdeil - I prefer the simpler solution for now; I prefer to have self-contained docs.  But, we don't want to host too many images.  If you want to make a PR to use sphinx-gallery, I'll support that, but I won't be implementing it myself.

**Comment by gracca** [comment]
@keflavich: Is it as simple as clonning astroquery repo and editing `besancon.rst` to add the example? And then commit and pull?

**Comment by keflavich** [comment]
Pretty much, yeah.   Unless we try one of the fancier plotting approaches
cdeil suggested

**Comment by cdeil** [comment]
@keflavich - So for this case you want the PNG to be committed into the repo?
(The other simple alternative would be to put a `.. plot::` directive into the `rst`.)

**Comment by keflavich** [comment]
I've never used the `.. plot::` directive; that sounds preferable if it works.

**Comment by cdeil** [comment]
@gracca - In case you haven't used the Sphinx plot directive before, here's an example:
* https://gammapy.readthedocs.org/en/latest/_sources/astro/source/snr.txt
* https://gammapy.readthedocs.org/en/latest/astro/source/snr.html

The drawback is that it will fail if the service isn't up ... but my suggestion would be to use it and if it turns out to be unreliable we can put the PNG or data in this repo or some other Github repo.

**Comment by keflavich** [comment]
Superseded by https://github.com/astropy/astroquery/issues/3027
