### ISSUE TITLE
SimbadClass got an unexpected keyword argument

### ISSUE THREAD

**Issue by mbbadaracco** [astropy/astroquery#3072]
Hello everyone

I'm trying to run the example script from the docs:
```
from astroquery.simbad import Simbad

simbad = Simbad()
simbad.ROW_LIMIT = 5
simbad.query_bibcode("2016PhRvL.*", wildcard=True, criteria="title LIKE '%gravitational wave%coalescence.'") 
```
and I get this error:

TypeError                                 Traceback (most recent call last)
Cell In[10], line 7
      3 simbad = Simbad()
      5 simbad.ROW_LIMIT = 5
----> 7 simbad.query_bibcode("2016PhRvL.*", wildcard=True,
      8 
      9                      criteria={"title LIKE '%gravitational wave%coalescence.'"})

TypeError: SimbadClass.query_bibcode() got an unexpected keyword argument 'criteria'

I get the same error with the keyword 'abstract'. Perhaps the following is useful information: this happens trying to run it in google colab as well as in my OS Ubuntu 22.04.4 LTS; the version of astroquery is 0.4.8.dev9321, and I have all the dependencies installed.

**Comment by ManonMarchand** [comment]
Hi! 

These two arguments are new and they are not in this version. If you want to use them, you'll have to do `pip install git+https://github.com/astropy/astroquery.git`

@bsipocz : looks like the documentation is a bit ahead of the releases, is it normal?

**Comment by mbbadaracco** [comment]
Solved! Thank you very much.

**Comment by bsipocz** [comment]
Yes, the documentation with "latest" in their URL is routinely reflects the dev branch, all around the ecosystem.

**Comment by bsipocz** [comment]
@ManonMarchand - I've pushed a dev release to pypi, so the docs' recommendation of `pip install --pre -U astroquery` now picks up a something fresh (including all the recent simbad changes).

**Comment by ManonMarchand** [comment]
Thanks! I'll keep an eye for questions and/or possible bug reports. Fingers crossed the transition will be smooth for everyone.
