### ISSUE TITLE
Astrometry.net: can query for job id once, rather than each time

### ISSUE THREAD

**Issue by dstndstn** [astropy/astroquery#3078]
Hi,

Minor request: in the Astrometry.net module, while polling for a submission to get solved, it looks like you're hitting two URLs each time - one to get the job id from the submission id, and then one to get the job status.  I think you only need to get the job id once.  So this could split into two loops, one where you poll until you get the job id, and then keep the job id fixed and poll for the job status.

eg don't do this request each time through the loop
https://github.com/astropy/astroquery/blob/main/astroquery/astrometry_net/core.py#L250

Thanks,
dustin

**Comment by keflavich** [comment]
Any chance you're interested in implementing that fix?  Should be pretty straightforward, I'd think

**Comment by dstndstn** [comment]
and get blamed for both sides of the API access? sounds fun! ;)
