### ISSUE TITLE
GAIA: No formatter has been found for the given MIME type "votable_gzip"

### ISSUE THREAD

**Issue by psmd-iberutaru** [astropy/astroquery#3098]
I have been having this issue recently when trying to download GAIA spectra data. Below is a minimal example of my current code, attempting to get some data for HD 34816.

```
import copy
import astroquery.gaia

# Setting up the Gaia engine.
Gaia = copy.deepcopy(astroquery.gaia.Gaia)
Gaia.MAIN_GAIA_TABLE = "gaiadr3.gaia_source" 
result = Gaia.load_data("2988329637719192960")
```

When attempting to run this, I get the following error:
```
Cannot process request: 'https://gea.esac.esa.int/data-server/data' (req: Reqid: anonymous1727233235716, retrieval access: DIRECT, retrieval type: ALL, compression: null), for user: UwsJobOwner{id='anonymous', name='null', mail='null', authUsername='null', authGroups=[], pseudo='anonymous', session='FADF59536338F011421D177E15D21039', ip='IP ADDRESS', roles=0, parameters=Owner parameters: 6},  due to: Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"  
```

This error is recent for me, and the above code worked before. Any insight is appreciated.

**Comment by bsipocz** [comment]
The code example works for me using the pre-release version from pypi; while it fails with 0.4.7. So I suggest to upgrade with `pip install -U --pre astroquery`

**Comment by psmd-iberutaru** [comment]
Upgrading to the pre-release version seems to fix the issue. Thanks.
