### ISSUE TITLE
BUG: use temporary directories for tests and cleanup after docs 

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#3099]
I keep getting a mastDownload directory in my repo whenever I run mast tests/doctests. It should not be there, either all the tests should work with temporary directories or for the documentation we should either setup temporary directories transparent to the user reading the docs or cleanup afterwards. 

cc @snbianco

**Comment by snbianco** [comment]
I don't get that directory when I run the doctests, but I do see it when I run `test_mast_remote.py::test_observations_download_products`. I'll make an MR to clean that up, but I want to make sure I'm not missing something from the doctests. The command I'm using is `python -m pytest --remote-data=any docs/mast`.

**Comment by bsipocz** [comment]
I do run the tests with `pytest -P mast -R`. TBH, I haven't dived into the details of whether the directory is created for the tests under astroquery/mast or for the doctests in docs/mast.

**Comment by snbianco** [comment]
Sorry, I read your first comment wrong! I did find the issue and made a fix at #3101
