### ISSUE TITLE
Temporary filenames in gaia.core not unique in multiprocessing environment

### ISSUE THREAD

**Issue by ndrory** [astropy/astroquery#3128]
We are using astroquery.gaia in a multiprocessing environment and we see failures with temporary output files created jusing now.strftime("%Y%m%d_%H%M%S") fail due to those not being unique.

Please consider either adding precision using now.strftime("%Y%m%d_%H%M%S.%f") or using mkdtemp() to get guaranteed unique directories/files. 

See for example https://github.com/astropy/astroquery/blob/main/astroquery/gaia/core.py#L242 and #L248

**Comment by cosmoJFH** [comment]
Hi @ndrory, thanks for your feedback, we will look into this issue asap.

**Comment by cosmoJFH** [comment]
Fixed in PR #3130
