### ISSUE TITLE
Astroquery's CASDA query for POSSUM cubes

### ISSUE THREAD

**Issue by ErikOsinga** [astropy/astroquery#3132]
Hi, 

I'm trying to download the first plane of each POSSUM cube from CASDA using astroquery (and specifically the cutout function), but I am getting the following behaviour which I don't know how to make sense of:

`ValueError: Data staging job did not complete successfully. Status was ERROR`

![image](https://github.com/user-attachments/assets/ff5abecc-07d5-45af-89f1-15895beed7c6)

Is it not possible to download a single plane of a POSSUM cube with CASDA? 

My script is as follows (following the instructions in the docs)

```
result = casda.query_region(sc, radius=30*u.arcmin)
# get only POSSUM
result = result[result['obs_collection'] == "POSSUM"]
# get only the file we want, e.g. image.restored.i.EMU_1200-73.SB67157.contcube.conv.fits
result = result[(np.char.startswith(result['filename'], 'image.restored.i.EMU')) & #
                  (np.char.endswith(result['filename'], 'contcube.conv.fits'))
                ]
# get the closest one, which should be the current SBID
idx = np.argmin(result['distance'])
result = result[idx:idx+1] # to make it a 1 length table
assert str(obsdata['sbid'][i]) in result['filename'][0], f"Something went wrong on {i=}"
print(f"Downloading first plane of {result['filename'][0]}")

channel = (0,0) # low and high channel inclusive
url_list = casda.cutout(result, channel=channel) # doesnt work for some reason
```

**Comment by jd-au** [comment]
Hi Eric,

The problem here is the channel range. The channels are numbered from 1, so if you change the second last line to:
`channel = (1,1) # low and high channel inclusive`
it will work without a problem.

Cheers,
James.

**Comment by bsipocz** [comment]
Should `The channels are numbered from 1` go into the docs, or it's enough if it's documented upstream at CASDA? Or maybe there should be better descriptive error message that points to this being the potential issue?
