### ISSUE TITLE
Problem with Gaia load data on astroquery newest version

### ISSUE THREAD

**Issue by Vincentbruga** [astropy/astroquery#3151]
Hi, sorry I dont know where to ask this question and I've been stuck on this for a few days now and dont know where to ask.
I just started a Phd and im continuing my code i wrote last year. In this code I use astroquery Gaia load data to query rvs spectrum of stars. However that code ran on the previous version on astroquery and on the new version my code returns this error everytime I try to query some spectra:

500 Error 500:
Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"

Cannot process request: 'https://gea.esac.esa.int/data-server/data' (req: Reqid: anonymous1734339297865, retrieval access: DIRECT, retrieval type: RVS, compression: null), for user: UwsJobOwner{id='anonymous', name='null', mail='null', authUsername='null', authGroups=[], pseudo='anonymous', session='7A4C56568D0E28BE8550AC4D300F5216', ip='152.77.248.24', roles=0, parameters=Owner parameters: 6},  due to: Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"
Error retrieving RVS data: Error 500:
Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"

In this an astroquery issue or a me issue ?

Thanks you for your answer !
Vincent

**Comment by cosmoJFH** [comment]
Hi @Vincentbruga , could you include the piece of code you used, to reproduce the error?

**Comment by Vincentbruga** [comment]
> Hi @Vincentbruga , could you include the piece of code you used, to reproduce the error?

Thank you for your answer ! Here is the code :

def get_obs(identification):
    RVSsourceIds = [identification]

    rvsdatalink = Gaia.load_data(ids=RVSsourceIds, retrieval_type='RVS', data_structure = 'INDIVIDUAL', output_file = None)
    rvsdatalink.keys()
    
    dl_key      = list(rvsdatalink.keys())[0]
    tables      = [product.to_table() for product in rvsdatalink[dl_key]]
    
    for rvsspectra in tables:
        wavelength_list = (rvsspectra['wavelength']*10).tolist()
        flux_list = rvsspectra['flux'].tolist()
        flux_error = rvsspectra['flux_error'].tolist()
    return wavelength_list,flux_list,flux_error

get_obs("Gaia DR3 6963761190199424")

This was just my standard function to retrieve a spectra from a Gaia DR3 name

**Comment by bsipocz** [comment]
Closing as this has been fixed in dev.
