### ISSUE TITLE
ESO queries: Add docs describing valid query keywords

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#317]
Any of the keywords available in the ESO form(s) (i.e. `http://archive.eso.org/wdb/wdb/eso/{instrument}/form`) are available to the user at the command line, but at present direct inspection of the form HTML is required to figure out what keyword to use.  For example, to query by PI, one could do:
`Eso.query_instrument('crires', pi_coi='Bill')`
to search for all CRIRES observations with `Bill` as a PI/CoI name.  

If the documentation is added, it should be accompanied by a scraping tool that will readily allow regeneration of the documentation if and when the forms are updated.

**Comment by jwoillez** [comment]
At the moment you can use `help=True` in any of `query_main()`, `query_instrument()`, `query_surverys()`. Isn't that sufficient?

**Comment by keflavich** [comment]
Sort of, yes, but it would be nice to have "offline" help too.  i.e., take the results of `help=True` and put them into an HTML document.  It's probably not that hard to do, but it hasn't risen anywhere near the top of my priorities...

**Comment by jwoillez** [comment]
#978 could help quite a lot in this. Maybe we could simply link to these `/prog` forms.

**Comment by keflavich** [comment]
The new approach to the ESO module renders this issue obsolete.
