### ISSUE TITLE
ESO Catalogue Facility

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#322]
Can we do this one too?  It's like ESO, but a little different.  Can probably use the same login code, but needs a different query tool on top.

http://www.eso.org/qi

**Comment by kakirastern** [comment]
Hi, is it okay for me to begin work on this issue?

**Comment by kakirastern** [comment]
Will start looking into how to implement this new service soon... and to follow up with a PR

**Comment by kakirastern** [comment]
Will need some time to check out what kind of architecture to be used for the module code base though... in case something else is considering the issue as well.

**Comment by keflavich** [comment]
The lack of demand for this issue over the last decade leads me to close this as not-really-wished-for.

**Comment by bsipocz** [comment]
Also, ESO TAP access should address this. I'll follow-up with folks on the plans about that at the next IVOA interop.
