### ISSUE TITLE
Skip remote tests if form page is inaccessible

### ISSUE THREAD

**Issue by derdon** [astropy/astroquery#328]
Proposal: check if accessing the form page for a respective test function results in a 200: if it does not, don't run the remote tests and give some informational output why those tests have been skipped. This issue can be considered assigned to me and I will fix it during the GSoC period when I find time for it :-)

**Comment by bsipocz** [comment]
I'm closing this issue now as I believe our remote-test setup works reasonable OK. I even find it a feature that the test choke on issues of accessing the remote service, so we more likely notice URL and service outage issue, and we also do a lot of `raise_on_status` for non 200 returns, too.
