### ISSUE TITLE
Herschel Science Archive

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#395]
http://archives.esac.esa.int/hsa/aio/doc/

**Comment by bsipocz** [comment]
Again, ESASky provides some Herschel access, though I'm not sure whether it reaches everything in the science archive.

**Comment by kakirastern** [comment]
Hi, I would like to tackle this Issue in preparation for GSoC. Can I start work on it to get used to the workflow for astroquery? I understand that this Issue was opened more than four years go... so many things may have changed since then.

**Comment by keflavich** [comment]
This would be a great tool for astroquery, but I suspect it may be part of ESA's planned contribution.  I would avoid working on this one for now.  You might have a look at finishing up the related HiGal archive PR:
https://github.com/astropy/astroquery/pull/1324

**Comment by kakirastern** [comment]
@keflavich Okay then, I should pick another issue to work on as you have suggested. Will check out #1324 soon.

**Comment by keflavich** [comment]
We have HSA access! #2122
