### ISSUE TITLE
Splatalogue's species.json should be generated on the fly

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#423]
https://github.com/astropy/astroquery/blob/master/astroquery/splatalogue/build_species_table.py generates https://github.com/astropy/astroquery/blob/master/astroquery/splatalogue/data/species.json.

This should be done on the fly instead of packaged with the source code.  The `species.json` table probably belongs in the cache directory too.

**Comment by laserkelvin** [comment]
I can take a crack at this!

**Comment by bsipocz** [comment]
Please do! and feel free to ping me on scipy slack. I'm sprinting with other project today, but happy to help here if there are any issues, questions.

**Comment by tinumide** [comment]
@bsipocz this issue has been merged. Is there still something to be done ?

**Comment by bsipocz** [comment]
Thank you, you're right it didn't get the xref closure.
