### ISSUE TITLE
Clean the caching suspension mechanism

### ISSUE THREAD

**Issue by jwoillez** [astropy/astroquery#437]
At the moment there are two ways of preventing caching:
- Pass `cache=True` to `BaseQuery._request()`
- Use of the context guard `with suspend_cache()`
  We should settle for one solution only.

I like `suspend_cache()` as you can suspend the cache for large sections where multiple requests can be present. As long as suspend_cache() counts the number of stacked suspension, you should be able to properly `suspend_cache()` within a section of code where `suspend_cache()` already apply.

Thoughts?

**Comment by bsipocz** [comment]
After the merge of #1634 I think this is now obsolete, but do reopen it if you think otherwise.
