### ISSUE TITLE
SDSS img cutout query tool?

### ISSUE THREAD

**Issue by eteq** [astropy/astroquery#444]
I have code to do this that I could pretty much move wholesale into a new PR if this makes sense, but before I do, I want to ask (esp. @keflavich , I presume?) if this really belongs in astroquery.  

Specifically, what I do very regularly is this:

```
sc = SkyCoord(1*u.deg, 2*u.deg)
view_in_sdss_navigate(sc)
```

And it then uses `webbrowser` to open a browser tab in the SDSS "navigate" interface (E.g., http://skyserver.sdss3.org/dr10/en/tools/chart/navi.aspx?ra=1&dec=2 ).  Another very similar use case is:

```
scs = SkyCoord([1, 2]*u.deg, [3,4]*u.deg)
view_in_sdss_imagelist(scs)
```

And then it shows me the SDSS image list tool (http://skyserver.sdss3.org/dr10/en/tools/chart/list.aspx).  

I can't help but think this sort of tool belongs in `astroquery` (probably in `astroquery.sdss`?), but it's not really a data "query" like the typical tools are.  Instead, it launches a visual tool. So where (if anywhere) makes sense as a place for it in `astroquery`?

**Comment by bsipocz** [comment]
Bad surprise that we still don't have this. 
This is something that can be done as a hackday project, or in prep for gsoc, etc.

**Comment by kakirastern** [comment]
Hi, I am interested in using this Issue as prep for GSoC 2019... Okay for me to open a PR?

**Comment by kakirastern** [comment]
As per indirect discussion through @kelle, I will start work on this soon.

**Comment by kakirastern** [comment]
PR #1383 opened to address this Issue.

**Comment by bsipocz** [comment]
Now looking into the code in the PR, and rereading the details of the feature request here, I don't think any more that this opening up the browser type of functionality fits well within astroquery. 

We certainly need functionality to download cutouts though, as far as I see we only provide options to download the full plates as fits, but not the functionality to get the cutout images to be used e.g. as finder charts.

What do you all think? pinging @ceb8 as our cutout expert.

**Comment by bsipocz** [comment]
As per the previous comment, and the lack of interest from anyone for years on this issue, I'm closing this as interaction with the browser is not within the remit of astroquery.

If there is interest and a PR to add a cutout method, I think it would fit better, but I'm not keeping this issue open to track that functionality.
