### ISSUE TITLE
Spitzer / WISE data query

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#45]
IRSA has a different interface to the Spitzer and WISE data than other surveys that have VO support (which in principal should make this easier to implement)

http://sha.ipac.caltech.edu/applications/Spitzer/SHA/help/doc/api.html
http://irsa.ipac.caltech.edu/ibe/

**Comment by keflavich** [comment]
SHA was implemented (at least as a first pass) in #102, and IRSA supports WISE retrieval.  Closing.

**Comment by bsipocz** [comment]
@keflavich - Please open an issue either here, or just ping me with actual useful examples for the docs. We already have Spitzer access examples, but can add any datasets that would make sense (including wise, sofia, euclid, whatever else).

(btw, we also have this: https://caltech-ipac.github.io/irsa-tutorials/, at some point I'll collect all these notebook resources and cross reference them)
