### ISSUE TITLE
Add ATLAS support to the IRSA module?

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#451]
The ATLAS service at IRSA provides API access to images:
http://irsa.ipac.caltech.edu/applications/Atlas/AtlasProgramInterface.html

but so far we've only implemented the gator service.  #450 implements the IBE interface, which may actually be a cleaner interface to exactly the same thing.  It's not clear how to list the available parameters (missions, surveys, etc.)

**Comment by bsipocz** [comment]
We're adding SIA rather than Atlas, and for cutouts the preference is also to use the ibe/data API rather than Atlas, so I'm closing this issue.
