### ISSUE TITLE
Cached Queries Cannot Be Re-run When Deleted

### ISSUE THREAD

**Issue by agroener** [astropy/astroquery#455]
I've been meaning to file this issue for a while. I've been using the caching mechanism (which is awesome, by the way). However, I've run into a bit of an issue. When a unique query is run for the first time, that particular query seems to be getting cached correctly. If I try to run it again, it won't create a new job. However, if I then delete the job from the (cosmosim) server and try to re-run the query, it returns the old cached jobid, and refuses to let me actually submit an http request. Is there someway of "updating" the cache to reflect the fact that some jobs may be deleted on my end? Is there perhaps a way to delete one particular query from the cache, running said method every time I delete a job on my end to keep things in sync?

**Comment by bsipocz** [comment]
The caching infrastructure has just been refactored. If there are some more outstanding, and addressable issues with it please reopen/open a new issue for it. Thanks.
