### ISSUE TITLE
Problem with Configuration for Vizier

### ISSUE THREAD

**Issue by steveehlert** [astropy/astroquery#463]
I have just installed astroquery on my Mac (OS X 10.9.5) and I appear to have some issues just getting the packages to initialize (the bleeding edge version). When I try and start a Vizier query, I get the following error message: 

In [1]: from astroquery.vizier import Vizier
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-b30b3faacb69> in <module>()
----> 1 from astroquery.vizier import Vizier

/usr/local/lib/python2.7/site-packages/astroquery/vizier/__init__.py in <module>()
     17 
     18 
---> 19 class Conf(_config.ConfigNamespace):
     20     """
     21     Configuration parameters for `astroquery.vizier`.

AttributeError: 'module' object has no attribute 'ConfigNamespace'

Can you help explain to me what might be happening here? There seems to be a major concern with how my version of astroquery is being implemented here. I can provide more data if need be. Thanks for your help in advance!

Steven Ehlert

**Comment by AnthonyESO** [comment]
Hi, I have the same problem. Can you help me?

**Comment by keflavich** [comment]
@astrofrog - I've been having serious issues with the whole configuration system from the dev side for the past ~2-3 weeks but I haven't had the time needed to sit down and fix it.  Thoughts?

@AnthonyESO - please let use know what version of astropy you're using so we can help

**Comment by steveehlert** [comment]
Okay, so I think I had the wrong version of astropy installed before. When I went to astropy version 0.4.2 everything appears to be behaving, at least from a software compilation point of view.

**Comment by AnthonyESO** [comment]
@keflavich How can I know the version?

**Comment by AnthonyESO** [comment]
Now, I've an another problem... the command from astroquery import vizier is OK, but not simbad! The error is : TypeError: Configuration value not valid:the value "vizier.u-strasbg.fr" is unacceptable. Thx for your help.

**Comment by keflavich** [comment]
@AnthonyESO from within python, do `import astropy; print astropy.__version__`
