### ISSUE TITLE
SIMBAD query failures: No VOTABLE return

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#466]
Reported today:

```
>>> from astroquery.simbad import Simbad
>>> t = Simbad.query_object('m1')
/usr/local/lib/python2.7/dist-packages/astroquery/simbad/core.py:852: UserWarning: Warning: The script line number 2 raised an error (recorded in the `errors` attribute of the result table): java.lang.NullPointerException
  (error.line, error.msg))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/astroquery/simbad/core.py", line 349, in query_object
    return self._parse_result(result, SimbadVOTableResult, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/astroquery/simbad/core.py", line 742, in _parse_result
    "Exception: " + str(ex))
astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error.  The attempted parsed result is in self.last_parsed_result.
Exception: No table found in VOTABLE file.
```

Reproducible.  

Script query is:

```
u'votable {main_id,coordinates}\nvotable open\nquery id  m1\nvotable close'
```

Result:
http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=votable+%7Bmain_id%2Ccoordinates%7D%0D%0Avotable+open%0D%0Aquery+id++m1%0D%0Avotable+close

or:

```
::script::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

votable {main_id,coordinates}
votable open
query id  m1
votable close

::console:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

C.D.S.  -  SIMBAD4 rel 1.223  -  2014.12.16CET02:22:09
total execution time: 0.108 secs
simbatch done

::error:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

[2] java.lang.NullPointerException

::data::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE xmlns="http://www.ivoa.net/xml/VOTable/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.2" version="1.2">
<DEFINITIONS>
<COOSYS ID="COOSYS" equinox="2000" epoch="J2000" system="ICRS"/>
</DEFINITIONS>
<RESOURCE name="Simbad query" type="results">
</RESOURCE>
</VOTABLE>
```

So it looks like the SIMBAD script submission is not working; I wonder if this is a server error?

**Comment by alvaroribas** [comment]
I wasn't sure if I should open a different ticket, but this same issue is happening again:

`from astroquery.simbad import Simbad
result_table = Simbad.query_object("m1")

---------------------------------------------------------------------------
TableParseError                           Traceback (most recent call last)
<ipython-input-4-c8344ed630d6> in <module>()
----> 1 result_table = Simbad.query_object("m1")

/Users/Alvaro/anaconda/lib/python2.7/site-packages/astroquery/simbad/core.pyc in query_object(self, object_name, wildcard, verbose)
    353         """
    354         result = self.query_object_async(object_name, wildcard=wildcard)
--> 355         return self._parse_result(result, SimbadVOTableResult, verbose=verbose)
    356 
    357     def query_object_async(self, object_name, wildcard=False):

/Users/Alvaro/anaconda/lib/python2.7/site-packages/astroquery/simbad/core.pyc in _parse_result(self, result, resultclass, verbose)
    752                                   " parsed result is in "
    753                                   "self.last_parsed_result.\n "
--> 754                                   "Exception: " + str(ex))
    755         resulttable.errors = self.last_parsed_result.errors
    756         return resulttable

TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in self.last_parsed_result.
 Exception: No table found in VOTABLE file.`
