### ISSUE TITLE
SDSS.query_region ignores additional fields

### ISSUE THREAD

**Issue by eteq** [astropy/astroquery#469]
I'm not entirely sure if this is a bug or a mis-understanding of what this is supposed to do, but I note the following two odd things about `SDSS.query_region`, which I suspect may be related:
```
In [10]: q = SDSS.query_region(SkyCoord('12h13m12s', '30deg'), radius=50*u.arcsec,fields=['objid', 'r'])
In [11]: q.colnames
Out[11]: ['objid']
```
and
```
In [12]: q = SDSS.query_region(SkyCoord('12h13m12s', '30deg'), radius=50*u.arcsec,fields=['r'])
IndexError: list index out of range
```
(the full traceback is at the bottom of this issue)

I would have expected the first one to either produce a table with 'objid' and 'r' or fail (if 'r' were not a valid entry), but it seems to *silently* not produce the ``'r'`` field.  I can't get it to produce output for *anything* other than the default values ('ra', 'dec', 'objid', 'run', 'rerun', 'camcol', and 'field').

The second may or may not be related - it seems that something fails hard of the 'objid' field is ommitted.  I speculate this is because objid is used for a join in the SQL or something?  In that case it might be a separate issue that it should always be included in the query but filtered out of the table output if it wasn't requested at the beginning.  Or it might be a sign of whatever the problem is in the first examople.

traceback from the second example:
```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/npyio.py:1403: UserWarning: genfromtxt: Empty input file: "<_io.BytesIO object at 0x10c54f0b0>"
  warnings.warn('genfromtxt: Empty input file: "%s"' % fname)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-bdd56f99f2e1> in <module>()
----> 1 q = SDSS.query_region(SkyCoord('12h13m12s', '30deg'), radius=50*u.arcsec,fields=['r'])

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroquery-0.3.dev2675-py2.7.egg/astroquery/utils/class_or_instance.pyc in <lambda>(*args, **kwds)
     22     def __get__(self, obj, cls):
     23         if obj is not None:
---> 24             f = lambda *args, **kwds: self.fn(obj, *args, **kwds)
     25         else:
     26             f = lambda *args, **kwds: self.fn(cls, *args, **kwds)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroquery-0.3.dev2675-py2.7.egg/astroquery/utils/process_asyncs.pyc in newmethod(self, *args, **kwargs)
     29             if kwargs.get('get_query_payload'):
     30                 return response
---> 31             result = self._parse_result(response, verbose=verbose)
     32             self.table = result
     33             return result

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroquery-0.3.dev2675-py2.7.egg/astroquery/sdss/core.pyc in _parse_result(self, response, verbose)
    638                             names=True, dtype=None, delimiter=',',
    639                             skip_header=1,  # this may be a hack; it is necessary for tests to pass
--> 640                             comments='#'))
    641 
    642         if len(arr) == 0:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/npyio.pyc in genfromtxt(fname, dtype, comments, delimiter, skiprows, skip_header, skip_footer, converters, missing, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise)
   1405     # Should we take the first values as names ?
   1406     if names is True:
-> 1407         fval = first_values[0].strip()
   1408         if fval in comments:
   1409             del first_values[0]
```

**Comment by eteq** [comment]
@keflavich - are you the main keeper of this,btw, or something else?

**Comment by keflavich** [comment]
@eteq - I'm the maintainer, but I didn't write this module.  The [blame](https://github.com/astropy/astroquery/blame/master/astroquery/sdss/core.py) shows that there have been many hands on  it... any help would be appreciated, but otherwise this goes on my list to investigate.

**Comment by loicseguin** [comment]
Omitting `'objid'` should not be a problem. For instance, the following query runs without a problem
```python
q = SDSS.query_region(SkyCoord('12h13m12s', '30deg'), radius=50*u.arcsec,fields=['ra', 'dec'])
```

It is true that only fields among the default values are considered. Around line 715 in `sdss/core.py`, the following code makes sure of that
```python
for sql_field in fields:
    if sql_field in photoobj_defs:
        q_select += 'p.%s,' % sql_field
    if sql_field in specobj_defs:
        q_select += 's.%s,' % sql_field
```
Hence, if you specify fields not in the default values, such as `'r'`, they are silently ignored. This means that if you only provide fields not in the defaults, the query sent to the server asks for nothing so you get nothing back.

What to do about it?

  - Nothing. I don't know what the original motivation for this behaviour was, but maybe there was a good reason.
  - Validate the user provided fields in the code to make sure it is one of the possible values based on the [spec](http://data.sdss3.org/datamodel/files/BOSS_PHOTOOBJ/RERUN/RUN/CAMCOL/photoObj.html).
  - Run the query with the user fields and process the output from the SDSS server. If a non-existent field is provided in the query, the server replies with a html error message
```python
In [34]: nop = SDSS.query_sql_async("""SELECT DISTINCT p.ra,p.dec,p.muffler
                                       FROM PhotoObjAll AS p
                                       WHERE ((p.ra between 183.286 and 183.314)
                                         and (p.dec between 29.9861 and 30.0139))""")

In [35]: nop.text
Out[35]: u"<html><head></head><body><h1>ERROR</h1><h2>Invalid column name 'muffler'.</h2></body></html>"
```
Checking for this message would allow to determine if the results should be converted to a table.

Personally, I think the third option would be best as it puts the burden of validating the fields on the server where it belongs.

Finally, the fact that the query crashes with an `IndexError` should be improved upon as it is uninformative.

**Comment by bsipocz** [comment]
I run into this as well. Using ``photoobj_fields`` instead of ``fields`` seems to be working as an alternative (but that accepts field names from the PhotoObjAll table and not the PhotoObj table!).

 I have a few additional problem though (can't query a large list of coordinates, gets "Your_browser_sent_an_invalid_request" in the result Table, etc), but will open separate issues for them.
