### ISSUE TITLE
pre-process troublesome SIMBAD identifiers

### ISSUE THREAD

**Issue by rickyegeland** [astropy/astroquery#471]
The identifier "BD+23_3912", which was stored in a VizieR catalog, is unknown to SIMBAD when submitted through the script interface:

http://simbad.cfa.harvard.edu/simbad/sim-script?submit=submit+script&script=id+BD%2B23_3912

There is no problem when submitting through the "by identifier" query form:

http://simbad.cfa.harvard.edu/simbad/sim-id?Ident=BD%2B23_3912&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

The identifier is found through the script interface when the underscore is replaced by a space.

http://simbad.cfa.harvard.edu/simbad/sim-script?submit=submit+script&script=id+BD%2B23+3912

Identifier queries such as `astroquery.simbad.Simbad.query_object` and `astroquery.simbad.Simbad.query_objectids` should pre-process identifiers of this form to make them work.

**Comment by keflavich** [comment]
@rickyegeland - That's an interesting problem.   I'd like to verify it with SIMBAD first, though, to make sure that a global underscore-to-space replacement won't cause any problems.  This seems like the sort of change they could reasonably make server-side too.  Would you be interested in raising the problem with them?

**Comment by rickyegeland** [comment]
I mailed cds-question(at)astro.unistra.fr about this.  My explanation was the same as above, concluding with:

> I am wondering, should underscores in general be replaced by spaces?  Could the SIMBAD script interface implement this behavior server side, to make the behavior identical to the "by identifier" query form?

**Comment by rickyegeland** [comment]
Someone at CDS has responded with:

> Yes, in general, underscores should be replaced by space (it is forbidden in nomenclature of identifiers).
You are right, I will add the replacement in the script mode also.

So it appears that this issue will be fixed server-side.

**Comment by keflavich** [comment]
That's great!  Thanks @rickyegeland.  I'll close this as 'fixed-upstream'
