### ISSUE TITLE
Troublesome binary identifiers

### ISSUE THREAD

**Issue by rickyegeland** [astropy/astroquery#472]
I've found another problematic identifier in a VizieR catalog that is not found it SIMBAD, 'HD 115404A' :

http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=id+HD+115404A%0D%0A

If I remove 'A', the star is found:

http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=id+HD+115404%0D%0A%0D%0A

The star is a binary, 'B' is found:

http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=id+HD+115404B%0D%0A

Should `astroquery.simbad` automatically re-check indicated binaries by removing the letter suffix?  I ran into this problem once before, but changed my data file to make it work.

I also posed this question to SIMBAD, to see if they will add the 'A' as an alias for HD 115404.  However, I suspect this may be a widespread problem...

**Comment by rickyegeland** [comment]
Hmm, it seems this problem is more complicated than I imagined, and there is unlikely to be a general solution that astroquery could implement.  A more complicated example is HD 18436A and HD 18436B (in the VizieR catalog).  Neither of those identifiers are found.  HD 18436 is found, but listed as a "multiple star".  The children objects are TYC 7560-550-1 and TYC 7560-550-2, there is no "HD" alias for either of them.  So from the information given in the catalog (coordinates not available) there is no way to distinguish which label corresponds to which individual star known by SIMBAD.  The individual stars are about 3 arcseconds apart.

**Comment by jwoillez** [comment]
Maybe you should use Vizier in astroquery? I has similar troubles with simbad in the past.

**Comment by keflavich** [comment]
Fixing this sort of clashing identifier issue is beyond the scope of astroquery.  These are really issues with the underlying database.   Julien's suggestion is helpful, but again I'd suggest taking this direct to CDS.

**Comment by rickyegeland** [comment]
Agreed.
