### ISSUE TITLE
Special-case timeout test failures for remote tests

### ISSUE THREAD

**Issue by cdeil** [astropy/astroquery#479]
To check #477 I tried running the remote-data tests and indeed they show the same error (as well as a few others) with Python 3:
https://gist.github.com/cdeil/3478f0aff8bba57f5cc6#file-gistfile1-txt-L3382

Here's the test fails I get with Python 2:
https://gist.github.com/cdeil/01d4e23a64ea117cb157#file-gistfile1-txt-L2633

But it's very tedious because
a) the timeouts are sometimes 60 seconds, so the test suite takes 15 minutes to finish
b) most fails are timeouts and it's hard to find the "real" issues.

So this is a feature request to implement shorter timeouts and to add an option to disregard timeout failures (or only list them in a separate table, but not show their tracebacks).
I have no idea if this already exists for `astroquery` or would be easy / hard to implement in the test runner.

**Comment by keflavich** [comment]
1. No, this doesn't exist yet
2. I don't know how easy it is to change the test parameters.  It may be possible to pre-load a configuration file and set shorter timeouts there.

**Comment by keflavich** [comment]
We've been playing whack-a-mole with these sorts of issues forever.  I'm closing as we never found a general solution but have found a long series of one-off solutions.
