### ISSUE TITLE
How to switch mirror?

### ISSUE THREAD

**Issue by kgullikson88** [astropy/astroquery#493]
I am using astroquery v0.2.2, and am wondering if there is a way to tell astroquery to use a specific mirror for simbad (or other services, but I mostly care about simbad)? I see that the mirror to use is defined in the init.py for astroquery.simbad, but it looks like I would have to go in and edit the code to whatever mirror I want. Is there a way to change the mirror from the astroquery api?

**Comment by keflavich** [comment]
Yes.  You can change `Simbad.SIMBAD_URL` interactively, or you can configure the default in your `~/.astropy/config/astroquery.cfg` file.  You should be able to change the default URL for a given session by changing `astroquery.simbad.conf.server`, then every subsequent `Simbad` instance should use that server.

For more details about the configuration system, see http://docs.astropy.org/en/v1.0/config/index.html

**Comment by kelle** [comment]
The Strasburg SIMBAD site is currently down and we (me and @sherelyna) are trying to change the `astroquery.simbad.conf.server` and am having a hard time. What we tried:
```
from astroquery.simbad import conf
conf.server = `simbad.harvard.edu`
```

But the code is still returning an error that says 
`503 Service Error. Service unavailable for http://simbad.u_strasburg.fr/simbad/sim`

**Comment by keflavich** [comment]
Change `Simbad.SIMBAD_URL`.  Changing the conf at runtime has no effect; I was wrong in 2015.

**Comment by kelle** [comment]
Thanks for the clarification!!
```
from astroquery.simbad import Simbad
Simbad.SERVER = 'harvard.simbad.edu'
```
or 
```
Simbad.SIMBAD_URL = 'harvard.simbad.edu'
```
I don't see anything about SIMBAD_URL in the docs.

**Comment by keflavich** [comment]
`Simbad.SIMBAD_URL='http://harvard.simbad.edu/simbad/sim-script'`

this is definitely something we should fix, both in terms of documenting and likely URLs

so what it _should_ be (but isn't now) is
`Simbad.URL = 'harvard.simbad.edu'`
or similar.

**Comment by bsipocz** [comment]
@keflavich - the URL part is picked up from the config, use it as it's intended and documented and it all works as expected: https://astroquery.readthedocs.io/en/latest/#default-configuration-file
There is one typo in that default render, namely that the field is called `server` and not `simbad_server`, so it's not enough to uncomment and change the value.

```
In [1]: from astroquery.simbad import Simbad

In [2]: Simbad.SIMBAD_URL
Out[2]: 'http://simbad.harvard.edu/simbad/sim-script'

In [3]: Simbad.query_object("m1")
Out[3]: 
<Table length=1>
MAIN_ID      RA         DEC     RA_PREC DEC_PREC COO_ERR_MAJA ... COO_ERR_ANGLE COO_QUAL COO_WAVELENGTH     COO_BIBCODE     SCRIPT_NUMBER_ID
          "h:m:s"     "d:m:s"                        mas      ...      deg                                                                  
 object    str13       str13     int16   int16     float32    ...     int16       str1        str1             object            int32      
------- ----------- ----------- ------- -------- ------------ ... ------------- -------- -------------- ------------------- ----------------
  M   1 05 34 31.94 +22 00 52.2       6        6           -- ...             0        C              R 2011A&A...533A..10L                1

```

The config itself can be successfully updated at runtime, too, but there I think there is some instantiation issue and the class is not picking up the updated value neither when changed globally nor in a context manager.
