### ISSUE TITLE
Documentation build failure

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#504]
The docs are failing with the error `ImportError: No module named astropy.extern.six.moves` despite the fact that astropy is in `rtd-pip-requirements`.  I don't know why...

https://readthedocs.org/builds/astroquery/2495221/

**Comment by hamogu** [comment]
Can this be closed? The current build passes.

**Comment by bsipocz** [comment]
thanks @hamogu, this indeed works at the moment. However there is something strange going on with rtd and version numbers, but I'll open a new issue for that.
