### ISSUE TITLE
Add SPHERE form to ESO query

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#510]
The SPHERE instrument specific form has just been created and it needs to be added.
http://archive.eso.org/cms/eso-data/instrument-specific-query-forms.html

**Comment by jwoillez** [comment]
Now that SPHERE is in the web page mentioned above, I don't think there is any extra thing we have to do.

    >>> from astroquery.eso import Eso
    >>> eso=Eso()
    >>> eso.list_instruments()
    ['fors1', 'fors2', 'sphere', 'vimos', 'omegacam', 'hawki', 'isaac', 'naco', 'visir', 'vircam', 'apex', 'uves', 'giraffe', 'xshooter', 'muse', 'crires', 'kmos', 'sinfoni', 'amber', 'midi', 'harps']

Close issue?

**Comment by bsipocz** [comment]
Yes, it was added to the instrument list in #551 (as it caused remote test failing). I haven't noticed this open issue then.
