### ISSUE TITLE
Implement the ``verbose`` keyword to the sdss module

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#520]
It seems like that the `verbose` keyword is not implemented in the sdss module. I guess this can be labeled as a novice task as only need to copy the solution over from the other modules.

**Comment by tinumide** [comment]
Would love to take a go at this

**Comment by bsipocz** [comment]
Let's wait with this one a bit, and discuss it first, I'm not sure the kwarg is preferable any more.

@keflavich @ceb8  - what do you think, should we still at verbose kwargs, or rather use the logger? @andamian good arguments was pushing my thinking towards the logger only setup rather than verbose printing
