### ISSUE TITLE
Changing the default SDSS table to query

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#527]
Querying `PhotoObjAll` and `SpecObjAll` should only be done when one needs special fields only stored in those tables. SDSS suggest to query one of the views which is faster and also may have more indexing.
Simply changing the default wouldn't break the current API as the custom field query was not working as noted in #469.

**Comment by eteq** [comment]
Note that #545 impacts this: there I noticed that actually (at least for DR12), the *same* fields are in ``PhotoObj`` and ``PhotoObjAll``.  The difference is in *which* objects are in the table, I believe, rather than which fields.  Or am I missing something, @bsipocz ?

**Comment by bsipocz** [comment]
@eteq - Yes, you're right. It seems that ``PhotoTag`` is the one with fewer fields. 
However I think we still have to consider whether we to keep ``PhotoObjAll`` as the default or to switch to a cleaner view, e.g. ``PhotoObj`` or even to a thinner table like ``PhotoTag``. I would vote for the going with ``PhotoObj``, but I only marginally use SDSS so my vote shouldn't count much.

**Comment by bsipocz** [comment]
Default is now the latest and greatest DR17, and we do test with all DRs for a while now, so I'm fairly certain this has been resolved at some point over the years.
