### ISSUE TITLE
Separate clean template from annotated template

### ISSUE THREAD

**Issue by abigailStev** [astropy/astroquery#528]
Suggestion: have a separate clean template to actually use, and an annotated template with many comments to look through for suggestions/advice/help.

**Comment by keflavich** [comment]
Wanted: script to strip out "junk" from template, or create new module with appropriate names by `s/Template/NewModule/g` on the template codes

**Comment by bsipocz** [comment]
Thank you for the idea. However, I'm closing this issue now as the template and using existing modules as examples seems to work fine in practice. If someone wants to implement a script to auto-generate a new module, they are welcome to do so, I just don't feel it has a particularly good cost-benefit relation to keep an issue open for it.
