### ISSUE TITLE
Add acknowledgement tools: astroquery.acknowledgement, astroquery.module.acknowledgement, etc.

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#530]
We need to tell users the best way to acknowledge astroquery and the utilities astroquery provides interfaces to.  

I envision an `Acknowledgement` class that includes the appropriate metadata with a `.bibtex` method and a `.footnote` method.  Each module should then include one of these!

**Comment by kalgash82** [comment]
could it be based on what @astrofrog has done? http://astrofrog.github.io/acknowledgment-generator/
Maybe you can use part of the code he uses in there. I am currently adding new software and facilities to that list.

**Comment by keflavich** [comment]
Yeah, I think it needs to be more than that, BUT we can also implement an astroquery interface to his service.

**Comment by keflavich** [comment]
Just cite https://ui.adsabs.harvard.edu/abs/2019AJ....157...98G/abstract
