### ISSUE TITLE
Add "nice astro images" service?

### ISSUE THREAD

**Issue by cdeil** [astropy/astroquery#533]
How about adding a "nice astro images" service?
This would be something that could be used for fun / demos.

I'm neither sure how it should work nor where to get the images from (or if it's useful to have something like this in astroquery at all).

Something like this?

``` python
>>> from astroquery.nice import get_images
>>> result = get_images(count=10, site='google', tags=['galaxy', 'merger'], resolution='high')
```

Maybe (if image archives support it) there could even be a way to get preview thumbnails or some way for the user to select which images to get.

I guess Google is the least scientific image server, then there's things like
 https://instagram.com/nasachandraxray/ and finally there's professional astro image servers like hubble where every image has WCS.

**Comment by keflavich** [comment]
:+1: cool idea

**Comment by keflavich** [comment]
I still love this idea, but I think it has fundamental problems.  Google isn't a reliable index, and I don't think there are any reliable indices.  Closing as "too hard" / "missing upstream solution".
