### ISSUE TITLE
add DR argument for sdss queries

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#543]
There are significant differences between the DRs of SDSS, it may be useful to have an optional argument which release should be used.
(I guess this is pretty straightforward to implement, one only needs to check that the API remained unchanged between releases and put all the URL in a dictionary, etc.)

**Comment by embray** [comment]
Ah okay, I was confused why this was assigned to me since I have no idea what this means :)

**Comment by eteq** [comment]
Hah, yeah, sorry, finger slipped on the mouse.

Also, @bsipocz, I assigned this to me because this is addressed by #545 .

**Comment by parejkoj** [comment]
Tests added for this in my fork, @eteq has merged them in. I'll make the code work with the (now failing) tests and check that in, and we can close this.
