### ISSUE TITLE
HTTPError: 405 Client Error: Method Not Allowed in Alma.stage_data()

### ISSUE THREAD

**Issue by mebpvisser** [astropy/astroquery#555]
I'm writing a program that loops over a list of project codes for cycle 1 data with the goal to grab all of the .tar files that contain .FITS files. My script successfully downloads the first project in the list, but always gets the HTTPError: 405... on the second project, regardless of the actual list of projects. Note that these are all public projects. I suspect it may have something to do with GET vs. POST in Alma.stage_data(). Is there some kind of work-around? I can provide my script if you need it.

Below is the full exception message:

```
HTTPError                                 Traceback (most recent call last)

/n/astromake/opt/casa/casa-stable-4.5.37/lib/python2.7/casapy.py in <module>()
----> 1 
      2 
      3 
      4 
      5 

/n/astromake/opt/casa/casa-stable-4.5.37/lib/python2.7/casapy.py in <module>()
     30 
     31 
---> 32             link_list = Alma.stage_data(uids)
     33 
     34             Alma.cache_location = '/n/subaruraid/mvisser/cycle1/' + project_code

/n/astromake/opt/casa/casa-stable-4.5.37/lib/python2.7/site-packages/astroquery/alma/core.pyc in stage_data(self, uids)
    242         self._staging_log['initial_response'] = response
    243         log.debug("First response URL: {0}".format(response.url))
--> 244         response.raise_for_status()
    245 
    246         if 'j_spring_cas_security_check' in response.url:

/n/astromake/opt/casa/casa-stable-4.5.37/lib/python2.7/site-packages/requests/models.pyc in raise_for_status(self)
    849 
    850         if http_error_msg:
--> 851             raise HTTPError(http_error_msg, response=self)
    852 
    853     def close(self):

HTTPError: 405 Client Error: Method Not Allowed
```

**Comment by keflavich** [comment]
@mebpvisser first, a github note: for code blocks, surround the code with triple-backticks (```), or for inline code, single-backticks.

As for this bug: I have encountered it as well, and I don't understand it.  Perhaps you're right about the "get" vs "post" issue.

The workaround is to create a new `Alma` instance each time.  So, within the loop:

```
for project in projects:
    Alma().stage_data(...)
```
instead of `Alma.stage_data` should work.

**Comment by mebpvisser** [comment]
Alright, thanks for letting me know.

With regards to the error, replacing Alma.etc with Alma().etc seems to have done the trick!
