### ISSUE TITLE
Add Hubble Legacy Archive (HLA) query tool

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#556]
As raised on facebook: 
https://www.facebook.com/groups/astropython/permalink/1620796111498406/

The archive:
http://hla.stsci.edu/

**Comment by bsipocz** [comment]
HLA is supposed to be available with ESASky. http://www.cosmos.esa.int/web/esdc/esasky-observations

**Comment by ceb8** [comment]
You can get HLA data through the MAST module. Set `obs_collection="HLA"` in a criteria query.

**Comment by bsipocz** [comment]
Is this a doc issue then to add a HLA example to e.g. the mast or esasky doc?

**Comment by ceb8** [comment]
It was originally raised in 2015, which was before the MAST module existed, I don't know about ESASky. So it might just be deprecated.

**Comment by bsipocz** [comment]
oh, fair enough, I didn't look at the date :) Let's close it then.
