### ISSUE TITLE
add query by position to the reddening maps from NED/IRSA

### ISSUE THREAD

**Issue by PaulKuin** [astropy/astroquery#562]
It would be useful to be able to retrieve the reddening given a position. NED/IRSA provides that via a web query, so it would be useful to have that available.  I find query by position more important for this than by name as transient objects are usually not in the name server.  

It is possible that this service is already provided from another provider. If so, it would be handy to know and apologies for my ignorance.

**Comment by keflavich** [comment]
IRSA_dust provides this (#110 originally implemented this).

**Comment by bsipocz** [comment]
Closing it following the comment above, feel free to open issues to irsa_dust if something comes up.
