### ISSUE TITLE
Vizier query_object returning too many objects?

### ISSUE THREAD

**Issue by AlexaVillaume** [astropy/astroquery#565]
Hi all,

I'm trying to get 2MASS information using astroquery.vizier by using the query_object function. If I go to the Vizier browser and query an object, say, 'J13545462-2600566' the information for one object is returned. However, if I do something like 

 Vizier.query_object("J13545462-2600566", catalog=['2MASS'])

the information of 20 objects is returned. Perhaps I'm misunderstanding how this function is supposed to work but I would like to be able to query an ID and just get the "right" star back. Is there a way to do that?

Thank you,
Alexa

**Comment by keflavich** [comment]
`query_object` queries around an object with a fixed radius.  You could shrink that radius, or you could `query_constraints` instead, e.g.:

`Vizier.query_constraints(**{'2MASS':"J13545462-2600566", 'catalog':'II/246'})`

**Comment by bsipocz** [comment]
I'm closing this as multiple workarounds have been provided. Feel free to reopen and provide more clarification of what is needed instead of the workaround in the comment above.
