### ISSUE TITLE
No errors returned for JHK magnitudes from Simbad Query

### ISSUE THREAD

**Issue by twotonnetess** [astropy/astroquery#567]
Hi all, 

I was querying for JHK magnitudes and errors. No errors are returned for any targets - all error fields are empty. 

Thanks, 
Grainne

**Comment by keflavich** [comment]
I think this can be fixed if you capitalize the filter names, e.g.:
```
S.add_votable_fields('flux(K)','flux_bibcode(K)','flux_error(K)','flux_quality(K)')
```

**Comment by twotonnetess** [comment]
yes, that did the trick, thanks!
