### ISSUE TITLE
simbad.Simbad.query_bibobj('2004MNRAS.350.1195M') gives TableParseError

### ISSUE THREAD

**Issue by zpace** [astropy/astroquery#568]
I am trying to scrape SIMBAD data for all the objects in the HIPASS catalog, using the corresponding paper's refcode.

When I run `simbad.Simbad.query_bibobj('2004MNRAS.350.1195M')`, I get the following error:

```
---------------------------------------------------------------------------
TableParseError                           Traceback (most recent call last)
<ipython-input-29-a5b49c6844d1> in <module>()
      1 unlimitedSimbad = simbad.Simbad()
      2 unlimitedSimbad.ROW_LIMIT = 8000
----> 3 HIPASS = unlimitedSimbad.query_bibobj('2004MNRAS.350.1195M')

/home/zpace/anaconda/lib/python2.7/site-packages/astroquery/simbad/core.pyc in query_bibobj(self, bibcode, verbose)
    535         """
    536         result = self.query_bibobj_async(bibcode)
--> 537         return self._parse_result(result, SimbadVOTableResult, verbose=verbose)
    538 
    539     def query_bibobj_async(self, bibcode):

/home/zpace/anaconda/lib/python2.7/site-packages/astroquery/simbad/core.pyc in _parse_result(self, result, resultclass, verbose)
    741                                   "in self.last_response, and the error in self.last_table_parse_error."
    742                                   "  The attempted parsed result is in self.last_parsed_result.\n"
--> 743                                   "Exception: " + str(ex))
    744         resulttable.errors = self.last_parsed_result.errors
    745         return resulttable

TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error.  The attempted parsed result is in self.last_parsed_result.
Exception: None:4398:69: ValueError: invalid literal for int() with base 10: 'no coord.' (in row 228, col 'RA_PREC')
```

This method seemed to work fine for other references. I thought initially that it could be a consequence of having so many objects (over 4000), but I set `ROW_LIMIT = 8000` and `TIMEOUT=8000`, well above the size of the catalog and the time required to view it on the web, and got the same result.

I also tried reproducing the error with another large dataset (all the SDSS quasars: `bibcode='2011ApJS..194...45S'`), and that succeeded (after I increased the time allotment).

I'm using astroquery v0.2.5.

**Comment by keflavich** [comment]
This seems to be a violation of some internal rule in the votable.  I believe it indicates a problem in the way SIMBAD has stored the table.  `no coord.` is not a valid coordinate, but it is in a column that has a coordinate type.  This needs to be reported to the SIMBAD team.  The relevant script to get this result is:
```
votable {main_id,coordinates}
votable open
query bibobj  2004MNRAS.350.1195M
votable close
```

**Comment by keflavich** [comment]
I never received a response.

**Comment by bsipocz** [comment]
Closing this issue as the example is working me today with v0.3.4.
