### ISSUE TITLE
Failing test on travis-ci: test_pyregion_subset

### ISSUE THREAD

**Issue by cdeil** [astropy/astroquery#569]
I noticed that the astroquery builds for Astropy master on travis-ci are currently failing because of `test_pyregion_subset`:
https://travis-ci.org/astropy/astroquery/jobs/73540619#L1109

(I don't have time to investigate / fix this week, sorry, just wanted to report it.)

**Comment by sudheesh001** [comment]
@cdeil It looks like this issue has been fixed in the test by asserting values between `313 and 315`
I think this issue can be closed now. :smile: 
https://github.com/astropy/astroquery/blob/e3b69e71051c1ef7c5e122cc81b454dbd7ddb606/astroquery/alma/tests/test_alma_utils.py#L32

**Comment by cdeil** [comment]
OK.
