### ISSUE TITLE
SkyView raises 404 for missing footprint rather than raising sensible exception

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroquery#572]
I'm tinkering with `SkyView` and found that some surveys which are listed in the "available" dict cannot be retrieved. For example: 

``` python
>>> from astropy.coordinates import SkyCoord
>>> import astropy.units as u
>>> from astroquery.skyview import SkyView
>>> SkyView.get_images(position=SkyCoord.from_name('Eta Carinae').icrs, coordinates='icrs', 
survey='DSS', radius=10*u.arcmin)   # This one works
Downloading http://skyview.gsfc.nasa.gov/tempspace/fits/skv668897475476.fits
|==========================================| 374k/374k (100.00%)         0s
[[<astropy.io.fits.hdu.image.PrimaryHDU at 0x10a4a6fd0>]]

>>> SkyView.get_images(position=SkyCoord.from_name('Eta Carinae').icrs, coordinates='icrs', 
survey='SDSSi', radius=10*u.arcmin)   # This one doesn't
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-38-bb7b9d70e956> in <module>()
----> 1 SkyView.get_images(position=SkyCoord.from_name('Eta Carinae').icrs, coordinates='icrs', 
survey='SDSSi', radius=10*u.arcmin)
HTTPError: HTTP Error 404: Not Found
```

I get similar results for all `"SDSS*"` surveys, `"DSS1 *"`, and more. I'm using py27, astroquery 0.2.6.

**Comment by keflavich** [comment]
Thanks - it's possible something on skyview changed or we're indexing them incorrectly.

**Comment by keflavich** [comment]
Revisiting this, I now get a timeout error, not the 404 error reported.  This makes me realize that SkyView does not have a configurable timeout setting.

**Comment by bsipocz** [comment]
`Eta Carinae` is now covered by SDSS, so I assume this is the way of the server saying there is no image to return. So we need a better handling of no return data.

Trying the same example with a valid coordinate it works again. (try e.g. `'M51'`).

**Comment by bsipocz** [comment]
I'm not sure what we can do here. The response here is a HTTPResponse, and even the webpage is fully useless and doesn't give the actual real reason for the error, namely that there is no coverage (for this particular example, but it's possible that the same 404 is thrown at other issues, too).

<img width="1120" alt="Screenshot 2022-11-30 at 23 33 29" src="https://user-images.githubusercontent.com/6788290/204993438-3505e8f1-acb4-4b7d-a804-028a79f707b7.png">

**Comment by bmorris3** [comment]
Agreed that this is probably out of scope for a fix within astroquery.

**Comment by bsipocz** [comment]
At best we can add-on an extra "maybe the problem...", message into the exception, but I don't feel totally well about that maybe message unless we know that seeing this is almost always comes down to missing coverage. So I suppose we may instead want to point users to use primary sources whenever they can.

**Comment by keflavich** [comment]
SkyView has undergone a significant refactoring recently too.  I'm going to close this as a known upstream problem that we don't have a general solution to (i.e., we're not able to make more specific errors)
