### ISSUE TITLE
Make SDSS module use unified API

### ISSUE THREAD

**Issue by parejkoj** [astropy/astroquery#573]
@adamamiller and I are interested in improving the SDSS module and making it use the unified astroquery API. Has any progress happened on that recently, or is there another issue where this is being tracked?

We're currently at AstroHackWeek, so we're perfectly placed to spend a few hours on this this week.

**Comment by keflavich** [comment]
@parejkoj work is very welcome on this!  You might have a look at https://github.com/astropy/astroquery/pull/545, which seems to have stalled.  @bsipocz, can you offer any further suggestions or comments on ongoing SDSS work?

**Comment by bsipocz** [comment]
@keflavich @parejkoj - I don't have any ongoing work atm on the module. Obviously it would be nice if you could also address some of the issues&feature requests already reported.
https://github.com/astropy/astroquery/search?q=sdss&state=open&type=Issues&utf8=%E2%9C%93

ping @eteq as he is the one who can commend on the status of #545

**Comment by bsipocz** [comment]
@parejkoj - Also if there's a way of remote hacking, I'm happy to join in for a few hours later this week.

**Comment by parejkoj** [comment]
Ok, I'll talk with @adamamiller and we'll see about scheduling something for Thursday or Friday, and post about it here. We could do this over skype, hangout, or the AstroHackWeek slack.

**Comment by bsipocz** [comment]
Sounds good.

**Comment by parejkoj** [comment]
@bsipocz @eteq a group of us are going to try to work on this (and other SDSS improvements) at #AstroHackWeek on Thursday circa 2pm ET. Will that work for you? How would you like to join in?

**Comment by bsipocz** [comment]
Sounds good. That's 7PM here, so I should have a quite office available :) 
I never used slack, but can check it out and then you can chose which  one you prefer from your suggestions.

**Comment by bsipocz** [comment]
@parejkoj - Change of plans on my side, going offline now while heading home but will be back in about 1.5-2 hours.

**Comment by parejkoj** [comment]
Ok. I sent you a tweet with how to get in to our slack group, or just email me at john.parejko@yale.edu

**Comment by bsipocz** [comment]
It would be really great to get that warning off the module. After all this time, @parejkoj and @eteq and anyone else, are you still interested in getting this done in the near future timescale?
I mean it's not just this issue, but sprinting on pushing these sdss related ones a bit down: https://github.com/astropy/astroquery/labels/sdss

**Comment by bsipocz** [comment]
@keflavich - I would say it's fit well within the API now, shall we close this?
