### ISSUE TITLE
Fix and un-xfail bytes/string disagreement in SDSS tests

### ISSUE THREAD

**Issue by eteq** [astropy/astroquery#581]
Following from #545, we pushed up a test that was failing (and xfailed) for reasons that _probably_ have to do with test monkeypatching rather than real failures. The issue is that in py3, the 'isntrument' column of the tables in the `test_sdss.py` file is `bytes` for the mocked-up version, and `str` for the version loaded from a file.  But this _doesn't_ happen in py2.x becaus str/bytes aren't distinct.

So it seems like a testing issue but _might_ be  real problem.  I think @parejkoj is going to work on this?

**Comment by bsipocz** [comment]
These have been fixed for a long time now, so I'm closing the issue.
