### ISSUE TITLE
Make use of older DRs for sdss actually work

### ISSUE THREAD

**Issue by eteq** [astropy/astroquery#582]
The version merged in #545 has some xfails because older DRs (not dr12) aren't working.  That needs to be fixed to get older DRs to work right.

Either @bsipocz or @parejkoj were working on this, I think?

**Comment by parejkoj** [comment]
I'm working on this. See #543

**Comment by bsipocz** [comment]
Some of the tests fails as the xfailer method ``_url_tester(dr)`` placed after the actual asserts in the given test function. I fixed that for #586.

**Comment by bsipocz** [comment]
This was accidentally closed in #586, what I meant to close is #584

**Comment by bsipocz** [comment]
This should be fixed for a while now, but feel free to reopen when running into any further issues with old DRs.
