### ISSUE TITLE
MockResponse needs a way to return a json

### ISSUE THREAD

**Issue by parejkoj** [astropy/astroquery#583]
In sdss.field_names.get_field_info(), we call _columns_json_to_table(qryres.json()), but a MockResponse doesn't have a json method. Without that, most of the new tests blow up with Errors.

**Comment by keflavich** [comment]
@parejkoj I added a json method in https://github.com/keflavich/astroquery/commit/a0e469d8db6e7299ba42b78af5ec3c18a2d610fa if you want to cherry-pick that

**Comment by keflavich** [comment]
@parejkoj maybe just merge that, don't cherry-pick

**Comment by parejkoj** [comment]
Ok, I found that, but now I've run into trouble because sdss was still using common.send_request instead of self._request, which do rather different things. Trying to sort that out now.

**Comment by weaverba137** [comment]
There is an additional underlying problem. The field_names.py module is "touching" the Internet behind the scenes, the functions that do this need to be marked @remote_data, and an appropriate monkey patch needs to be added for testing.

**Comment by bsipocz** [comment]
@parejkoj, @weaverba137 - Did you get any progress on this? If yes could you push it to a brach/PR whatever, even if it's unfinished? I'm almost finished to make the transition to use ``self._request``, and prefer to cherry-pick any work you've done.

**Comment by parejkoj** [comment]
It's a two line fix, as mentioned by keflavich above. I'll commit and push my stuff from yesterday now, even though it's still broken, and you can take a look.

**Comment by bsipocz** [comment]
Yes, I have json stuff from @keflavich's branch already.

**Comment by parejkoj** [comment]
Ok, the problem @weaverba137 brought up above is going to require more work: the tests are still failing because of it. See this commit for what progress I made: 8a8afe9e9a6a83deb1fbc5adbbb5435780dad206

**Comment by weaverba137** [comment]
I am sort of away from the Internet until Monday.
