### ISSUE TITLE
SkyView.get_images fails with Python 3

### ISSUE THREAD

**Issue by evertrol** [astropy/astroquery#593]
astroquery nicely points out that FITS files should be downloaded with a binary encoding, when `SkyView.get_images_async` uses the `utils.common.FileContainer` class to download  FITS files from the skyview server.

For Python 2(.7), this still works fine. With Python 3(.5), one gets a UnicodeDecodeError. 

The simple fix seems to be to change [line 222 in skyview/core.py](https://github.com/astropy/astroquery/blob/master/astroquery/skyview/core.py#L222) to 

        return [commons.FileContainer(url, encoding='binary') for url in image_urls]

<hr>
Since it appears this bug was not caught earlier (I can't find it in another issue), I'm either doing something wrong, or there may be a unit test missing. I hope someone can clarify this for me.

**Comment by keflavich** [comment]
Likely there is a missing unit test.  We probably ought to add both a remote and a local test for skyview image downloads.  @evertrol interested in making one?

**Comment by bsipocz** [comment]
just as a side note: we're not yet testing against 3.5, so there is a slight chance that this on that. Anyway extending the test coverage would be highly appreciated.

**Comment by evertrol** [comment]
It looks like `get_images()` doesn't fail on its unit test `test_skyview_remote::test_get_images()`, because the latter actually never downloads the image: it just retrieves the list of images, making the unit test essentially the same as `test_get_image_list()`. As long as the images stay on the Skyview server, the encoding error will never occur.
So, the current test is:

```python
@remote_data                                                                           
def test_get_images():                                                                 
    images = SkyView().get_image_list(position='Eta Carinae',                          
                                      survey=['2MASS-K'])                              
    assert len(images) == 1                                                            
    for im in images:                                                                  
        assert im.startswith('http://skyview.gsfc.nasa.gov/')                          
```

which I've changed to 

```python

@remote_data                                                                           
def test_get_images():                                                                 
    images = SkyView().get_images(position='Eta Carinae', survey=['2MASS-K'])          
    assert len(images) == 1                                                            
    assert isinstance(images[0], HDUList)                                              
```
and that fails properly (and succeeds with the suggested fix).

I'm not sure what can be done for the local test. Possibly, a simple FITS image file can be stored in the data directory, but then the local relative URLs should change, since they currently start with `../../skv*`, which requires the FITS file to be in an odd directory.
