### ISSUE TITLE
Setting up new tests for a module

### ISSUE THREAD

**Issue by agroener** [astropy/astroquery#599]
Hi, It's been quite a while since I've worked on the CosmoSim module. One of the biggest loose ends which I would like to address first (before moving on to new features), is creating a solid test structure of its foundation. An issue is already open for the creation of tests for CosmoSim (https://github.com/astropy/astroquery/issues/457), however, I'm having some issues with running the tests.

Firstly, how can I hook my current branch into this issue?

**Comment by keflavich** [comment]
@agroener to hook a branch into an issue and make a pull request, you need write access to the repository - so if you want me to do that, just let me know the branch name and I will

**Comment by bsipocz** [comment]
You can do this through the GitHub api. There's a tools repo and an
issuetopr script either under the astropy user or @eteq, or I also must
have a fork of it (sorry I can't check it ATM as I'm away from laptops).

Anyway with that script you can turn an issue to a PR using a branch of
yours without write access.

**Comment by agroener** [comment]
@keflavich The branch is: cosmosim-latest-unittests

**Comment by keflavich** [comment]
@agroener since #600 already exists, we can't attach a new PR.  We'll just close this issue when that one is merged.  Let's move discussion there.

**Comment by bsipocz** [comment]
I'm closing this in favour of https://github.com/astropy/astroquery/issues/457. Also, there are more relevant info in linked, closed PRs.
