### ISSUE TITLE
Updating travis matrix with different astropy versions

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#612]
We may want to test against different astropy versions. Currently it's only against "stable" which means the stable released version available through conda.

However the [astroquery requirement page](https://astroquery.readthedocs.org/en/latest/#requirements) lists that astropy>=0.4 is required. Also 1.1 is out very soon meaning that the LTS version may need to beg into the matrix, too. Also testing agains the dev version would make some sense, too.

cc @keflavich

**Comment by keflavich** [comment]
:+1:, let's test against the latest release, the stable, and the dev?

**Comment by bsipocz** [comment]
@keflavich - OK. I'll update the matrix once 1.1 is out. 
What shall we make with 0.4 then? If we still support that there should be a build for it, but I think it's old enough to drop and update the requirements on the docs for >=1.0

**Comment by keflavich** [comment]
:+1: to dropping 0.4 support in favor of >=1.0.  Also, thanks a bunch for the ci-centralization work!  That sounds great.  I have ~5-6 other projects that use package-template but are not affiliated, and I haven't gotten around to updating them yet, so this will be huge.

**Comment by bsipocz** [comment]
Yes, that was the idea. Also there are around 30 affiliated now, so even making sure they work is a nightmare.

If you give me a list, I can make the changes for them to use ``ci-helpers``, etc.

**Comment by keflavich** [comment]
I think this is the best way to get at that list:
https://github.com/search?utf8=%E2%9C%93&q=user%3Akeflavich+submodule+%22astropy-helpers%22&type=Code&ref=searchresults
or maybe:
https://github.com/search?utf8=%E2%9C%93&q=user%3Akeflavich+submodule+%22astropy-helpers%22&type=Code&ref=searchresults

gaussfitter, sdpy, higal_sedfitter, image_tools, dust_emissivity, fits_tools, class_reader, sdpy

**Comment by bsipocz** [comment]
:+1:

**Comment by bsipocz** [comment]
OK, so I've opened PRs for all except ``class_reader``, as it seems to be one that hasn't been set up with ``astropy-helpers``, etc. Also I didn't updated ``APEX_CMZ_H2CO`` as it doesn't looked like a package. If you think it would do any good to update that, too I can do it quite quickly now.

On the other hand many things are failing or errored, I may be able to get back to them, in most cases I guess the problems can be fixed by giving a dependency list.

**Comment by bsipocz** [comment]
Done in #627
