### ISSUE TITLE
Add VAMDC interface

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#618]
Probably only a limited variant to match the splatalogue query tool:
http://portal.vamdc.eu/

**Comment by keflavich** [comment]
As a step along the way, and possibly the only one I'm interested in implementing, I'd like to be able to parse CDMS results into astropy tables.  Here is an example query:
```
    import requests
    import bs4
    url = 'http://cdms.ph1.uni-koeln.de/cdms/tap/'
    rslt = requests.post(url+"/sync", data={'REQUEST':"doQuery", 'LANG': 'VSS2', 'FORMAT':'XSAMS', 'QUERY':"SELECT SPECIES WHERE MoleculeStoichiometricFormula='CH2O'"})
    bb = bs4.BeautifulSoup(rslt.content, 'html5lib')
    h = [x for x in bb.findAll('molecule') if x.ordinarystructuralformula.value.text=='H2CO'][0]
    tem_, Q_ = h.partitionfunction.findAll('datalist')
    tem = [float(x) for x in tem_.text.split()]
    Q = [float(x) for x in Q_.text.split()]
```
So the first priority is implementing a CDMS table parser.  @vilhelmp, I think you might also be interested in this?

**Comment by vilhelmp** [comment]
Yes, this would be nice indeed.

**Comment by vilhelmp** [comment]
After working a bit with Holger Muller (guy behind http://www.astro.uni-koeln.de/cdms), I realize that it might also be good to have an interface to the "normal" cgi-bin POST interface. If they update any files in the database, it is through the web interface (i.e. http://www.astro.uni-koeln.de/cgi-bin/cdmssearch) which all the updates are accessible first. The VAMDC comes later, they have to do some manual updating for that to happen. I've been trying to figure out the POST request (using Live HTTP headers Chrome plugin) but haven't fully figured it out yet. The results are in fixed-width tables with the same format as the JPL molecular line catalog (http://spec.jpl.nasa.gov/ftp/pub/catalog/README) where the format is given as a Fortran fixed width format specifier. Anyway, just some thoughts on this.

**Comment by keflavich** [comment]
:+1: @vilhelmp, this is the best approach for astroquery, at least until we integrate `vamdclib` into astroquery (which I hope we can eventually do).

**Comment by vilhelmp** [comment]
The shortest way I figured out to get the CDMS text results into Astropy Table format is the following:

    from astropy.table import Table
    import astropy.constants as c
    import astropy.units as u
    cdms_colnames = ('FREQ', 'ERR', 'LGINT', 'DR',  'ELO', 'GUP', 'TAG', 'QNFMT',  'QN1',  'QN2',     'SPECIES')
    cdms_colstarts = (0,       13,   24,  35,    37,  47,  50, 57, 61,   72, 89 )
    lines = Table.read('cdms_table_file.tab',
                format='ascii.fixed_width_no_header',
                names=cdms_colnames,
                col_starts=cdms_colstarts,
                 )

and then proceed to parse the units

    lines['FREQ'] = lines['FREQ'] * 1e-3
    lines['FREQ'].unit = u.GHz
    lines['ERR'] = lines['ERR'] * 1e-3
    lines['ERR'].unit = u.GHz
    lines['ELO'].unit = u.cm**-1
    lines['ELO'] = (lines['ELO'].quantity*c.c*c.h/c.k_B).decompose()
    lines['ELO'].unit = u.K
    
    # calculate the E_up (in Kelvin) from the E_low (in Kelvin)
    lines['EUP'] = lines['ELO'] + ((c.h * lines['FREQ'].quantity)/c.k_B).decompose()

**Comment by bsipocz** [comment]
Closing this one as an experimental VAMDC module has beed added in #658. Please feel free to reopen if you think otherwise.
