### ISSUE TITLE
Cleanup code base before new release

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#623]
@keflavich - Doing the pep8 cleanup, I run into a few places with workarounds of old astroquery/astropy issues that have been solved since, commented out (probably obsolete) code, and astropy 0.3 compatibility hacks.

I wonder what you think about cleaning these up before a new release (you can assign me on to this).

**Comment by keflavich** [comment]
:+1: to removing all the cruft

**Comment by bsipocz** [comment]
Closing as this was mostly done in #626.
