### ISSUE TITLE
SDSS documentation examples are incorrect

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#628]
The first example on https://astroquery.readthedocs.org/en/masterclone/astroquery/sdss.html does not work because `crossID` has been removed.

Thanks to Andrea Tramacere for reporting this.

cc @eteq @bsipocz

**Comment by bsipocz** [comment]
I can look at and fix this by next week.

**Comment by bsipocz** [comment]
Can't find which page you're referring  to here, and grepping the pages none of  the examples seem to use the term ``crossID``.

**Comment by keflavich** [comment]
...I admit great confusion about this.  I think there must have been some ancient version of astroquery docs sitting around on google that are now deceased, and that ancient version contained this error.
