### ISSUE TITLE
astroquery.vizier: how to select the server

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astroquery#634]
This is a documentation user guide question. i am using astroquery.vizier 

I would like to change the Vizier server used in my python script to use my local Vizier server at:

`vizier.ast.cam.ac.uk`

i have a few dummy questions: how do I determine what server is being used, the list of server  and how do I change it within a python script.

https://github.com/astropy/astroquery/blob/master/astroquery/vizier/__init__.py

has a list of servers:
```
server = _config.ConfigItem(
        ['vizier.u-strasbg.fr',
         'vizier.nao.ac.jp',
         'vizier.hia.nrc.ca',
         'vizier.ast.cam.ac.uk',
         'vizier.cfa.harvard.edu',
         'www.ukirt.jach.hawaii.edu',
         'vizier.iucaa.ernet.in',
         'vizier.china-vo.org',
         ],
        'Name of the VizieR mirror to use.'
```
thanks

**Comment by keflavich** [comment]
@richardgmcmahon Within a python script, you can look at the `VIZIER_SERVER` variable:
```
>>> from astroquery.vizier import Vizier
>>> Vizier.VIZIER_SERVER
vizier.u-strasbg.fr
```

You can change that interactively in a script.

You can also modify it globally on your system by editing the file `~/.astropy/config/astroquery.cfg` in the `[vizier]` section.

**Comment by richardgmcmahon** [comment]
Thanks,

server = Vizier.VIZIER_SERVER
print('astroquery.vizier server: ', server)
Vizier.VIZIER_SERVER = 'vizier.ast.cam.ac.uk'server = Vizier.VIZIER_SERVER
print('astroquery.vizier server: ', server)

produces:

astroquery.vizier server:  vizier.u-strasbg.fr
astroquery.vizier server:  vizier.ast.cam.ac.uk
