### ISSUE TITLE
Getting warning on all Vizier calls with Python 3.5+, but not 2.7.

### ISSUE THREAD

**Issue by guillochon** [astropy/astroquery#635]
Hi all, getting the following warning when using `get_catalogs` within Python 3.5.1 whenever I try to pull the catalogs from a Vizier source. I was *not* getting this warning when running the same command in Python 2.7.3.

    /usr/local/lib/python3.5/site-packages/astroquery/vizier/core.py:685: UserWarning: VOTABLE parsing 
    raised exception: warnings.warn("VOTABLE parsing raised exception: {0}".format(ex))

Any ideas?

**Comment by keflavich** [comment]
@guillochon could you provide an example of a query that produces these warnings?

**Comment by guillochon** [comment]
This example throws the warning, but any catalog I've tried also produces the warning:

    from astroquery.vizier import Vizier
    result = Vizier.get_catalogs("J/A+A/538/A120/usc")

**Comment by keflavich** [comment]
what version of astropy are you using?

**Comment by guillochon** [comment]
1.1.1

**Comment by keflavich** [comment]
I can't reproduce the issue:
```
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> astropy.__version__
'1.1.1'
>>> from astroquery.vizier import Vizier
>>> result = Vizier.get_catalogs("J/A+A/538/A120/usc")
>>>
```

Which version of astroquery are you using?  dev or release?

**Comment by guillochon** [comment]
Installed from pip, 0.3.0.

**Comment by keflavich** [comment]
OK.  Upgrade to the dev version - we've apparently fixed this since v0.3.0.  We'll make a new release.

**Comment by guillochon** [comment]
I verify that the dev version does not produce this warning.

**Comment by keflavich** [comment]
Great, thanks!

@bsipocz I'll work on release v0.3.1 today - let me know if there's anything you'd like incorporated.

**Comment by bsipocz** [comment]
@keflavich - Sure, go ahead. I don't have anything release blocking.
