### ISSUE TITLE
Querying Simbad is broken

### ISSUE THREAD

**Issue by samverstocken** [astropy/astroquery#639]
I believe the Simbad module is broken. I tried all of the examples on the webpage, I always get the same error:

```python
astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error.  The attempted parsed result is in self.last_parsed_result.
Exception: No table found in VOTABLE file.
```

I'm using what I think is the latest release version (0.3.0) (since I just upgraded with pip). I'm using Enthought Canopy Python 2.7.6 on OS X 10.10.5.

**Comment by keflavich** [comment]
@samverstocken I can't reproduce this issue.  Is it possible that SIMBAD was down at the time, and it works again now?  If not, could you post a complete example of a failure?

**Comment by samverstocken** [comment]
Yes, apparently that was the problem. It's working perfect now!

**Comment by keflavich** [comment]
Great!  Glad it's back.  Sometimes you can try a different mirror if the main one is down, but they rarely have long downtimes.
