### ISSUE TITLE
Version 0.3 is missing from RTD

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#640]
For some reasons the only versions on rtd is 0.1, 0.2 and latest. Would it be possible to set up one for the latest released version as well (0.3 atm, but will be 0.3.1 soon)? Is it a bug or a feature that it needs to be added manually?

cc @keflavich @cdeil

**Comment by keflavich** [comment]
@bsipocz make yourself an RTD account and I'll add you as an admin.  I'll try to figure out why this isn't working too.

**Comment by bsipocz** [comment]
OK, I've registered, username is ``bsipocz``. However I'm not sure I can do anything about it as I don't know anything about rtd inner workings.

**Comment by keflavich** [comment]
I added you, and I added the versions that weren't included.  However, the build status is apparently "failing"....

**Comment by bsipocz** [comment]
It seems only the pdf build was failing, I wiped the build so hopefully it will pass now.

**Comment by bsipocz** [comment]
Version 0.3 is still failing with the pdf, and 0.3.1 weirdly shows ``astroquery v0.3.1.dev3141`` in the top left corner at http://astroquery.readthedocs.org/en/v0.3.1/ instead of just ``0.3.1``, but these are separate and super minor issues, so I'm closing this issue now.
