### ISSUE TITLE
decorator `prepend_docstring_noreturns` only works for non-standard docstrings.

### ISSUE THREAD

**Issue by hamogu** [astropy/astroquery#643]
See #641 where this lead to a longer search for the cause of the sphinx warning.

It turns out that the first line of the docstring has to be empty, i.e.

```
def func():
    '''
    This is a function that does ...

    Returns
    -----------
    stuff : 
'''
```

instead of the usual numpydoc format.

```
def func():
    '''one line summary of function

    Longer text that describes function in detail.

    Returns
    -----------
    stuff : 
'''
```

The reason is that it uses `textwrap.dedent` which strips whitespace _common to all lines_. So, if the first line in the docstring has text but no whichspace, `detend` will not do anything.

**Comment by keflavich** [comment]
Thanks for catching this.  Any ideas for how to work around it? I'm weakly in favor of requiring docstrings like:
```
"""
docstr here
"""
```
and not allowing
```
"""docstr here
"""
```
because I think the latter looks a little uglier in the code, but I don't feel strongly enough about it to enforce it as a standard; I'd rather support both approaches.

**Comment by astrofrog** [comment]
+1 for:

```
docstr here
```

**Comment by hamogu** [comment]
I looked at it for a while and I am now in favor of recommending the first version. Fixing the decorator is fiddly. The best way to do it would be to make the decorator use the relevant function from numpydoc, but I don't think it's worth another dependency for just that in the case of astroquery.

**Comment by bsipocz** [comment]
another :+1: for the first version.

**Comment by hamogu** [comment]
Note that PEP 257 (https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings)
suggests:
```
"""docstr here

for multiline docstrings (which almost all of our docstrings are)
"""
```

**Comment by astrofrog** [comment]
I really don't understand that recommendation - that style really bugs me...

**Comment by keflavich** [comment]
agreed.  I don't follow PEP8+ for everything all the time.  Anyway, I think we're agreed on the solution now.  Anyone want to dig through and find the non-compliant docstrings?  Probably any non-compliant ones also need `..automodapi` added to their doc .rst's

**Comment by hamogu** [comment]
I like it. I write almost all of my code this way (which is how I discovered that it does not work with the generator).

I don't think we need to resolve this here (that's why peopel had a discussion about that PEP), but my main reason is that I don't like that almost empty line (`'''`). It visually breaks between the line with `def func()` and the text that make up the function and it's doc.

**Comment by bsipocz** [comment]
I'm not sure this is againts pep8, as it says: "The summary line may be on the same line as the opening quotes or on the next line."

**Comment by hamogu** [comment]
I think that we should just replace `textwrap.detend` with `inspect.clean_doc` and it will work for both cases. I will try that out later, but don't have time right now, so I'll just put a comment here to make sure I don't forget.

**Comment by keflavich** [comment]
We've solved this by using only:
```python
"""
    docstrings
    formatted
    like this
"""
```
as opposed to 
```python
"""those that look
    like this
"""
```
