### ISSUE TITLE
Add module for SkyView ?

### ISSUE THREAD

**Issue by esoPanda** [astropy/astroquery#647]
Hi,
It'd be great if someone could add a module to query SkyView:
http://skyview.gsfc.nasa.gov/current/cgi/query.pl
There are many databases!

**Comment by keflavich** [comment]
@esoPanda already implemented: https://astroquery.readthedocs.org/en/latest/skyview/skyview.html

**Comment by keflavich** [comment]
@esoPanda did you have a hard time finding this in the documentation?  Is there something we could do to make it more visible?

**Comment by esoPanda** [comment]
@keflavich  Oh I was looking at an old version (v0.1x), sorry!
