### ISSUE TITLE
Input validation for splatalogue 

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroquery#651]
Edit: The documentation issue has been resolved from here, but there is still no input validation.

=======
Original:

Options such as:

```
        line_strengths : list
            CDMS/JPL Intensity : ls1
            Sij : ls3
            Aij : ls4
            Lovas/AST : ls5
        energy_levels : list
            E_lower (cm^-1) : el1
            E_lower (K) : el2
            E_upper (cm^-1) : el3
            E_upper (K) : el4
```

aren't rendering well in Sphinx - I think they should be:

```
        line_strengths : list
            * CDMS/JPL Intensity : ls1
            * Sij : ls3
            * Aij : ls4
            * Lovas/AST : ls5
        energy_levels : list
            * E_lower (cm^-1) : el1
            * E_lower (K) : el2
            * E_upper (cm^-1) : el3
            * E_upper (K) : el4
```

instead. There are other similar options

**Comment by astrofrog** [comment]
Also, we should add input validation for these types of options

**Comment by bsipocz** [comment]
@astrofrog - Any idea how should we build the validator? Should it work only for splatalogue, or for other modules as well?

**Comment by astrofrog** [comment]
@bsipocz - I'm not sure what the best approach would be, but I'd ask @keflavich to see what he thinks

**Comment by keflavich** [comment]
Input validation for splatalogue would be great, but they frequently refactor their UI without announcing it and that has taken all the available dev time for that module.  It's still useful, but I'm closing this as "won't fix".  If someone else wants to come along and put in the effort, they're welcome - this is not a bad idea, it's just not where I'm putting my time, and I prefer to close the issue.
