### ISSUE TITLE
404 Client Error: Not Found for url: https://almascience.nao.ac.jp/

### ISSUE THREAD

**Issue by archer81** [astropy/astroquery#660]
Hi!
Thanks for develping a good python package.

I tried to use astroquery for ALMA ('Alma.query_region(c, radius=r)') but I faced a connection-related problem(?). 
Here is a error. 
"HTTPError: 404 Client Error: Not Found for url: https://almascience.nao.ac.jp/aq"

Could you please check it?

**Comment by keflavich** [comment]
This is a temporary issue, see https://almascience.nao.ac.jp:
![image](https://cloud.githubusercontent.com/assets/143715/13837624/626ce880-ec0d-11e5-8e01-f5a8ec75785e.png)

**Comment by bsipocz** [comment]
The site is accessible again, thus closing this issue.
