### ISSUE TITLE
find_catalogs is not working

### ISSUE THREAD

**Issue by mwcraig** [astropy/astroquery#661]
I've been trying to use `find_catalogs` the past couple of days and keep hitting an error when I try one of the examples from the docs:

``` python
catalog_list = Vizier.find_catalogs('Kang W51')
print(catalog_list)
```

When I run it I get:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-144-a9f5e9b450bd> in <module>()
      1 catalog_list = Vizier.find_catalogs('Kang W51')
----> 2 print(catalog_list)

/Users/mcraig/anaconda/envs/gw/lib/python2.7/site-packages/astropy/io/votable/tree.pyc in __repr__(self)
   3017         buff = io.StringIO()
   3018         XMLWriter(buff).element(
-> 3019             self._element_name,
   3020             attrib=w.object_attrs(self, self._attr_list))
   3021         return buff.getvalue().strip()

AttributeError: 'Resource' object has no attribute '_element_name'
```

I'm using  astroquery 0.3.1 with astropy 1.1.1 on a mac, anaconda, python 2.7.

**Comment by keflavich** [comment]
I can confirm the error.  It is a weird one and almost certainly has to do with something strange being returned from vizier.   Remote tests pass, though, so we clearly need a new test.

**Comment by cdeil** [comment]
I just now ran into the same error.

Related: #610

**Comment by bsipocz** [comment]
I don't see this error at the moment, but nevertheless the example is not working, I get back an empty catalogue list.  

We definitely need to come up with a way to run the doctests in the rst files when running the remote tests, #633.

**Comment by lupinix** [comment]
Any news on this? Still have the issue here (astropy 1.2.1, astroquery 0.3.2).

**Comment by keflavich** [comment]
This is an astropy bug that may be fixed in https://github.com/astropy/astropy/pull/4546.

**Comment by bsipocz** [comment]
This seems to be working for me with astropy dev. 
@mwcraig - could you please confirm and then close the issue?

**Comment by mwcraig** [comment]
@bsipocz -- yes, it works with master, closing.
