### ISSUE TITLE
ERROR:  No object found

### ISSUE THREAD

**Issue by archer81** [astropy/astroquery#662]
Hi!

Thanks for sharing astroquery.

With for loop, I tried to use astroquery for  some objects using  "result_ned  = Ned.query_region(c, radius=r,verbose=False)" but I met a error if there is no object founded.
"RemoteServiceError: The remote service returned the following error message.
ERROR:  No object found."

I think this command is better to return no data for the case of no object founded better than the error.

How about this?

**Comment by keflavich** [comment]
@archer81 actually, we strongly prefer returning an error in this case.  An "empty" table is harder to deal with than an exception.  To catch exceptions like this, you should define a filter function like this:

```
def try_to_get_ned_result(...):
     try:
        Ned.query_region(...)
    except RemoteServiceError:
        return None
```
then you can loop using this function.

**Comment by bsipocz** [comment]
Closing this as @keflavich provided a workaround and an explanation why we do what we do. 

@archer81 - please feel free to reopen if you are unhappy with the solution above and have a good argument why we should return empty tables instead.
