### ISSUE TITLE
Incompatibility with new version of Python 3.5

### ISSUE THREAD

**Issue by ViviCoder** [astropy/astroquery#691]
For some reason, the module distutils.config of Python 3.5 has been modified to use RawConfigParser instead of ConfigParser (https://hg.python.org/cpython/rev/eae59b6bf133).
As a consequence, astroquery fails to build with this version (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824170).

I suggest you stop using the config parser included in distutils.config to use directly the ConfigParser module.

**Comment by bsipocz** [comment]
@ViviCoder - Thanks for the heads up. It's an upstream issue for ``astroquery``, and I've opened an issue in ``package-template``, as most of our infrastructure is taken from there.
