### ISSUE TITLE
SDSS.query_region does not work

### ISSUE THREAD

**Issue by dalya** [astropy/astroquery#694]
Hello,
I tried to do a query region like this:
```
from astroquery.sdss import SDSS
from astropy import coordinates as coords
c = coords.SkyCoord(10.625, 41.2, frame='icrs', unit='deg')
result = SDSS.query_region(c)
```

I get the following error:

> ValueError                                Traceback (most recent call last)
> <ipython-input-7-7154745e1f76> in <module>()
> ----> 1 result = SDSS.query_region(c)
> 
> /Users/dalyabaron/.virtualenvs/astro/lib/python2.7/site-packages/astroquery/utils/class_or_instance.pyc in f(*args, **kwds)
>      23         def f(*args, **kwds):
>      24             if obj is not None:
> ---> 25                 return self.fn(obj, *args, **kwds)
>      26             else:
>      27                 return self.fn(cls, *args, **kwds)
> 
> /Users/dalyabaron/.virtualenvs/astro/lib/python2.7/site-packages/astroquery/utils/process_asyncs.pyc in newmethod(self, *args, **kwargs)
>      27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
>      28                 return response
> ---> 29             result = self._parse_result(response, verbose=verbose)
>      30             self.table = result
>      31             return result
> 
> /Users/dalyabaron/.virtualenvs/astro/lib/python2.7/site-packages/astroquery/sdss/core.pyc in _parse_result(self, response, verbose)
>     833                                           names=True, dtype=None,
>     834                                           delimiter=',', skip_header=1,
> --> 835                                           comments='#'))
>     836 
>     837         if len(arr) == 0:
> 
> /Users/dalyabaron/.virtualenvs/astro/lib/python2.7/site-packages/numpy/lib/npyio.pyc in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows)
>    1767             # Raise an exception ?
>    1768             if invalid_raise:
> -> 1769                 raise ValueError(errmsg)
>    1770             # Issue a warning ?
>    1771             else:
> 
> ValueError: Some errors were detected !
>     Line #60 (got 4 columns instead of 1)
>     Line #122 (got 6 columns instead of 1)
>     Line #123 (got 7 columns instead of 1)
>     Line #124 (got 4 columns instead of 1)
>     Line #125 (got 4 columns instead of 1)
>     Line #126 (got 4 columns instead of 1)
>     Line #128 (got 2 columns instead of 1)

I was looking at the URLs that are defined in the class and I suspect that some of them are broken (on the SDSS side). The URLs I have:
`SDSS.IMAGING_URL_SUFFIX`

> u'{base}/dr{dr}/boss/photoObj/frames/{rerun}/{run}/{camcol}/frame-{band}-{run:06d}-{camcol}-{field:04d}.fits.bz2'

`SDSS.QUERY_URL_SUFFIX_DR_NEW`

> u'/dr{dr}/en/tools/search/x_sql.aspx'

`SDSS.QUERY_URL_SUFFIX_DR_OLD`

> u'/dr{dr}/en/tools/search/sql.asp'

`SDSS.SPECTRA_URL_SUFFIX`

> u'{base}/dr{dr}/{instrument}/spectro/redux/{run2d}/spectra/{plate:04d}/spec-{plate:04d}-{mjd}-{fiber:04d}.fits'

`SDSS.XID_URL_SUFFIX`

> u'/dr{dr}/en/tools/crossid/x_crossid.aspx'

Does this command work for any of you? If it is, are you using the same URLs I'm using?

Thanks! :)

**Comment by bsipocz** [comment]
@dalya - The sdss remote api recently changed. We fixed this in astroquery, but there hasn't been a new release yet. You can install the master version where it is fixed, or can wait for the new release that we plan to do in the near future.

**Comment by dalya** [comment]
@bsipocz - thank you very much! :)
