### ISSUE TITLE
SDSS imaging query fails

### ISSUE THREAD

**Issue by zpace** [astropy/astroquery#699]
I'm having trouble constructing valid SDSS `get_images` queries.

For example, I've tried to run a test case to download the FITS images for a galaxy at (RA, DEC) of (110.88851, 41.434907). The documentation suggests that I should be able to do this directly with a SkyCoord object, as follows.

`
SDSS.get_images(coordinates=coords.SkyCoord('110.88851d +41.434907d', frame='icrs'), band='r', radius=20.*u.arcsec)
`

This yields the following error:

`/home/zpace/anaconda/lib/python2.7/site-packages/astroquery/sdss/core.pyc in get_images(self, coordinates, radius, matches, run, rerun, camcol, field, band, timeout, cache, get_query_payload, data_release)
    739             coordinates=coordinates, radius=radius, matches=matches, run=run,
    740             rerun=rerun, data_release=data_release, camcol=camcol, field=field,
--> 741             band=band, timeout=timeout, get_query_payload=get_query_payload)
    742 
    743         if readable_objs is not None:

/home/zpace/anaconda/lib/python2.7/site-packages/astroquery/sdss/core.pyc in get_images_async(self, coordinates, radius, matches, run, rerun, camcol, field, band, timeout, get_query_payload, cache, data_release)
    700             r = self._request("GET", url, params=request_payload,
    701                               timeout=timeout, cache=cache)
--> 702             matches = self._parse_result(r)
    703             if matches is None:
    704                 warnings.warn("Query returned no results.", NoResultsWarning)

/home/zpace/anaconda/lib/python2.7/site-packages/astroquery/sdss/core.pyc in _parse_result(self, response, verbose)
    833                                           names=True, dtype=None,
    834                                           delimiter=',', skip_header=1,
--> 835                                           comments='#'))
    836 
    837         if len(arr) == 0:

/home/zpace/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.pyc in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows)
   1767             # Raise an exception ?
   1768             if invalid_raise:
-> 1769                 raise ValueError(errmsg)
   1770             # Issue a warning ?
   1771             else:

ValueError: Some errors were detected !
    Line #60 (got 4 columns instead of 1)
    Line #122 (got 6 columns instead of 1)
    Line #123 (got 7 columns instead of 1)
    Line #124 (got 4 columns instead of 1)
    Line #125 (got 4 columns instead of 1)
    Line #126 (got 4 columns instead of 1)
    Line #128 (got 2 columns instead of 1)`

This error also occurs when I try to retrieve the image using the `run`, `rerun`, `camcol`, and `field` arguments.

My version is 0.3.1

**Comment by bsipocz** [comment]
@zpace - SDSS changed its API for DR12 recently, and it is incompatible with the previous one. We have fixed it in astroquery. You can either install the current development version, or wait for the next release that we plan to make in the near future.

**Comment by zpace** [comment]
Great, thanks!
