### ISSUE TITLE
Remote issues for 0.3.2

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#704]
These are uncorrected issues in 0.3.2.  Maybe we can fix these and make another release soon.

astroquery/alma/utils.py:268: ImportError --> https://bpaste.net/show/ace95c439590
astroquery/lcogt/core.py:340: TableParseError --> https://bpaste.net/show/b46fe9064c32
astroquery/lcogt/core.py:340: TableParseError --> https://bpaste.net/show/331077956ba3
astroquery/lcogt/core.py:340: TableParseError --> https://bpaste.net/show/a2a206849bc5
//anaconda/lib/python2.7/site-packages/requests/models.py:844: HTTPError --> https://bpaste.net/show/0d6e76f7ec54

**Comment by keflavich** [comment]
More remote issues:

astroquery/alma/tests/test_alma_remote.py:76: Failed --> https://bpaste.net/show/be078fb3047f
astroquery/alma/tests/test_alma_remote.py:88: AssertionError --> https://bpaste.net/show/2cd5c03bb4ed
astroquery/alma/tests/test_alma_remote.py:112: AssertionError --> https://bpaste.net/show/ff6ca300ac8a
astroquery/alma/tests/test_alma_remote.py:143: AssertionError --> https://bpaste.net/show/3a59711ee799
/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/requests/models.py:851: HTTPError --> https://bpaste.net/show/df978f708bcc
astroquery/alma/utils.py:422: IndexError --> https://bpaste.net/show/0009df3205a1
astroquery/esasky/core.py:787: TableParseError --> https://bpaste.net/show/35243d40d952
astroquery/esasky/core.py:787: TableParseError --> https://bpaste.net/show/f7f2fb586bf4
astroquery/esasky/core.py:787: TableParseError --> https://bpaste.net/show/91d197c0e289
astroquery/eso/tests/test_eso_remote.py:120: AssertionError --> https://bpaste.net/show/195174b103b1
astroquery/nrao/tests/test_nrao_remote.py:23: AssertionError --> https://bpaste.net/show/35369ba664c4
astroquery/nrao/core.py:387: ValueError --> https://bpaste.net/show/4ecc7d50be32
astroquery/nrao/core.py:426: TableParseError --> https://bpaste.net/show/d2df4d30e949
astroquery/utils/commons.py:442: TimeoutError --> https://bpaste.net/show/e0977117000e
astroquery/utils/commons.py:442: TimeoutError --> https://bpaste.net/show/73787656ce14
astroquery/utils/commons.py:442: TimeoutError --> https://bpaste.net/show/737b13c10a23
astroquery/utils/commons.py:442: TimeoutError --> https://bpaste.net/show/2dd22b653628
astroquery/utils/commons.py:442: TimeoutError --> https://bpaste.net/show/fdfb6516124b
astroquery/utils/commons.py:442: TimeoutError --> https://bpaste.net/show/52b42cfc3a4b
astroquery/vamdc/load_species_table.py:43: UnicodeEncodeError --> https://bpaste.net/show/ddfec55733f4
/Users/adam/anaconda/envs/astropy27/lib/python2.7/copy_reg.py:70: TypeError --> https://bpaste.net/show/4ec16bab024f

**Comment by bsipocz** [comment]
@keflavich - somehow the bpaste links don't work for me, is that normal?

**Comment by keflavich** [comment]
I wonder if they've timed out?  I don't really know how bpaste works.

**Comment by MSeifert04** [comment]
I haven't used bpaste yet, but just to mention it: Markdown also supports the HTML `details`-tag which could be a good alternative to externally saving longish code snippets or test-reports:

<details>
```
<details>
:-)
</details>
```
</details>

**Comment by bsipocz** [comment]
Thanks @MSeifert04, this is very handy.

**Comment by bsipocz** [comment]
I'm closing this and post updates of the failures in #724. There are quite a few using the latest dev version.
