### ISSUE TITLE
Cleanup the intro page on pypi

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#706]
I'm not yet sure which file gets uploaded to the main page, but the page is in need of a formatting.
https://pypi.python.org/pypi/astroquery/0.3.2

**Comment by astrofrog** [comment]
What gets put there is what is in ``long_description``

**Comment by cdeil** [comment]
I just now noticed the same thing.
+10 to fix this.
Having a short description and a working link to the Github and docs page is the most important ... IMO no need to have all that other info on PyPI.

**Comment by bsipocz** [comment]
The rendering seems to be working again with the crispy new 0.3.4, I'll leave it open though to let @keflavich decide whether he wants any cut backs on the readme.

**Comment by bsipocz** [comment]
This got into the release notes, so closing now.
