### ISSUE TITLE
Windows 10 test failures

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astroquery#713]
On Windows some tests failed with `python setup.py test`: I've placed the log in a gist: https://gist.github.com/MSeifert04/b2aef84e761c532bc8b747b01d13f392

**Comment by bsipocz** [comment]
We don't have appveyor CI running for astroquery, thus it's expected that there are various windows failures. 

Actually I'm not sure whether this is deliberate or not, @keflavich?

 Anyway any help ironing these out is very welcome.

**Comment by MSeifert04** [comment]
@bsipocz In https://github.com/astropy/astroquery/pull/709#issuecomment-225684630 @keflavich asked if the appveyor tests should be enabled.

Most of these test failures are because ``\\`` (windows) is used instead of ``/`` (linux) as folder-seperator. Maybe it's just a matter of using ``os.path.join`` or ``pathlib`` (python 3.4+) to create paths.

Unfortunatly I don't have much time going after them just now.

**Comment by bsipocz** [comment]
@MSeifert04 - Ahh, OK, I hasn't follow that issue. In this case I'll put this on my todo.

**Comment by bsipocz** [comment]
@MSeifert04 - Could you please check whether any of these are still there?

**Comment by MSeifert04** [comment]
I'm running the remote-data tests now. I'll upload the encountered failures :smile:

**Comment by MSeifert04** [comment]
Unfortunatly there were some failures.

https://gist.github.com/MSeifert04/7322bafb40ed58be449a33ba9acf0560

There are some failures even without remote (Simbad) but most of the remote tests seem real or due to ConnectionError.

**Comment by MSeifert04** [comment]
@bsipocz (or someone else): Do the remote data tests work on other platforms? If not could you upload an Error-log here so I can focus on the windows-specific failures?

**Comment by bsipocz** [comment]
@MSeifert04 - There are quite a few failures, the log is here: https://gist.github.com/bsipocz/f4951ae7d5060611967db312ed1745d3 and in #724

**Comment by MSeifert04** [comment]
The difference (probably windows specific failures):
- `alma_remote`: last test
- `sdss_remote`: lots of tests
- `simbad`: not remote, not appveyor, only local encountered failures

I'll have a look at these.

**Comment by MSeifert04** [comment]
sdss_remote doesn't fail on python3 except for two overflow errors: https://gist.github.com/MSeifert04/ab626b64f2de196b3852d2c7765b82ac

Not sure if it's possible to fix them on windows.

**Comment by bsipocz** [comment]
Currently there 6 alma remote failures, everything else passes for me. Could you check whether you see any windows specific issues other than those? Would be nice to close this issue.

**Comment by MSeifert04** [comment]
I will run the tests and report back.

**Comment by MSeifert04** [comment]
There are two weird failures apart from the known alma remote tests:

```
______________________________ test_xmatch_query ______________________________

xmatch = <astroquery.xmatch.core.XMatchClass object at 0x0000029C512D4D68>

    @remote_data
    def test_xmatch_query(xmatch):
        with open(os.path.join(DATA_DIR, 'posList.csv'), 'r') as pos_list:
            table = xmatch.query(
                cat1=pos_list, cat2='vizier:II/246/out', max_distance=5 * arcsec,
                colRA1='ra', colDec1='dec')
        assert isinstance(table, Table)
        assert table.colnames == [
            'angDist', 'ra', 'dec', 'my_id', '2MASS', 'RAJ2000', 'DEJ2000',
            'errHalfMaj', 'errHalfMin', 'errPosAng', 'Jmag', 'Hmag', 'Kmag',
            'e_Jmag', 'e_Hmag', 'e_Kmag', 'Qfl', 'Rfl', 'X', 'MeasureJD']
        assert len(table) == 11

>       http_test_table = http_test()

astroquery\xmatch\tests\test_xmatch_remote.py:54:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
astroquery\xmatch\tests\test_xmatch_remote.py:81: in http_test
    table = ascii.read(outfile, format='csv')
c:\users\admin\git\astropy\astropy\io\ascii\ui.py:328: in read
    dat = fast_reader.read(table)
c:\users\admin\git\astropy\astropy\io\ascii\fastbasic.py:116: in read
    return Table(data, names=list(self.engine.get_names()), meta=meta)
c:\users\admin\git\astropy\astropy\table\table.py:377: in __init__
    init_func(data, names, dtype, n_cols, copy)
c:\users\admin\git\astropy\astropy\table\table.py:641: in _init_from_list
    self._init_from_cols(cols)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Table length=0>
<No columns>, cols = []

    def _init_from_cols(self, cols):
        """Initialize table from a list of Column or mixin objects"""

        lengths = set(len(col) for col in cols)
        if len(lengths) != 1:
            raise ValueError('Inconsistent data column lengths: {0}'
>                            .format(lengths))
E           ValueError: Inconsistent data column lengths: set()

c:\users\admin\git\astropy\astropy\table\table.py:706: ValueError
---------------------------- Captured stderr call -----------------------------
Der Befehl "curl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
_______________________ test_xmatch_query_astropy_table _______________________

xmatch = <astroquery.xmatch.core.XMatchClass object at 0x0000029C512BF9B0>

    @remote_data
    def test_xmatch_query_astropy_table(xmatch):
        datapath = os.path.join(DATA_DIR, 'posList.csv')
        input_table = Table.read(datapath, format='ascii.csv')
        table = xmatch.query(
            cat1=input_table, cat2='vizier:II/246/out', max_distance=5 * arcsec,
            colRA1='ra', colDec1='dec')
        assert isinstance(table, Table)
        assert table.colnames == [
            'angDist', 'ra', 'dec', 'my_id', '2MASS', 'RAJ2000', 'DEJ2000',
            'errHalfMaj', 'errHalfMin', 'errPosAng', 'Jmag', 'Hmag', 'Kmag',
            'e_Jmag', 'e_Hmag', 'e_Kmag', 'Qfl', 'Rfl', 'X', 'MeasureJD']
        assert len(table) == 11

>       http_test_table = http_test()

astroquery\xmatch\tests\test_xmatch_remote.py:71:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
astroquery\xmatch\tests\test_xmatch_remote.py:81: in http_test
    table = ascii.read(outfile, format='csv')
c:\users\admin\git\astropy\astropy\io\ascii\ui.py:328: in read
    dat = fast_reader.read(table)
c:\users\admin\git\astropy\astropy\io\ascii\fastbasic.py:116: in read
    return Table(data, names=list(self.engine.get_names()), meta=meta)
c:\users\admin\git\astropy\astropy\table\table.py:377: in __init__
    init_func(data, names, dtype, n_cols, copy)
c:\users\admin\git\astropy\astropy\table\table.py:641: in _init_from_list
    self._init_from_cols(cols)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Table length=0>
<No columns>, cols = []

    def _init_from_cols(self, cols):
        """Initialize table from a list of Column or mixin objects"""

        lengths = set(len(col) for col in cols)
        if len(lengths) != 1:
            raise ValueError('Inconsistent data column lengths: {0}'
>                            .format(lengths))
E           ValueError: Inconsistent data column lengths: set()

c:\users\admin\git\astropy\astropy\table\table.py:706: ValueError
---------------------------- Captured stderr call -----------------------------
Der Befehl "curl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

**Comment by bsipocz** [comment]
I wonder whether @keflavich saw any similar failure when fixing xmatch recently?

**Comment by bsipocz** [comment]
@MSeifert04 - What about changing the ``os.path.join()``s to ``url_helpers.join()``? That did the trick for some other modules?

**Comment by MSeifert04** [comment]
Oh, just realized that the problem could be simply that I don't have `curl` - that's what the `stderr` (german locale, sorry!) message means.

**Comment by MSeifert04** [comment]
Yeah, installing `curl` fixed it. 😅

**Comment by bsipocz** [comment]
Sounds great, in that case I'm closing this and declare astroquery windows compatible.

**Comment by MSeifert04** [comment]
Maybe `curl` could be included in the dependencies?

**Comment by bsipocz** [comment]
Is there maybe a windows equivalent that is installed by default? Otherwise, yes, it can be added to the docs.

**Comment by MSeifert04** [comment]
Not sure but at least curl is avaiable via [conda](https://anaconda.org/anaconda/curl).

**Comment by bsipocz** [comment]
That's OK then, PR's coming soon.
