### ISSUE TITLE
ALMA: Known upstream issue: UnicodeDecodeError

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#718]
For `astroquery.Alma` queries, there is a bug in the returned VOTables where non-utf-8 characters are included in the votables, which renders them unprintable.  This has been reported and acknowledged by the ALMA archive devs.

The error will look something like this:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte`

The workaround is to avoid trying to print the 'band' column of the votable.  The data are still correctly parsed, they just can't be printed, and the band information is useless.

**Comment by keflavich** [comment]
Example workaround:
```
rslt = Alma.query(...)
colnames = rslt.colnames
colnames.remove('Band')
rslt[colnames]
```

**Comment by pllim** [comment]
Is astropy/astropy#6836 a different manifestation of this scenario?

**Comment by keflavich** [comment]
It might be, but it looks like that error actually has a *valid* utf-8 character, while this one has an *invalid* character?

**Comment by pllim** [comment]
OK maybe not. Just want to double check. Thanks!

**Comment by pllim** [comment]
My hunch so far is that the ALMA table violates the VO standards and should be fixed over at ALMA's side, but I am open to further discussions.

**Comment by keflavich** [comment]
This has been fixed upstream.
