### ISSUE TITLE
Astroquery html5lib requirement breaks spyder

### ISSUE THREAD

**Issue by ivvv** [astropy/astroquery#722]
Just for information. I just installed astroquery from git clone (0.3.3.dev3320) and suddenly the spyder development environment stopped working, with an error coming from html5lib.

html5lim >= 0.999 is a requirement for astroquery and apparently html5lib 1.0b10-py3.5is not good.

**Comment by keflavich** [comment]
OK, someone else reported something similar.  I don't understand the issue, though.  Maybe we should change the html5lib version requirement?

**Comment by keflavich** [comment]
I'm going to close this as it was likely tied to specific versions of each of these packages that may no longer exist.  Please open a new issue if this recurs.
