### ISSUE TITLE
SDSS DR12 query returns wrong url: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by banados** [astropy/astroquery#739]
This problem happens when I tried to get a spectrum with the DR12 Plate MJD FiberID parameters, it does not crash if I used the DR7 parameters.

This is easier to explain with an example:

```
from astroquery.sdss import SDSS
s = SDSS.get_spectra(plate=7167, mjd=56604, fiberID=182) 
```

returns `HTTPError: HTTP Error 404: Not Found`

This is because it is querying the wrong url:

```
s2 = SDSS.get_spectra_async(plate=7167, mjd=56604, fiberID=182)
[Downloaded object from URL http://data.sdss3.org/sas/dr12/boss/spectro/redux/b'v5_7_0'/spectra/7167/spec-7167-56604-0182.fits with ID 5558563336]
```

The problem is with the **b'v5_7_0'** part it should be just **v5_7_0** without the ' '

And the correct URL that takes you to download the spectrum is 

```
http://data.sdss3.org/sas/dr12/boss/spectro/redux/v5_7_0/spectra/7167/spec-7167-56604-0182.fits
```

I'm sure the problem is in this [part](https://github.com/astropy/astroquery/blob/master/astroquery/sdss/core.py#L582), especifically in the {run2d} argument.

This should be easy to fix but I could not find the root of the problem in the code

**Comment by MSeifert04** [comment]
Thank you for the report and the analysis. :+1: 

Your suspicion is correct about `run2d`. I'm working on a fix.

**Comment by banados** [comment]
Thanks @MSeifert04 That solves that particular problem. I updated my version with your updates while waiting for the PR to be merged.

Now I found another problem at least for one specific object but it might occur on more:

```
s = SDSS.get_spectra_async(plate=5177, mjd=56245, fiberID=114)

ValueError: Some errors were detected !
    Line #60 (got 4 columns instead of 1)
    Line #123 (got 2 columns instead of 1)
    Line #124 (got 2 columns instead of 1)
    Line #129 (got 4 columns instead of 1)
    Line #130 (got 2 columns instead of 1)
    Line #131 (got 2 columns instead of 1)
    Line #132 (got 2 columns instead of 1)
    Line #134 (got 4 columns instead of 1)
    Line #135 (got 2 columns instead of 1)
    Line #137 (got 2 columns instead of 1)
```

The problem is this time in [here](https://github.com/astropy/astroquery/blob/master/astroquery/sdss/core.py#L840)

The `io.BytesIO(response.content)` returns a web page with an error that cannot be read by `np.genfromtxt` nor taken care by the `if` above it.

However, I don't think there should be any error raised for this particular object, as its spectrum does exist: 

http://skyserver.sdss.org/dr12/en/tools/explore/summary.aspx?plate=5177&mjd=56245&fiber=114

Let me know if I should open a new issue for this problem/object

**Comment by MSeifert04** [comment]
@banados I think you should open another issue, because I can't reproduce it right now. Could you include your astropy/astroquery/numpy/python version and the exact code which produces the error?

**Comment by banados** [comment]
Done #743
