### ISSUE TITLE
AppVeyor tests fail

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astroquery#741]
The tests with AppVeyor fail because of:

> error: The 'test' command requires the astropy package to be installed and importable.
Command exited with code 1

These failures started somewhere between 15 days ago (24.7.) and 22 days ago (17.7.) see [AppVeyor history](https://ci.appveyor.com/project/Astropy/astroquery/history)

cc @bsipocz @astrofrog

**Comment by bsipocz** [comment]
Thanks @MSeifert04, I've seen these and hoped to be able to fix them but this month in travel season for me and thus hasn't yet found the time.

**Comment by MSeifert04** [comment]
Could it have something to do with https://github.com/astropy/ci-helpers/pull/128? That one was merged 17 days ago and seems like a potential candidate.
