### ISSUE TITLE
Build failure: qt4?

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#748]
The latest builds fail with this after I merged the latest (green) PRs:

https://travis-ci.org/astropy/astroquery/jobs/160595430

I suspect this is something temporary related to conda?

**Comment by MSeifert04** [comment]
Yes, probably related to the PyQT 5.6 release on conda (yesterday).

**Comment by MSeifert04** [comment]
Just to link it here as well: The underlying issue is some patch with matplotlib rc-something, also reported here: https://github.com/ContinuumIO/anaconda-issues/issues/1068.
