### ISSUE TITLE
Add 'cache' info to docstrings

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#752]
There are a lot of functions with the `cache` keyword but no documentation on what it does.  Documentation should be added to all of the docstrings with a link to a page describing how to remove the cache (e.g., http://docs.astropy.org/en/stable/api/astropy.utils.data.clear_download_cache.html) and how to remove a single file from the cache.

**Comment by janga1997** [comment]
@keflavich I suppose this issue is still open and not being tackled by anybody?

**Comment by keflavich** [comment]
That's right.  Some of the modules may have had their docstrings updated, but it hasn't been addressed systematically

**Comment by shreyasbapat** [comment]
Is it still open for contribution?

**Comment by shreyasbapat** [comment]
In some places something like this is written : 
`cache : bool
            Cache the query?`
Is it fine?

**Comment by keflavich** [comment]
yes.  Do you have any concerns about that text?

**Comment by shreyasbapat** [comment]
No! I got confused due to that question mark! No issues, I will create a PR soon! :)

**Comment by vaishnav97** [comment]
Is this open?

**Comment by swati9star** [comment]
Is this issue still open?

**Comment by bsipocz** [comment]
`cache` has been mostly added adequated to the documentation, so I'm closing this for now.
