### ISSUE TITLE
Limit cache size?

### ISSUE THREAD

**Issue by timothydmorton** [astropy/astroquery#759]
Related to #752, I have been running lots of individual queries, and didn't realize that the results were automatically being cached.  As a result, I cluttered up my home directory with ~10s of Gb of astroquery cache.  I assume I can set `cache=False` to prevent this in the future, but it might be a good idea to automatically limit the size of the cache so that beyond a certain size, older queries get removed?

**Comment by keflavich** [comment]
Good idea.  For timing out, there is this PR: https://github.com/astropy/astroquery/pull/442 which just needs to be finished.

As for limiting the cache size, I think this is a good idea for a user configuration item.   Could you raise that issue on astropy-core?

**Comment by kakirastern** [comment]
Hi, is it okay for me to work on this issue related to astropy/astropy#5368?

**Comment by kakirastern** [comment]
@keflavich So would it be a good idea to enable both a cache limit by default, as well as to allow customization by the user through configuration?

**Comment by keflavich** [comment]
Yes

**Comment by kakirastern** [comment]
Thanks, will start work on this soon...

**Comment by bsipocz** [comment]
@ceb8 - could you comment on this? Does the new system address this, or it's more like an upstream astropy issue?

**Comment by ceb8** [comment]
@bsipocz  The new system does not address this. I think ideally it would be implemented at the astropy level.

**Comment by bsipocz** [comment]
OK. I'm closing this then in favour of https://github.com/astropy/astropy/issues/5368
