### ISSUE TITLE
Selected columns for table returned by function Irsa.query_region

### ISSUE THREAD

**Issue by RussLaher** [astropy/astroquery#766]
It would save on the amount of data transferred if the function Irsa.query_region had controls to select a subset of the available columns in the catalog.

**Comment by AyushYadav** [comment]
@RussLaher @bsipocz which columns would you specifically need to be selected if a patch needed to be completed for this?

**Comment by keflavich** [comment]
The user needs to be able to specify which columns they want.  The important thing is that we make the original query select which columns to transfer, otherwise there is no savings.

**Comment by AyushYadav** [comment]
@keflavich Agreed. The select needs to come on the API side from where the data is to be fetched. I haven't had much experience with IRSA API and hence need to look if `SELECT` will be possible from that end. Let me search it and if possible I'll update.

**Comment by dkagrawal** [comment]
@keflavich @bsipocz Should me make it something like `Simbad` api where the user can add & remove VOTable fields? What about adding an `votable_fields_dict.json` file to get info about every column just like in `Simbad`?

**Comment by dkagrawal** [comment]
@keflavich @bsipocz Should me make it something like `Simbad` queries where the user can add & remove VOTable fields? What about adding an `votable_fields_dict.json` file to get info about every column just like in `Simbad`?

**Comment by dkagrawal** [comment]
@keflavich @bsipocz Should me make it something like `Simbad` api where the user can add & remove VOTable fields? What about adding an `votable_fields_dict.json` file to get info about every column of the VOTable similar to Simbad?

**Comment by bsipocz** [comment]
@dkagrawal - I'm not sure that's the way to go. IRSA is a very different beast compared to SIMBAD, and also a moving target in terms of available catalogs, so I would rather not keep a local snapshot of available column names. Let's see what @AyushYadav finds out about their API.

**Comment by jradavenport** [comment]
A [brief look](http://irsa.ipac.caltech.edu/applications/Gator/GatorAid/irsa/dd.html) indicates there's at least the "long form" output, that includes *all* columns, rather than the short default number, but I'm not sure if this translates to the same API that `astroquery` is using...

Is there a way to get all columns for Irsa queries?

**Comment by jgagneastro** [comment]
I just had the same issue, and the only thing I could figure out was to modify the core.py file and add a "selcols" keyword. This can be done through the following lines in the core.py file of "astroquery":

(...)

def query_region(self, coordinates=None, catalog=None, spatial='Cone',
                     radius=10 * u.arcsec, width=None, polygon=None,
                     get_query_payload=False, verbose=False,selcols=None):

(...)

response = self.query_region_async(coordinates, catalog=catalog,
                                           spatial=spatial, radius=radius,
                                           width=width, polygon=polygon,
                                           get_query_payload=get_query_payload,selcols=selcols)

(...)

def query_region_async(self, coordinates=None, catalog=None,
                           spatial='Cone', radius=10 * u.arcsec, width=None,
                           polygon=None, get_query_payload=False,
                           selcols=None):

(...)

request_payload = self._args_to_payload(catalog,selcols=selcols)

(...)

    def _args_to_payload(self, catalog, selcols=None):
        """
        Sets the common parameters for all cgi -queries

        Parameters
        ----------
        catalog : str
            The name of the catalog to query.

        Returns
        -------
        request_payload : dict
        """
        if selcols is None:
            selcols=''
        request_payload = dict(catalog=catalog,
                               outfmt=3,
                               outrows=Irsa.ROW_LIMIT,
                               selcols=selcols)
        return request_payload

That's it ! After that you can just use the "selcols" keyword when using query_region; e.g., selcols='ra,dec,mjd,w1mpro'. I've put the modified core.py file here:
https://www.dropbox.com/s/0f88iwczpy25buw/astroquery_irsa_core_backup.py?dl=0

**Comment by keflavich** [comment]
@jgagneastro would you consider submitting that as a pull reqest?

**Comment by jgagneastro** [comment]
> @jgagneastro would you consider submitting that as a pull reqest?

Absolutely. I thought I needed to be registered to some astropy group to do this - I'm cloning it right now (had installed it through pip and I don't know how to push anything from the pip version)

**Comment by bsipocz** [comment]
This has been fixed for a long while now, thus closing the issue.
