### ISSUE TITLE
Change usage response.text to response.content

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#777]
As @mirca pointed out in #773 that `requests.Response.text` returns unicode or str depending on the python version, and it could cause problems such the one reported in #714.

@keflavich  suggested that we should instead use `requests.Response.content` as it's always comes back a bytes.

This issue is a reminder to revise all the usage of `requests.Response.text`

**Comment by tinumide** [comment]
Hi @bsipocz ! I would love to work on this

**Comment by tinumide** [comment]
Does anyone think there could be any exceptions in using `requests.Response.content` especially when the result would be acted upon by another method.

**Comment by tinumide** [comment]
Hi @bsipocz, @ceb8 , while working on this issue I made a commit for every change I made in a file. I was wondering if it is a good idea to squash the commits before making a PR since there are a number of them.

**Comment by ceb8** [comment]
@tinumide Go ahead and squash. Squashing at merge is also an option though.

**Comment by tinumide** [comment]
Alright. Thanks

**Comment by bsipocz** [comment]
Hmm, @keflavich @ceb8 - do we expect this to cause any trouble now that we don't support python2 anymore? Can you recall any recent instance of it?

**Comment by ceb8** [comment]
I don't think it should cause issues. I think the problems would arise when a string is expected and instead you get a bytes object, but looking at the associated PR Tinuade seems to have handled that.

**Comment by keflavich** [comment]
No, I think we should move forward assuming `response.text` is a python3-str.

I do not want to merge #1869 or a similar change - `response.text` is readable and behaves consistently, in that it returns a string of the type native to that python version.  I'm not convinced that any problems have ever been created by using `response.text`, including the NIST issue commented on in #714.  If there are problems associated with string/byte types, changing `response.text->response.content.decode(something)` is not the solution.

**Comment by bsipocz** [comment]
Yes, I'm also inclined towards not merging #1869 as the text is a bit more readable, let's close these then as a case where passing time resolved the issue naturally 😅
