### ISSUE TITLE
Refactor angle parsing to use astropy

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#794]
There are still places where astroquery does the angle parsing, rather than using the astropy machinery to do this. Would be nice to weed all these out one day. 

#753 points this out in the Simbad module, but probably there are other modules doing this, too.

**Comment by AyushYadav** [comment]
@bsipocz I went through the documentation of [astroquery.simbad](http://astroquery.readthedocs.io/en/latest/simbad/simbad.html) and looked the the only ICRS support for entry of coordinates as `string`. Should I work on fixing it in the `simbad.core` ? Let me know if there are any specific points to be kept in mind. Guidance needed!

**Comment by keflavich** [comment]
@AyushYadav Could you clarify what you're asking?  It looks like there's a typo in your question ("the the"), which makes it difficult to understand.

The point of this issue is that we want to let astropy do as much of the angle parsing as possible.  The `simbad._parse_radius` function is an example that can and should be replaced by astropy's units framework.

**Comment by AyushYadav** [comment]
@keflavich Sorry for the typo. But you cleared my doubt. 
I will start looking at the `simbad._parse_radius` and see if I can come up with something. 
Any ideas you already have about how to begin or go forward with it?

**Comment by AyushYadav** [comment]
@keflavich @bsipocz Is there any module where I can look for a reference so as to cover all edge cases?

**Comment by keflavich** [comment]
@AyushYadav No, I don't think so.  The most common cases will be:

 * Scalar floats (e.g, 1.5677).  They should either be interpreted as degrees or raise an exception if there is no default unit, depending on the documentation
 * Astropy quantities.  These are easy
 * Strings containing scalar floats: see above
 * Strings like `"1.566d"` should be parsed into 1.566 degrees, but it's not clear exactly how to accomplish this.  Similarly, `"1.566'"` should be 1.566 arcminutes, and `'1.566"'` should parse to 1.566 arcseconds.

**Comment by bsipocz** [comment]
most of the latter cases should be parsed by Skycoord, or at least I have an open PR somewhere to make most of the unambiguous cases work for 2.0. Let me know if you find a case that it not parsed by it.

**Comment by bsipocz** [comment]
Fixed by #867
