### ISSUE TITLE
Query and retrieve ESO phase 3 products

### ISSUE THREAD

**Issue by andycasey** [astropy/astroquery#800]
Hi everyone,

The docs state that you can use astroquery to search for Phase 3 data products (http://astroquery.readthedocs.io/en/latest/eso/eso.html#module-astroquery.eso), but there isn't an example given and I don't see any relevant methods to be able to search (or retrieve) Phase 3 products.

Is there a way to do this already, or was the list at the top of the documentation page more of a wishlist?

Thanks!

**Comment by andycasey** [comment]
On closer inspection it seems this is possible by querying surveys:

```
surveys = eso.list_surveys()
```

and then doing (e.g. for HARPS):

```
foo = eso.query_survey("HARPS")
```

The issue is that `eso.list_surveys()` returns an empty list, which could be because the ESO website is using jQuery to populate the `collection_name_option` form item. But doing this hack makes it possible to query the survey:

```
eso._survey_list = ["HARPS"]
foo = eso.query_survey("HARPS")
```

**Comment by bsipocz** [comment]
``eso.list_surveys()`` returns a 30 long list for me, could you check it again? However I believe ``eso.query_surveys()`` is still broken, but with having astropy feature freeze today I won't have time to fix it.

Nevertheless you're right that we need to add an example to the docs. 

PRs are welcome as always :) .

**Comment by keflavich** [comment]
@andycasey for retrieving the data, use `Eso.retrieve_data`.  I'm not sure which IDs are relevant, but it might be the ` 'Run/Program ID',` returned from `query_surveys`.

**Comment by jdavidrcamacho** [comment]
Hi @bsipocz 
Is it possible to retrieve the phase 3 spectral data products or` query_surveys `only works for the generic data products?

**Comment by keflavich** [comment]
@jwoillez any ideas on this one, or on who we should contact to find out more?  I don't have time to dig in deeply, and it seems like it needs expert attention from the ESO side.

https://twitter.com/exoplaneteer/status/1258406057552068608 raised this as a still-outstanding issue.

**Comment by gellule** [comment]
@keflavich I'll have a look tonight, or over the week-end.

**Comment by jwoillez** [comment]
@keflavich Let me have a look tonight, or over the week-end.

**Comment by jwoillez** [comment]
For me, the following works:

    from astroquery.eso import Eso

    eso = Eso()
    tbl = eso.query_surveys('HARPS', target="HD203608")
    filenames = eso.retrieve_data(tbl['ARCFILE'][:2])

It is just a matter of documentation.

**Comment by jwoillez** [comment]
@keflavich Can you tweet back and see if this explanation is enough, or if we are missing a functionality?

**Comment by jwoillez** [comment]
FYI, the use case described by @dfm there: https://github.com/astropy/astroquery/pull/1716#issuecomment-625767213 indeed does not work with the current astroquery.

**Comment by jwoillez** [comment]
@keflavich Should we open a specific issue with @dfm 's use case?

**Comment by keflavich** [comment]
Sure, that's a good idea - @dfm, would you like to do that?  Is it clearly distinct from this one?

**Comment by jdavidrcamacho** [comment]
I've been working in a way of searching and downloading reduces spectra using astroquery, you can find it here: 
https://github.com/jdavidrcamacho/StarSearch

Its still a work in progress but I'm getting there
