### ISSUE TITLE
ESASky remote data failure

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#803]
I see various KeyErrors when running the remote tests, e.g. here:
https://travis-ci.org/astropy/astroquery/jobs/182585185

cc @imbasimba 

<details>
platform darwin -- Python 3.5.2, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with astroquery version 0.3.5.dev3612.
Running tests in lib.macosx-10.10-x86_64-3.5/astroquery/esasky docs/esasky.

Date: 2016-12-09T15:01:43

Platform: Darwin-14.5.0-x86_64-i386-64bit

Executable: /Users/bsipocz/.virtualenvs/astropy-dev/bin/python

Full Python Version: 
3.5.2 (default, Jul  1 2016, 18:08:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.11.2
Matplotlib: 1.5.3
Astropy: 1.3.dev17339
APLpy: not available
pyregion: not available
Using Astropy options: remote_data.

rootdir: /private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/astroquery-test-u_i_owcg, inifile: setup.cfg
plugins: xdist-1.14
collected 9 items 

astroquery/esasky/tests/test_esasky.py ....
astroquery/esasky/tests/test_esasky_remote.py FFFF
../docs/esasky/esasky.rst .

=============================================================================== FAILURES ===============================================================================
_______________________________________________________________ TestESASky.test_esasky_query_region_maps _______________________________________________________________

self = <astroquery.esasky.tests.test_esasky_remote.TestESASky object at 0x10644dda0>

    def test_esasky_query_region_maps(self):
>       result = esasky.core.ESASkyClass().query_region_maps("M51", "5 arcmin")

astroquery/esasky/tests/test_esasky_remote.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astroquery/esasky/core.py:218: in query_region_maps
    sanitized_missions = self._sanitize_input_mission(missions)
astroquery/esasky/core.py:467: in _sanitize_input_mission
    return self.list_maps()
astroquery/esasky/core.py:64: in list_maps
    self._get_observation_json(cache = True), self.__MISSION_STRING)
astroquery/esasky/core.py:742: in _get_observation_json
    return self._fetch_and_parse_json(self.__OBSERVATIONS_STRING, cache)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <astroquery.esasky.core.ESASkyClass object at 0x10644db38>, object_name = 'observations', cache = True

    def _fetch_and_parse_json(self, object_name, cache):
        url = self.URLbase + "/" + object_name
        response = self._request('GET', url, cache = cache)
        string_response = response.content.decode('utf-8')
        json_response = json.loads(string_response)
>       return json_response[object_name]
E       KeyError: 'observations'

astroquery/esasky/core.py:752: KeyError
_______________________________________________________________ TestESASky.test_esasky_query_object_maps _______________________________________________________________

self = <astroquery.esasky.tests.test_esasky_remote.TestESASky object at 0x1063c2ac8>

    def test_esasky_query_object_maps(self):
>       result = esasky.core.ESASkyClass().query_object_maps("M51")

astroquery/esasky/tests/test_esasky_remote.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astroquery/esasky/core.py:118: in query_object_maps
    cache=cache)
astroquery/esasky/core.py:218: in query_region_maps
    sanitized_missions = self._sanitize_input_mission(missions)
astroquery/esasky/core.py:467: in _sanitize_input_mission
    return self.list_maps()
astroquery/esasky/core.py:64: in list_maps
    self._get_observation_json(cache = True), self.__MISSION_STRING)
astroquery/esasky/core.py:742: in _get_observation_json
    return self._fetch_and_parse_json(self.__OBSERVATIONS_STRING, cache)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <astroquery.esasky.core.ESASkyClass object at 0x1063c2e10>, object_name = 'observations', cache = True

    def _fetch_and_parse_json(self, object_name, cache):
        url = self.URLbase + "/" + object_name
        response = self._request('GET', url, cache = cache)
        string_response = response.content.decode('utf-8')
        json_response = json.loads(string_response)
>       return json_response[object_name]
E       KeyError: 'observations'

astroquery/esasky/core.py:752: KeyError
_____________________________________________________________ TestESASky.test_esasky_query_region_catalogs _____________________________________________________________

self = <astroquery.esasky.tests.test_esasky_remote.TestESASky object at 0x106561e10>

    def test_esasky_query_region_catalogs(self):
>       result = esasky.core.ESASkyClass().query_region_catalogs("M51", "5 arcmin")

astroquery/esasky/tests/test_esasky_remote.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astroquery/esasky/core.py:283: in query_region_catalogs
    sanitized_catalogs = self._sanitize_input_catalogs(catalogs)
astroquery/esasky/core.py:478: in _sanitize_input_catalogs
    return self.list_catalogs()
astroquery/esasky/core.py:71: in list_catalogs
    self._get_catalogs_json(cache = True), self.__MISSION_STRING)
astroquery/esasky/core.py:745: in _get_catalogs_json
    return self._fetch_and_parse_json(self.__CATALOGS_STRING, cache)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <astroquery.esasky.core.ESASkyClass object at 0x106561908>, object_name = 'catalogs', cache = True

    def _fetch_and_parse_json(self, object_name, cache):
        url = self.URLbase + "/" + object_name
        response = self._request('GET', url, cache = cache)
        string_response = response.content.decode('utf-8')
        json_response = json.loads(string_response)
>       return json_response[object_name]
E       KeyError: 'catalogs'

astroquery/esasky/core.py:752: KeyError
_____________________________________________________________ TestESASky.test_esasky_query_object_catalogs _____________________________________________________________

self = <astroquery.esasky.tests.test_esasky_remote.TestESASky object at 0x10638a3c8>

    def test_esasky_query_object_catalogs(self):
>       result = esasky.core.ESASkyClass().query_object_maps("M51")

astroquery/esasky/tests/test_esasky_remote.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astroquery/esasky/core.py:118: in query_object_maps
    cache=cache)
astroquery/esasky/core.py:218: in query_region_maps
    sanitized_missions = self._sanitize_input_mission(missions)
astroquery/esasky/core.py:467: in _sanitize_input_mission
    return self.list_maps()
astroquery/esasky/core.py:64: in list_maps
    self._get_observation_json(cache = True), self.__MISSION_STRING)
astroquery/esasky/core.py:742: in _get_observation_json
    return self._fetch_and_parse_json(self.__OBSERVATIONS_STRING, cache)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <astroquery.esasky.core.ESASkyClass object at 0x10638ac18>, object_name = 'observations', cache = True

    def _fetch_and_parse_json(self, object_name, cache):
        url = self.URLbase + "/" + object_name
        response = self._request('GET', url, cache = cache)
        string_response = response.content.decode('utf-8')
        json_response = json.loads(string_response)
>       return json_response[object_name]
E       KeyError: 'observations'

astroquery/esasky/core.py:752: KeyError

**Comment by imbasimba** [comment]
Good catch!
We have updated the names in the json files without thinking about how that affected the astroquery module.
I'll make a fix asap.

**Comment by bsipocz** [comment]
Great to here there is no mystery here. 
I've just revised our CI testing to make sure we run the remote tests at least once a week for catching cases exactly like this.

**Comment by imbasimba** [comment]
I have made a pull request with the fix for this problem.
https://github.com/astropy/astroquery/pull/805
