### ISSUE TITLE
Refactor usage of pyregion in favour of regions

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#804]
regions is probably getting mature enough with 0.2 to remove all usage of ``pyregion`` in favour of ``regions``.

**Comment by bsipocz** [comment]
@keflavich - There is a remote data failure with the alma finding chart generation: https://travis-ci.org/astropy/astroquery/jobs/188257369#L2461 Have you seen it?

Without looking much into the details it seems to be an upstream pyregions issue, so probably getting this change to use regions would be a good solution for it.

**Comment by keflavich** [comment]
I've seen it, but I don't recall now whether that proved to be something temporary or an actual bad URL (maybe they moved to https?).    I'll check it out later.

**Comment by bsipocz** [comment]
The line it complains doesn't seem to be python3 compatible in pyregions, so it's something we can't really address within astroquery. 
There may be an url error on top of it as even the python2 build halts and fails at this point.

**Comment by bsipocz** [comment]
@keflavich - you are the most familiar with functionalities in both. Are we any closer to ditch pyregions in favour of regions? E.g. now it started to trigger numpy deprecation warnings and frankly I would rather ditch it if we can than keep it on life support any longer.
