### ISSUE TITLE
Remove matplolib as dependency

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#816]
@keflavich  - I wonder about the reason that matplotlib is listed in the CI files as a dependency. We use it nowhere in the code, so I would incline not to install it for testing.

**Comment by keflavich** [comment]
The alma utilities package uses aplpy which requires matplotlib.  That's the only place I can find it.  Unless installing matplotlib takes a long time, I think we can keep it.

**Comment by bsipocz** [comment]
But then it will be installed with aplpy as a dependency?

**Comment by keflavich** [comment]
Right, as long as that's happening, then we can remove the explicit mpl dependency.
