### ISSUE TITLE
Error 500 over ALMA Request Handler for download data from archive

### ISSUE THREAD

**Issue by camilo-nunez** [astropy/astroquery#827]
Hi ! i trying to download some observation (HD163296Band6 and M83) with the method Alma.stage_data, but i get the error 500 from the archive of NRAO.

http://prntscr.com/drwl2w

why happens this ?

**Comment by keflavich** [comment]
This appears to be a problem with http/https.  This is a frustrating error because it means the ALMA archive is returning the wrong form.  We'll need to implement a workaround.

**Comment by camilo-nunez** [comment]
This error is new or comes from before ?

**Comment by keflavich** [comment]
This is new, probably as of this week.

**Comment by keflavich** [comment]
This is addressed in #828.  It should be addressed here, but there is a bug I don't understand with github's API.

**Comment by keflavich** [comment]
This should be solved with #828 merged.  Could you try again and confirm it works?

**Comment by camilo-nunez** [comment]
I done the same change that was done  in [#828](https://github.com/astropy/astroquery/pull/828), but now, i have news errors:

http://prnt.sc/ds0nix
http://prnt.sc/ds0nr1

**Comment by keflavich** [comment]
This is a server-side bug on the NRAO servers.  Try the ESO ones by changing `Alma.archive_url = 'https://almascience.eso.org'`.

**Comment by camilo-nunez** [comment]
This doesn't stop jajajja. I get this error now with the tag's of VOtable:

http://prnt.sc/ds1vzo
http://prnt.sc/ds1w3u

I do not know if this happens due to the change of Archive or if it is a problem of the file.

**Comment by camilo-nunez** [comment]
I tested with the archive of ESO and NAOJ, but i get this error: 

` Received an error 405: this may indicate you have already staged the data.  Try downloading the file URLs directly with download_files.`

I understand that services of NRAO are down now, but i don't think this error is due to this.

**Comment by keflavich** [comment]
No, that error means you have already *successfully* staged the data, and
now you should try downloading (the servers reject repeated attempts to
stage the data).​
