### ISSUE TITLE
Changes in ALMA API/return data

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#831]
Yet again there were some changes in the ALMA API and the format of the results changed slightly causing a few test failures.

@keflavich - Could you give it  a look? https://travis-ci.org/astropy/astroquery/jobs/190720027

**Comment by keflavich** [comment]
will do.  argh.

**Comment by bsipocz** [comment]
I wonder whether this and the esasky changes would deserve a release in the near future?

**Comment by keflavich** [comment]
Sure!  Releases are great!

**Comment by bsipocz** [comment]
Fixed by #832
