### ISSUE TITLE
SkyView.get_images and get_image_list returning empty list for valid queries

### ISSUE THREAD

**Issue by StuartLittlefair** [astropy/astroquery#843]
With Python 3.5.2, astropy 1.3, and astroquery 0.3.4 or 0.3.5.dev the example in the docs yields:

```python
>>> SkyView.get_image_list(position='Eta Carinae',
                  survey=['Fermi 5', 'HRI', 'DSS'])
[]
```

**Comment by nitish6174** [comment]
All 3 versions you mentioned (python, astropy, astroquery) are same on my machine.  
Running the above command gave following output :
 ```
['http://skyview.gsfc.nasa.gov/tempspace/fits/skv573690101153_1.fits', 'http://skyview.gsfc.nasa.gov/tempspace/fits/skv573690101153_2.fits', 'http://skyview.gsfc.nasa.gov/tempspace/fits/skv573690101153_3.fits']
```
So it must be some issue on your end.

**Comment by keflavich** [comment]
It's possible there was a temporary failure on the server.

**Comment by StuartLittlefair** [comment]
Yes - it looks like this is the case, as the example works fine now. Apologies for false alarm.

**Comment by carlos-lco** [comment]
I have similar problem from yesterday Jun18. Is it possible a server problem is happening? 
I think the function SkyView should have a timeout in order to show the problem.

**Comment by keflavich** [comment]
> I have similar problem from yesterday Jun18. Is it possible a server problem is happening? 
> I think the function SkyView should have a timeout in order to show the problem.

This issue is ancient and unlikely to be recurring.  Please read any of the most recent 5 issues to see solved problems with skyview.
