### ISSUE TITLE
query_region() results to include the distance to the target

### ISSUE THREAD

**Issue by ivvv** [astropy/astroquery#845]
I don't know if this is implemented in any of the `astroquery` services, but I could not find the distance to the target for each match when I was doing `query_region("name",radius=x*10.arcsec)` with `astroquery.simbad`.

It would be helpful to have this information returned in the results. When I do a query with Simbad's web interface I see the distance column. I tried to identify which Simbad vo_table field may contain this, but it is not obvious and I am not sure if it is available.  Of course I can do a loop over all matches and calculate it but if it is available then this will save some unnecessary loops.

**Comment by keflavich** [comment]
This is a nice idea and could in principle be implemented for all services that return source location columns reproducibly.  That might be a nice GSoC project.

For SIMBAD specifically, I think there is a flag that can be passed, but I don't know it off the top of my head

**Comment by bsipocz** [comment]
This is not fixed by #849.

**Comment by keflavich** [comment]
Not fixed?  Should this have been closed, then?

**Comment by bsipocz** [comment]
silly typo, not=now...
