### ISSUE TITLE
Adding 3D-HST to astroquery

### ISSUE THREAD

**Issue by AyushYadav** [astropy/astroquery#853]
I would like to suggest one addition. Not sure if the API is upto the task. But I would like to recommend to add [3D-HST](http://3d-hst.github.io/3dhst_api/) API. 3D-HST comes from the near-infrared spectroscopic survey with the Hubble Space Telescope. It is a very detailed survey of the five well-studied extragalactic survey fields (AEGIS, COSMOS, GOODS-S, UKIDSS-UDS) with two orbits of primary WFC3/G141 grism coverage and two to four orbits with ACS/G800L coverage [Link](http://3dhst.research.yale.edu/Home.html).

**Comment by bsipocz** [comment]
I'm repeating my previous comment here as it's rather relevant here, too:

Personally would prefer not to have tons of smaller modules for every survey of a few orbits but rather to have one big module to access all HST/WFC3 preferably via a MAST module.

**Comment by AyushYadav** [comment]
@bsipocz This Treasury program has been allocated 248 orbits of HST time during Cycles 18 and 19. The dataset has a large amount of 1D and 2D spectra data as well. Currently the API is not exposed to serve that part but in future it will. A `conesearch` query along with `object` `nearest` i.e. near object search is currently under working.

**Comment by bsipocz** [comment]
We do have both astroquery.mast and astroquery.esa.hubble to access HST data. So I do go ahead and close this issue now.
