### ISSUE TITLE
Restructure index page and update example gallery

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#863]
With recent additions of rather complex and non-conform* modules (e.g. ``gaia`` or ``vo-conesearch``), it's about time to restructure the index page a bit. Maybe add a section for TAP (even though we only have one module atm), order modules within sections alphabetical.

* in both case the common API may not be the most natural structure of the modules

**Comment by bsipocz** [comment]
We should also update the example gallery, it wasn't touched for a while and new users may end up there first when looking at the webpage.

**Comment by bsipocz** [comment]
This issue should be addressed for https://github.com/adamginsburg/astroquery-paper/issues/26

Alternatively reconsider getting rid of this page and rely on the examples in the individual services.

**Comment by keflavich** [comment]
The reason for the gallery is to show examples where astroquery modules interact with one another and with other elements of the greater astropy environment.  They are probably more appropriate in astropy-tutorials, so if we eliminate them here, we should replace the gallery with a set of links to relevant astropy tutorials.

**Comment by keflavich** [comment]
For now, the gallery is in an OK state, but long term, we want to move much of it to tutorials.

**Comment by bsipocz** [comment]
The gallery has been removed, and the restructuring of the main landing page is tracked e.g. here: https://github.com/astropy/astroquery/issues/2555
