### ISSUE TITLE
_args_to_payload in Magpis has doc string mismatch

### ISSUE THREAD

**Issue by AyushYadav** [astropy/astroquery#865]
The doc-string in the ``MagpisClass._args_to_payoad`` has the parameter `image_size` while the doc-string incorrectly classifies it as `radius`

**Comment by AyushYadav** [comment]
@bsipocz  Will submit it in the PR with other issues fixed later tonight.

**Comment by bsipocz** [comment]
@AyushYadav - Thanks for spotting this. If it's unrelated to the other issues you're referring to, then adding them in separate PRs is a bit more preferable.
