### ISSUE TITLE
Upgrade fails with setuptools

### ISSUE THREAD

**Issue by ivvv** [astropy/astroquery#878]
I just tried to `pip install --upgrade astroquery` and it failed with this message:

`
Installing collected packages: setuptools
  Found existing installation: setuptools 27.2.0
Cannot remove entries from nonexistent file .../anaconda3/lib/python3.5/site-packages/easy-install.pth
`
So, the installation uninstalled a number of dependencies in order to upgrade them too (astropy, numpy etc.) and with this error none of those are available any longer. I can re-install them one by one in order to get a working astropy, but I'd rather like to fix this error and get the updates `astroquery`.

**Comment by ivvv** [comment]
Found an answer by googling the error. It worked by `pip install --ignore-installed setuptools` and then `pip install --upgrade astroquery`.

Seems to work now.

**Comment by keflavich** [comment]
Thanks for providing the solution.  I don't think there's anything we need to change, so I'm closing this.
