### ISSUE TITLE
Vizier.query_object return empty lists

### ISSUE THREAD

**Issue by msotov** [astropy/astroquery#882]
Hi,

I'm having issues when trying to obtain data from catalogs in Vizier using astroquery.Vizier. No matter what object I use, my results are always 'Empty TableList'. I even tried with one of the query_object examples:

result = Vizier.query_object("sirius")

and even in that case I get 'Empty TableList'. 

Could this be a problem of the package, or from the Vizier servers?

Thank you!

**Comment by keflavich** [comment]
This is an announced downtime from the CDS:
```
We would like to make you aware of a scheduled down-time for all Strasbourg sites for CDS services on Monday April 3, starting at 7h00 CET (5h00 GMT) and lasting for 6 to 10 hours.

This is an unavoidable down-time due to major electrical work that requires all power to our site to be shut down for that time.
Please, forward this information to make sure that all partners are aware of the CDS down-time scheduled for April 3, 2017.


A redirection will be done for main web pages of Simbad and Vizier to cfa.harvard.edu, but everything will not work properly.


We recommend the use of our mirror sites during this period: Simbad at CfA, or VizieR at CfA, Tokyo, CADC, IUCAA in India, Beijing Obs., or SAAO in South Africa.
We sincerely apologize for the inconvenience.
```

Try switching to a different mirror

**Comment by pllim** [comment]
@keflavich , I think it is also worth documenting ways to get query payload (URL) and raw response as alternatives for finding out what is wrong. I am only aware of those options because I read the API.

**Comment by keflavich** [comment]
@pllim I agree, though in this particular case, the return from the Vizier servers is quite unenlightening.  I seem to have been automatically redirected to a mirror that is returning bad results:
```
>>> result = Vizier.query_object_async('sirius')
>>> print(result.text)
<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE version="1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.ivoa.net/xml/VOTable/v1.2"
  xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.2 http://www.ivoa.net/xml/VOTable/v1.2">
 <DESCRIPTION>
   VizieR Astronomical Server vizier.cfa.harvard.edu
    Date: 2017-04-03T19:17:57 [V1.99+ (14-Oct-2013)]
   Explanations and Statistics of UCDs:			See LINK below
   In case of problem, please report to:	cds-question@unistra.fr
   In this version, NULL integer columns are written as an empty string
   &lt;TD&gt;&lt;/TD&gt;, explicitely possible from VOTable-1.3
 </DESCRIPTION>
<!-- VOTable description at http://www.ivoa.net/Documents/latest/VOT.html -->
<INFO ID="VERSION" name="votable-version" value="1.99+ (14-Oct-2013)"/>
<INFO ID="Ref" name="-ref" value="VOTx15495"/>
<INFO name="MaxTuples" value="50000" />
<INFO name="queryParameters" value="1">
-oc.form=D.
</INFO>
<INFO ID="fatalError" name="Error" value="No catalogue or table was specified or found.
"/>
</VOTABLE>
```


This also raises the issue that it is not easy to determine what the available mirrors are from within a python session.  You can see them:

```
>>> from astroquery import vizier
>>> vizier.Conf.server.cfgtype
'option(vizier.u-strasbg.fr, vizier.nao.ac.jp, vizier.hia.nrc.ca, vizier.ast.cam.ac.uk, vizier.cfa.harvard.edu, www.ukirt.jach.hawaii.edu, vizier.iucaa.ernet.in, vizier.china-vo.org)'
```

@pllim @bsipocz do you know, is there an easier way using astropy configuration tools to view the available options?

**Comment by keflavich** [comment]
Actually, I think this is a weird error with the mirrors.  If I try to access Vizier @ strasbourg via the browser (vizier.u-strasbg.fr/viz-bin/VizieR), I am redirected to a nonfunctioning version of vizier hosted at harvard (http://vizier.cfa.harvard.edu/viz-bin/VizieR).

If I access harvard's mirror directly (http://vizier.cfa.harvard.edu), I am redirected to a functional version of Vizier (http://vizier.cfa.harvard.edu/index.gml).  

Similarly, the redirect happening via astroquery is going to this 'bad' version of Vizier.  I think this is a server-side issue, but maybe we can find some way to get to the "good" version too...

**Comment by pllim** [comment]
Re: config. Does this help?
```python
>>> from astroquery import vizier
>>> print(vizier.Conf.server)
ConfigItem: server
  cfgtype='option(vizier.u-strasbg.fr, vizier.nao.ac.jp, vizier.hia.nrc.ca, vizier.ast.cam.ac.uk, vizier.cfa.harvard.edu, www.ukirt.jach.hawaii.edu, vizier.iucaa.ernet.in, vizier.china-vo.org)'
  defaultvalue='vizier.u-strasbg.fr'
  description='Name of the VizieR mirror to use.'
  module=astroquery.vizier
  value='vizier.u-strasbg.fr'
>>> print(vizier.conf.server)
vizier.u-strasbg.fr
```

**Comment by keflavich** [comment]
Actually, it looks like astroquery may be doing something wrong when handling the redirection.  The Strasbourg server is redirecting us, but the request content is lost.

```
>>> V_harvard = Vizier()
>>> V_harvard.VIZIER_SERVER = 'vizier.cfa.harvard.edu'
>>> V_strasbourg = Vizier()
>>> V_strasbourg.VIZIER_SERVER='vizier.u-strasbg.fr'
>>> result_strasbourg = V_strasbourg.query_object_async('Sgr A*')
>>> result_harvard = V_harvard.query_object_async('Sgr A*')
>>> result_strasbourg.request.body
None
>>> result_harvard.request.body
'-out=*\n-out.max=50\n-c=Sgr A*\n-out.meta=huUD\n-out.form=mini\n-oc.form=d'
```

**Comment by keflavich** [comment]
@pllim that helps.  Is there any way to access those values in a list, or only via `__repr__` as you showed?

**Comment by keflavich** [comment]
OK, the problem is related to this:
https://github.com/kennethreitz/requests/issues/3107

```
>>> result_strasbourg.history
[<Response [302]>]
>>> first_result = result_strasbourg.history[0]
>>> first_result.request.method
'POST'
>>> result_strasbourg.request.method
'GET'
```
So we're at least kinda doing the right thing in astroquery, we just can't rely on the redirects. 

There are a few options:
1. On a 302, raise an Exception telling the user to switch mirrors
2. On a 302, find the redirect URL, and post a fresh request to that URL (this technically violates the HTTP standard...)

**Comment by keflavich** [comment]
I've e-mailed CDS asking if they can change their redirect to use [307](https://httpstatuses.com/307) instead of [302](https://httpstatuses.com/302)

**Comment by pllim** [comment]
@keflavich short answer to your config question is "no". `astropy.config` uses `astropy.extern.configobj`, which uses regex magic, so your option is permanently turned into a string. If you want a nice list, you will have to write your own parser for it.

**Comment by msotov** [comment]
Hi,

I tried again today, and I still obtain Empty TableList. Could this be still related to the downtime from yesterday?

**Comment by keflavich** [comment]
Clear your cache (delete files in `~/.astropy/cache/astroquery/vizier/`).  Bad (empty) results were cached there, most likely.

**Comment by keflavich** [comment]
This was a temporary failure that has been resolved.  It's not clear to me whether the redirects issue has been handled, but that was a side issue anyway.
