### ISSUE TITLE
RTD stable version denies access

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#883]
http://astroquery.readthedocs.io/en/stable/ gives me
```
Permission Denied

You don't have the proper permissions to view this page.
Please contact the owner of this project to request permission.
```

Is this intentional?

**Comment by bsipocz** [comment]
I'm not sure what we should have as "stable". There is a stable tag for an ancient version, but we don't have a stable branch like for astropy, and there is no active stable version on RTD either. Where did you find that link?

On the other hand there was no build yet for the latest 0.3.5 release, so I've activated that one.

**Comment by pllim** [comment]
Does stable not automatically point to the latest GitHub release? It does for some packages that I maintain.

**Comment by pllim** [comment]
> Where did you find that link?

I typed it in manually. Isn't that the intuitive thing to do? :sweat_smile:

**Comment by MSeifert04** [comment]
@pllim Not if deactivated. In RTD -> Admin you can select "Versions" and activate/deactivate everything including "master", "latest" and "stable" 😄

**Comment by bsipocz** [comment]
> I typed it in manually. Isn't that the intuitive thing to do?

Well, not if you're an average user. Available versions are listed in the dropdown menu of the lower right corner.
Also in case of astroquery, we're very cautious to call something "stable" given the moving target nature of the the modules.

**Comment by pllim** [comment]
Okay, fair enough. The original intention is to link a stable doc to the Cone Search tutorial, as I did when it was in Astropy (in its non-deprecated form). But I can just hardcode 0.3.5 in the link instead.

**Comment by bsipocz** [comment]
Ah, OK. I guess you can hard-code latest, as the release cycle is pretty frequent, and probably there wont be much change to cone search.

@keflavich - do you think we should turn building stable back on?

**Comment by keflavich** [comment]
I have no objection to it.  Sure, a large fraction of astroquery is 'never stable', but I can see the need for a long-term link for docs.  That said... what would we call our 'stable' version?  0.3.5?

**Comment by bsipocz** [comment]
Always the latest release? Though I'm not sure how RTD recognizes a new release, as we don't have a stable tag or branch.

**Comment by bsipocz** [comment]
Ahh, reading the docs of rtd answers my own question:
``We also create a stable version, if your project has any tagged releases. stable will be automatically kept up to date to point at your highest version.``

**Comment by pllim** [comment]
Well, please let me know if you decide to enable "stable" build. Otherwise, I'll just use "latest" as you suggested above. Thank you!

**Comment by bsipocz** [comment]
@pllim - I've already tried, but the build fails. I suspect that it doesn't pick up the latest release but probably that ancient stable tag.

**Comment by pllim** [comment]
Don't worry about it then. Thanks!
