### ISSUE TITLE
Problems with sha

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astroquery#884]
I'm trying to use the astroquery.sha module and unfortunately, I get the following error:

    >>> from astroquery import sha
    /Users/crawford/anaconda/envs/pyjedi/lib/python3.5/site-packages/astroquery/sha/__init__.py:14:   UserWarning: Experimental: SHA has not yet been refactored to have its API match the rest of astroquery.
    warnings.warn("Experimental: SHA has not yet been refactored to have its "
    >>> pos_t2 = sha.query(ra=163.6136, dec=-11.784, size=0.5)
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/Users/crawford/anaconda/envs/pyjedi/lib/python3.5/site-packages/astroquery/sha/core.py", line 144, in query
       dtypes = _map_dtypes(type_names, field_widths)
     File "/Users/crawford/anaconda/envs/pyjedi/lib/python3.5/site-packages/astroquery/sha/core.py", line 265, in _map_dtypes
       raise ValueError('Unexpected type name: {0}.'.format(name))
    ValueError: Unexpected type name: reqkey.
    >>> import astroquery
    >>> astroquery.__version__
    '0.3.5'
    >>> import astropy
    >>> astropy.__version__
    '1.3.2' 

I've tried this in python 3.6 and python 2.7, and both return the same error.   

It would appear the error is being generated due to an extra initial line  being returned in results from the spitzers heritage archive then what the code is expecting.   

I just wanted to check whether this was a known problem or if this was something unique to me  prior to submitting a pull request to fix it.    Strangely, if I run the tests for this package, it passes without an error even though the command above is the same being used in the

**Comment by bsipocz** [comment]
@crawfordsm - I haven't recall of seeing this issue before, but I think ``sha`` is not one of our most used modules. It also one of those ones that doesn't yet use the common API, and it doesn't have any remote tests either so no wonder the tests didn't pick it up.

**Comment by crawfordsm** [comment]
Okay, then I'll at least submit my working fix tomorrow.   Probably don't have time to do much more than that right now.
