### ISSUE TITLE
Issue with ALMA query and votable

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroquery#890]
The following example:

```python
from astroquery.alma import make_finder_chart
from astropy import units as u
make_finder_chart('M42', 10 * u.arcmin, 'm42')
```

results in the following error:

```
INFO: Querying <bound method SkyViewClass.get_images of <astroquery.skyview.core.SkyViewClass object at 0x10f227910>> for images [astroquery.alma.utils]
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv3944982217174.fits
|=======================================================================================================================================| 1.0M/1.0M (100.00%)         1s
INFO: Querying ALMA around M42 [astroquery.alma.utils]
Traceback (most recent call last):
  File "chart.py", line 4, in <module>
    make_finder_chart('M42', 10 * u.arcmin, 'm42')
  File "/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/astroquery/alma/utils.py", line 175, in make_finder_chart
    **kwargs)
  File "/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/astroquery/alma/utils.py", line 212, in make_finder_chart_from_image
    **alma_kwargs)
  File "/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/astroquery/alma/core.py", line 412, in _parse_result
    vo_tree = votable.parse(tf, pedantic=False, invalid='mask')
  File "/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/astropy/io/votable/table.py", line 140, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/astropy/io/votable/tree.py", line 3344, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:0: no element found
```

Note that if I run it again, I then get the issue reported in #889 - weird!

**Comment by bsipocz** [comment]
There are two possibly related PRs open #888 and #881. Hopefully either of those will fix these issues?

**Comment by astrofrog** [comment]
Unfortunately it seems like neither PR fixes the VO table issue

**Comment by astrofrog** [comment]
The start of the VO table looks like:

```
^@ all the spectral windows, from frequency resolution.</DESCRIPTION>
      </FIELD>
      <FIELD name="Pol products" datatype="char" ID="1238" ucd="phys.polarization;meta.code" xtype="adql:VARCHAR" arraysize="64*">
        <DESCRIPTION>Polarisation products provided.</DESCRIPTION>
      </FIELD>
      <FIELD name="Observation date" datatype="char" unit="" xtype="adql:VARCHAR" arraysize="*" />
      <FIELD name="PI name" datatype="char" ID="1260" ucd="meta.id.PI" xtype="adql:VARCHAR" arraysize="256*">
        <DESCRIPTION>case-insensitive partial match over the full PI name. Wildcards can be used</DESCRIPTION>
      </FIELD>
```

which is probably the issue...

**Comment by keflavich** [comment]
@astrofrog #888 may fix this.  The finder chart maker was *completely broken* by some huge upstream changes.  Specifically, the ALMA archive removed a *vast* number of entries by slimming down from reporting every individual pointing to reporting every scheduling block.  The original finder chart maker required individual pointings, #888 uses the new (but very inaccessible) `Footprint` column instead.

The VOTable issue may be another manifestation of #889, i.e., nondeterministic ALMA returns.  You could `%debug` and see if `Alma._last_response.text == ''` to check that.

**Comment by astrofrog** [comment]
#888 doesn't seem to fix it, see above, it seems the VO table is actually truncated at the start or something. Can you reproduce the issue on your side?

**Comment by keflavich** [comment]
It really leads with `^@`?  What?!  I'll try.  

Are you running with `cache=False`?  Might have been one failed query that is repeating itself...

**Comment by astrofrog** [comment]
I think there are major issues with the server today... Makes it hard to debug! Sometimes the server does return a valid XML table, it does seem to be sporadic.

**Comment by keflavich** [comment]
@astrofrog - I wish it were a 'today' issue, but it's been happening to me for the last few weeks.  It's super frustrating that bad returns still have HTTP code 200.

**Comment by astrofrog** [comment]
Sometimes the server also reports no matches and then the next query it reports matches (when using ``query_region``)

**Comment by astrofrog** [comment]
To be fair, the results are also random when using the web interface (sometimes no results are returned, sometimes they are)

**Comment by keflavich** [comment]
@astrofrog - could you report that as a problem to the ALMA helpdesk?  The archivists need to know about these issues.

**Comment by keflavich** [comment]
I get fine results using #888 and the test query.  I'll let #888 close this unless someone reports an additional reason not to

![m42_almafinderchart](https://cloud.githubusercontent.com/assets/143715/25090582/4b636df0-2341-11e7-9b85-eb2d93d28db3.png)

**Comment by astrofrog** [comment]
Ok, fine by me to close, will open an ALMA ticket if I keep running into issues.

**Comment by bsipocz** [comment]
I don't see this error any more,  so closing the issue. Feel free to reopen if it pops up again.
