### ISSUE TITLE
Working on MAST query tool

### ISSUE THREAD

**Issue by ceb8** [astropy/astroquery#896]
Just letting anyone interested know that an astroquery tool to query MAST databases is in the works.  

### MAST Query Tool Design and planned features

**MastClass:**

* [x] service_request\[_async](service,params): Astropy Table of mashup results

**ObservationsClass(MastClass):**

* [x] query_object\[_async](objectname,radius,pagesize,page): Astropy Table of observations
* [x] query_region\[_async](coordinates,radius,pagesize,page): Astropy Table of observations
* [x] query_criteria\[_async](filters,objectname,coordinates,radius,pagesize,page): Astropy Table of observations

* [x]    query_object_count(objectname,radius): Number of observations
* [x]    query_region_count(coordinates,radius): Number of observations
* [x]    query_criteria_count(filters,objectname,coordinates,radius): Number of observations

* [x]    get_product_list(obsidOrRow): Astropy Table of data products
* [x]    filter_products(products,filters): Astropy Table of data products
* [x]    download_products(obsidsOrProductRows,downloadDir,mrpOnly,filters,curlFlag): Astropy Table manifest of downloaded files

* [x]  list_missions(): List of available missions

**CatalogClass(MastClass):**

* [x]   query_object\[_async](objectname,radius,catalog,pagesize,page,**kwargs): Astropy Table of catalog entries
* [x]   query_region\[_async](coordinates,radius,catalog,pagesize,page,**kwargs): Astropy Table of catalog entries
* [x] query_criteria\[_async](catalog,pagesize,page,**criteria): Astropy Table of catalog entries
* [x]  query_hsc_matchid\[_async](match,pagesize,page): Astropy Table of catalog entries
* [x]  get_hsc_spectra\[_async](pagesize,page): Astropy Table of HSC spectra
* [x] download_hsc_spectra(spectra, download_dir, cache, curl_flag): Astropy Table manifest of downloaded files

**Other planned features**

* [X] Login capability

**Comment by keflavich** [comment]
Part 1 implemented in https://github.com/astropy/astroquery/pull/920

@ceb8 Could you add a checklist here for additional features?  We'll keep this issue open until you're done.

**Comment by ceb8** [comment]
### MAST Query Tool Design and planned features

**MastClass:**

* [x] service_request\[_async](service,params): Astropy Table of mashup results

**ObservationsClass(MastClass):**

* [x] query_object\[_async](objectname,radius,pagesize,page): Astropy Table of observations
* [x] query_region\[_async](coordinates,radius,pagesize,page): Astropy Table of observations
* [ ] query_criteria\[_async](filters,objectname,coordinates,radius,pagesize,page): Astropy Table of observations

* [ ]    query_object_count(objectname,radius): Number of observations
* [ ]    query_region_count(coordinates,radius): Number of observations
* [ ]    query_criteria_count(filters,objectname,coordinates,radius): Number of observations

* [ ]    get_product_list(obsidOrRow): Astropy Table of data products
* [ ]    filter_products(products,filters): Astropy Table of data products
* [ ]    download_products(obsidsOrProductRows,downloadDir,mrpOnly,filters,curlFlag): Astropy Table manifest of downloaded files

**CatalogClass(MastClass):**

* [ ]   query_object_catalog(objectname,radius,resource,pagesize,page): Astropy Table of catalog entries
* [ ]   query_region_catalog(coordinates,radius,resource,pagesize,page): Astropy Table of catalog entries
* [ ]  query_match_id(matchid,resource,pagesize,page): Astropy Table of catalog entries
* [ ]  get_hsc_spectra(): Astropy Table of HSC spectra

**Other planned features**

* [ ] Login capability

**Comment by bsipocz** [comment]
@ceb8 - I've moved the checklist to the top comment, so that its summary is visible from the issue list, too.

**Comment by bsipocz** [comment]
@ceb8 - Would that be possible to have a (convenience)method that lists the available catalogs/projects? E.g. I see that with filtering it's possible to query for data from only a specified mission, but it would be great to have a few convenience methods on top of the more complex generic filtering.

**Comment by ceb8** [comment]
@bsipocz I was already planning a method to list available catalogs for the catalog class.  I can definitely do one that lists missions in the observations class.

**Comment by bsipocz** [comment]
I'm relaying a question I got yesterday after giving a talk about astroquery, namely whether we have PanSTARRS access via the mast module or if not whether it's planned?

(I told them MAST is a very new module and there are still some ongoing work, but couldn't give much details about panstarrs).

**Comment by ceb8** [comment]
@bsipocz Yes there will be PanSTARRS access through the module, it allows access to anything in CAOM, i.e. anything that can be accessed through the Discovery Portal (mast.stsci.edu), so when PanSTARRS becomes available through that interface (which I believe will be in the next release) it will also be accessible through astroquery.mast.

**Comment by bsipocz** [comment]
Brilliant! Thanks for the clarification.

**Comment by sushobhana** [comment]
Hi all!
i came across this while going through the GSOC project ideas and found it interesting.
i went through the Mast web api documentation and as well as the astroquery.mast module to get a vague idea of how things are getting implemented. i am getting most of the things but did not get what does `list_missions` do??I tried looking for the `Mast.Caom.All` service but did not get anything.Can anyone please help me out?? And there is a small typo error in the function docstring of `list_missions`.

**Comment by ceb8** [comment]
Hi @sushobhana .

list_missions lists all the missions that MAST holds Observations for ([documentation](https://astroquery.readthedocs.io/en/latest/mast/mast.html#listing-available-missions) ).

It is not included in the current stable release, you need the development version to access it.

Thanks for pointing out the typo, I'll fix it in my next MAST update.

**Comment by sushobhana** [comment]
Thanks for the clarification.! @ceb8

**Comment by keflavich** [comment]
@ceb8 will the MAST module provide access to things like this cutout service? http://ps1images.stsci.edu/cgi-bin/ps1cutouts

If not, we might want a separate interface for that.

**Comment by ceb8** [comment]
@keflavich The MAST module does not currently offer cutout functionality.  We have plans for TESS cutout functionality, but I don't know if that will expand to include things like panstarrs.  Going forwards we want to provide good APIs including astroquery components for new interfaces as we build them, but retrofitting APIs for old interfaces is more piecemeal, simply because we do not have infinite time/resources. 

I do think it would makes sense to put an interface to that service under the mast module, perhaps mast.Cutouts.

**Comment by keflavich** [comment]
Alright, cool, let's add that as a to-do item, either here or in its own issue.  I understand the resource limitation issue, but perhaps this is the sort of relatively straightforward task a student (or someone just interested in getting access to the cutouts) might take on.

**Comment by bsipocz** [comment]
Thank you @ceb8 for working on this!
Looking at the list above, everything has been implemented, so I would close this issue. Any new enhancements could come as PRs or todo items can go into a new issue.
