### ISSUE TITLE
query_object not returning all catalog keywords

### ISSUE THREAD

**Issue by msotov** [astropy/astroquery#897]
Hello,

I'm using Vizier.query_object for an object and a list of catalogs, but in the result I don't see all the valid keywords of the catalogues listed, only the default ones in Vizier. How do I force query_object to return all keywords for each catalogue?

Thanks

**Comment by keflavich** [comment]
Could you provide a specific example?

**Comment by msotov** [comment]
For example, I want to look for the star HD23249 in the Hipparcos
catalogue. I do the following:

result = Vizier.query_object('HD23249', catalog = 'I/311/hip2', radius =
10.*u.arcsec)

but I obtain only 13 columns, when the original catalogue has 29 columns.


2017-04-20 10:44 GMT-03:00 Adam Ginsburg <notifications@github.com>:

**Comment by bsipocz** [comment]
@msotov - The query returns the same default columns Vizier does. To get all columns rather than the default selection I would do this:

```
v=Vizier(columns=["**"])
result = v.query_object('HD23249', catalog='I/311/hip2', radius=10.*u.arcsec)
```

The docs is here:
http://astroquery.readthedocs.io/en/latest/vizier/vizier.html#specifying-keywords-output-columns-and-constraints-on-columns
