### ISSUE TITLE
Incomplete list of columns retrieved from Vizier

### ISSUE THREAD

**Issue by outs1der** [astropy/astroquery#900]
Am experiencing a problem with an incomplete list of columns being retrieved from Vizier. The code below worked fine on astroquery 0.3.4, but with the upgrade to 0.3.5, we are missing some of the columns (seems to be all those with an underscore in the name).

Below is an example of code which will reproduce the issue. This works fine on 0.3.4 but fails on 0.3.5

```
from astroquery.vizier import Vizier
model_table = Vizier.get_catalogs('J/ApJ/819/46')
data=model_table[0]
data['e_tDel’]
```

Thanks
D.

**Comment by keflavich** [comment]
I can reproduce this.  It looks like those columns are not selected by default in the online query tool:
http://vizier.u-strasbg.fr/viz-bin/VizieR?-source=J/ApJ/819/46&-to=3
but we should be able to access them via astroquery.  I'll investigate.

**Comment by keflavich** [comment]
The solution is to set `Vizier.columns = ['all']` or `Vizier.columns = ['**']`, which will select all columns.  The default is `Vizier.columns = ['*']`, which selects all of the 'default' columns that are checked when you use the online interface.

@outs1der Are you sure it worked differently on previous versions of astroquery?  It is possible that it did, and it was an upstream change in Vizier, though such changes are uncommon.

**Comment by outs1der** [comment]
Hi Adam,

thanks for the reply, I can confirm this solution did the trick. Sorry if this option was covered in the documentation (I looked, but could not find it).

Definitely worked differently with the previous version, although I note in the upgrade there were a number of other packages that were updated too. Perhaps one of the other packages could have somehow influenced the column selection

In any case problem solved!

Cheers
Duncan

> On 9 May 2017, at 5:18 PM, Adam Ginsburg <notifications@github.com> wrote:
> 
> The solution is to set Vizier.columns = ['all'] or Vizier.columns = ['**'], which will select all columns. The default is Vizier.columns = ['*'], which selects all of the 'default' columns that are checked when you use the online interface.
> 
> @outs1der Are you sure it worked differently on previous versions of astroquery? It is possible that it did, and it was an upstream change in Vizier, though such changes are uncommon.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Duncan Galloway, Senior Lecturer
Monash Centre for Astrophysics (MoCA), School of Physics & Astronomy
tel. +61 (0)3 99054422 | +61 (0)414 139763
http://users.monash.edu.au/~dgallow
duncan.galloway@monash.edu
