### ISSUE TITLE
Is it possible to submit a SIMBAD URL to astroquery.simbad?

### ISSUE THREAD

**Issue by hover2pi** [astropy/astroquery#904]
I performed a complex search on SIMBAD and have a URL that displays the results. Is there a way for me to put this URL into astroquery.simbad so that I can retrieve the results as an astropy table?

http://simbad.u-strasbg.fr/simbad/sim-id?Ident=NAME+Orion+Nebula+Cluster&NbIdent=query_hlinks&Coord=05+35.0-05+29&children=396&submit=children&hlinksdisplay=h_all

Otherwise, I'd like to construct an astroquery search so that it returns the same results as the SIMBAD URL? Is it possible to translate this URL into text for Simbad.query_criteria()?

Thanks!

**Comment by keflavich** [comment]
Yes, the query should be reproducible in astroquery, but no, you cannot use the URL directly.

I actually don't know how to do a children-of-object search through the SIMBAD script interface, though.  Anything that can be submitted through http://simbad.u-strasbg.fr/simbad/sim-fscript should be submittable via astroquery, but we might have to ask the CDS folks to help us figure out how to do that.

**Comment by keflavich** [comment]
@hover2pi I asked CDS, and they reported that it is not presently possible to get a machine-readable page of the children of an object, but it's on their list, so maybe soon!

**Comment by aoberto** [comment]
Then, now it is ... sorry for the delay.
From scripts, you can use a dedicated sort of queries  "query children", for instance: 
votable {id(ADS), distance, membership, link_bibcode}
votable open
query children ADS 7 AB
votable close

Then, now a new function should be created in astropy to be able to use: customSimbad.query_children('ADS 7 AB')

By the way, anytime you have a web result in Simbad, there is a link to download in VOTable or ASCII at the bottom, and then you can manipulate the result as a table in python.
