### ISSUE TITLE
Preparation for v0.3.6

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#926]
Some remote failures:

astroquery/alma/tests/test_alma_remote.py:144: AssertionError --> https://bpaste.net/show/dfb5778e13a5
astroquery/alma/tests/test_alma_remote.py:167: AssertionError --> https://bpaste.net/show/afb137f2fbee
/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/requests/adapters.py:497: SSLError --> https://bpaste.net/show/cda659cefcb1
/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/requests/adapters.py:497: SSLError --> https://bpaste.net/show/32d4496a3d91
/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/requests/models.py:909: HTTPError --> https://bpaste.net/show/015b39a5e579
astroquery/nrao/core.py:402: ValueError --> https://bpaste.net/show/06b4c57c7f3d
/Users/adam/anaconda/envs/astropy35/lib/python3.5/urllib/request.py:1256: URLError --> https://bpaste.net/show/db929d1e1048
/Users/adam/anaconda/envs/astropy35/lib/python3.5/urllib/request.py:1256: URLError --> https://bpaste.net/show/70b463d3777e

@bsipocz any others to add?

**Comment by bsipocz** [comment]
I think that's it. I'm also linking the latest travis log here: https://travis-ci.org/astropy/astroquery/jobs/242601190#L2200 but that should cover the same 8 failures.

**Comment by bsipocz** [comment]
Also the changelog will need to be taken care of, I can do that if you like.

**Comment by bsipocz** [comment]
@keflavich - Another question that is somewhat related to the new release. Shall we come up with a minimum astropy version requirement, or keep the old 1.3, 1.2?, 1.1? tested even when 2.0 is out (and being the new LTS)?

**Comment by keflavich** [comment]
Yes, we should.  I think 1.3 is a good idea?

**Comment by bsipocz** [comment]
Sounds good to me!

**Comment by bsipocz** [comment]
The sdss failures are rather weird ones, locally I only see them with python3.6 (everything passes with 3.5), but even then it's not the same tests that fail as on travis...

**Comment by bsipocz** [comment]
@keflavich - I've just realized that the NAM talk I'll have on astroquery is on Monday next week. Can we release by then, so if people wants to give it a try can do it with a new version?
