### ISSUE TITLE
Work around the pandas dependency in alma

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#938]
``pandas`` is used in alma as a workaround to parse table when it's returned in a CSV-like format. Sometimes it causes remote tests to fail as it's basically impossible to ``pytest.skip`` when pandas is not available. As a workaround I've added pandas as a dependency for testing, but this should be removed.

This is a reminder to report the parsing issue upstream to astropy and remove the workaround.

Edit: context:

The dependency was added in #888 as 
>No, I don't want to make pandas a dependency, but I couldn't get astropy.table to parse these files correctly. If I recall, it was a problem where astropy refused to ingest unicode and/or ignored quotation pairs, but pandas worked just fine. Really I should have made this an upstream astropy bug but I didn't have time.

**Comment by bsipocz** [comment]
What a useless bug report of not mentioning what the upstream issue was...

@keflavich - if this rings a bell, please let me know. Would be nice to remove the dependency.

**Comment by keflavich** [comment]
That original bug report was almost certainly my doing.  

Since we don't have a test... I guess we should remove it and see what happens...

**Comment by bsipocz** [comment]
yeah, I'm trying to change it to a simple `Table.read` now.
