### ISSUE TITLE
astropy.units integration into esasky result Tables

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#941]
Currently the columns in the esasky result tables don't have any units, but simple numpy.float values. 
e.g.

```
In [7]: esasky.ESASky().query_object_catalogs('HD189733')['GAIA DR1']
WARNING: W35: None:5:2: W35: 'value' attribute required for INFO elements [astropy.io.votable.tree]
WARNING: W35: None:6:2: W35: 'value' attribute required for INFO elements [astropy.io.votable.tree]
WARNING: W06: None:11:3: W06: Invalid UCD 'pmra': Unknown word 'pmra' [astropy.io.votable.tree]
WARNING: W06: None:12:3: W06: Invalid UCD 'pmdec': Unknown word 'pmdec' [astropy.io.votable.tree]
Out[7]: 
<Table masked=True length=1>
        name            ra [1]       dec [1]    ... phot_g_mean_flux_error [1] phot_g_mean_mag [1] phot_variable_flag
       object          float64       float64    ...          float64                 float64             object      
------------------- ------------- ------------- ... -------------------------- ------------------- ------------------
1827242811876888960 300.182122759 22.7098106295 ...              19814.8199333       7.36159117116      NOT_AVAILABLE

```
@imbasimba

**Comment by imbasimba** [comment]
Thanks for reporting. I will hopefully have time to look into this in about 2 weeks.

**Comment by bsipocz** [comment]
Sure, no rush.

I've just run some of the modules through a package novice user before releasing 0.3.6 last night, and thus we bumped into a few things.

**Comment by imbasimba** [comment]
These are issues with the data originating from the mission archives and cannot feasibly be fixed by ESASky. In this particuar case, it seems like Gaia has improved their data for the current release of DR3. The user experience is improved as much as can be expected by https://github.com/astropy/astroquery/pull/2550
