### ISSUE TITLE
Ship released tarball @pypi with license file

### ISSUE THREAD

**Issue by lupinix** [astropy/astroquery#949]
While updating the Fedora package for astroquery, I recognized that the file licenses/LICENSE.rst is not part of the 0.3.6 tar downloadable via pypi. In git repo there is a LICENSE.rst in top level directory, which is also not part of the tar. Please add the license file again in future releases.

**Comment by bsipocz** [comment]
Thanks @lupinix for the report. This was as oversight in https://github.com/astropy/astroquery/pull/877. 

The other issue you may run into is that there are rst files missing from under the astropy_helpers directory due to another reshuffle upstream. We're working on fixing it, too.
