### ISSUE TITLE
Release 0.3.6 with license included

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#951]
#949 pointed out that we missed to add the license in the last release. This has been fixed since, but maybe we need to release to be able to build the conda package (https://github.com/conda-forge/astroquery-feedstock/pull/3/).

I can either tag a 0.3.6.post1 release later today or tomorrow if we agree to go ahead with this.

**Comment by keflavich** [comment]
Yes, let's do that.  I'll push to pip once it's ready.

**Comment by bsipocz** [comment]
OK. I'll do it after astropy 2.0 is ready.

**Comment by bsipocz** [comment]
Should it be 0.3.6.post1 or 0.3.7?

**Comment by keflavich** [comment]
I prefer `.post1`, let's reserve #'s for feature &/or bugfix releases
