### ISSUE TITLE
Tests with Python 3.6

### ISSUE THREAD

**Issue by ViviCoder** [astropy/astroquery#952]
With Python 3.6, the test collection fails with the following error message:
`DeprecationWarning: generator 'pytest_pycollect_makeitem' raised StopIteration`
A full log can be found [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867502) (it was obtained with version 0.3.5, but the error is still there with version 0.3.6).

**Comment by bsipocz** [comment]
@ViviCoder - Do you see this issue with the latest master (or 0.3.6 release)? it seems that you've used the 0.3.5 release.

**Comment by ViviCoder** [comment]
@bsipocz Yes. I edited my post just before I saw your question. ^^

**Comment by bsipocz** [comment]
Do you see this issue with astropy or other affiliates, too? (e.g. photutils?)

**Comment by ViviCoder** [comment]
As far as I know, photutils is not affected.
I will try to test the other packages I maintain for Debian.

**Comment by ViviCoder** [comment]
astroplan, pydl and pyregion are not affected either.

**Comment by ViviCoder** [comment]
It is probably an issue in pytest, not in astroquery.

**Comment by bsipocz** [comment]
Looking at it again, it's probably an issue with our tests. I see that you test against the python 3.6.2rc1, so guess those deprecations are new in that version (and we raise all deprecations as errors in our test suite, that can be switched off in astroquery/conftest.py)

**Comment by pllim** [comment]
A search brought me to pytest-dev/pytest#2226 . Perhaps this is already fixed upstream in `pytest`?

**Comment by ViviCoder** [comment]
It seems so. This issue probably occurs because the version of pytest used in Debian is not up to date.

**Comment by mwhudson** [comment]
Isn't this the same as #861 ?

**Comment by mwhudson** [comment]
Although being able to fix this via updating pytest would be nice...

**Comment by ViviCoder** [comment]
@mwhudson - You are right. This is the same issue.

**Comment by bsipocz** [comment]
I'm closing this now as duplicate as it either needs a fix upstream in pytest or the workaround of #861.
