### ISSUE TITLE
Add TRILEGAL and Padova model query?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astroquery#954]
The Besançon model is already present, could the [TRILEGAL](http://stev.oapd.inaf.it/cgi-bin/trilegal) model also be added?

**Comment by keflavich** [comment]
Perhaps, are you interested in contributing?  The Besançon model was fairly difficult to implement because they use a custom output format that is not particularly easy to parse; it required a good deal of manual format specification.  I'm not sure if TRILEGAL does anything nicer.

**Comment by bsipocz** [comment]
Oh, but then parsec could be added to the same module, too. They must have the same data format (I guess).
http://stev.oapd.inaf.it/cgi-bin/cmd

**Comment by Gabriel-p** [comment]
There's the [Padova](https://github.com/jonathansick/padova) package for querying CMD, adapted from [ezPadova](https://github.com/mfouesneau/ezpadova).

I have a *much* simpler fork called [ezPadova-2](https://github.com/asteca/ezpadova-2) which basically downloads a set of tracks given some input values and nothing else.  Also, I think I might have a Perl script to query Trilegal that was shared with me several years ago which could be useful.

I'd be glad to help, keeping in mind I've never contributed to astropy or any of its related packages before.

**Comment by keflavich** [comment]
That's fine, this is a great place to start!  We'll happily help with style and python tips if you can do the hard work of figuring out what HTTP parameters need to be passed to the server and how to parse the returned files.

**Comment by bsipocz** [comment]
I also have my version of getting the padova models, but none of those are yet part of astroquery. So getting in even the simplest implementation is a good addition.

 cc-ing @jonathansick in case he is interested in this.

**Comment by Gabriel-p** [comment]
Just found the [VESPA](https://github.com/timothydmorton/VESPA) package. It contains the [Perl script](https://github.com/timothydmorton/VESPA/blob/master/scripts/get_trilegal) I was talking about, with a very convenient [Python wrapper](https://github.com/timothydmorton/VESPA/blob/master/vespa/stars/trilegal.py) already implemented.

**Comment by jonathansick** [comment]
Thanks for the heads-up on this. I wonder if the better way to do this, from a long-term maintainability standpoint, is to collaborate directly with Girardi's group and deploy a JSON API to go alongside their web form. That'd make the client easier to write and likely be more reliable. Maybe it's organizationally  impractical, I don't know :)

**Comment by Gabriel-p** [comment]
In any case, a heads up to Leo Girardi would be advisable should this get implemented.

**Comment by keflavich** [comment]
Some reference implementations in case anyone wants to try:

For padova, we have https://github.com/jonathansick/padova

For MIST, my quick hack version:
```python
import requests
from bs4 import BeautifulSoup
from zipfile import ZipFile
from io import BytesIO


def get_mist(feh=0.0, ages=[10], av=0.12):
    sess = requests.Session()
    data = {"v_div_vcrit": "vvcrit0.4",
            "age_scale": "log10",
            "age_value": "",
            "age_range_low": "",
            "age_range_high": "",
            "age_range_delta": "",
            "age_type": "list",
            "age_list": " ".join(map(str,ages)),
            "FeH_value": feh,
            "theory_output": "basic",
            "output_option": "photometry",
            "output": "UBVRIplus",
            "Av_value": av,}
    result = sess.post("http://waps.cfa.harvard.edu/MIST/iso_form.php", data=data)
    soup = BeautifulSoup(result.text, 'html5')
    ref = soup.find('a').attrs['href']
    result2 = requests.get(f'http://waps.cfa.harvard.edu/MIST/{ref}')
    zf = ZipFile(BytesIO(result2.content))
    return ascii.read(BytesIO(zf.read(zf.filelist[0])), format='commented_header', header_start=-1)
```

**Comment by bsipocz** [comment]
Keeping the other issue open (https://github.com/astropy/astroquery/issues/2570) for tracking this new service request.
