### ISSUE TITLE
IRSA Moving Object Search

### ISSUE THREAD

**Issue by ysBach** [astropy/astroquery#956]
IRSA offers a nice moving object (especially MPC known targets) search tool as in [this link](http://irsa.ipac.caltech.edu/applications/Gator/GatorAid/irsa/catsearch.html#moving). 

As I am not a good programmer, what I use is just a very primitive url-encoding script.
I guess it will be very helpful if we can query the moving object through IRSA via ``astroquery`` to utilize WISE/NEOWISE data.

**Comment by bsipocz** [comment]
@ysBach - The is already an irsa module. Briefly looking into this, I think you can get away with adding only one new method and modify the payload generation to match the moving object API. 
Realistically I don't this either of us maintainers will implement this any time soon, but anyone interested in contributing we can provide code review, etc.

**Comment by bsipocz** [comment]
@ysBach - the MOST service has been added to the irsa module, so I go ahead and close this.

Please do check the module and let us know if there are some functionality missing: https://astroquery.readthedocs.io/en/latest/ipac/irsa/most.html
