### ISSUE TITLE
Why does TapColumn have getters and setters?

### ISSUE THREAD

**Issue by adrn** [astropy/astroquery#964]
The `TapColumn` class basically acts like a `NamedTuple`, but has `get_` and `set_` methods for every attribute that just return or set an internal attribute:
https://github.com/astropy/astroquery/blob/3b4cac2f0385895989d3acbe21ca553c5d894dc0/astroquery/utils/tap/model/tapcolumn.py

Am I missing something, or can this just be replaced by:

```python
class TapColumn(object):
    """TAP column object
    """

    def __init__(self):
        """
        Constructor
        """
        self.name = None
        self.description = None
        self.unit = None
        self.ucd = None
        self.utype = None
        self.datatype = None
        self.arraysize = None
        self.flag = None
```

Though, it's really just acting as a namespace...so why isn't it just a dictionary? 

cc @smoh

**Comment by bsipocz** [comment]
cc @jcsegovia

**Comment by jcsegovia** [comment]
Well, yes, I guess I can remove that class and create a dictionary.
No objections from my side.

**Comment by bsipocz** [comment]
This has been cleaned up.
