### ISSUE TITLE
Why the distance column (_r) in a cone search is calculated wrong?

### ISSUE THREAD

**Issue by Titanosaurus** [astropy/astroquery#965]
Let's make an example:
You enter in the Vizier web-page a search by position for the 04:32:01.845 +53:54:39.03 coordinates (with J2000 and radius of 5 arcsec).
In the 'I/331/hip2' catalogue you have one entry.
In the '_r' column it says that there is a source in the catalogue located **0.021 arcsecs** from the exact coordinates.

I wanted to extract this information using astroquery. I did the following:

```python
from astroquery.vizier import Vizier
from astropy import units as u
from astropy.coordinates import SkyCoord

result=Vizier.query_region('04:32:01.845 +53:54:39.03', radius=5*u.arcsec)
print result['I/311/hip2']['_r']
```

From this I get **0.052** instead of 0.021. Why?

This is even stranger when you consider that this slightly modified code (that should do the same) gives you **0.050**

```python
from astroquery.vizier import Vizier
from astropy import units as u
from astropy.coordinates import SkyCoord

coord=SkyCoord('04:32:01.845 +53:54:39.03', unit=(u.hourangle, u.deg))
result=Vizier.query_region(coord, radius=5*u.arcsec)
print result['I/311/hip2']['_r']
```

What is the issue here? How can I extract that 0.021 that I need so badly.

P.S: This is a particular example but it always happens, with every different search you do

**Comment by pllim** [comment]
Which Vizier web page are you talking about?

**Comment by bsipocz** [comment]
I also wonder about which Vizier page you compare the results. Also I'm pretty sure it's a different code you use to create those values, as there is no ``['_r']`` column in the result in your first example:

```
In [5]: result['I/311/hip2']
Out[5]: 
<Table masked=True length=1>
 HIP  n_HIP    Sn    So     RArad        DErad       Plx    e_Plx    pmRA     pmDE    Hpmag    B-V    HIP1 
                             deg          deg        mas     mas   mas / yr mas / yr   mag     mag         
int32 bytes1 int16 uint8   float64      float64    float32 float32 float64  float64  float32 float32 bytes4
----- ------ ----- ----- ------------ ------------ ------- ------- -------- -------- ------- ------- ------
21148      P    15     3  68.00768144  53.91084624   -4.60    1.85    -1.29    -0.17  5.8249   0.119   HIP1
```

**Comment by pllim** [comment]
There is `_r` in `vo_conesearch` but the result does not match what was reported, nor was from the mentioned catalog:
```
>>> from astroquery.vo_conesearch import conesearch
>>> from astropy.coordinates import SkyCoord
>>> from astropy import units as u
>>> c = SkyCoord('04:32:01.845 +53:54:39.03', unit=(u.hourangle, u.deg), frame='icrs')
>>> res = conesearch.conesearch(c, 5 * u.arcsec)
Trying http://vizier.u-strasbg.fr/viz-bin/votable/-A?-out.all&-source=I/254/out&
>>> res
<Table masked=True length=1>
   _r       GSC      RAJ2000   DEJ2000  ... Plate   Epoch   Mult  Versions
  deg                  deg       deg    ...           yr                  
float64   bytes10    float64   float64  ... bytes4 float64 bytes1  bytes7 
-------- ---------- --------- --------- ... ------ ------- ------ --------
0.001384 0373201028  68.00583  53.91169 ...   +056      --      F  GSC-all
```

**Comment by pllim** [comment]
So... Here is what you can do in `astroquery.vo_conesearch` to get that object you want. It takes a bit of digging (so you probably wouldn't have figured it out unless you carefully read the entire documentation) but doable.

First, to track down the VO catalog that you mentioned (you can skip this if you already have the "service URL" but I did not:
```python
>>> from astroquery.vo_conesearch import validator
>>> from astroquery.vo_conesearch import vos_catalog
>>> db = vos_catalog.VOSDatabase.from_registry(validator.conf.conesearch_master_list, encoding='binary')  # The binary part is needed for py3, not sure about py2
>>> urls = db.list_catalogs_by_url(pattern='vizier')
>>> for url in urls:
    if 'I/311/hip2' in url:
        print(url)
http://vizier.u-strasbg.fr/viz-bin/votable/-A?-out.all&-source=I/311/hip2&
```

Now, we have the "service URL", we can extract the catalog entry from master database:
```python
>>> url = 'http://vizier.u-strasbg.fr/viz-bin/votable/-A?-out.all&-source=I/311/hip2&'
>>> cat = db.get_catalog_by_url(url)
```

Now, we can query the catalog of interest:
```python
>>> from astroquery.vo_conesearch import conesearch
>>> from astropy.coordinates import SkyCoord
>>> from astropy import units as u
>>> c = SkyCoord('04:32:01.845 +53:54:39.03', unit=(u.hourangle, u.deg), frame='icrs')
>>> res = conesearch.conesearch(c, 5 * u.arcsec, catalog_db=cat)
```

However, for backward-compatibility, this cone search returns a VO table, not Astropy table. So, we need an extra step to convert it to Astropy table:
```python
>>> from astropy.table import Table
>>> t = Table.read(res)
>>> t
<Table masked=True length=1>
   _r    recno  HIP   n_HIP    Sn  ...   B-V    e_B-V    V-I    HIP1   Phot 
  deg                              ...   mag     mag     mag                
float64  int32 bytes6 bytes1 int16 ... float32 float32 float32 bytes4 bytes4
-------- ----- ------ ------ ----- ... ------- ------- ------- ------ ------
0.000006 21095  21148      P    15 ...   0.119   0.004   0.130   HIP1   Phot
```

Distance is given in the unit of degree as stated in VO standards, so you need to convert to arcsec yourself:
```python
>>> t['_r'].to(u.arcsec)
<Quantity [ 0.0216] arcsec>
```

Hope this is the result you are looking for.

**Comment by Titanosaurus** [comment]
Thank you for your thoughtful responses. My astropy version is the 1.1.2 and my astroquery is the 0.3.1(maybe that's the reason the code works on my machine and not in yours).

In the end I choose to make my own calculation. I used the separation function between the center of the cone search and the coordinates of the source. It was exactly the result I was searching for: 0.021 arcsec.

@pllim your code looks great. But the result is wrong, since reounding your output gives 0.022 arcsec (I know is not a big deal but it matters for my calculations).

Thank you for the quick answers to all of you

**Comment by pllim** [comment]
The distance is returned directly by the cone search service, which is out of my control. Please close the issue if you feel it has been resolved on your end. Thank you.
