### ISSUE TITLE
What is astroquery's plan of dropping Python 2 support?

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#974]
I need to fix some imports to replace `astropy.utils.compat.futures`, which is deprecated in astropy/astropy#6598, in `vo_conesearch` here. *How* I fix it depends on Astroquery's plan with Python 2 support going forward. Please advise.

**Comment by keflavich** [comment]
I'm not inclined to remove astroquery's python2 support for the foreseeable future.  Unlike astropy, there is no LTS version of astroquery, and we almost always recommend that users use the latest dev version, since we have to update the dev version to keep up with remote API changes.

**Comment by pllim** [comment]
> I'm not inclined to remove astroquery's python2 support for the foreseeable future

In that case... Should I move the deleted files from `astropy.utils.compat.futures` to this package? If we continue to use `astropy.utils.compat.futures` as-is, it is going to raise `AstropyDeprecationWarning` and cause some `vo_conesearch` tests to fail.

**Comment by pllim** [comment]
Or... I can simply do the `try ... except` on the import, but that assumes dependencies are properly pinned in `setup.py`.

**Comment by keflavich** [comment]
What sorts of files are needed?  Is there stuff we can't just `six` in?

**Comment by saimn** [comment]
There is a backport for Python 2, if it helps: https://pypi.python.org/pypi/futures
(I think it's easier to have an optional dependency for this kind of situations).
