### ISSUE TITLE
Revise esasky test coverage

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#980]
#977 pointed out that there are gaps in the test coverage of esasky. This issue is a reminder to look at the issue when @imbasimba has the time.

**Comment by eerovaher** [comment]
Shouldn't this have been closed by #1001?

**Comment by bsipocz** [comment]
We need to check the coverage %, but as I recall there were still gaps when I last checked.

**Comment by bsipocz** [comment]
Test coverage is in fact 80%+, and it's mostly the exceptions that are not covered, and a few duplicated lines, which is fine, so I'm going ahead and closing this now. Thanks for the ping!
