### ISSUE TITLE
astroquery XMatch not returning all columns

### ISSUE THREAD

**Issue by aburgasser** [astropy/astroquery#985]
I was wondering if it was possible to have XMatch return all columns of a given table, as it currently only returns a "default" set. For example:

```
t_match = XMatch.query(t,'vizier:J/ApJS/220/16/table4',30.*u.arcsec,colRA1='RA',colDec1='DEC')
```

returns columns:

```
angDist | RA | DEC | _RAJ2000 | _DEJ2000 | 2MASS | RAJ2000 | DEJ2000 | RVel | e_RVel | BC | MTeffK | MFeHK | MMHK | EWNa | EWCa | UCAC4 | MCat | Simbad
```

while:

```
c = splat.properCoordinates('J13455527+2723131') # creates a SkyCoord instance
v = Vizier(columns=["**", "+_r"], catalog='J/ApJS/220/16/table4')
t_vizier = v.query_region(c,radius=30.*u.arcsec)['J/ApJS/220/16/table4']
```

returns columns:

```
_r | _2MASS | RAJ2000 | DEJ2000 | Jmag | e_Jmag | Hmag | e_Hmag | Ksmag | e_Ksmag | _2MQF | Amag | e_Amag | pmRA | pmDEC | r_pm | plx | e_plx | r_plx | Vmag | RVel | e_RVel | BC | MH2OJ | CH2OH | RH2OK2 | MJI | MHI | MKI | NSpT | PSpT | MTeffJ | MTeffH | MTeffK | MFeHJ | MFeHH | MFeHK | MMHJ | MMHH | MMHK | MFeHL | NFeH | T12FeH | EWNa | EWCa | NMg148 | NMg150 | NK151 | NMG157 | NSi158 | NCO161 | NCO162 | Nl167A | Nl167B | NMg171 | NTeff | NRad | NLogL | Notes | UCAC4 | MCat | Simbad
```

I guess I'm asking if its possible to add a "columns" keyword argument to the XMatch query calls to provide some flexibility in what is returned/sorted?

Thanks!

**Comment by aburgasser** [comment]
it looks like there are optional parameters:

http://cdsxmatch.u-strasbg.fr/xmatch/doc/API-calls.html

Optional parameters

selection - match selection. Allowed values are best|all. Default selection mode is all.
all: all matches are kept. In this mode, the cross-match is symmetric.
best: keep best match in cat2 for each row of cat1. In this mode, the cross-match is not symmetric.

MAXREC - maximum number of rows to return. The server has a hard upper limit (currently set at $2\, 000\, 000$ records) which can not be overriden by the user.

cols1 - comma-separated list of columns of cat1 to be kept in output.
Example: cols1=ra,dec,main_id

cols2 - comma-separated list of columns of cat2 to be kept in output.

**Comment by tboch** [comment]
VizieR tables in cross-match service contain only default columns. Hence, it is currently not possible to retrieve all columns.
We have a midterm plan to allow for more flexibility in order to let the user choose the columns of her choice.

**Comment by iskren-y-g** [comment]
Hi, it's been awhile, but has this issue been resolved? It would be nice to XMatch.query and get all columns. My current workaround is to get all columns for one of the tables (with most columns) with a Vizier query `columns=['all']` and then XMatch with the other. Somehow it seems to work ... but I've tried it only on two tables. One with 22 and the other with 145 columns. The latter I saved as a cvs, and used 'vizier: ...' for the former. The result from the XMatch was sum of the columns.

**Comment by bsipocz** [comment]
I'm inclined to close this as the requested functionality is not supported by the upstream API, so we cannot support it here either atm (I've just double-checked, and it's not possible to add or deselect columns at http://cdsxmatch.u-strasbg.fr/xmatch#tab=xmatch&).
