### ISSUE TITLE
Cone Search gives me unexpected 400 response (bad request)

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#992]
Using Astropy 2.0.2 and either released or dev Astroquery on Python 3.5:
```python
from astropy import units as u
from astropy.coordinates import SkyCoord
from astroquery.vo_conesearch import conesearch

# Define your search object.
# See http://astropy.readthedocs.io/en/stable/coordinates/index.html
c = SkyCoord(0, 0, frame='icrs', unit='deg')

# Define your search radius.
# See http://astropy.readthedocs.io/en/stable/units/index.html
sr = 0.1 * u.degree

from astroquery.vo_conesearch import ConeSearch

ConeSearch.URL = 'https://irsa.ipac.caltech.edu/SCS?table=akari_fis&'
result = ConeSearch.query_region(c, sr)
# ERROR! Tracked it down to 400 bad request
```
```
VOSError: Catalog server 'https://irsa.ipac.caltech.edu/SCS?table=akari_fis&' returned error 'Unknown parameter:  '
```

But direct URL query works, so it is not the service provider: https://irsa.ipac.caltech.edu/SCS?table=akari_fis&VERB=1&DEC=0.0&SR=0.1&RA=0.0

I think it is somewhere in `BaseQuery._request()` method that I inherited. Any idea on how to debug this is appreciated.

**Comment by bsipocz** [comment]
released astroquery means 0.3.6? Could you check with 0.3.5?
There was a minor change to BaseQuery._request() in #928, which I don't think could cause any troubles, but that was new in 0.3.6

**Comment by pllim** [comment]
Release used was 0.3.6.post2

**Comment by pllim** [comment]
Same error in 0.3.5. :disappointed:

**Comment by pllim** [comment]
Must be some special edge case... I'll investigate.

**Comment by pllim** [comment]
For whatever reason, this particular service does not accept search values via `params` keyword. Have you had to deal with such services before? What is the best way around this?

This gives me error:
```python
>>> import requests
>>> url = 'https://irsa.ipac.caltech.edu/SCS?table=akari_fis&'
>>> params = {'RA':0.0, 'DEC':0.0, 'SR':0.1, 'VERB':1}
>>> r = requests.get(url, params=params)
>>> r.ok
False
>>> print(r.content)
b'<?xml version="1.0" encoding="utf-8"?>\n<VOTABLE version="1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ivoa.net/xml/VOTable/v1.3" xmlns:stc="http://www.ivoa.net/xml/STC/v1.30">\n  <DESCRIPTION>IRSA IVOA Simple Cone Search Service</DESCRIPTION>\n  <INFO ID="Error" name="Error" value="Unknown parameter: \n"/>\n</VOTABLE>\n'
```
But this works:
```python
>>> url2 = 'https://irsa.ipac.caltech.edu/SCS?table=akari_fis&RA=0.0&DEC=0.0&SR=0.1&VERB=1'
>>> r = requests.get(url2)
>>> r.ok  # And I see proper result in the content
True
```

**Comment by MSeifert04** [comment]
Odd, ifI look at the `r.url` it *almost* seems okay:

```
>>>r.url
https://irsa.ipac.caltech.edu/SCS?table=akari_fis&&DEC=0.0&SR=0.1&RA=0.0&VERB=1
```
Is the double `&` the problem?

**Comment by pllim** [comment]
Ohhh, good catch! If I remove the ending `&` in `url`, it works. Now I have to investigate why there is a trailing `&`.

**Comment by pllim** [comment]
Trying with another service that works, its final `r.url` also has `&&` but that didn't throw an error. Still, `&&` is a problem. I'll see how to best avoid that in the future.
