### ISSUE TITLE
Inherited QueryWithLogin or BaseQuery methods should get docstrings

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#995]
It came up in https://github.com/astropy/astroquery/pull/982#discussion_r146584527 that while the ``login()`` method gets created based on the ``_login()`` provided in the module, it doesn't inherit any docstrings which would be vital as it's user facing. 

Once it's addressed, ``MastClass.login()`` can be removed from ``astroquery/mast/core.py``

**Comment by saimn** [comment]
This is indeed annoying, I'm trying to find a solution :)
