### ISSUE TITLE
Querying all catalogs with a specific stellar property (e.g., ages) for a specified star

### ISSUE THREAD

**Issue by baddison2005** [astropy/astroquery#998]
Is there a way to query all of the catalogs on VizieR with a specific stellar property such as ages or stellar vsini's for a specified star using astroquery vizier? My goal is to extract certain stellar properties for a list of stars that I have.

I've tried doing this by specifying Vizier columns using 
`v = Vizier(columns=['_RAJ2000', '_DEJ2000','Name', 'Ages'])`
I then either querying the region or object such as:
`result = v.query_region("Sirius", radius=10 * u.arcsec)`
`result = v.query_object("Sirius")`
Running this I get a large set of results but none of the catalogs containing ages or age.

If I specify only an ages or age column.
`v = Vizier(columns=['Age'])`
`v = Vizier(columns=['Ages'])`

And then run 
`result = v.query_region("Sirius", radius=10 * u.arcsec)`
or
`result = v.query_object("Sirius")`

I get an error:
astroquery.exceptions.TableParseError: Failed to parse VIZIER result! The raw response can be found in self.response, and the error in self.table_parse_error. The attempted parsed result is in self.parsed_result.
 Exception: Setting void-array with object members using buffer.

Is there a way to accomplish what I'm trying to do?
Thanks

**Comment by keflavich** [comment]
You can do something like:

```
result = Vizier(ucd='time.age*').query_object('Sirius')
```

I get the following result doing that:
```
TableList with 7 tables:
	'0:V/137D/XHIP' with 15 column(s) and 1 row(s)
	'1:J/ApJ/653/675/table1' with 15 column(s) and 1 row(s)
	'2:J/ApJ/660/1556/table4' with 10 column(s) and 1 row(s)
	'3:J/ApJ/804/146/table5' with 16 column(s) and 1 row(s)
	'4:J/ApJ/826/171/table3' with 11 column(s) and 1 row(s)
	'5:J/A+A/348/897/tablea6' with 13 column(s) and 1 row(s)
	'6:J/AJ/138/1681/WD20pc' with 17 column(s) and 1 row(s)
```

You need to use the "Unified Content Descriptor" tools provided by Vizier to do this.

**Comment by baddison2005** [comment]
Thank you this works! Unfortunately the 'age' column names for the different tables are not consistent. I guess this means I need to create a lookup table with the different possible names for 'age' such as: age, Age, medAge, aveAge, logage, LogAge, etc. and deal with the different units which are sometime in yr, Myr, Gyr, or logyr. This is why I'm helping to create the Starchive, an open-access stellar database that will contain all the stellar properties (observable and derived) for stars within 30pc.
